### ISSUE TITLE
Tripwire Strings Render as Opaque Instead of Transparent

### ISSUE THREAD

**Issue by StephenJPlant** [jellysquid3/Sodium#2420] opened 2024-04-13 21:19 UTC
### Bug Description

Normally tripwire strings are semi-transparent, but when I run Sodium, the pixels with any amount of opacity become completely solid. Only the completely transparent pixels remain transparent.

### Reproduction Steps

Place a tripwire.

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/14968665/latest.log)

### Crash Report

[crash-2024-04-13_15.16.36-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/14968669/crash-2024-04-13_15.16.36-client.txt)

**Comment by yamayaki1** [comment] 2024-04-13 22:16
Duplicate of https://github.com/CaffeineMC/sodium-fabric/issues/2409?

**Closed as not planned** 2024-04-13 22:28 UTC
Labels: E-duplicate
