### ISSUE TITLE
Sodium doesn't render translucent blocks properly

### ISSUE THREAD

**Issue by Onionus007** [jellysquid3/Sodium#981] opened 2021-11-20 13:29 UTC
If you have a model that has translucent parts in it, you will be able to see pretty much everything through it, except for the other parts of the very same model which are behind it
Example: 
Expected appearance 
![image](https://user-images.githubusercontent.com/37909484/142728074-4f9a8a28-d5f2-415b-ba5b-a66a7b3ffed8.png)

The appearance with sodium
![image](https://user-images.githubusercontent.com/37909484/142728116-5c54ad13-f3a4-4553-9598-fae54f9d697f.png)
P.S. The redstone block is rendered separately, it's not a part of the model

**Comment by Onionus007** [comment] 2021-11-20 13:29
Ig the item in hand is untouched by the sodium renderer so that's why it is not broken

**Comment by MESLewis** [comment] 2021-11-20 18:55
Possibly duplicate of #38

**Comment by Onionus007** [comment] 2021-11-20 21:15
I think this is somewhat different, the parts that are not rendered are part of the very same model, but I guess could be related

**Comment by MESLewis** [comment] 2021-11-22 16:23
What model is the model in your example from? I can try and reproduce the issue.

**Comment by MESLewis** [comment] 2021-11-22 16:25
Also a simple test to see if it is related to #38 is if the model looks correct when viewed from 1 or 2 sides(north, south, east, west), but wrong from the opposite side(s).

**Comment by Onionus007** [comment] 2021-11-22 17:15
Made it in blockbench, blockbench has the same issue rendering translucent objects

**Comment by jellysquid3** [comment] 2021-12-01 22:26
Caused by #38. See that issue for more information.

**Closed as completed by jellysquid3** 2021-12-01 22:26 UTC
