### ISSUE TITLE
campanion mod rendering issue

### ISSUE THREAD

**Issue by ParkerDemmler** [jellysquid3/Sodium#658] opened 2021-05-13 17:52 UTC
### Version

mc1.16.3-0.1.0

### Reproduction Steps

Use the mod Campanion and place a down two rope bridge posts across a 5 block gap over the void then right click one with 2 rope in your hand and then right click the other one with that same rope, then right click the posts with planks to fill in the bridge

[crash-2021-05-13_13.23.30-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/6474129/crash-2021-05-13_13.23.30-client.txt)

I was unable to recreate this crash in a single player world by placing the blocks, but in a multiplayer server where they already existed the crash occured

also in the single player world the block models didn't even render

then when rejoining the server the game crashed almost immediately

**Comment by Leo40Git** [comment] 2021-05-14 21:10
This is caused by Sodium's current lack of support for the Fabric Rendering API - duplicate of #5.

**Closed as completed** 2021-05-17 10:51 UTC
Labels: E-duplicate, T-crash
