### ISSUE TITLE
No core dump will be written. Minidumps are not enabled by default on client versions of Windows

### ISSUE THREAD

**Issue by TafGB** [jellysquid3/Sodium#1615] opened 2023-02-11 22:45 UTC
### Version information

sodium-fabric-mc1.19.2-0.4.4+build.18

### Reproduction Steps

The crash can happen in a few ways (on all 1.19.2+ versions of sodium with only fabric API as another mod and without fabric API as a mod)

1st way
1. log into a server
2. join a game (ex: pvp legacy match)
3. sometimes it will crash and other times it won't as soon as I get put in

2nd way
1. log into a server
2. join a game (if I don't crash)
3. finish the game and get teleported to lobby
4. sometimes will crash

3rd way
1. Log into single player world
2. f3+a and hold
3. see all chunks being reloaded then only see one chuck be reloaded 
4. crash

### Crash Report file

[hs_err_pid33700.log](https://github.com/CaffeineMC/sodium-fabric/files/10714850/hs_err_pid33700.log)

### Additional information

I will not crash when I use sodium on clients however I want to use sodium with other mods

3060ti

i7-11700F

16GB of memory

Crashes on multiple versions of java
Crashes on multiple versions of fabric
Crashes even when it is the only mod in my mods folder
Using curse forge 
Only crashes using sodium

**Comment by Timolino456** [comment] 2023-02-12 10:20
Do you happen to have a NVIDIA GPU and have up to date drivers?

**Comment by TafGB** [comment] 2023-02-14 01:30
yes i do and they are all up to date

**Comment by Timolino456** [comment] 2023-02-14 06:32
Then this is likely just another case of #1486. Either update to 1.19.3 and use its latest Sodium version as it has a workaround, or downgrade your drivers to a version below the affected ones.

**Comment by TafGB** [comment] 2023-02-15 22:29
sodium-fabric-mc1.19.3-0.4.9+build.23 is still causing the crash, however, downgrading graphics drivers fixes it. Would you like me to close issue?

**Comment by jellysquid3** [comment] 2023-07-22 02:08
This is a duplicate of #1816.

**Closed as not planned by jellysquid3** 2023-07-22 02:08 UTC
Labels: E-will-not-fix, T-crash
