### ISSUE TITLE
Item Textures missing when using Sodium with All of Fabric 3

### ISSUE THREAD

**Issue by Filaton** [jellysquid3/Sodium#567] opened 2021-03-04 21:28 UTC
### Expected Behavior
I installed Sodium in All of All of Fabric 3 and it should load all textures like it does without Sodium.

### Actual Behavior
But for some reason some of the vanilla Textures (such as Stone Pickaxe for example) aren't shown correctly. They are just a block out of pink and black squares.

### Reproduction Steps
1. Install All of Fabric 3 with curseforge
2. Paste the sodium file in the mods folder
3. Look through the Items some of them (only vanilla items) have no texture anymore

### Attachments
![2021-03-04_22 23 26](https://user-images.githubusercontent.com/49982385/110032437-6de07800-7d38-11eb-9773-676b4fd19a8e.png)

### System Information
- Java Version: Java 8 (Build 1.8.0_281-b09)
- CPU: AMD Ryzen 7 3700
- GPU: AMD Radeon RX 5700 XT

**Comment by ImperatorStorm** [comment] 2021-03-04 21:29
duplicate of #5

**Closed as completed** 2021-03-04 21:36 UTC
Labels: T-bug, E-duplicate
