### ISSUE TITLE
 game crashes when changing dimension

### ISSUE THREAD

**Issue by yummyodeee** [jellysquid3/Sodium#1617] opened 2023-02-12 09:32 UTC
Every time I enter the portal, my game crashes. dumps do not appear in crash-reports. there is only hs_err. I am using sodium version 0.4.4 on version 1.19.2, I had the same problem on version 1.19. please fix it.

**Comment by Timolino456** [comment] 2023-02-12 10:19
Duplicate of #1486. Downgrade your drivers, as the fix is only available for 1.19.3+

**Closed as completed** 2023-02-14 00:42 UTC
Labels: E-duplicate
