### ISSUE TITLE
Illuminations is incompatible with Sodium

### ISSUE THREAD

**Issue by NxD136** [jellysquid3/Sodium#169] opened 2020-07-24 20:34 UTC
### Reproduction Steps
Game crashes at launch. Nothing to replicate really...

### Crash Report File
[(https://paste.ee/p/keq9t)]

### Additional Information
This is in a test modpack environment with over 200+ other mods. Might be a compatibility issue. Here is the latest.log file
[latest.log](https://github.com/jellysquid3/sodium-fabric/files/4974135/latest.log)

**Comment by amnotbananaama** [comment] 2020-07-24 21:27
Some of those mods in the list are for Forge. With more than 200 mods loaded, it's almost certain this issue is not caused by Sodium. And even if it was, there is just no way to know which mod it is incompatible with.

My suggestion is double checking each of your mods to make sure you are using the latest stable version **for Fabric**. If the issue still persists, do a binary search by disabling half of your mods until the crash doesn't happen. You can narrow down from there.

If you find an incompatibility between a specific mod and Sodium, this issue can remain open. Otherwise it should be closed as an external issue.

**Comment by Erazer750** [comment] 2020-07-24 22:31
Try to remove "roughly enough items" and see if it eliminates your problem. Its something that i've experienced myself.

**Comment by jellysquid3** [comment] 2020-07-25 17:31
Illuminations is trying to mixin to some code we replace, and it's causing crashes. This will need to be worked around on one of our sides.

**Comment by jellysquid3** [comment] 2020-07-25 17:36
It actually looks like they already worked around this issue in [Illuminations 1.0.1.1](https://www.curseforge.com/minecraft/mc-mods/illuminations/files/3013909).

> Fixed an issue where the game would crash upon loading the mod with Sodium

Please upgrade to the latest version of Illuminations.

**Closed as completed by jellysquid3** 2020-07-25 17:36 UTC
Labels: A-mods, T-crash, S-confirmed
