### ISSUE TITLE
Frustum culling can rarely change the draw order of render regions

### ISSUE THREAD

**Issue by douira** [jellysquid3/Sodium#2244] opened 2024-01-04 13:51 UTC
### Bug Description

The render order is wrong in this situation which leads to sorting artifacts. Since the artifacts go away with camera angle, it's not a normal translucency sorting problem.

![Screenshot 2024-01-04 at 04 45 08](https://github.com/CaffeineMC/sodium-fabric/assets/17120022/554fe1ab-60f6-4e44-9bcf-2d668e758452)
![Screenshot 2024-01-04 at 04 45 06](https://github.com/CaffeineMC/sodium-fabric/assets/17120022/459b1e02-29e8-46c7-8e52-c418aa99e772)

### Reproduction Steps

- Make a world with seed `-1209221951706518130`, RD 2 is enough. According to @Lolothepro, it needs FOV <= 71
- Run `/execute in minecraft:overworld run tp @s -2091.80 82.74 -1928.06 47.84 23.10`
- Observe a line in the ice near the bottom of the screen
- Run `/execute in minecraft:overworld run tp @s -2091.80 82.74 -1928.06 50.54 25.80`
- Observe the line disappear

The tp commands only differ in camera facing.

### Log File

[2024-01-04-7.log](https://github.com/CaffeineMC/sodium-fabric/files/13830444/2024-01-04-7.log)

### Crash Report

[crash-2024-01-04_14.47.36-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/13830447/crash-2024-01-04_14.47.36-client.txt)

**Comment by embeddedt** [comment] 2024-01-04 15:10
Clarification so that the next person isn't unable to reproduce for 5 minutes: in the third step, you just need to turn your head, not actually move the player. :laughing:

**Comment by Lolothepro** [comment] 2024-01-04 22:33
Note: FOV <= 71

**Comment by jellysquid3** [comment] 2024-01-05 09:44
The problem is that regions are only enqueued when a chunk section is visible... This means if a chunk section is skipped due to frustum checks, it will not update the ordering of regions, and in the edge case demonstrated here, will break things.

The solution is trivial (update the regions list before failing any chunk sections) but it will require some minor code refactoring.

**Comment by jellysquid3** [comment] 2024-01-18 07:26
Fixed with https://github.com/CaffeineMC/sodium-fabric/commit/27e531f36479c4de63c36afdc5b8707d96487c16.

**Closed as completed** 2024-01-18 07:26 UTC
Labels: T-bug, S-confirmed
