### ISSUE TITLE
Water culls improperly when behind stained or tinted glass.

### ISSUE THREAD

**Issue by MadCow667** [jellysquid3/Sodium#2580] opened 2024-06-27 01:03 UTC
### Bug Description

Water is culled in a bizarre way when it is behind stained glass, which sometimes makes it nearly impossible to tell there is even water behind the glass. However, this issue does not apply to regular glass. The issue is most pronounced when viewing from the east, north, and south.

expected behavior (regular glass)
south view
![2024-06-26_20 53 30](https://github.com/CaffeineMC/sodium-fabric/assets/48391734/2ddfab2d-3390-48a4-8d5c-85a9ef2b9fe8)
east view
![2024-06-26_20 54 09](https://github.com/CaffeineMC/sodium-fabric/assets/48391734/483c44fe-8c64-4e52-a70d-731c92c9bf86)
north view
![2024-06-26_20 54 37](https://github.com/CaffeineMC/sodium-fabric/assets/48391734/f1b9faa3-c473-474a-961d-9e5c7eadea65)
west view
![2024-06-26_20 55 17](https://github.com/CaffeineMC/sodium-fabric/assets/48391734/2cb52ce7-5c00-4615-8d09-a3b649d2c127)

actual behavior
south view
![2024-06-26_20 56 03](https://github.com/CaffeineMC/sodium-fabric/assets/48391734/d7a4a4c6-4ba9-435c-8473-4212f96f4051)
east view
![2024-06-26_20 56 20](https://github.com/CaffeineMC/sodium-fabric/assets/48391734/f17821a3-190e-4210-a8a8-452355671a49)
north view
![2024-06-26_20 56 26](https://github.com/CaffeineMC/sodium-fabric/assets/48391734/c4e722de-de80-4948-823d-906a31f91a8b)
west view
![2024-06-26_20 56 49](https://github.com/CaffeineMC/sodium-fabric/assets/48391734/70d34e0a-5be9-4547-94bc-7d7f9254f01d)

The problem also applies to flowing water, and water that is not even directly next to the glass
![2024-06-26_21 00 48](https://github.com/CaffeineMC/sodium-fabric/assets/48391734/3f0b3229-5408-4211-a73d-8b6e6428a186)
![2024-06-26_21 00 56](https://github.com/CaffeineMC/sodium-fabric/assets/48391734/871418e7-e56c-4a20-9c0b-cda7760766b5)

### Reproduction Steps

Create a new creative super flat world , and build a 3x3x4 pillar of glass, then hollow out the center and fill it with water.

I'm using this game setup, with no additional mods or resource packs, and on the default sodium settings:
Minecraft 1.21
fabric 0.15.11
sodium 0.5.9

### Log File

[latest.log](https://github.com/user-attachments/files/16006406/latest.log)

### Crash Report

[crash-2024-06-26_21.03.07-client.txt](https://github.com/user-attachments/files/16006405/crash-2024-06-26_21.03.07-client.txt)

**Comment by IMS212** [comment] 2024-06-27 01:05
Duplicate of #38, will be fixed in 0.6.

**Closed as not planned by IMS212** 2024-06-27 01:05 UTC
Labels: S-needs-triage
