### ISSUE TITLE
Crash on world load

### ISSUE THREAD

**Issue by NothingSpecific** [jellysquid3/Sodium#1721] opened 2023-05-03 03:21 UTC
### Version information

0.4.11+build.26

### Reproduction Steps

1. Start game
2. Join singleplayer world OR server
3. Wait for it to build chunks
4. Watch it crash

### Crash Report file

https://mclo.gs/Jb4d9dz

### Additional information

The crash seems to only happen when I enable Distant Horizons after the latest Sodium update. Disabling Distant Horizons OR downgrading Sodium to 0.4.10+build.24 fixes the issue.

**Comment by piuvas** [comment] 2023-05-03 22:12
could you add the mod incompatibility label to all three of your recent issues?

**Comment by jellysquid3** [comment] 2023-05-07 18:28
This is a duplicate of #1624.

**Comment by NothingSpecific** [comment] 2023-05-07 20:46
@jellysquid3 This can't possibly be a duplicate of #1624, seeing as I'm on X11 and that issue applies specifically to Wayland.

**Comment by jellysquid3** [comment] 2023-05-07 20:49
Sorry, I have been closing a lot of issues today. I didn't intend to close this as a duplicate, just reference it as likely related.

**Comment by jellysquid3** [comment] 2023-05-07 20:50
Can you please still try to edit the configuration file as mentioned in that issue, and see if the problem still happens? I think something about the No Error Context is breaking the graphics stack, because this crash is happening during context creation.

**Comment by NothingSpecific** [comment] 2023-05-07 21:06
I just checked, the solution listed there does solve this issue.

**Closed as not planned** 2023-07-22 01:39 UTC
Labels: T-crash
