### ISSUE TITLE
Clouds are not translucent

### ISSUE THREAD

**Issue by PrivateYT-AG** [jellysquid3/Sodium#2842] opened 2024-10-26 01:53 UTC
### Bug Description

The clouds are completely opaque, and are not translucent like in Sodium 0.5.11. Version is 0.6.0-beta.3
![2024-10-26_08 39 28](https://github.com/user-attachments/assets/d0a49400-eff0-4843-be2b-b9464ecfd47d)

### Reproduction Steps

Steps to reproduce:
-Go to options -> settings -> quality
-Turn on clouds to fancy or fast
-The clouds are opaque

### Log File

[latest.log](https://github.com/user-attachments/files/17528609/latest.log)

### Crash Report

[crash-2024-10-26_08.52.43-client.txt](https://github.com/user-attachments/files/17528611/crash-2024-10-26_08.52.43-client.txt)

**Comment by douira** [comment] 2024-10-26 01:56
I can't reproduce this on `dev` with just sodium. Maybe this was fixed in the mean time or one of the installed mods or your graphics drivers are causing this?

**Comment by douira** [comment] 2024-10-26 02:10
Reproducible with nothing but sodium on [`snapshot/dev`](https://github.com/CaffeineMC/sodium/commit/0488d7df7be44320ab57edb318dcf9119c02a216). Seems to be a regression on 1.21.2+

**Comment by jellysquid3** [comment] 2024-10-26 07:07
Resolved with https://github.com/CaffeineMC/sodium/commit/16a2895f424243df102ffbf2562abdf68bdf02c3. The patch will be included with Sodium 0.6.0-beta.4.

**Closed as completed by jellysquid3** 2024-10-26 07:07 UTC
Labels: T-bug, P-high, A-vanilla-parity
