### ISSUE TITLE
Cauldron looks odd underwater

### ISSUE THREAD

**Issue by FewerFlaws** [jellysquid3/Sodium#469] opened 2021-01-06 23:40 UTC
### Expected Behavior
The cauldron should look the same underwater as it does above water.

### Actual Behavior
The outermost layer an underwater's cauldron's skin is removed when viewed from above trhe water; likely an issue with the moving water texture.

### Reproduction Steps
1. Find a lake.
2. Place a cauldron underwater.
3. Observe the cauldron from air and from within the water.

### Attachments
![2021-01-06_15 28 28](https://user-images.githubusercontent.com/75643699/103833119-05756300-5035-11eb-8c7f-e01ad2f19dd6.png)
(Sodium) Underwater cauldron viewed from air.

![2021-01-06_15 28 26_2](https://user-images.githubusercontent.com/75643699/103833127-0a3a1700-5035-11eb-861e-1c990f3bdeb0.png)
(Sodium) Underwater cauldron viewed from underwater.

![2021-01-06_15 30 25](https://user-images.githubusercontent.com/75643699/103833135-102ff800-5035-11eb-9668-55c02eb64751.png)
(Vanilla) Underwater cauldron viewed from underwater.

### System Information
- Java Version: 1.8.0_271
- CPU: Core i7-3770
- GPU: GTX 1060

![2021-01-06_15 39 38](https://user-images.githubusercontent.com/75643699/103833272-6f8e0800-5035-11eb-8a5b-ee25ce50393f.png)

**Comment by Cloudperry** [comment] 2021-01-10 13:14
I can't reproduce this issue. For me it looks exactly as in vanilla.

Sodium:
![2021-01-10_15 05 02](https://user-images.githubusercontent.com/25011618/104123770-bd688000-5355-11eb-9041-b772b71ea41f.png)

Vanilla:
![2021-01-10_15 15 41](https://user-images.githubusercontent.com/25011618/104123965-c3ab2c00-5356-11eb-81af-0f9ccc79c611.png)

I guess this could be an Nvidia driver issue, since you are using an Nvidia gpu and I'm using AMD.

**Comment by FewerFlaws** [comment] 2021-01-10 19:16
Interesting.  Upon a bit of further investigation I immediately notice that the running water texture sometimes disappears and doesn't always cause this issue.  In the screenshots I originally posted you can see that the running water texture is z-fighting with the cauldron side.

One potentially relevant thing to mention is that I have "use compact vertex format" turned off.  I'll do some more investigation.

Here's a couple screenshots showing the running water texture disappearing when viewed from slightly different angles:
![2021-01-10_10 09 59](https://user-images.githubusercontent.com/75643699/104132933-4622f400-5335-11eb-9643-2cf373ecdf7c.png)
![2021-01-10_10 09 57](https://user-images.githubusercontent.com/75643699/104132934-46bb8a80-5335-11eb-8c0f-602cf5bd631f.png)

**Comment by FewerFlaws** [comment] 2021-01-10 19:23
Oh, here we go.  I duplicated the issue using viewing angles and made a video right [here](https://drive.google.com/file/d/1F296v-QdgMIko6kPERe7lnE6g5k9nhhK/view?usp=sharing).

**Comment by Cloudperry** [comment] 2021-01-14 11:32
I wouldn't say that the cauldron's side not rendering is for sure z-fighting. I still can't reproduce the cauldron side texture not rendering even when trying weird angles. I do have the same issue with the flowing water textures not rendering from some angles though.

[Here](https://drive.google.com/file/d/1_TB2g5EsKFcHKXDZXWItM8v6pxEN5gxV/view?usp=sharing) is a video of the rendering bugs (pretty bad quality because I don't usually record my screen on Linux and 1440p monitor makes it harder). I also tried with vanilla and the only difference was that the flowing water texture was always visible on all sides of the cauldron.

These are the settings I'm using
![2021-01-14_13 02 45](https://user-images.githubusercontent.com/25011618/104585402-9e773000-566c-11eb-8119-4a099f772895.png)
![2021-01-14_13 02 47](https://user-images.githubusercontent.com/25011618/104585412-a20ab700-566c-11eb-94c0-3488c6121f12.png)

**Comment by Cloudperry** [comment] 2021-01-14 12:06
Okay so I tried sodium-fabric-mc1.16.4-0.1.1-SNAPSHOT-1609237523.jar, that can be found on the #mod-testers channel on JellySquid's discord. With it there are no bugs with the flowing water texture when looking at it from below the water surface. However that version still has rendering bugs when looking at the flowing water texture from above the water surface.

**Comment by MeeniMc** [comment] 2023-05-11 02:18
Resolved in 0.4.10, probably same issue as #394

**Closed as completed** 2023-05-11 11:22 UTC
Labels: T-bug, S-fixed
