### ISSUE TITLE
Lecterns have black lines in their model with Sodium.

### ISSUE THREAD

**Issue by Lolothepro** [jellysquid3/Sodium#1995] opened 2023-08-12 19:41 UTC
### Bug Description

![2023-08-12_21 37 55](https://github.com/CaffeineMC/sodium-fabric/assets/68275908/648f4542-8046-4bc3-8a3d-6e2640ac70f7)

### Reproduction Steps

place a lectern

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12328153/latest.log)

### Crash Report

[crash-2023-08-12_21.40.59-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12328154/crash-2023-08-12_21.40.59-client.txt)

**Comment by Altirix** [comment] 2023-08-12 20:52
Could reproduce in positive X & Z directions only.

**Comment by muzikbike** [comment] 2023-08-12 21:12
Can we be sure this isn't #1902?

**Comment by jellysquid3** [comment] 2023-08-14 18:19
We can't really fix any of these vertex precision issues until the fluid renderer is rewritten to not abuse them. At that point, it should become possible to correct the off-by-one issue which affects texture coordinates, since it won't cause texture gaps in fluid rendering.

**Comment by jellysquid3** [comment] 2023-08-14 18:20
I believe this is a duplicate of #1902 since the problem in both cases is a result of subtly incorrect UV coordinates which are introduced in the vertex compression step.

**Closed as not planned by jellysquid3** 2023-08-14 18:20 UTC
Labels: E-duplicate
