### ISSUE TITLE
1.19 Sodium 0.4.2-build.16 freezes on splash screen

### ISSUE THREAD

**Issue by rayzchen** [jellysquid3/Sodium#1433] opened 2022-08-22 17:01 UTC
### Version information

mc1.19-0.4.2+build.16

### Expected Behavior

Launch normally

### Actual Behavior

Freezes after loading a bit

### Reproduction Steps

Launch fabric with sodium

### Java version

Java 17

### CPU

Intel Core i5-3210M

### GPU

Intel HD Graphics 4000

**Comment by rayzchen** [comment] 2022-08-22 17:08
Updating to 1.19.2 fixes this problem, but 1.19 does not work

**Comment by KerimPotter** [comment] 2022-08-24 11:17
I have the same issue. The Java version, CPU and GPUs are same. But I'm using 1.19.2 and doesn't work. I didn't tested 1.19.

**Comment by KerimPotter** [comment] 2022-08-24 11:30
When I switched my GPU to Nvidia Geforce gt620m, It's opens. @rayzchen If you have a external GPU, go to windows settings > search graphic settings. Select desktop app > browse > find javaw.exe > options > select your external GPU. I hope it solves your problem.

**Comment by pajicadvance** [comment] 2023-05-14 11:58
Duplicate of #899.

**Closed as not planned by pajicadvance** 2023-05-14 11:58 UTC
Labels: T-bug, E-duplicate, A-drivers
