### ISSUE TITLE
Chunk glitch/bug with water behind glass

### ISSUE THREAD

**Issue by Killstepz** [jellysquid3/Sodium#1214] opened 2022-03-05 11:16 UTC
### Version information

sodium-fabric-mc1.18.2-0.4.1+build.15

### Expected Behavior

The weird lines from the chunks in the water behind glass should not be seen, (also the water with sodium is super clear behind glass i really love it)

### Actual Behavior

![2022-03-05_12 04 48](https://user-images.githubusercontent.com/63002661/156880755-9e0e89ca-dc07-48d8-ba81-e12c1ac420b3.png)
![2022-03-05_12 04 36](https://user-images.githubusercontent.com/63002661/156880756-62f53842-b378-430a-8d7f-473c28c6df1d.png)

### Reproduction Steps

Nothing Happends

### Java version

1.18.2 (but this bug is there since sodium first release)

### CPU

IntelR Core i7-7820x 3,6GHz

### GPU

NVIDIA 1080 8GB

### Additional information

im just using Sodium, with Fabric loader both on the most updated versions, but iv always had this bug seen with any versions of fabric/sodium, this bug was always there.

**Comment by justadudeongithub** [comment] 2022-03-06 17:31
Can confirm 1.18.1 & sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14. Also, water doesn't render at all behind stained glass. Axolotls look like they're swimming in the air. Related, maybe?
https://imgur.com/x3z2pft

**Comment by Lythael** [comment] 2022-03-06 18:22
I have same issue also it isn't even just restrticted to water blocks behind glass. The flowing water blocks themselves don't get their textures rendered properly as mentioned in https://github.com/CaffeineMC/sodium-fabric/issues/1216 causing very similar "artifacts" (for the lack of better word) to appear.

But yea the issue is most visible with Flowing liquid blocks behind Tinted glass blocks.

**Comment by Killstepz** [comment] 2022-03-06 20:16
> Can confirm 1.18.1 & sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14. Also, water doesn't render at all behind stained glass. Axolotls look like they're swimming in the air. Related, maybe? https://imgur.com/x3z2pft

i kinda like that the water looks invisible behind glass, its looks super clear and clean, this should stay actually, or atleast there be an option for this, but the chunk line error should be fixed.

**Comment by Lythael** [comment] 2022-03-06 20:41
> > Can confirm 1.18.1 & sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14. Also, water doesn't render at all behind stained glass. Axolotls look like they're swimming in the air. Related, maybe? https://imgur.com/x3z2pft
> 
> i kinda like that the water looks invisible behind glass, its looks super clear and clean, this should stay actually, or atleast there be an option for this, but the chunk line error should be fixed.

Problem is this "mod" i supposed to boost performance WITHOUT changing anything how vanilla looks.
This issue is the opposite of that idea. 

Both the artifacting water and invisible water behind Tinted Glass should be fixed (btw regular Glass has no issues water renders like in vanilla behind it)

For "clean water" purpose that's what data/texture packs are for.

EDIT: Happens with Ice too so both behind Tited Glass and Ice water textures glitch out.

**Comment by magneticflux-** [comment] 2022-03-06 21:04
Duplicate of https://github.com/CaffeineMC/sodium-fabric/issues/38

**Closed as completed** 2022-03-08 03:29 UTC
Labels: T-bug, E-duplicate
