### ISSUE TITLE
F3+A Crash (only for Sodium)

### ISSUE THREAD

**Issue by 1QMIK** [jellysquid3/Sodium#1578] opened 2023-01-19 17:01 UTC
### Version information

sodium-fabric-mc1.19.3-0.4.8+build.22

### Reproduction Steps

1. If I spam F3+A game crashes 100%
2. If I'm entering dimensions game sometimes crashes

### Crash Report file

[hs_err_pid16856.log](https://github.com/CaffeineMC/sodium-fabric/files/10458970/hs_err_pid16856.log)

### Additional information

Also I played hardcore and items were just duplicating or dissappearing

**Comment by 1QNIK** [comment] 2023-01-19 17:17
Also I played hardcore and items were just duplicating or dissappearing

**Comment by Timolino456** [comment] 2023-02-12 20:26
Could you send a latest.log? This sound a lot like the NVIDIA driver crash issue, but it should be fixed in the version of Sodium you're using.

**Comment by DuisPlay** [comment] 2023-04-08 21:11
I updated today my NVIDIA driver and what should I say? After every 2nd entry into a portal, Minecraft crashes with error code 1. 

Infos:
Minecraft 1.19.3
Sodium 0.4.9
Fabric 0.14.19
Nvidia Driver Version 531.41
[hs_err_pid17708.log](https://github.com/CaffeineMC/sodium-fabric/files/11184241/hs_err_pid17708.log)

**Comment by pajicadvance** [comment] 2023-05-12 18:10
Can you provide the full game log? Does the Minecraft window title say "Minecraft (version hidden from driver)" when you launch the game?

**Comment by jellysquid3** [comment] 2023-07-22 01:46
Not a problem with Sodium. The issue is with the NVIDIA Graphics Driver, as described in #1486 and #1816. See the [known issues](https://github.com/CaffeineMC/sodium-fabric/wiki/Driver-Compatibility) for information on how to fix it.

**Closed as not planned by jellysquid3** 2023-07-22 01:46 UTC
Labels: E-external, T-crash

**Comment by Shadows-of-Fire** [comment] 2023-09-27 23:17
If this bug is the same as  https://bugs.mojang.com/browse/MC-263607 it should be resolved in upcoming driver version 545

**Comment by pajicadvance** [comment] 2023-09-27 23:26
> If this bug is the same as https://bugs.mojang.com/browse/MC-263607 it should be resolved in upcoming driver version 545

Where is this info coming from?
