### ISSUE TITLE
Sodium causes my game to basically destroy itself

### ISSUE THREAD

**Issue by moosetwin0** [jellysquid3/Sodium#633] opened 2021-04-14 22:10 UTC
I just accidently deleted this and now I have to write it again :(
### Version Information

>sodium-fabric-mc1.16.3-0.1.0
### Expected Behavior

> Speed up my game

### Actual Behavior

> Texture madness? Not really sure how to describe it.

### Reproduction Steps

> 1. Download & install Fabric
> 2. Put latest version of Sodium in mods folder
> 3. Run Minecraft
> 4. Start OBS
> 5. Run the Demo world from the Curseforge page

### System Information

> - Java Version: 1.16.5
> - CPU: Intel i7-3770 @ 3.40 GHz
> - GPU: Intel HD 4000

### Other Information

> No other mods
> Before Sodium: https://youtu.be/sY2rz7D7ApM
> After Sodium: https://youtu.be/920fyrKaMPU
> Obligatory Rickroll: (Although I am actually experiencing this problem) https://youtu.be/6n3pFFPSlW4
> For some reason it appears correctly when in water.

**Comment by silversquirl** [comment] 2021-04-14 22:41
Change `Chunk Renderer` to `Oneshot (GL 3.0)` under the Advanced tab in Video Settings

**Comment by silversquirl** [comment] 2021-04-14 22:43
Duplicate of #179

**Closed as completed by silversquirl** 2021-04-14 22:43 UTC
Labels: T-bug, E-duplicate
