### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by Tsaitou7361** [jellysquid3/Sodium#1420] opened 2022-08-09 08:07 UTC
Hello, Sodium team.
Your mod gives me better performance on my PC.
But, even this mod have good optimization, if no a good translation, user can't find want setting, then can't make most better performance of game.
So I make a translationed Chinese lang document for Sodium.
[link](https://www.mediafire.com/file/wrstcho3elmo5mc/zh_tw.json/file)
Can add this to after sodium mod? thanks.
If I make it update I will write this again, or your team re-translate

2022.08.09 16:07/UTC+8

**Comment by Tsaitou7361** [comment] 2022-08-09 08:14
If my article inaccurate words, I'm sorry, Cause my English is bad, so I make this

**Comment by IMS212** [comment] 2022-08-24 17:01
Duplicate of #44, currently translations are not being accepted.

**Closed as not planned by IMS212** 2022-08-24 17:01 UTC
Labels: T-enhancement, S-needs-triage

**Comment by Tsaitou7361** [comment] 2022-08-25 04:12
Ok, Thanks for your reply to me.
