### ISSUE TITLE
Ice z-fighting

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#866] opened 2021-08-29 17:57 UTC
### Version information

sodium-fabric-mc1.17.1-0.3.1+build.6

### Expected Behavior

Ice should not have weird z-fighting while swimming underwater.

### Actual Behavior

Ice has weird z-fighting. See video below:

https://user-images.githubusercontent.com/75946024/131260403-efb0323b-41be-4f3b-8010-6175e01b10ac.mp4

### Reproduction Steps

1. Find frozen_ocean biome.
2. Swim underwater and look at the icebergs. 
3. Observe weird z-fighting at ice far away.

### Java version

16.0.1.9.1

### CPU

8x Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz

### GPU

NVIDIA GeForce GTX 1080/PCIe/SSE2 GL version 3.2.0 NVIDIA 471.41, NVIDIA Corporation

### Additional information

I tested this with nothing but fabric api and sodium 0.3.1. Issue still observed.

**Comment by amnotbananaama** [comment] 2021-08-29 18:13
I *believe* this is a duplicate of #38. Someone correct me if I am wrong please

**Closed as completed by amnotbananaama** 2021-08-29 18:13 UTC
Labels: E-duplicate

**Comment by Altirix** [comment] 2021-09-11 06:38
> 
> 
> I _believe_ this is a duplicate of #38. Someone correct me if I am wrong please

nah, just had a look, its Z fighting seems to affect ice and tinted glass, also noticed it wont render water or other transparent blocks that are placed next to the tinted glass. if you place normal glass or coloured glass you dont have the running water rendered of the face

https://github.com/CaffeineMC/sodium-fabric/blob/68ca12bcbd57eddfaf47aa66492464540c2c7581/src/main/java/me/jellysquid/mods/sodium/client/render/pipeline/FluidRenderer.java#L329

but seems water not rendering thru the glass/ice types is something else 
![image](https://user-images.githubusercontent.com/19439141/132939614-ce099956-b057-4d7b-b73f-3aa2d4ef00b4.png)
