### ISSUE TITLE
Block Placing

### ISSUE THREAD

**Issue by Oculie** [jellysquid3/Sodium#1829] opened 2023-06-20 10:32 UTC
### Version information

mc1.20-0.4.10+build.27-sources

### Expected Behavior

Normal Chunks

### Actual Behavior

Chunks flickers whenever a block/s gets placed or broken, This doesn't seem to happen when using OptiFine. This has been my problem with Sodium ever since.

### Reproduction Steps

Just place blocks and chunks will flick.

### Java version

Java 17.0.3 64bit

### CPU

4x Intel(R) Pentium (R) Silver N6000 @ 1.10Ghz

### GPU

Intel(R) HD Graphics Gen11

### Additional information

Lunar Client, Bundled with Iris. This also happens even if I just use Sodium itself in vanilla.

**Comment by Lolothepro** [comment] 2023-06-20 10:43
Duplicate of https://github.com/CaffeineMC/sodium-fabric/issues/869

**Closed as not planned** 2023-06-21 11:33 UTC
Labels: T-bug, A-drivers
