### ISSUE TITLE
Allow to render the game in a % of the current screen resolutions

### ISSUE THREAD

**Issue by gabboman** [jellysquid3/Sodium#416] opened 2020-12-10 18:09 UTC
**Is your feature request related to a problem? Please describe.**
I use some low end computers to play the game. The problem is that some of them can't handle thegame in a medium sized window.

**Describe the solution you'd like**
Add an option to render at a 60% or 40% of the resolution, like optifine.

**Describe alternatives you've considered**
Allow to set the render resolution to some steps like 0.5, 0.7 and even 1.5 or 2 for high end systems
**Additional context**

**Comment by gabboman** [comment] 2020-12-10 18:12
![Captura de pantalla 2020-12-10 a las 19 11 49](https://user-images.githubusercontent.com/3456181/101812430-a139af00-3b1b-11eb-8e97-7b2d3f8e32f2.png)
screenshot of the feature in optifine

**Comment by amnotbananaama** [comment] 2020-12-12 08:40
Closing as a duplicate of #121

**Closed as completed by amnotbananaama** 2020-12-12 08:40 UTC
Labels: E-duplicate, T-enhancement
