### ISSUE TITLE
nametags don't render their background in 1.21.4

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#2917] opened 2024-12-07 00:52 UTC
### Bug Description

Nametags should have a dark backdrop behind them
![image](https://github.com/user-attachments/assets/bb67ec57-9686-4e11-bf31-6d84a4b69ba4)

### Reproduction Steps

Look at a name tag on sodium 1.21.4

### Log File

N/A

### Crash Report

N/A

**Comment by douira** [comment] 2024-12-07 00:58
Duplicate of https://github.com/CaffeineMC/sodium/issues/2909, fixed in Sodium 0.6.3

**Closed as not planned by douira** 2024-12-07 00:58 UTC
Labels: E-duplicate
