### ISSUE TITLE
when entering water all textures get mixed, even airblocks, everything turns into a vomit 

### ISSUE THREAD

**Issue by scaloy** [jellysquid3/Sodium#153] opened 2020-07-23 04:41 UTC
### Expected Behavior
I mean, when entering water you should.. just get underwater

### Actual Behavior
but instead all textures just randomize and you can't see anything anymore because even airblocks get a random texture

### Reproduction Steps
1-i've downloaded the mod;
2-installed it;
3-when i loaded the first map i noticed the water textures where invisible;
4-then when i went to check, everything turned into random forest textures, i can provide a screenshot tomorrow morning if wanted

### Attachments
can only give'em to you tomorrow :v

### System Information
intel core i5-330
4RAM
Windows8

- Java Version: [latest?]
- CPU: [intel core i5]
- GPU: [i have no idea, sorry]

**Comment by LucilleTea** [comment] 2020-07-23 05:42
This is probably a duplicate of #127. You should be able to work around it by going to Video Settings > Advanced and changing the Chunk Renderer setting to Oneshot (GL 3.0).

**Comment by scaloy** [comment] 2020-07-23 13:19
I will try this, if it works I'll let you know :D

**Comment by scaloy** [comment] 2020-07-23 14:07
oh thanks, it worked, but the fps seems to be a bit of the same as before,
but it's probably my computers fault..

thanks anyways :)

**Comment by jellysquid3** [comment] 2020-07-25 17:48
Merging this issue into #179.

**Closed as completed by jellysquid3** 2020-07-25 17:48 UTC
Labels: T-bug
