### ISSUE TITLE
Air is replaced by random blocks

### ISSUE THREAD

**Issue by thevasek** [jellysquid3/Sodium#362] opened 2020-10-25 17:48 UTC
![ED6F99F4-86D9-4A3B-91EC-C471DEB8F0A8](https://user-images.githubusercontent.com/73439704/97114737-94d7cf00-16f2-11eb-8cbe-fc984a564ddf.jpeg)
This 
![Uploading 8E62B51B-7983-427B-9915-13ADB1C11053.jpeg…]()

**Comment by thevasek** [comment] 2020-10-25 17:49
![Uploading 4A4009E2-C55F-4A12-9566-EFBAC4EFC2A1.jpeg…]()

**Comment by amnotbananaama** [comment] 2020-10-26 06:40
In the future, please use [the issue templates](https://github.com/jellysquid3/sodium-fabric/issues/new/choose) they exist so that we can more easily help you.

This is either a duplicate of #179 or #24 depending on which graphics card you are using. There will be a workaround in the next release, in the meantime you can workaround this by going to `Options` -> `Video Settings` -> `Advanced` and setting "Chunk Renderer" to 3.0 or 2.1. This should fix your issue for now.

**Closed as completed by amnotbananaama** 2020-10-26 06:40 UTC
Labels: T-bug, E-duplicate

**Comment by thevasek** [comment] 2020-10-26 10:35
Thank you so much.
