### ISSUE TITLE
When breaking a block while looking straight down, the block breaking animation disappears.

### ISSUE THREAD

**Issue by Eldritch6847** [jellysquid3/Sodium#329] opened 2020-10-02 23:54 UTC
[The bug in action](https://www.youtube.com/watch?v=ns_0nIWVhr4)

My Fabric Version:
![image](https://user-images.githubusercontent.com/72284711/94977889-e7a1da80-04e8-11eb-95bf-5dac64515fe9.png)

My Modlist:
![image](https://user-images.githubusercontent.com/72284711/94977860-bf19e080-04e8-11eb-81f7-520181521e3d.png)

Here are my settings:
![image](https://user-images.githubusercontent.com/72284711/94977624-99400c00-04e7-11eb-8990-44d4ff8c844f.png)
![image](https://user-images.githubusercontent.com/72284711/94977633-a826be80-04e7-11eb-8f90-cb5f5f1afc7b.png)
![image](https://user-images.githubusercontent.com/72284711/94977653-b4ab1700-04e7-11eb-8fe8-d2dc14640865.png)

My minecraft F3 menu, if thats important:
![image](https://user-images.githubusercontent.com/72284711/94977811-72cea080-04e8-11eb-8e21-c3b1f2f7922f.png)

**Comment by Eldritch6847** [comment] 2020-10-02 23:58
Update: The issue also happens when looking at a block straight on while breaking it

**Comment by amnotbananaama** [comment] 2020-10-03 02:37
This was (supposedly) fixed in a7f058b which has not made it into a release yet. This is either a duplicate of #36 or #232, I’m not 100% sure if it is still occurring.

**Closed as completed by amnotbananaama** 2020-10-03 02:37 UTC
Labels: T-bug, E-duplicate
