### ISSUE TITLE
Cannot see Create copycat panels through each other except at multiple of 10 y levels

### ISSUE THREAD

**Issue by drewcassidy** [jellysquid3/Sodium#1919] opened 2023-07-29 04:46 UTC
### Bug Description

I cannot see the copycat steps below the copycat panels with the panel at y level 76 and facing east
<img width="1512" alt="image" src="https://github.com/CaffeineMC/sodium-fabric/assets/3837797/bace811a-9d71-4157-9052-e6e39ed74001">
<img width="1512" alt="image" src="https://github.com/CaffeineMC/sodium-fabric/assets/3837797/9d159d70-5789-4d38-a517-9cd5ec46119d">

One floor up with the panel at y level 80, I can see through it just fine
<img width="1512" alt="image" src="https://github.com/CaffeineMC/sodium-fabric/assets/3837797/1e582554-d43c-4435-8cda-1d2f7defd782">

Confirmed this pattern repeats at y=70 as well, so I think its every 10 blocks

I thought it was some kind of overeager culling but I can see parts of the step when it pokes out from behind the panel. draw order maybe?

### Reproduction Steps

Place a Create copycat panel at a multiple of 10 y level, then a step below it. Try to look at the step through the panel.

### Log File

https://mclo.gs/ZGqaKra
[sodium-options.json.txt](https://github.com/CaffeineMC/sodium-fabric/files/12206289/sodium-options.json.txt)

### Crash Report

https://mclo.gs/bhW7GO1

**Comment by astridellensdottir** [comment] 2023-07-29 18:11
is this #38? y=80 is a subchunk boundary, it would make sense to me.

**Comment by drewcassidy** [comment] 2023-08-05 20:29
Maybe, but I don't think the blocks are translucent, they're binary alpha.

**Comment by AMDKilla** [comment] 2023-11-18 11:33
Try disabling the flywheel backend. /flywheel backend off

**Comment by PepperCode1** [comment] 2024-02-16 21:06
This is caused by the fact that copycat blocks always render on the translucent layer and that Sodium did not have translucency sorting. Now that #38 is fixed, this issue is also fixed. However, this should also be fixed on Create Fabric's side; it is already reported as Fabricators-of-Create/Create#964.

**Comment by drewcassidy** [comment] 2024-02-17 03:36
That makes sense, explains why it happens despite the bars being cutout rendered (though probably shouldn't be for mipmap reasons). 

Looks like 0.6 is close to coming out, I'm looking forward to it :)

**Comment by jellysquid3** [comment] 2024-02-17 04:46
Going to merge this into the Sodium 0.6 milestone then, since it looks resolved.

**Closed as completed by jellysquid3** 2024-02-17 04:46 UTC
Labels: T-bug, A-mods
