### ISSUE TITLE
Block with custom VoxelShapes not rendering behind block.

### ISSUE THREAD

**Issue by RXJpaw** [jellysquid3/Sodium#1250] opened 2022-03-30 01:29 UTC
### Version information

sodium-fabric-mc1.18.2-0.4.1+build.15

### Expected Behavior

Directional faces of "Block with custom VoxelShapes" should render behind blocks.

### Actual Behavior

Directional faces of "Block with custom VoxelShapes" aren't rendering at all and showing the skybox instead.

### Reproduction Steps

1. Create your own Fabric Mod including a Block with custom VoxelShapes.
2. Place a block in direction of the removed section of the block.

### Java version

Java 17.0.1

### CPU

AMD Ryzen 5 2600

### GPU

NVIDIA GeForce GTX 1660 SUPER

### Additional information

Disabling parts of the config wont fix it.

Not Blocking:
![image](https://user-images.githubusercontent.com/45784529/160732662-2100c219-c07b-4c8f-ba41-0066573ccfbd.png)

Blocking:
![image](https://user-images.githubusercontent.com/45784529/160732687-7afabae3-25e2-4dd8-8319-5d4b11b6c69d.png)

**Comment by jellysquid3** [comment] 2023-11-06 18:13
This issue is old and we don't have a test case to actually reproduce the problem. We've made some improvements to the face culling code since this issue was created, so the issue described here might just be fixed nowadays. If it isn't, then please provide an example mod/resource pack which demonstrates this problem, and ask for the issue to be re-opened.

**Closed as not planned by jellysquid3** 2023-11-06 18:13 UTC
Labels: T-bug, S-cannot-repro
