### ISSUE TITLE
Kibe's Invisible items due to sodium

### ISSUE THREAD

**Issue by Lunize** [jellysquid3/Sodium#1458] opened 2022-09-22 14:36 UTC
### Version information

1.19.2

### Expected Behavior

Nothing should be invisible.

### Actual Behavior

Several items such as draw bridge / xp tank & entangled items are completely invisible not only in inventory but when placed. 

### Reproduction Steps

searching for items in creative and or placing them they are invisible.

### Java version

Java 17

### CPU

i7-7700k

### GPU

Nvidia GTX 1080 TI 

### Additional information

This has been a known bug since 2021 I'd really like to see if it gets fixed especially seeing how the mod has over 2 million downloads I cant be the only one experiencing this problem but the mod also offers some of the best misc features from older mod packs. I'd rate it 10/10 if it was fully functional with sodium but current state would be 7/10 ;(

**Comment by bytzo** [comment] 2022-09-27 22:05
Since Kibe uses the Fabric Rendering API to render some items, you will need to install [Indium](https://modrinth.com/mod/indium) alongside Sodium. See https://github.com/lucaargolo/kibe/issues/168 for more information.

**Comment by pajicadvance** [comment] 2023-05-10 17:40
Duplicate of #5.

**Comment by piuvas** [comment] 2023-05-14 11:43
i think you forgot do close it.

**Comment by pajicadvance** [comment] 2023-05-14 11:45
Definitely did, thanks :)

**Closed as not planned by pajicadvance** 2023-05-14 11:45 UTC
Labels: T-bug, E-duplicate, A-mods
