### ISSUE TITLE
Game crashing when finishing to generate world

### ISSUE THREAD

**Issue by startFX** [jellysquid3/Sodium#1750] opened 2023-05-10 17:05 UTC
### Version information

fabric-loader-0.14.19-1.19.3

### Reproduction Steps

1. Create a world
2. When finishing to generate, game crashes

### Crash Report file

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2023-05-10 19:01:55
Description: Unexpected error

java.lang.NoClassDefFoundError: net/caffeinemc/mods/sodium/api/vertex/buffer/VertexBufferWriter
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:153)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.diebuddies.render.MainRenderer.render(MainRenderer.java:417)
	at net.diebuddies.render.MainRenderer.renderAll(MainRenderer.java:219)
	at net.minecraft.class_761.handler$bao000$physicsmod$renderMain(class_761.java:9453)
	at net.minecraft.class_761.method_3251(class_761.java:12016)
	at net.minecraft.class_761.invokeRenderChunkLayer(class_761.java)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:429)
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:808)
	at net.minecraft.class_761.handler$zlc000$iris$renderTerrainShadows(class_761.java:6509)
	at net.minecraft.class_761.method_22710(class_761.java:1234)
	at net.minecraft.class_757.method_3188(class_757.java:1085)
	at net.minecraft.class_757.method_3192(class_757.java:864)
	at net.minecraft.class_310.method_1523(class_310.java:1193)
	at net.minecraft.class_310.method_1514(class_310.java:781)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: net.caffeinemc.mods.sodium.api.vertex.buffer.VertexBufferWriter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 26 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:153)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.diebuddies.render.MainRenderer.render(MainRenderer.java:417)
	at net.diebuddies.render.MainRenderer.renderAll(MainRenderer.java:219)
	at net.minecraft.class_761.handler$bao000$physicsmod$renderMain(class_761.java:9453)
	at net.minecraft.class_761.method_3251(class_761.java:12016)
	at net.minecraft.class_761.invokeRenderChunkLayer(class_761.java)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:429)
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:808)
	at net.minecraft.class_761.handler$zlc000$iris$renderTerrainShadows(class_761.java:6509)
	at net.minecraft.class_761.method_22710(class_761.java:1234)
	at net.minecraft.class_757.method_3188(class_757.java:1085)

-- Affected level --
Details:
	All players: 1 total; [class_746['itzDirty_boi'/299, l='ClientLevel', x=0.50, y=77.00, z=3.50]]
	Chunk stats: 1024, 213
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,84,0), Section: (at 0,4,0 in 0,5,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 25 game time, 25 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:455)
	at net.minecraft.class_310.method_1587(class_310.java:2390)
	at net.minecraft.class_310.method_1514(class_310.java:805)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, Fabric Mods, minecraft/physicsmod

-- System Details --
Details:
	Minecraft Version: 1.19.3
	Minecraft Version ID: 1.19.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 820776424 bytes (782 MiB) / 1946157056 bytes (1856 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) CPU E3-1270 V2 @ 3.50GHz
	Identifier: Intel64 Family 6 Model 58 Stepping 9
	Microarchitecture: Ivy Bridge (Client)
	Frequency (GHz): 3.49
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: AMD Radeon HD 7800 Series
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x6818
	Graphics card #0 versionInfo: DriverVersion=27.20.20913.2000
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 1.60
	Memory slot #1 type: DDR3
	Memory slot #2 capacity (MB): 4096.00
	Memory slot #2 clockSpeed (GHz): 1.60
	Memory slot #2 type: DDR3
	Memory slot #3 capacity (MB): 4096.00
	Memory slot #3 clockSpeed (GHz): 1.60
	Memory slot #3 type: DDR3
	Virtual memory max (MB): 18772.73
	Virtual memory used (MB): 12830.64
	Swap memory total (MB): 2432.00
	Swap memory used (MB): 38.91
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric-api: Fabric API 0.76.1+1.19.3
			fabric-api-base: Fabric API Base 0.4.21+70be179c85
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.20+49abcf7e85
			fabric-biome-api-v1: Fabric Biome API (v1) 12.1.2+f1c68e5885
			fabric-block-api-v1: Fabric Block API (v1) 1.0.5+e022e5d185
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.31+928d44d585
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.12+1134c5b885
			fabric-command-api-v1: Fabric Command API (v1) 1.2.23+f71b366f85
			fabric-command-api-v2: Fabric Command API (v2) 2.2.2+2961b4a085
			fabric-commands-v0: Fabric Commands (v0) 0.2.40+df3654b385
			fabric-containers-v0: Fabric Containers (v0) 0.1.47+df3654b385
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.3+1d37d50285
			fabric-convention-tags-v1: Fabric Convention Tags 1.3.0+521b5c5285
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.14+aeb40ebe85
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.3.3+40dc7a9485
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.42+00a2eb1085
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.7+b83334a085
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.40+3baeb27a85
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.45+df3654b385
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.30+99f9db8085
			fabric-item-api-v1: Fabric Item API (v1) 2.1.11+71b8257385
			fabric-item-group-api-v1: Fabric Item Group API (v1) 2.1.14+b5470ac785
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.31+bc01e09785
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.29+df3654b385
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.10+23a79c8a85
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.22+75e9821185
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.26+9e7660c685
			fabric-message-api-v1: Fabric Message API (v1) 5.1.0+c85585f885
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.33+49abcf7e85
			fabric-models-v0: Fabric Models (v0) 0.3.27+11ba9c3b85
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.17+4017a8cb85
			fabric-networking-v0: Fabric Networking (v0) 0.3.34+df3654b385
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 5.4.3+eb2a3ba985
			fabric-particles-v1: Fabric Particles (v1) 1.0.20+f1e4495b85
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.1+5176f73d85
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.1.0+f7b4d36485
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.2.2+3a95925a85
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.8.0+3a95925a85
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.31+df3654b385
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.25+afca2f3e85
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.18+f1e4495b85
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.34+df3654b385
			fabric-rendering-v1: Fabric Rendering (v1) 1.13.0+ad17775585
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.0+e63306e085
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.1+b93ffe4d85
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.41+f1e4495b85
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.13+99f9db8085
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.8+75e9821185
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.15+ccd377ba85
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 2.3.1+40dc7a9485
		fabricloader: Fabric Loader 0.14.19
		iris: Iris 1.5.2
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre9
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.19.3
		physicsmod: Physics Mod 2.12.4
		sodium: Sodium 0.4.9+build.23
	Loaded Shaderpack: ComplementaryReimagined_r1.4.zip
		Profile: Custom (+13 options changed by user)
	NEC status: No NEC detected
	Launched Version: fabric-loader-0.14.19-1.19.3
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: AMD Radeon HD 7800 Series GL version 3.2.14830 Core Profile Forward-Compatible Context 22.6.1 27.20.20913.2000, ATI Technologies Inc.
	Window size: 1920x1017
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, fabric
	Current Language: English (US)
	CPU: 8x Intel(R) Xeon(R) CPU E3-1270 V2 @ 3.50GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['itzDirty_boi'/299, l='ServerLevel[physicss]', x=0.50, y=77.00, z=3.50]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable

### Additional information

I have 4 mods installed : Sodium, Iris, Physics Mod Pro v153b and fabric api. All for Minecraft Fabric 1.19.3

**Comment by Octol1ttle** [comment] 2023-05-10 17:11
Duplicate of #1745

**Closed as not planned** 2023-05-10 18:04 UTC
Labels: E-duplicate, A-mods, T-crash
