### ISSUE TITLE
Java 17 support

### ISSUE THREAD

**Issue by eshankiyer** [jellysquid3/Sodium#920] opened 2021-09-26 14:20 UTC
Java 17 GA has just released, and I tried it out with fabric + CaffeineMC. It didn't work but I was just wondering what would be the status on implementing it

**Comment by jellysquid3** [comment] 2021-10-01 18:49
Java 17 should work fine. Please provide a log file if there is an issue.

**Comment by amnotbananaama** [comment] 2021-10-01 20:26
Possibly related: [MCL-18306](https://bugs.mojang.com/browse/MCL-18306), which prevents Java 17 from being used with the vanilla launcher. Can you confirm that your issue is with Sodium specifically, as opposed to:
- The vanilla launcher
- Minecraft itself
-  Fabric Loader

If your issue *only* occurs with Sodium installed, please upload a log file as requested

**Comment by eshankiyer** [comment] 2021-10-03 17:32
Uhhhhhhhhhhhh I tried with fabric + fabric api and it booted fine. The log file mentioned something about mixins

**Comment by ghost** [comment] 2021-10-10 15:48
Java 17 And Works So Well With Sodium
Tested many assemblies Java 17 releases and others

Notes java 17 do not work with the luncher from the official minecraft site
Works with other licensed launchers
I will not leave which ones, because not advertising, you can find a lot of them yourself

**Comment by jellysquid3** [comment] 2021-10-10 17:07
I'm going to close this issue since I'm not able to reproduce it, and it works fine both in a developer workspace and in the launcher for me.

**Closed as completed by jellysquid3** 2021-10-10 17:07 UTC
Labels: S-cannot-repro
