### ISSUE TITLE
Sodium detects 15.33 Driver as 10.18.10.5161

### ISSUE THREAD

**Issue by RukoBlood** [jellysquid3/Sodium#2464] opened 2024-05-04 10:37 UTC
### Bug Description

I installed 15.33 driver from your wiki page
But sodium detects this driver as 10.18.10.5161

Forum says that drivers has two versions (Example: 15.33.18.64.3496(10.18.10.3496) )

Also, it is possible to skip IGPU check and run game on dedicated gpu (GT 720M)?

CPU: I5-3230m (2.6ghz, Ivy Bridge)
IGPU: Intel HD 4000 ( 15.33.53.5161 aka 10.18.10.5161)
DGPU: Nvidia GeForce GT 720M

### Reproduction Steps

Run 1.20.5 with latest sodium on I5-3230M with Intel HD 4000

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/15209411/latest.log)

### Crash Report

It crashes without a crash report lol
[2024-04-28-3.log.gz](https://github.com/CaffeineMC/sodium-fabric/files/15209413/2024-04-28-3.log.gz)

**Comment by pajicadvance** [comment] 2024-05-05 15:58
Duplicate of #2432

**Closed as not planned by pajicadvance** 2024-05-05 15:58 UTC
Labels: E-duplicate
