### ISSUE TITLE
Both Sodiam or Sodiam from iris has flesh issue

### ISSUE THREAD

**Issue by jerry-0314** [jellysquid3/Sodium#819] opened 2021-08-05 01:02 UTC
### Version information

minecraft 1.17

### Expected Behavior

It looks like you reload the chunk after break/place/block stacts change(like piston extend) a block and it cause a lot of lag.

### Actual Behavior

It looks like you reload the chunk after break/place/block stacts change(like piston extend) a block and it cause a lot of lag.

### Reproduction Steps

It looks like you reload the chunk after break/place/block stacts change(like piston extend) a block and it cause a lot of lag.

### Java version

java 8/java 16

### CPU

i5 1035G1

### GPU

intel (R) UHD graphics

### Additional information

And i wanna ask is the HopperOptimization from 2No2Name has the version for 1.17 or Lithium has the feature of it

**Comment by Rajbir98** [comment] 2021-08-05 04:21
fix the spelling of sodium

**Comment by Altirix** [comment] 2021-08-05 16:29
known issue with intel XE ive only seen chunk flicker being reported by intel 10th and 11th gen igpus

**Comment by Snivine** [comment] 2021-08-08 20:49
google translator strikes again

**Comment by jellysquid3** [comment] 2021-08-29 18:29
Closing as duplicate of #853 since I'm pretty sure this issue is describing the same problem and is much better described.

**Closed as completed by jellysquid3** 2021-08-29 18:29 UTC
Labels: T-bug
