### ISSUE TITLE
Water and lava flow textures don't render correctly at certain distances

### ISSUE THREAD

**Issue by BoldStep** [jellysquid3/Sodium#193] opened 2020-07-27 06:21 UTC
### Expected Behavior
Water and lava flows should be fully rendered

### Actual Behavior
Portions of the flow rendering are missing at certain distances and position

.

### Reproduction Steps
1. Find or place water or lava flows and allow them to finish
2. Walk some distance away (as long as it's in the frame.)
3. Portions stop rendering depending on position and distance.

### Attachments

![2020-07-27_15 37 07](https://user-images.githubusercontent.com/53684197/88509635-dc33be00-d024-11ea-8100-be8b748f1577.png)
![2020-07-27_15 37 11](https://user-images.githubusercontent.com/53684197/88509642-dfc74500-d024-11ea-8894-1c52b2830f51.png)
![2020-07-27_15 37 38](https://user-images.githubusercontent.com/53684197/88509650-e48bf900-d024-11ea-8f39-65db3e6b4c80.png)
![2020-07-27_16 13 36](https://user-images.githubusercontent.com/53684197/88509659-e9e94380-d024-11ea-9165-8ed8700e8420.png)
![2020-07-27_16 13 39](https://user-images.githubusercontent.com/53684197/88509673-eeadf780-d024-11ea-8117-cf92bc302bd2.png)

### System Information

- Java Version: 1.16.1
- CPU: Intel Core i7 8700K
- GPU: Nvidia Geforce GTX 1080

**Comment by LucilleTea** [comment] 2020-07-27 06:50
Duplicate of #171 (no proper issue tracking it?)
Either way, it's already fixed in the development branch by 5840ca2f42b6f2e29c4ae906fa4c95d4a4d86e38

**Comment by BoldStep** [comment] 2020-07-27 07:06
> Duplicate of #171 (no proper issue tracking it?)
> Either way, it's already fixed in the development branch by [5840ca2](https://github.com/jellysquid3/sodium-fabric/commit/5840ca2f42b6f2e29c4ae906fa4c95d4a4d86e38)

Oh, I tried checking if this was already mentioned, but guess I didn't go far enough. Sorry

**Closed as completed** 2020-07-27 14:53 UTC
Labels: T-bug, E-duplicate
