### ISSUE TITLE
Nether Portal rendering order issue

### ISSUE THREAD

**Issue by marcelwo96** [jellysquid3/Sodium#938] opened 2021-10-15 10:25 UTC
### Version information

sodium-fabric-mc1.17.1-0.3.2+build.7

### Expected Behavior

The nether portal behind light gray stained glass panes should be visible when looked at.

### Actual Behavior

Depending on the position the player is looking from, some horizontal segments of the nether portal don't render at all.

![javaw_BG3Kfm4Sdc](https://user-images.githubusercontent.com/65011954/137472902-23b212a2-6ac7-4770-bdcb-0a341a370fb6.png)
![javaw_FJ5vGuywSl](https://user-images.githubusercontent.com/65011954/137472912-5c1ec32e-5e4f-4c3f-be24-3150ff752c75.png)

### Reproduction Steps

1. Build a nether portal
2. Build a wall with light gray stained glass panes as a window
3. Look at the portal through the window

### Java version

Java 16 

### CPU

Intel Core i5 7300HQ

### GPU

Nvidia GTX 1050Ti

**Comment by silversquirl** [comment] 2021-10-15 10:42
Duplicate of #38

**Closed as completed by silversquirl** 2021-10-15 10:42 UTC
Labels: E-duplicate
