### ISSUE TITLE
my game crash when i start

### ISSUE THREAD

**Issue by wathakate** [jellysquid3/Sodium#745] opened 2021-07-08 12:48 UTC
### Version information

mc1.16.3-0.1.0

### Reproduction Steps

I start the game and crash

### Crash Report file

[crash-2021-06-25_17.06.21-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/6784602/crash-2021-06-25_17.06.21-client.txt)

**Comment by amnotbananaama** [comment] 2021-07-08 13:52
Duplicate of #15. Sodium and Immersive Portals are incompatible at this time

**Closed as completed by amnotbananaama** 2021-07-08 13:52 UTC
Labels: E-duplicate, T-crash
