### ISSUE TITLE
Bug with grass path lighting

### ISSUE THREAD

**Issue by Foxing772** [jellysquid3/Sodium#242] opened 2020-08-08 07:09 UTC
After installing this mod, I noticed that the lighting on the grass paths was gone. Everything works correctly without Sodium. Thanks in advance for your reply.

![LIght Bug](https://user-images.githubusercontent.com/69380184/89704675-66f2b200-d96f-11ea-9787-0fc47a6e4431.png)

**Comment by ZtereoHYPE** [comment] 2020-08-08 07:12
As much as this might seem like a bug, it's not. Sodium here is just applying a shadow of 1/16th of a block (1 pixel) instead of a whole block worth of shadow because there is only 1 pixel rising in the edge. Vanilla instead applies 1 whole block of shadow even though it's incorrect.
EDIT: taken from the discord server

**Comment by Foxing772** [comment] 2020-08-08 08:44
> 
> 
> As much as this might seem like a bug, it's not. Sodium here is just applying a shadow of 1/16th of a block (1 pixel) instead of a whole block worth of shadow because there is only 1 pixel rising in the edge. Vanilla instead applies 1 whole block of shadow even though it's incorrect.
> EDIT: taken from the discord server

Thanks for the answer. Is it possible to return the vanilla lighting without removing sodium?

**Comment by Kroppeb** [comment] 2020-08-08 10:59
> Thanks for the answer. Is it possible to return the vanilla lighting without removing sodium?

Sadly no, iirc readding the bug wasn't that easy and would have come with or performance cost.

**Comment by Foxing772** [comment] 2020-08-08 12:42
> 
> 
> > Thanks for the answer. Is it possible to return the vanilla lighting without removing sodium?
> 
> Sadly no, iirc readding the bug wasn't that easy and would have come with or performance cost.

Thanks

**Comment by jellysquid3** [comment] 2020-08-08 17:55
Duplicate of #50.

**Closed as completed by jellysquid3** 2020-08-08 17:55 UTC
Labels: E-duplicate, E-will-not-fix
