### ISSUE TITLE
Broken Vanilla Tweaks 3D Iron Bars

### ISSUE THREAD

**Issue by Julienraptor01** [jellysquid3/Sodium#1239] opened 2022-03-24 12:43 UTC
### Version information

sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14

### Expected Behavior

The ressource pack should be working like in vanilla.

### Actual Behavior

Sodium breaks VanillaTweaks 3D Iron Bars.
There is a line of pixel that does something like z-fighting

### Reproduction Steps

Install the RP.
Go into some world.
Place two iron bars next to each other.
Look at the left of the iron bars.

### Java version

Java 17.0.1 64bit

### CPU

i7-9750H

### GPU

NVIDIA GeForce RTX2060

### Additional information

https://imgur.com/a/B3OO9Lb
You can experience this from at least sodium-fabric-mc1.16.5-0.2.0+build.4.jar (i didn't have time to go before in time) to sodium-fabric-mc1.18.2-0.4.1+build.15.jar

**Comment by litoj** [comment] 2022-04-06 07:44
It is probably an imperfection of the model.
You can use this version of iron bars, they work just fine.
Blockstate: https://github.com/JosefLitos/Enhanced-Faithcraft/blob/master/assets/minecraft/blockstates/iron_bars.json
Models:
https://github.com/JosefLitos/Enhanced-Faithcraft/blob/master/assets/minecraft/models/block/iron_bars_post.json
https://github.com/JosefLitos/Enhanced-Faithcraft/blob/master/assets/minecraft/models/block/iron_bars_side.json
https://github.com/JosefLitos/Enhanced-Faithcraft/blob/master/assets/minecraft/models/block/iron_bars_side_alt.json

**Comment by Julienraptor01** [comment] 2022-04-06 11:17
Thanks
If it's an imperfection of the model why doesn't it happen in vanilla ?

**Comment by Julienraptor01** [comment] 2022-04-06 15:36
@JosefLitos i tried to simply use you file but it don't work.

**Comment by Julienraptor01** [comment] 2022-04-06 17:09
i've decided to take a long look into it (i needed to learn modeling) and i've found a solution but it breaks vanilla

**Comment by Julienraptor01** [comment] 2022-04-06 17:14
the issue really come from sodium

**Comment by Julienraptor01** [comment] 2022-04-06 17:27
~~if anyone use the RP and want less broken
you can replace the 2 files in assets\minecraft\models\block by the one just under (you need to get rid of the .txt extension i just added it because github didn't want json files)
[iron_bars_cap.json.txt](https://github.com/CaffeineMC/sodium-fabric/files/8429110/iron_bars_cap.json.txt)
[iron_bars_cap_alt.json.txt](https://github.com/CaffeineMC/sodium-fabric/files/8429111/iron_bars_cap_alt.json.txt)~~
i just noticed the entire pack is kinda broken so i'mma try to rewrite it and if it don't work i'mma discuss with VT team

**Comment by litoj** [comment] 2022-04-07 20:18
OK, let me know, if you need anything. Btw for models, on linux (or Windows) you can use BlockBench.

**Comment by amnotbananaama** [comment] 2022-05-21 00:44
Duplicate of #460

> If it's an imperfection of the model why doesn't it happen in vanilla ?

> the problem is that Mojang relies on infinitesimally small offsets in some edge cases  
  
\- Jelly

**Closed as not planned by amnotbananaama** 2022-05-21 00:44 UTC
Labels: T-bug, E-duplicate
