### ISSUE TITLE
Game crashes when i start up my world or create a new one (CloudRenderer.java:100) ~[sodium-fabric-0.5.9+mc1.21.jar:?]

### ISSUE THREAD

**Issue by danielalex011** [jellysquid3/Sodium#2565] opened 2024-06-21 13:23 UTC
java.lang.IllegalStateException: BufferBuilder was empty
	at net.minecraft.class_287.method_60800(class_287.java:69) ~[client-intermediary.jar:?]
	at me.jellysquid.mods.sodium.client.render.immediate.CloudRenderer.render(CloudRenderer.java:100) ~[sodium-fabric-0.5.9+mc1.21.jar:?]
	at net.minecraft.class_761.method_3259(class_761.java:14180) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1260) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1087) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:850) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1285) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.11.jar:?

[latest.log](https://github.com/user-attachments/files/15928218/latest.log)

Hardware information:
 CPU: 12x 11th Gen Intel(R) Core(TM) i5-11600K @ 3.90GHz
 GPU: NVIDIA GeForce RTX 4070/PCIe/SSE2 (Supports OpenGL 3.2.0 NVIDIA 555.99)
 OS: Windows 11, version 23H2

**Comment by MeeniMc** [comment] 2024-06-21 14:02
Looks like duplicate of https://github.com/CaffeineMC/sodium-fabric/issues/2552

**Comment by danielalex011** [comment] 2024-06-21 14:22
Found out why it crashed, it was one of my texture packs that caused it.

**Comment by jellysquid3** [comment] 2024-06-21 19:01
Please do not omit information from the issue template next time.

This is a duplicate of #2552.

**Closed as not planned by jellysquid3** 2024-06-21 19:01 UTC
Labels: E-duplicate
