### ISSUE TITLE
block/ctm textures cause z-fighting

### ISSUE THREAD

**Issue by Diskman20** [jellysquid3/Sodium#918] opened 2021-09-23 00:48 UTC
### Version information

sodium-fabric-mc1.17.1-0.3.2+build.7

### Expected Behavior

Blocks should display with a base texture surrounded by a border texture with no z-fighting between border and base textures.

### Actual Behavior

The borders overlap the base texture in a strange way and cause z-fighting

### Reproduction Steps

1. Use a texture pack that uses the 'block/ctm' parent model for a block. (see VanillaTweaks.net)
2. Place blocks.
3. Observe the z-fighting.

### Java version

Java 16

### CPU

AMD Ryzen 5 2600

### GPU

NVIDIA GeForce GTX 1660 SUPER

### Additional information

The only other mod that I have that might change rendering is Lithium

**Comment by jellysquid3** [comment] 2021-10-01 18:56
Can you check if your issue was resolved by the patched version mentioned [here](https://github.com/CaffeineMC/sodium-fabric/issues/806#issuecomment-921225933)?

**Comment by Diskman20** [comment] 2021-10-04 21:53
I'm afraid I'm a bit dense and do not know how to use the patched version, sorry.

**Comment by giabao06** [comment] 2021-10-14 01:48
> I'm afraid I'm a bit dense and do not know how to use the patched version, sorry.

Go to GitHub Actions to download the bleeding-edge versions (meaning: versions that have the latest changes)

**Comment by Diskman20** [comment] 2021-10-14 21:26
Sorry I'm so dumb but I went to Actions and couldn't figure out how to download anything.

**Comment by giabao06** [comment] 2021-10-23 01:43
> Sorry I'm so dumb but I went to Actions and couldn't figure out how to download anything.

In GitHub actions you should see a list of recently-built versions. Click on the one one top (usually the latest changes) then look in the artifacts section. There should be a link there, click on it and you will recieve a zip file with the latest mod build

**Comment by Diskman20** [comment] 2021-10-24 01:51
Thanks so much for all the help, the issue is fixed in the latest bleeding edge version.

**Comment by MESLewis** [comment] 2021-11-21 00:54
Duplicate of #815

**Comment by jellysquid3** [comment] 2021-11-23 16:25
Closing as duplicate of the aforementioned issue.

**Closed as completed by jellysquid3** 2021-11-23 16:25 UTC
Labels: T-bug
