### ISSUE TITLE
Option to ignore server chunk unloading

### ISSUE THREAD

**Issue by Khodyn** [jellysquid3/Sodium#149] opened 2020-07-22 22:57 UTC
Right now, if the servers max chunk networking distance is 10 chunks and your render distance is set to 32, it will be as if your render distance was 10. This option would ignore the server unloading chunks on your client, keeping chunks received by the server until they've left your actual render distance.

**Comment by amnotbananaama** [comment] 2020-07-22 23:07
See https://bugs.mojang.com/browse/MC-149714 and [here](https://discordapp.com/channels/602796788608401408/651120262129123330/693326129674584064) for previous discussion on the topic. From Jelly:
> My concern would be that it could result in de-sync to old chunks without a lot of special handling.

I would love this, but I'm not sure if it belongs in Sodium. This behavior was present before 1.14.0 in vanilla so it would be great if it could be fixed in vanilla. If Jelly defers this, it would be a great companion mod for Sodium. It shouldn't be too hard to naively implement,  just ignore any `UnloadChunkS2CPacket` packets, with special handling for issues that might crop up.

**Comment by Khodyn** [comment] 2020-07-26 18:21
Adding onto this, if this feature were to be added to Sodium it should cache chunks up to **twice** the render distance away, only rendering them when they come within the normal distance. This is because otherwise if you were to go around loading chunks on a 8-chunk distance server so that you can see a 32x32 area of chunks, you wouldn't be able to load them all without unloading others.

Black pixels: Chunks I want loaded
Blue pixels: Chunks loaded by the server
Red pixels Chunks my client keeps loaded + rendered

![chunks](https://user-images.githubusercontent.com/49518050/88486357-757cb900-cfc0-11ea-867b-56b7ee65e274.gif)

**Comment by ghost** [comment] 2020-08-01 14:46
I have the same issue but I want to lower my render distance cause I lag and I am forced to be using the server's view distance which is terrible..

**Comment by MeeniMc** [comment] 2021-04-05 17:25
You could try Bobby
https://github.com/johni0702/bobby

**Comment by Redd56** [comment] 2021-05-15 23:43
> You could try Bobby
> https://github.com/johni0702/bobby

ill look into this, great to know that the issue is still being thought about tho. atleast in some minor capacity

**Comment by mrmangohands** [comment] 2021-07-11 06:27
As mentioned bobby is an available solution for this, and I think it's probably not within sodium's scope.

**Closed as completed by mrmangohands** 2021-07-11 06:27 UTC
Labels: T-enhancement
