### ISSUE TITLE
at 29999999 is a flikering bug

### ISSUE THREAD

**Issue by ElectroGehirn** [jellysquid3/Sodium#1119] opened 2022-01-09 16:06 UTC
### Version information

1.18.1

### Expected Behavior

tp to /tp 29999999 100 29999999 and see the flikering

### Actual Behavior

flikering

### Reproduction Steps

tp to /tp 29999999 100 29999999 and see the flikering

### Java version

17

### CPU

i5-3470

### GPU

r9-280x

**Comment by DioEgizio** [comment] 2022-01-09 17:50
Known issue, duplicate of #990, fixed in https://github.com/CaffeineMC/sodium-fabric/commit/29b8852f38595ec4df789301cc58e9a36681c9ab

**Closed as completed** 2022-01-29 22:10 UTC
Labels: T-bug, E-duplicate

**Comment by master7720** [comment] 2022-03-16 22:59
i5-3470 XDD

**Comment by ElectroGehirn** [comment] 2022-03-16 23:50
> i5-3470 XDD

Okay?, i use an 10 years old cpu... you can still use it for games today, but for hard games like cyberpunkt not but i did not want use my pc for realy good games... ill have all what i want, i still use an s1, wile i only need time and musik, not more... are you going to make fun of me again?

**Comment by jellysquid3** [comment] 2022-03-16 23:57
I banned the other user in question from this issue tracker. Just a troll, please don't think much of them.
