### ISSUE TITLE
Flickering when breaking blocks

### ISSUE THREAD

**Issue by awong6687** [jellysquid3/Sodium#1229] opened 2022-03-15 17:14 UTC
### Version information

sodium 0.4.1-build-15

### Expected Behavior

 I expected blocks to not flicker when I broke them

### Actual Behavior

Blocks flicker when I break them

### Reproduction Steps

Start single player world with sodium installed, break blocks with shovel, the block and sometimes surrounding blocks flicker invisible

### Java version

Java 17

### CPU

Intel Core i7 1065G7

### GPU

Iris Plus Graphics

### Additional information

tested with graphics driver 26.20.100.7926 and 30.0.101.1404, latest.log file (FILE)

**Comment by awong6687** [comment] 2022-03-15 17:16
Here is the link to the log file
https://drive.google.com/file/d/1r7veVOEnQdqkzu6MtXKNwSgpE8qRLdyy/view?usp=sharing

**Comment by wangwang-code** [comment] 2022-03-19 10:09
https://github.com/CaffeineMC/sodium-fabric/issues/869

**Comment by pajicadvance** [comment] 2023-05-10 16:56
Duplicate of #869.

**Closed as not planned by pajicadvance** 2023-05-10 16:56 UTC
Labels: T-bug, E-duplicate, A-drivers
