### ISSUE TITLE
Glass Breaks Nether Portal texture

### ISSUE THREAD

**Issue by yuval20601** [jellysquid3/Sodium#2186] opened 2023-11-28 19:12 UTC
### Bug Description

Looking at nether portal through Glass Breaks the portal texture In latest release. 

### Reproduction Steps

Placing a wall of Black  Stained Glass one right next to a nether portal and looking at the portal through it.

### Log File

I don't have it. I am using another device.

### Crash Report

Irrelevant since it happened on another device.

**Comment by pajicadvance** [comment] 2023-11-28 19:18
Please don't post issue reports without any logs attached. The issue template makes it clear that they're required and explains how to obtain them.

Anyways, this is most likely a duplicate of #38.

**Closed as completed by pajicadvance** 2023-11-28 19:18 UTC
Labels: E-invalid
