### ISSUE TITLE
Missing fullscreen resolution option

### ISSUE THREAD

**Issue by GameParrot** [jellysquid3/Sodium#847] opened 2021-08-21 16:37 UTC
### Version information

mc1.16.5-0.2.0+build.4

### Expected Behavior

There should be an option called "Fullscreen Resolution" in video settings.

### Actual Behavior

There is no option to change the fullscreen resolution in the video settings, which is a vanilla feature.

### Reproduction Steps

1. Go to video settings
2. Look for a fullscreen resolution option
3. Notice that it is missing.

### Java version

16.0.2

### CPU

Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz

### GPU

Radeon Pro 555X

### Additional information

This also happens with mc1.17.1-0.3.0+build.5. A workaround is to launch the game without sodium and change the setting, then launch it with sodium again.

**Comment by amnotbananaama** [comment] 2021-08-21 18:06
Duplicate of #46

**Closed as completed by amnotbananaama** 2021-08-21 18:06 UTC
Labels: E-duplicate
