### ISSUE TITLE
world flickering at long distances 

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#1025] opened 2021-12-05 01:12 UTC
### Version information

mc1.18-0.4.0-alpha5

### Expected Behavior

the world should be consistent

### Actual Behavior

all chunks around me start flickering when over a million blocks out

i dont think it matters but this is on a server.

https://user-images.githubusercontent.com/61369184/144729441-16519fb8-5271-45ee-b491-b8409bd64cc8.mp4

.

### Reproduction Steps

go over a million blocks out and move 

### Java version

java 17

### CPU

amd ryzen 3600 6-core

### GPU

Nvidia 1060 6gb

### Additional information

using multimc. on Ubuntu 20.04 LTS

**Comment by LucilleTea** [comment] 2021-12-05 11:11
duplicate of #1006 or #990

**Closed as completed by LucilleTea** 2021-12-05 11:11 UTC
Labels: E-duplicate
