### ISSUE TITLE
Game crashes whenever i change render distance

### ISSUE THREAD

**Issue by BSmanz** [jellysquid3/Sodium#1651] opened 2023-03-05 05:53 UTC
### Version information

sodium-fabric-mc1.19.3-0.49+build.23

### Reproduction Steps

Change render distance 

### Crash Report file

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffcaad85fc0, pid=12976, tid=12368
#
# JRE version: OpenJDK Runtime Environment Microsoft-32931 (17.0.3+7) (build 17.0.3+7-LTS)
# Java VM: OpenJDK 64-Bit Server VM Microsoft-32931 (17.0.3+7-LTS, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  [nvoglv64.dll+0x1855fc0]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   https://github.com/microsoft/openjdk/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

**Comment by pajicadvance** [comment] 2023-03-17 13:13
This seems to be a duplicate of #1486. Make sure that Sodium's Nvidia driver workaround is applied; the game window's title should say "Minecraft (version hidden from driver)". If you're using Litematica, make sure that the mod is up to date.

**Comment by jellysquid3** [comment] 2023-04-04 00:17
You did not follow the instructions for creating an issue, and we are not going to guess what the problem is. As pajic mentions above, it's probably another instance of NVIDIA's drivers being buggy.

**Closed as completed by jellysquid3** 2023-04-04 00:17 UTC
Labels: E-invalid, T-crash
