### ISSUE TITLE
Game does not start because it wants unused drivers to be updated

### ISSUE THREAD

**Issue by Brokkonaut** [jellysquid3/Sodium#2448] opened 2024-05-02 02:58 UTC
### Bug Description

Sodium complains about old intel drivers (intel says there are no updates), but I don't even want to use the intel graphics as I have a nvidia card that I use for playing. It should just ignore the intel drivers and use the nvidia hardware with updated drivers. This did not happen in minecraft 1.20.4/Sodium 0.5.5

### Reproduction Steps

sodium 0.5.8+mc1.20.6, MC1.20.6, Start the game

### Log File

[04:48:18] [main/INFO]: Searching for graphics cards...
[04:48:19] [main/INFO]: Found graphics card: GraphicsAdapterInfo[vendor=INTEL, name=Intel(R) HD Graphics, version=10.18.10.4358]
[04:48:19] [main/INFO]: Found graphics card: GraphicsAdapterInfo[vendor=NVIDIA, name=NVIDIA GeForce GTX 1660, version=31.0.15.5161]
[04:48:19] [main/ERROR]: The game failed to start because the currently installed Intel Graphics Driver is not compatible.

### Crash Report

i cannot start mc, so not possible

**Comment by astridellensdottir** [comment] 2024-05-02 07:22
When Sodium is initializing, it checks driver version of all available video adapters. It does this before it can be known which adapter is being used, so it informs you if a driver is out of date (as old hardware drivers cause a lot of issues). Something changed in the way driver versions are reported between 1.20.4 and 1.20.5, and as a result Sodium misidentifies valid Intel drivers as being out of date (the reported versions are correct, but Intel reports two different versions depending on how it’s queried).

Once you confirm your drivers are up-to-date, you can modify the "JVM Arguments" in your launcher profile to include the following:
-Dsodium.checks.win32.intelGen7=false

This should disable the check for the intel driver, and allow your game to start.

**Comment by pajicadvance** [comment] 2024-05-02 11:34
Duplicate of #2432

**Closed as not planned by pajicadvance** 2024-05-02 11:34 UTC
Labels: E-duplicate

**Comment by Programmeroexe** [comment] 2024-05-02 15:58
how do I do that with tlauncher?

**Comment by SPINZ1** [comment] 2024-05-02 16:52
You won’t get any help with that illegal malware launcher here.

**Comment by Programmeroexe** [comment] 2024-05-05 16:34
ok switching to ultimMC
