### ISSUE TITLE
Issue when kelp is in contact with non-water block.

### ISSUE THREAD

**Issue by SozoKa** [jellysquid3/Sodium#782] opened 2021-07-19 15:16 UTC
### Version information

mc1.17.1-0.3.0+build.5

### Expected Behavior

I placed kelp to see the texture by putting light blocks so water doesn't flow everywhere... (Works with signs too)

### Actual Behavior

Every kelp under the upper one had no water visible.

### Reproduction Steps

![2021-07-19_17 10 10](https://user-images.githubusercontent.com/70240607/126183616-4467c8b8-2cf9-470a-b475-d3d83cfce907.png)

### Java version

Java 16

### CPU

Intel Xeon CPU E5-2630

### GPU

Nvidia Quadro M2000

**Comment by Kroppeb** [comment] 2021-07-19 15:18
Duplicate of #769

**Closed as completed** 2021-07-19 16:26 UTC
Labels: E-duplicate
