### ISSUE TITLE
AE2 Fluix cable has no texture

### ISSUE THREAD

**Issue by Ioandar** [jellysquid3/Sodium#946] opened 2021-10-21 08:49 UTC
### Version information

sodium-fabric-mc1.17.1-0.3.2+build.7

### Expected Behavior

Render Fluix Cable from AE2 normaly

### Actual Behavior

Fluix Cable from AE2 has missing texture (purple/black checker)

### Reproduction Steps

use Sodium (fabric) 
place fluix cable

### Java version

16.01 64bit

### CPU

Intel i5-6800k 3.6GHz (noOC) 16G Memory

### GPU

GTX1050Ti

### Additional information

All other blocks from AE2 render just fine

**Comment by Jomyy** [comment] 2021-10-26 10:39
this could be due to sodium currently not supporting the Fabric rendering API so no luck there sorry

**Comment by silversquirl** [comment] 2021-10-26 13:14
Duplicate of #5

**Closed as completed by silversquirl** 2021-10-26 13:14 UTC
Labels: E-duplicate

**Comment by Ioandar** [comment] 2021-11-24 13:39
@silversquirl 

fyi: 
I added **[Indium](https://www.curseforge.com/minecraft/mc-mods/indium) by comp500** to my modlist and now all renders and runs fine!
maybe that can help others too?
Thanks for your great work on sodium!
cheers
