### ISSUE TITLE
I used sodium for a long time now, but i cant use it anymore, it just crashs when i enter a world or open Video settings

### ISSUE THREAD

**Issue by CreeperMarone** [jellysquid3/Sodium#887] opened 2021-09-06 00:54 UTC
### Version information

sodium-fabric-mc1.16.3-0.1.0

### Reproduction Steps

install sodium and enter a world i guess

### Crash Report file

[crash-2021-09-05_21.42.14-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/7112664/crash-2021-09-05_21.42.14-client.txt)

### Additional information

i used more mods then just sodium, but the crash report say its sodium that is causing it
![image](https://user-images.githubusercontent.com/90162359/132146701-7deaefef-c90a-47d9-b54c-93d634e72dea.png)

**Comment by amnotbananaama** [comment] 2021-09-06 01:00
Your config file has been corrupted. Recently, extensive work has been tried to fix this. In the meantime, delete `sodium-options.json` from `.minecraft/config` and Sodium will generate a new file.

Duplicate of #219

**Closed as completed by amnotbananaama** 2021-09-06 01:00 UTC
Labels: E-duplicate, T-crash
