### ISSUE TITLE
when ever i change dimensions my game crashes

### ISSUE THREAD

**Issue by Kariyui** [jellysquid3/Sodium#1773] opened 2023-05-20 21:34 UTC
### Version information

mc1.19.2-0.44+build.18.jar

### Reproduction Steps

1. make nether portal
2. go through

### Crash Report file

Exit Code:1

### Additional information

https://github.com/CaffeineMC/sodium-fabric/assets/134172174/1de35461-d018-4890-a7c9-fd326676d406

**Comment by Felix14-v2** [comment] 2023-05-21 00:26
See #1486 
As a fast solution, try disabling thread optimization in the Nvidia control panel settings.

**Comment by piuvas** [comment] 2023-05-23 19:28
please upload a crash log.

**Comment by pajicadvance** [comment] 2023-05-26 10:27
As mentioned above, this is most likely a duplicate of #1486.

**Closed as not planned by pajicadvance** 2023-05-26 10:27 UTC
Labels: A-drivers, T-crash
