### ISSUE TITLE
Game keep crashing for no reason

### ISSUE THREAD

**Issue by SubiNoob1** [jellysquid3/Sodium#324] opened 2020-09-30 12:26 UTC
### Reproduction Steps

1. Open Minecraft
2. Join any world
3. The game get stuck on saving world
4. The game crashes

Alternatively

1. Open Minecraft
2. Go to Options
3. Go to Video Settings
4. The game crashes

### Crash Report File
[crash-2020-09-30_20.12.00-client.txt](https://github.com/jellysquid3/sodium-fabric/files/5305398/crash-2020-09-30_20.12.00-client.txt)

### Additional Information
This issues just started a few days ago because I've played Minecraft with Sodium since the release and suddenly this happened.
I don't know what caused this because I Didn't use any other mods expect for sodium. My performance was good when using this but without this my game lags a lot.

**Comment by LucilleTea** [comment] 2020-09-30 12:32
Duplicate of #219 
Workaround: delete the `sodium-options.json` file from your game's config folder.

**Closed as completed** 2020-09-30 15:28 UTC
Labels: E-duplicate, T-crash
