### ISSUE TITLE
1.20.1 Sodium for Forge

### ISSUE THREAD

**Issue by wolfieboy09** [jellysquid3/Sodium#2338] opened 2024-02-15 12:37 UTC
### Request Description

So I am using the Create mod with other mods, and that does drop my frames quite a bit. So I do want to use Sodium for Forge 1.20.1. There is a mod that connects fabric and forge mods together, but I don't know if that will actually work

**Comment by Lolothepro** [comment] 2024-02-15 12:39
duplicate of https://github.com/CaffeineMC/sodium-fabric/issues/2229
Note: NeoForge mods are compatible with Forge with Minecraft 1.20.1

**Comment by wolfieboy09** [comment] 2024-02-15 12:40
NeoForge 1.20.1 would work with Forge 1.20.1?

**Comment by Lolothepro** [comment] 2024-02-15 12:40
yeap

**Comment by Lolothepro** [comment] 2024-02-15 12:41
NeoForge is basically Forge in 1.20.1

**Comment by wolfieboy09** [comment] 2024-02-15 12:41
I never knew NeoForge would work with Forge 1.20.1

**Closed as completed** 2024-02-15 12:42 UTC
Labels: T-enhancement, S-needs-triage
