### ISSUE TITLE
30s long world loading screen caused by specific join position

### ISSUE THREAD

**Issue by booky10** [jellysquid3/Sodium#2159] opened 2023-11-08 21:15 UTC
### Bug Description

I'm currently experiencing an issue where the world loading screen is always exactly 30s (vanilla limit) long.

After some testing and staring at code, I think I've figured out the cause of the problem.
The world loading screens ends when the chunk section which the player is in gets built for rendering. If your spawn direction doesn't point at where your current section is, sodium doesn't built this section and the world loading screen won't end.

A possible fix for this problem would be to always build the section which the player's position (not their eye position) is in, regardless if visible or not.

### Reproduction Steps

(Tested with an FOV of 90, issue will be present at more positions with an FOV of 30)

- Teleport to `-111.50 127.00 -44.50 90.00 0.00`
  - The eye position of player is in a different section than the bottom position of the player
  - The player's section isn't visible to the camera
- Rejoin your world

### Log File

[latest_sodium.log](https://github.com/CaffeineMC/sodium-fabric/files/13301123/latest_sodium.log)

### Crash Report

[crash-2023-11-08_21.33.25-client_sodium.txt](https://github.com/CaffeineMC/sodium-fabric/files/13301133/crash-2023-11-08_21.33.25-client_sodium.txt)

**Comment by embeddedt** [comment] 2023-11-09 17:33
Do you have a specific seed you used for testing? I'm not able to reproduce this, but the logic error seems valid from a code analysis.

**Comment by booky10** [comment] 2023-11-09 20:04
I can reproduce this on any world, as long as the bottom section has a block in it somewhere.

**Comment by jellysquid3** [comment] 2023-11-11 21:09
Possibly related to #2157.

**Comment by jellysquid3** [comment] 2023-11-11 22:41
Commit https://github.com/CaffeineMC/sodium-fabric/commit/b90ca838936fcba75e938c5033c210e96fa19025 may fix this problem. Not sure yet.

**Comment by jellysquid3** [comment] 2023-11-11 22:51
This issue appears to be fully fixed with the addition of https://github.com/CaffeineMC/sodium-fabric/commit/d9081b4822eb2ea9b6cb523e2511f07f46c3c82a in my testing. Please let me know if you are still able to reproduce it despite these fixes.

**Closed as completed** 2023-11-11 22:50 UTC
Labels: S-confirmed

**Comment by booky10** [comment] 2023-11-12 04:00
> This issue appears to be fully fixed with the addition of [d9081b4](https://github.com/CaffeineMC/sodium-fabric/commit/d9081b4822eb2ea9b6cb523e2511f07f46c3c82a) in my testing. Please let me know if you are still able to reproduce it despite these fixes.

I also can't reproduce this any longer, thanks for fixing! :+1:
