### ISSUE TITLE
Water is not rendered in some cases with Framed Blocks (occlusion when waterlogged)

### ISSUE THREAD

**Issue by Lolothepro** [jellysquid3/Sodium#2699] opened 2024-08-21 14:11 UTC
### Bug Description

Water is not rendered in some cases with Framed Blocks (occlusion when waterlogged)

![2024-08-21_16 11 33](https://github.com/user-attachments/assets/0f256526-8b1e-48c4-b805-f31a6d9d49e3)

### Reproduction Steps

Place the “Framed Inner Corner Slope” frame from Framed Blocks, and waterlog it.

### Log File

https://mclo.gs/U5BAsH9

### Crash Report

*

**Comment by Lolothepro** [comment] 2024-09-15 14:23
caused by https://github.com/CaffeineMC/sodium-fabric/pull/2649

**Comment by douira** [comment] 2024-12-03 18:40
Can reproduce on 1.21.1/stable at 63ebaef39a49f58d15903833c4207f2039b30b8d and reverting the commit 54f34066b55a657f3408703edd3c7a9e6733ca12 that merged #2649 fixes the problem. The issue is figuring out how to both fix this and not regress the other issue the PR was fixing.

**Closed as completed** 2024-12-04 16:50 UTC
Labels: T-bug

**Comment by Lolothepro** [comment] 2024-12-04 16:55
nice
