### ISSUE TITLE
The sky is not visible in the water

### ISSUE THREAD

**Issue by Lolothepro** [jellysquid3/Sodium#2323] opened 2024-02-10 13:43 UTC
### Reproduction Steps

Go into the water
The sun is not rendered

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/14229397/latest.log)

### Crash Report

[crash-2024-02-10_14.42.57-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/14229400/crash-2024-02-10_14.42.57-client.txt)

**Comment by Lolothepro** [comment] 2024-02-10 13:47
![2024-02-10_14 46 41](https://github.com/CaffeineMC/sodium-fabric/assets/68275908/b8d22aa8-e6ce-4527-81e2-05396e05af81)
with Sodium

**Comment by Lolothepro** [comment] 2024-02-10 14:02
https://bugs.mojang.com/browse/MC-152504

**Comment by Felix14-v2** [comment] 2024-02-11 20:36
![image](https://github.com/CaffeineMC/sodium-fabric/assets/75726196/5c638d03-de37-40e5-9f87-d2fcf593e663)
Wait, clouds aren't visible too, how did you get this result?

> ![2024-02-10_14 46 41](https://private-user-images.githubusercontent.com/68275908/303840324-b8d22aa8-e6ce-4527-81e2-05396e05af81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2ODM4MjIsIm5iZiI6MTcwNzY4MzUyMiwicGF0aCI6Ii82ODI3NTkwOC8zMDM4NDAzMjQtYjhkMjJhYTgtZTZjZS00NTI3LTgxZTItMDUzOTZlMDVhZjgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjExVDIwMzIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiNDg4NzkyNzY1YTk1YzE0MzFiNWYzYzdhOGEwNTkxZDI0OWFhYjVlNTFkMjM5YzNkZDQ3MzY3ZTM4MWQ4YTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4a6sSKKFtP3UtmevQEg-ieqH34lk_90ZShIA_KwF9_U) with Sodium

**Comment by mrjasonn** [comment] 2024-05-08 06:47
@Lolothepro Sodium just hiding sun moon underwater is probably not such a good fix for that bug, I suggest to please reopen this issue if this bug has not already been reported before and closed. If it has, maybe discuss on the CaffeineMC discord and see if it would be viable to fix in a better way now.

**Comment by douira** [comment] 2024-05-08 12:39
Why is hiding the sun under water not a good solution? It fixes the mojira issue by making sure the sun is hidden by the water fog.

**Comment by mrjasonn** [comment] 2024-05-08 12:52
> Why is hiding the sun under water not a good solution? It fixes the mojira issue by making sure the sun is hidden by the water fog.

@douira Because it is a vanilla parity enhancement to not just hide it, so I'm suggesting this should be fixed in a better way to remove the bleeding instead of removing the sun and moon.

**Comment by mrjasonn** [comment] 2024-05-11 17:43
So this is why I'm suggesting @Lolothepro to open this issue

**Comment by MeeniMc** [comment] 2024-05-13 07:26
Looks like a duplicate of wontfix issue https://github.com/CaffeineMC/sodium-fabric/issues/2485

**Comment by mrjasonn** [comment] 2024-05-14 16:35
> Looks like a duplicate of wontfix issue #2485

I'd suggest maybe @jellysquid3 decide on this issue in this case

**Comment by jellysquid3** [comment] 2024-05-14 22:44
> ... so I'm suggesting this should be fixed in a better way to remove the bleeding ...

This would require re-implementing the skybox coloration function into the shaders, which while not impossible, is work that I don't want to be doing, as the original code is difficult to read through and understand. Maybe someone could volunteer to do that, but it isn't within the cards otherwise.

**Closed as not planned by jellysquid3** 2024-05-14 22:44 UTC
Labels: E-will-not-fix

**Comment by mrjasonn** [comment] 2024-05-15 03:19
> > ... so I'm suggesting this should be fixed in a better way to remove the bleeding ...
> 
> This would require re-implementing the skybox coloration function into the shaders, which while not impossible, is work that I don't want to be doing, as the original code is difficult to read through and understand. Maybe someone could volunteer to do that, but it isn't within the cards otherwise.

If that is the case, @jellysquid3 would it be better to just put a help wanted label on the issue and reopen it, so people know that they could actually contribute to this?
