### ISSUE TITLE
Game crashing when changing resource pack/reloading resources with f3+t

### ISSUE THREAD

**Issue by Tyfaspo** [jellysquid3/Sodium#446] opened 2020-12-26 12:57 UTC
### Reproduction Steps
1.Change or reload resource pack
2.???
3.Crash with exit code 0

### Crash Report File
https://gist.github.com/Tyfaspo/ec9f58bf92ae883859d7ff2d3f99af57

### Additional Information
Sometimes Minecraft crashes, sometimes not. Crashes are happening in fullscreen and windowed modes.
I'm also using Lithium and Phosphor mods in the video below, but Minecraft crashes even without them.
Link where I'm showing crash https://lowkey.gg/v/7272bd4d-a08c-4ca2-9b0b-c2ef0e1a5214
Using Ryzen 5 3500u APU with Vega 8 Graphics

**Comment by fsharpseven** [comment] 2021-01-28 00:04
From what I could find, this is related to AMD's drivers. See [MC-105853](https://bugs.mojang.com/browse/MC-105853), [MC-31618](https://bugs.mojang.com/browse/MC-31618) (and just for good measure, this [Microsoft answers post](https://answers.microsoft.com/en-us/windows/forum/games_windows_10/minecraft-errors/6118f18e-c068-4c33-8ffa-83f43b6a6f55)). This also [appears to be an issue outside of Minecraft.](https://developer.blender.org/T71463) Try updating your drivers.

**Comment by jellysquid3** [comment] 2021-01-28 00:06
#471 might resolve this.

**Comment by vanjmali** [comment] 2021-02-07 12:44
I had the same issue for months, same CPU and same graphics.
I had this in vanilla too however.

The problem was that the Mipmap was set to 0. If you have it set to 4 (which is default) it fixes the issue.
I don't know why that fixes it but it works for me.

**Comment by mrmangohands** [comment] 2021-05-04 21:19
I've run into this a good number of times, but not that I can recall since #471 was merged, so I'm thinking it has in fact been fixed. Unfortunately I can't reproduce it on old builds as consistently as the others here seem to be able to, but if any of you can still reproduce it on the latest build of the next branch (https://github.com/CaffeineMC/sodium-fabric/actions/runs/759038204 at the time of writing) please let us know.

**Closed as completed by mrmangohands** 2021-05-04 21:19 UTC
Labels: T-crash

**Comment by FilipH25** [comment] 2026-04-19 17:24
true
