### ISSUE TITLE
Sodium for 1.19.4 stops game loading

### ISSUE THREAD

**Issue by cooldroider** [jellysquid3/Sodium#1664] opened 2023-03-15 04:41 UTC
### Version information

mc1.19.4-0.4.10+build.24

### Reproduction Steps

1. Install Fabric & Fabric API for 1.19.4
2. Install Sodium
3. Try to open the game.
Congrats! The loading is freezing at one point

### Crash Report file

After you close minecraft, launcher shows error code "-805306369"

### Additional information

For sure I tried to use another mod with no sodium, and game loaded properly, so the problem is not in laptop's weakness or fabric itself

**Comment by sluryishot** [comment] 2023-03-17 10:31
i have been having the same issue.

**Comment by pajicadvance** [comment] 2023-03-17 13:19
Please reproduce the crash again and upload the game log located in `.minecraft/logs/latest.log`.

**Comment by mrjasonn** [comment] 2023-04-03 01:42
Please add your logs.

**Comment by IMS212** [comment] 2023-05-08 17:46
Likely a duplicate of #899, read that for more info.

**Closed as not planned by IMS212** 2023-05-08 17:46 UTC
Labels: E-duplicate, T-crash
