### ISSUE TITLE
Sodium crashes when i join a server or open video settings. [MultiMC] [1.16.4]

### ISSUE THREAD

**Issue by MedievalHeat** [jellysquid3/Sodium#518] opened 2021-02-04 22:46 UTC
hello, so basically when i join a server or open video settings with sodium active it says saving world and then crashes. I have seen similar other reports to this one, one which said to delete the sodium folder, however i dont have a sodium folder in my files. i am not sure but it might be an issue to do with 1.16.4, because theres a release for 1.16.3 and 1.16.5 but not 1.16.4. the mods i have installed besides sodium are a boosted brightness mod, fabric api, litematica, malilib, minihud, phospor, and tweakeroo. All these mods work fine if sodium is removed from the folder and the crash report lists something about sodium. If sending my mods folder or the entire crash report will help solve the issue then i can do just that.

**Comment by FlashyReese** [comment] 2021-02-04 22:48
It would be great if you can provide a crash report but in CaffeineMC's `#mod-support` channel. Here is a [link](https://jellysquid.me/discord) to the discord.

**Comment by amnotbananaama** [comment] 2021-02-04 23:23
Closing, troubleshooting confirmed this was a duplicate of #219

**Closed as completed by amnotbananaama** 2021-02-04 23:23 UTC
Labels: E-duplicate, T-crash
