### ISSUE TITLE
Wierd glass rendering on 1.20.6

### ISSUE THREAD

**Issue by frosthuuund** [jellysquid3/Sodium#2451] opened 2024-05-02 11:21 UTC
### Bug Description

I know about this game have sorting issues, but its more broken than 1.20.4
![bug](https://github.com/CaffeineMC/sodium-fabric/assets/168279382/bc72b6a4-a6e6-405a-a576-37bc85853c1c)

### Reproduction Steps

This bug happens on 1.20.6 version with Sodium + Extra installed.
JVM is Graal VM 21 with no flags, my card is nvidia, with 552.12 driver.
Without Sodium glass rendering like this
![vanilla](https://github.com/CaffeineMC/sodium-fabric/assets/168279382/1b9329fa-83c0-412a-9d88-7dd643f87921)

### Log File

Nothing out of ordinary

### Crash Report

-

**Comment by Fnige** [comment] 2024-05-02 11:22
See #38 + #2016

**Comment by frosthuuund** [comment] 2024-05-02 11:25
This wasn't an issue in 1.20.4.
![1204](https://github.com/CaffeineMC/sodium-fabric/assets/168279382/ba592d53-2a66-4adb-b4d1-72a02ee97cf4)

**Comment by pajicadvance** [comment] 2024-05-02 11:48
The glass looking different has nothing to do with the version of MC or Sodium, you're comparing two completely different scenes. In any case, it doesn't really matter in what manner the rendering is broken - the root issue is the same. Duplicate of #38

**Closed as not planned by pajicadvance** 2024-05-02 11:48 UTC
Labels: E-duplicate
