### ISSUE TITLE
Compatibility issue with continuity. Connected blocks have Z-fighting

### ISSUE THREAD

**Issue by djmrFunnyMan** [jellysquid3/Sodium#2418] opened 2024-04-12 02:37 UTC
### Bug Description

When using the continuity mod with a connected textures resource pack you will see Z-fighting on the connected textures.
![2024-04-11_21 32 23](https://github.com/CaffeineMC/sodium-fabric/assets/68905776/b0b87371-9519-4511-b3d6-99222a095dd1)

### Reproduction Steps

Install sodium and continuity. Use this resourcepack: https://github.com/xalixilax/xali-s-Enhanced-Vanilla-16x (github link because CF/modrinth downloads are corrupted)

Place down connectable blocks in a line (netherrack and magma in my case). You should see Z-fighting occur on some blocks (seems to be random in my case it occurs on these 6 blocks)
![2024-04-11_21 43 48](https://github.com/CaffeineMC/sodium-fabric/assets/68905776/00069c1e-f08d-4ad1-a668-60756af0a4fd)

### Log File

Not relevant

### Crash Report

Not relevant

**Comment by pajicadvance** [comment] 2024-05-02 12:05
This is going to be fixed once the solution proposed in #2004 gets implemented - it is in the Sodium 0.7 milestone.

**Comment by djmrFunnyMan** [comment] 2024-05-02 13:22
~~Actually it's gonna be fixed in Sodium 0.6 thanks to this https://github.com/CaffeineMC/sodium-fabric/commit/ea0172768a5da9907b5a5711160dc3984fafea83 (I think)~~

Nvm apparently

**Comment by douira** [comment] 2024-05-12 15:36
Has that commit fixed this?

**Comment by djmrFunnyMan** [comment] 2024-05-12 17:42
> Has that commit fixed this?

Using that commit doesn't allow me to use any CTM resourcepack
https://gist.github.com/djmrFunnyMan/88553d6aba1e8f258705387fd5335508

**Comment by Lolothepro** [comment] 2024-05-12 17:43
> > Has that commit fixed this?
> 
> Using that commit doesn't allow me to use any CTM resourcepack [gist.github.com/djmrFunnyMan/88553d6aba1e8f258705387fd5335508](https://gist.github.com/djmrFunnyMan/88553d6aba1e8f258705387fd5335508)

Can you try with the multiloader branch or with Indium?

**Comment by djmrFunnyMan** [comment] 2024-05-12 17:58
Using this build it is not fixed
https://github.com/CaffeineMC/sodium-fabric/actions/runs/8903395759
![2024-05-12_19 57 58](https://github.com/CaffeineMC/sodium-fabric/assets/68905776/76a7136f-7c5c-45fe-858b-e9c323673e81)

**Comment by Lolothepro** [comment] 2024-05-12 18:01
and with https://github.com/CaffeineMC/sodium-fabric/actions/runs/9043821032 ?

**Comment by djmrFunnyMan** [comment] 2024-05-12 18:07
it crashes when loading into a world

**Comment by Lolothepro** [comment] 2024-05-12 18:14
So it can't be tested

**Comment by djmrFunnyMan** [comment] 2024-05-12 18:24
I literally tested it on a built which had the commit in question and it wasn't fixed. Wdym it can't be tested. The major difference between the version I used and the one you sent me is yours is on 1.20.5 and mine is on 1.20.4 which shouldn't affect anything

**Comment by Lolothepro** [comment] 2024-05-12 18:27
> I literally tested it on a built which had the commit in question and it wasn't fixed. Wdym it can't be tested. The major difference between the version I used and the one you sent me is yours is on 1.20.5 and mine is on 1.20.4 which shouldn't affect anything

The 1.20.4/multiloader-0.6 branch doesn't have all the CVF changes iirc

**Comment by jellysquid3** [comment] 2024-05-12 18:30
This issue wasn't closed because the described problem still exists. Block overlays are not entirely fixed with the improvements to our vertex format. It still needs further investigation/work.

**Comment by Lolothepro** [comment] 2024-05-12 18:32
> (Caused by compact vertex format)


so it's not caused by the Compact Vertex Format, it's caused by the reorientation of the quad?
If yes, please change the title of the bug report

**Comment by Lolothepro** [comment] 2024-05-12 18:32
If yes, please change title

**Comment by djmrFunnyMan** [comment] 2024-05-12 20:38
Just in case you don't already know, the resourcepack I use is https://github.com/xalixilax/xali-s-Enhanced-Vanilla-16x
So if you wanna reproduce the issue yourself use that. The z-fighting does appear to happen more frequently between netherrack and magma than with any other block, so that should make it easier to reproduce.

(Also do download the resourcepack from the rep, the curseforge and modrinth downloads are corrupted and will break your mipmaps and just not work properly)

**Comment by jellysquid3** [comment] 2024-09-23 01:53
Should be resolved with Sodium 0.6.0-beta.2.

**Closed as completed by jellysquid3** 2024-09-23 01:53 UTC
Labels: T-bug, A-mods
