### ISSUE TITLE
Ice rendering is broken

### ISSUE THREAD

**Issue by Jadestrouble** [jellysquid3/Sodium#882] opened 2021-09-02 05:03 UTC
### Version information

sodium-fabric-mc1.17.1-0.3.0+build.5.jar

### Expected Behavior

Ice rendering without sodium looks like this:
![2021-09-01_21 46 23](https://user-images.githubusercontent.com/81522136/131783330-84636bca-d81a-462b-a3e4-621c93537b5b.png)

### Actual Behavior

Ice rendering looks like this:
![2021-09-01_21 43 42](https://user-images.githubusercontent.com/81522136/131783352-654b9673-d4c3-4bba-be47-b319ab4b0016.png)

### Reproduction Steps

Find ice on the same layer as water
look at it

### Java version

Java 16

### CPU

Intel(R) Core(TM) i7-9700F

### GPU

NIVIDA GeForce GTX 1660 SUPER

### Additional information

screenshots are with a resource pack and other mods but i did test this in vanilla and only sodium after they were taken

**Comment by silversquirl** [comment] 2021-09-02 08:52
Duplicate of #38

**Closed as completed by silversquirl** 2021-09-02 08:52 UTC
Labels: E-duplicate
