### ISSUE TITLE
Blocks not showing up in an xray-ish way when digging down next to chunk border

### ISSUE THREAD

**Issue by itsbumble** [jellysquid3/Sodium#605] opened 2021-03-24 20:41 UTC
### Expected Behavior
All blocks render and i am able to dig down without having an xray type rendering issue

### Actual Behavior
This happens 
![image](https://user-images.githubusercontent.com/78655784/112380075-f0fd4a00-8cb6-11eb-89f0-0f2f7833e098.png)

### Reproduction Steps
Go to the edge of a chunk (the block next to the border in f3+g)
dig down around 20 blocks
see issue happen

### Attachments
See above image

### System Information

- Java Version: [Java 11 with GraalVM]
- CPU: 
![image](https://user-images.githubusercontent.com/78655784/112380313-3faae400-8cb7-11eb-8821-9dd0541d5ef3.png)

- GPU: 
![image](https://user-images.githubusercontent.com/78655784/112380350-4c2f3c80-8cb7-11eb-9e0f-3fdeef515521.png)

**Comment by itsbumble** [comment] 2021-03-24 20:48
Forgot to mention that pressing f3 + a fixes it until the next time i restart the game

**Comment by DragonEggBedrockBreaking** [comment] 2021-03-24 20:50
can confirm this issue on intel core i7 7500U and Intel HD Graphics 620 (OpenGL 4.3)

**Comment by Genau6502** [comment] 2021-03-24 21:59
Can confirm, windows with i5-1035G1/iGPU

**Comment by LucilleTea** [comment] 2021-03-25 05:44
This issue doesn't occur in all situations, detailed reproduction steps are very important. Full mod lists with specific version information are also essential!
I have now reproduced the issue - using seed `-3915904043254659825` fly to -191.5, -511.5, and dig down on this chunk corner.
I've confirmed this occurs on github actions builds 309, 296 and 287, but not 282.

**Comment by itsbumble** [comment] 2021-03-25 13:37
I was in a seed that was having it happen every time. Strange

**Comment by itsbumble** [comment] 2021-03-25 13:43
Try restarting your game if you haven't already. If you change any video settings or reload chunks the issue disappears until the next time the game is restarted.

**Comment by fsharpseven** [comment] 2021-03-31 02:40
This appears to start at commit [`de545a`](https://github.com/CaffeineMC/sodium-fabric/commit/de545a500a31f96b5caf7f698a38902945e70f2e).

**Comment by Genau6502** [comment] 2021-04-02 07:54
So, using build 299, I could reproduce the issue, see here:

https://user-images.githubusercontent.com/66269211/113394918-fc283800-9390-11eb-9fce-f166ed7b4bc1.mp4

However, when updating to build 309, the issue was not present, with the same chunk border and the same settings


https://user-images.githubusercontent.com/66269211/113394987-16621600-9391-11eb-85e1-79363fb3e718.mp4

**Comment by Genau6502** [comment] 2021-04-02 17:04
I have since reproduced this again, seems to have changed in behaviour in the time mentioned above

**Comment by Tommeh1** [comment] 2021-04-07 14:57
Can confirm with an i7 6700 and gtx960(Using multidraw), however, i would like to note that this also applies to vertical chunks and is especially common if blocks fall from a vertical chunk into another.

**Comment by itsbumble** [comment] 2021-04-09 18:35
Does anyone know if it happens with an AMD GPU? So far in this issue it has only been reproduced with Nvidia and Intel

**Comment by mrmangohands** [comment] 2021-04-09 23:13
The issue has nothing to do with gpu vendor

**Comment by itsbumble** [comment] 2021-04-10 00:29
> The issue has nothing to do with gpu vendor

ah okay, I'm not the most technical person so I didn't know

**Comment by mrmangohands** [comment] 2021-04-10 01:19
Seems this is also responsible for the discrepancy I'd noted before https://github.com/CaffeineMC/sodium-fabric/commit/de545a500a31f96b5caf7f698a38902945e70f2e between sodium and vanilla in time to render blocks after changing dimension, which is fixed with #627.

**Closed as completed** 2021-04-10 02:29 UTC
Labels: T-bug
