### ISSUE TITLE
Game does not load past ~1/8th of the progress bar

### ISSUE THREAD

**Issue by operator571** [jellysquid3/Sodium#1045] opened 2021-12-11 23:01 UTC
### Version information

sodium-fabric-mc1.18-0.4.0-alpha5+build.9 with fabric-loader-0.12.11-1.18 
AND 
sodium-fabric-mc1.17.1-0.3.1+build.6 , sodium-fabric-mc1.17.1-0.3.2+build.7 , and sodium-fabric-mc1.17.1-0.3.3+build.8 with fabric-loader-0.12.11-1.17

### Reproduction Steps

1.  Start the game
2.  See that the does not load past 1/8th the progress bar
![i love sodium](https://user-images.githubusercontent.com/95985830/145693542-691c5edf-77e2-48f0-acb7-98b13dca719a.png)

### Crash Report file

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/7697853/latest.log)
game does not provide crash report as it has to be force closed

### Additional information

using no other mods
[DxDiag.txt](https://github.com/CaffeineMC/sodium-fabric/files/7697861/DxDiag.txt)

EDIT: I have done some more experimentation and found that the game loads using version 0.3.0 but not on subsequent versions

**Comment by dolpce** [comment] 2021-12-12 10:27
I have the same issue. **Both with 1.17 & 1.18.** 

I tried everything: 

- Removing Texture Pack because it have some "OptiFine Only" stuff.
- Only Loading Sodium & Extra without other mods. 
- Even though its a problem with TLauncher separating each version by folder. _(I use License account in TL btw.)_

**Nothing worked**. I guess it either problem with Sodium or my Laptop :(

**Comment by smeksz** [comment] 2021-12-12 16:20
I have the same exact issue. I tried using a different launcher and everything but nothing worked. It works on 1.16.5 or lower but not 1.17,

**Comment by jellysquid3** [comment] 2021-12-12 16:53
Duplicate of #899. Try updating your graphics drivers... every report we've seen has been fixed by doing so.

**Closed as completed by jellysquid3** 2021-12-12 16:53 UTC
Labels: E-duplicate, T-crash

**Comment by petersonas** [comment] 2022-06-29 20:04
I had the same problem, and I solved it by installing Sodium Extra and Reese's Sodium Options. I don't know if it works for everyone, but it worked for me.

**Comment by 7seasking** [comment] 2023-06-14 14:15
> I have the same exact issue. I tried using a different launcher and everything but nothing worked. It works on 1.16.5 or lower but not 1.17,

Same I have Intel HD graphics 2500 and sodium works on 1.16 and lower it sometimes works on 1.19.2 for 1-2 times then it gets stuck on Mojang Screen
