### ISSUE TITLE
Can't change how many hertz the game runs on

### ISSUE THREAD

**Issue by AntoanBG** [jellysquid3/Sodium#436] opened 2020-12-22 17:57 UTC
### Expected Behavior
In vanilla Minecraft, I go to settings, and on the resolution bar, I can change how many hertz the game runs on!

### Actual Behavior
No resolution bar which means - can't change hertz

### Reproduction Steps
1. Open Minecraft
2. Go to settings
3. Go to video settings
4. No resolution bar

### Attachments
Add any relevant screenshots or videos to this issue as you feel necessary to explain the issue.

### System Information
GTX 1650
I5 9400F
16GB of RAM
144Hz Monitor.

- Java Version: [the latest one]
- CPU: [i5 9400F]
- GPU: [Nvidia GTX 1650]

**Comment by altrisi** [comment] 2020-12-22 18:02
Duplicate of #46.

Meanwhile, you should be able to access the vanilla options menu by using `Shift+P`.

**Closed as completed** 2020-12-22 18:05 UTC
Labels: T-bug, E-duplicate
