### ISSUE TITLE
Crash when entering nether portal.

### ISSUE THREAD

**Issue by itschews** [jellysquid3/Sodium#832] opened 2021-08-13 04:14 UTC
### Version information

mc1.17.1-0.3.0+build.5

### Reproduction Steps

1.  Enter Nether Portal
2. Nausea thing indicates that you are about to enter a new dimension
3. Crash

### Crash Report file

[using multimc idk how to find file](https://paste.ee/p/3rpQ8)
edit: ^ this is the link to the log, I meant idk how to find directory of file but it showed in multimc.

### Additional information

I am using a M1 Mac and this trick to get it running [https://github.com/r58Playz/m1-multimc-hack](https://github.com/r58Playz/m1-multimc-hack) 

When I start up my game it has like 18-20 fps for the first few minutes before going to a steady 90ish

**Comment by LucilleTea** [comment] 2021-08-13 04:19
Duplicate of #748 
There is a different M1 hack discussed there that you can try.

**Closed as completed by LucilleTea** 2021-08-13 04:19 UTC
Labels: E-duplicate

**Comment by itschews** [comment] 2021-08-14 09:20
I am using zulu java 16. zulu-8 works with 1.8.9 for me and zulu-8 worked with 1.16.5. multimc says im using lwjgl 3.2.2.
I tried, 
https://github.com/yusefnapora/m1-multimc-hack
https://github.com/17hoehbr/m1-multimc-hack
https://github.com/r58Playz/m1-multimc-hack

but they still crash.

> We'll merge the workaround from Iris into Sodium 0.3.1.

This means it will be fixed in 0.3.1 rite?
