### ISSUE TITLE
Game crushes with the build from the stable branch

### ISSUE THREAD

**Issue by vdyma** [jellysquid3/Sodium#384] opened 2020-11-08 01:20 UTC
I built Sodium from source from the 1.16.x/stable branch and the game crashes just before entering the main menu screen after launch. I use Minecraft 1.16.4 and fabric 0.10.6 build 214.
The error window says:

> The game crashed whilst rendering screen
Error: java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
Exit Code: -1

Here is the the crash report file:
[crash-2020-11-08_03.12.46-client.txt](https://github.com/jellysquid3/sodium-fabric/files/5505729/crash-2020-11-08_03.12.46-client.txt)

**Comment by amnotbananaama** [comment] 2020-11-08 01:27
Duplicate of #16. You need to build with Java 8 if you are going to run with Java 8. At the moment Sodium uses Java 14 to build the stable branch in GitHub Actions, there is a Pull Request open to change this. 

You can use a service such as [JitPack](https://jitpack.io) if you don’t have access to a JDK 8.

**Closed as completed by amnotbananaama** 2020-11-08 01:27 UTC
Labels: E-duplicate, T-crash
