### ISSUE TITLE
sodium not coompatible with connected texture mod (continuity)

### ISSUE THREAD

**Issue by Kibitzit** [jellysquid3/Sodium#1157] opened 2022-01-30 21:31 UTC
### Version information

mc1.18.1-0.4.0-alpha6

### Expected Behavior

the glas should be connected without borders when activating the continuity texturepack

### Actual Behavior

the glas connects with borders using the continuity fabric mod while playing on sodium

### Reproduction Steps

download and run sodium and continuity fabric mod

### Java version

java 17

### CPU

intel core i5-7600k

### GPU

nvidia geforce gtx 1070

### Additional information

i hope that u someday can play with connected texture and sodium because thats the only thing im missing while not playing optifine and it has really helpt me to get the better performance from sodium opposed to optifine

**Comment by efffauw** [comment] 2022-02-02 17:13
Do you have [Indium](https://www.curseforge.com/minecraft/mc-mods/indium) installed? If not you should use it and see if the problem is still there.

**Comment by Kibitzit** [comment] 2022-02-02 17:25
That was what it needed, thanks man.

**Comment by Pectacular** [comment] 2022-02-07 04:46
> That was what it needed, thanks man.

Shouldn't this issue be closed then?

**Comment by silversquirl** [comment] 2022-02-16 06:45
Duplicate of #5

**Closed as completed by silversquirl** 2022-02-16 06:45 UTC
Labels: T-bug, E-duplicate

**Comment by delvo23** [comment] 2023-06-13 04:29
i already install the indium mod,but that still a problem
