### ISSUE TITLE
Chunks have "x-ray effect" from distance

### ISSUE THREAD

**Issue by luckeYpublic** [jellysquid3/Sodium#1514] opened 2022-11-18 11:12 UTC
### Version information

sodium-fabric-mc1.19.2-0.4.4+build.18

### Expected Behavior

No holes.

**In the chunk**
![2022-11-18_11 59 15](https://user-images.githubusercontent.com/81254020/202691329-94cfb833-54a8-4fc5-b847-0b96fd305db2.png)
![2022-11-18_11 59 38](https://user-images.githubusercontent.com/81254020/202691334-c3712d31-2281-4d9c-9a28-db6299ff5f4a.png)

### Actual Behavior

There's a hole.

**Next to the chunk**
![2022-11-18_11 59 19](https://user-images.githubusercontent.com/81254020/202691851-f5e5e883-8c55-443e-b071-717ec191a349.png)
![2022-11-18_11 59 42](https://user-images.githubusercontent.com/81254020/202691858-0519e077-563f-4fa5-8208-a6e9f4da00d8.png)

### Reproduction Steps

1. Build big walls and make fog effect
2. Holes

### Java version

Java Version 8 Update 351 (build 1.8.0_351-b10)

### CPU

i9-10900K

### GPU

ASUS TUF RTX 4090

**Comment by Blobanium** [comment] 2022-11-20 02:56
Possibly experiencing the same issue here, images below for proof.
![2022-11-19_18 38 22](https://user-images.githubusercontent.com/45613796/202880301-6220ac1e-a713-4c12-9291-465533ae42a3.png)
![2022-11-19_18 38 37](https://user-images.githubusercontent.com/45613796/202880302-4ad68ae5-5127-4086-8385-f56c4e5ae5a6.png)

Also this error appears in the log (Presumably it generates this error every time it xrays a certain chunk) i'll post the full log file if needed.
![image](https://user-images.githubusercontent.com/45613796/202880464-32e58830-e007-4b3c-b05d-4a94da835601.png)


Also to note Running AMD Ryzen 5 3600x, Radeon RX 570.

**Comment by Ayman-Isam** [comment] 2022-12-22 17:13
Have you guys tried updating java to java 16 or java 17

**Comment by Blobanium** [comment] 2022-12-28 04:00
> Have you guys tried updating java to java 16 or java 17

Minecraft 1.18+ Should already require Java 17 by default. I'm 99.9% Certain that it isn't java itself causing the issue. 

Based on the stack trace in my last comment, this seems to be pointing at sodium. But however, there is a chance that it could be conflicting with [Fxmorin's More Culling Mod](https://github.com/fxmorin/MoreCulling) but I cannot 100% confirm that mod is conflicting with sodium just because it is in the stack trace (Correct me if im wrong). I haven't tested it to see if it is actually conflicting with sodium myself.

A temporary workaround I found is to reload the textures by doing F3+T when the error happens.

**Comment by piuvas** [comment] 2023-05-03 00:17
looks like a culling issue similar to #722.

**Comment by pajicadvance** [comment] 2023-05-11 11:50
Duplicate of #872.

**Closed as not planned by pajicadvance** 2023-05-11 11:50 UTC
Labels: T-bug, E-duplicate
