### ISSUE TITLE
See through walls

### ISSUE THREAD

**Issue by georgeosheen** [jellysquid3/Sodium#1832] opened 2023-06-21 18:11 UTC
### Version information

sodium-fabric-mc1.20-0.4.10+build.27

### Expected Behavior

![1](https://github.com/CaffeineMC/sodium-fabric/assets/137105277/a4773b64-2fb6-4eb9-abdb-d8653b728fb4)

### Actual Behavior

![2](https://github.com/CaffeineMC/sodium-fabric/assets/137105277/638b3a9f-468f-4072-bb74-0f7e56ff42ec)

Blocks are see through at a certain distance. Confirmed this is definitely Sodium causing this. 

### Reproduction Steps

Seems to happen at specific points in world.

Seed: -5767523442098900832

Co-ordinates (in screenshots): -1825 / 1 / -963

### Java version

Java 1.20.1

### CPU

Ryzen 7 5700x

### GPU

RTX 3060 Ti

### Additional information

Reinstalled Sodium - issue still present.

Tested without Sodium and there is no issue. Tried changing various settings but still ongoing.

Any help appreciated, thanks.

**Comment by Lolothepro** [comment] 2023-06-21 18:15
duplicate of #872

**Comment by georgeosheen** [comment] 2023-06-21 18:17
Is this still ongoing?

**Comment by pajicadvance** [comment] 2023-06-21 18:24
Yes, a fix is being worked on.

**Closed as not planned by pajicadvance** 2023-06-21 18:24 UTC
Labels: T-bug, S-needs-triage
