### ISSUE TITLE
Game crashes, upon hovering over an item with "Legendary Tooltips"; seems to be an incompatability with Iceberg?

### ISSUE THREAD

**Issue by mistakeL** [jellysquid3/Sodium#2033] opened 2023-08-22 10:39 UTC
### Bug Description

So, as the title says, my game starts and works well, everything doing okay, untill I hover over an item

for some reason, legendary tooltips, which uses Iceberg, which also seems to have an compatibility issue, crashes my game

Is there a way to fix it?

### Reproduction Steps

- download sodium and all mods needed for legendary tooltips
- open a world
- open inventory and hover over an enchanted/rare to find item
- game should crash

### Log File

[2023-08-21-3.log.gz](https://github.com/CaffeineMC/sodium-fabric/files/12407886/2023-08-21-3.log.gz)

### Crash Report

[crash-2023-08-21_17.08.28-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12407861/crash-2023-08-21_17.08.28-client.txt)

**Comment by hexadecimal233** [comment] 2023-08-22 11:10
Known issue, Duplicate of #1602

**Comment by mistakeL** [comment] 2023-08-22 11:18
oh I see, thank you very much
is there a way to manualy fix it?

**Comment by mistakeL** [comment] 2023-08-22 11:23
nvm, found the config file^^

**Closed as not planned** 2023-08-22 12:10 UTC
Labels: E-duplicate
