### ISSUE TITLE
PureBDCraft + PureBDCraft 3D Blocks issue

### ISSUE THREAD

**Issue by Aerodin** [jellysquid3/Sodium#586] opened 2021-03-15 19:58 UTC
### Expected Behavior
I expect the Furnace to be exactly like the unlit version with the animation when using PureBDCraft Texture pack and the accompanying 3D Blocks addon texture pack. 

### Actual Behavior
Furnaces are dark.  
See this imgur:
https://imgur.com/a/1f7bQ9Y

### Reproduction Steps
1. Load PureBDCraft Texture pack and PureBDCraft 3D Blocks.  Do not load Sodium yet. Observe furnace in action (fuel + smelting or cooking something).  This is the expected result.
2. Load Sodium.  Observe the same result but the furnace is now very dark when in action.

### Attachments
https://imgur.com/a/1f7bQ9Y

**Comment by Leo40Git** [comment] 2021-03-15 19:59
Could you post an image of how it's supposed to look for reference?

**Comment by Aerodin** [comment] 2021-03-15 20:06
Sure here:
https://imgur.com/a/MCqvBoe

**Comment by amnotbananaama** [comment] 2021-03-15 22:02
Duplicate of #226

**Closed as completed by amnotbananaama** 2021-03-15 22:02 UTC
Labels: T-bug, E-duplicate
