### ISSUE TITLE
rendering error 2

### ISSUE THREAD

**Issue by salince1** [jellysquid3/Sodium#1786] opened 2023-05-30 12:07 UTC
### Version information

sodium-fabric-mc1.19.4-0.4.10+build.24

### Expected Behavior

normal display of textures and the world

### Actual Behavior

black interface mob textures and invisible world
![javaw 2023-05-30 14-23-52-532](https://github.com/CaffeineMC/sodium-fabric/assets/135023797/354b5398-0804-4e4b-bb1f-2b1e62613a9c)
![javaw 2023-05-30 14-24-03-432](https://github.com/CaffeineMC/sodium-fabric/assets/135023797/f01c6c84-7c4d-4dd5-b7aa-288b41ab3eaa)
![javaw 2023-05-30 14-25-56-621](https://github.com/CaffeineMC/sodium-fabric/assets/135023797/710d7fab-9322-486e-a30d-17b34424212d)
![javaw 2023-05-30 14-25-59-360](https://github.com/CaffeineMC/sodium-fabric/assets/135023797/6d6b5d0b-895b-4ce7-8c72-dbb7388f2c0c)
![javaw 2023-05-30 14-28-12-488](https://github.com/CaffeineMC/sodium-fabric/assets/135023797/6d6c38ac-45e4-4421-86d5-a6ac3e3255db)
![javaw 2023-05-30 14-29-02-647](https://github.com/CaffeineMC/sodium-fabric/assets/135023797/6e2d2081-9547-4447-a775-a6d50ca03418)
![javaw 2023-05-30 14-29-25-246](https://github.com/CaffeineMC/sodium-fabric/assets/135023797/7e1a7c90-2155-49e8-a35c-de4ba5c12ff0)

### Reproduction Steps

1 version newer than 1.16.5
2 sodium

### Java version

java 17 and recommended launcher

### CPU

intel i5 460m

### GPU

ATI Mobility Radeon HD 5650

### Additional information

![githab](https://github.com/CaffeineMC/sodium-fabric/assets/135023797/03a497c7-e41a-45f8-bde7-828162fea8bb)

**Comment by pajicadvance** [comment] 2023-05-30 12:43
Can you try updating Iris and see if the issue is still there?

**Comment by salince1** [comment] 2023-05-31 15:47
> Можете ли вы попробовать обновить Iris и посмотреть, есть ли проблема?

updated did not help)

**Comment by Felix14-v2** [comment] 2023-06-01 01:22
> updated did not help)

Попробуй только с Sodium, без других модов. Если это не поможет, вероятно, проблема в видеодрайвере.
##
Try with only Sodium, without other mods. If this doesn't help, the problem is probably related to your graphics driver.

**Comment by salince1** [comment] 2023-06-01 17:39
> > обновлено не помогло)
> 
> Пропой толко с Натрием, без други модов. Если это не поможет, вероятно, проблема в видеодрайвере.
> 
> Попробуйте только с натрием, без других модов. Если это не поможет, проблема, вероятно, связана с вашим графическим драйвером.

ok I'll try sodium only. strange on version 1.16.5 everything is fine with me current on new ones so(

**Comment by salince1** [comment] 2023-06-02 12:41
> > > Обново не помогло)
> > 
> > 
> > Пропой толко с Натрием, без други модов. Если это не поможет, вероятно, проблема в видеодрайвере.
> > Пропрубейте толко с натрием, без други модов. Если это не поможет, проблема, вероятно, свазана с вашим графючем драйвером.
> 
> хорошо, я попробую только натрий. странно в версии 1.16.5 все в порядке со мной, актуально для новых так (

tried only sodium did not help
(thanks for trying to help)

**Comment by jellysquid3** [comment] 2023-07-22 01:22
Per our new [hardware support policy](https://github.com/CaffeineMC/sodium-fabric/blob/3f12f36e58d977f417d22ea6e643a9d7aeb4f0ca/README.md#-hardware-compatibility), your graphics card does not meet the required specifications. As such, this issue is being closed as "won't fix."

**Closed as not planned by jellysquid3** 2023-07-22 01:22 UTC
Labels: T-bug, E-will-not-fix, A-drivers

**Comment by Felix14-v2** [comment] 2023-07-22 10:46
> your graphics card does not meet the required specifications

Wait, does Sodium already use any OpenGL 4.6 features? I know only about ARB_buffer_storage requirement (OpenGL 4.4), but their GPU should support it.

**Comment by douira** [comment] 2023-07-22 10:47
It doesn't. However, only devices that support OGL 4.6 are worth supporting. Older devices often have broken drivers or quirks that need working around.

**Comment by douira** [comment] 2023-07-22 10:48
The hardware support page mentions
> In some cases, older graphics cards may also work (so long as they have up-to-date drivers which have support for OpenGL 3.3), but they are not officially supported, and may not be compatible with future versions of Sodium.
