### ISSUE TITLE
block breaking animation bug

### ISSUE THREAD

**Issue by vHybridv** [jellysquid3/Sodium#424] opened 2020-12-17 16:55 UTC
### Expected Behavior
Block break animation to work from all viewing angles.

### Actual Behavior
The block breaking animation does not appear when looking directly down.

### Reproduction Steps
Look directly down and mine a block. The block breaking animation will not appear.

- Java Version: Fabric 1.16.3
- CPU: i5-10300H
- GPU: RTX 2060

**Comment by amnotbananaama** [comment] 2020-12-17 17:28
Duplicate of #232. This has been fixed but no release with the fix yet

**Closed as completed by amnotbananaama** 2020-12-17 17:28 UTC
Labels: T-bug, E-duplicate

**Comment by vHybridv** [comment] 2020-12-17 17:46
ok thanks
