### ISSUE TITLE
Texture Flickering on Iron Bars block when placed on top of another block

### ISSUE THREAD

**Issue by brethnew** [jellysquid3/Sodium#2247] opened 2024-01-06 19:21 UTC
### Bug Description

I have noticed some texture flickering going on when using Sodium when it comes to Iron Bars.. there could be other textures with issues however I have found it most obvious on these.
![2024-01-06_14 14 53](https://github.com/CaffeineMC/sodium-fabric/assets/40444084/d6405e3b-f33d-443a-bbda-02da020ecc94)

### Reproduction Steps

Install Fabric API and Sodium. Place an Iron Bar on any full block.

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/13850944/latest.log)

### Crash Report

[crash-2024-01-06_14.21.06-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/13850973/crash-2024-01-06_14.21.06-client.txt)

**Comment by Lolothepro** [comment] 2024-01-06 19:22
duplicate of https://github.com/CaffeineMC/sodium-fabric/issues/460

**Closed as not planned** 2024-01-09 18:13 UTC
Labels: E-duplicate
