### ISSUE TITLE
Crash with Exotic-Matters, but Exotic-Matters is not in the modpack

### ISSUE THREAD

**Issue by decosawa** [jellysquid3/Sodium#330] opened 2020-10-03 02:27 UTC
### Reproduction Steps

Just opening the minecraft and the crash appears:

![image](https://user-images.githubusercontent.com/62211442/94981051-70c70a80-0505-11eb-99d3-511b3f076cf3.png)

### Crash Report File

https://gist.github.com/andytxr/cf6ac22ebcacab7da2ebaa951b59df04

### Additional Information

Minecraft version: 1.16.2

Mods of the modpack:

[1.16.2]+SuperAxes-2.0.1
advancementinfo-1.16.2-fabric0.17.2-1.1
appleskin-mc1.16-fabric-1.0.11
appliedenergistics2-fabric-8.1.0-alpha.10
astromine-1.9.0+fabric-1.16.2
audiooutput-1.16.2-0.0.3
authme-1.16.2-1.3.1
bettergraves-0.4.1
betterstones-0.0.4
blockus-1.6.3.1
Blur-1.0.7-1.16.2[fabric]
borderless-mining-1.0.6+1.16.2
campanion-1.2.0+build.39.jar.disabled
can-i-mine-this-block-1.0.2
Cardinal-Components-API-2.5.4
cavebiomes-0.3.0
CleanView-1.16.2-v1-fabric
cloth-api-1.4.6
config-2-4.8.1
Controlling-For-Fabric-1.1.3
Couplings-1.3.2
Craftable-Utilities-1.16.2-1.0.2
CraftPresence-Fabric-1.16.2-Release-1.7.1
dark-loading-screen-1.5.0
Dawn-API-1.0.2-(Fabric-1.16.2)
deepmoblearning-refabricated-0.2.1-beta2
diggusmaximus-1.3.1-1.16
 durability_banks-0.1.2
 durabilityviewer-1.16.2-fabric0.17.2-1.8.6
dynamic-fps-1.2.1
DynamicSoundFilters-1.1.3+1.16.2
eldritch-mobs-1.4.0
EnchantedToolTips-1.3.3-1.16
EndRebellion+[1.8]
expandedstorage-5.5.23+1.16.2
ezpas-1.2.1-1.16.2
fabric-api-0.19.0+build.398-1.16
fabric-language-kotlin-1.4.0+build.1
fabric-language-scala-0.3.2.12-fat
 facility-mc116-0.11.184
get-off-my-lawn-1.16.2-1.1.0-GM
gunpowder-base-0.2.9+1.16.2
gunpowder-currency-1.0.1+gunpowder.0.2.9.mc.1.16.2
gunpowder-market-1.0.1+gunpowder.0.2.9.mc.1.16.2
gunpowder-teleport-1.0.1+gunpowder.0.2.9.mc.1.16.2
gunpowder-utilities-1.0.1+gunpowder.0.2.9.mc.1.16.2
Hwyla-fabric-1.16.2-1.9.23-79
illuminations-1.0.5.jar.disabled
improved-stations-2.0.3
indrev-1.6.11-BETA-pro_andy_gay_
inmis-1.3.0-1.16.2
inventoryprofiles-fabric-1.16.2-0.4.2
item-model-fix-0.2.3
temscroller-fabric-1.16.2-0.15.0-dev.20200812.031004
kibe-1.16.2-1.4.1-BETA
kubejs-fabric-1.4.5
lambdynamiclights-fabric-1.3.0+1.16.2
libblockattributes-all-0.8.1
libcd-2.5.0+1.16.1
Library-Of-Exile-1.16.2-1.0.2
litematica-fabric-1.16.2-0.0.0-dev.20200824.031346
lithium-fabric-mc1.16.2-0.5.4
Magic+Mirror-1.0.2
malilib-fabric-1.16.2-0.10.0-dev.21+arne.1
Mambience-2.1.0+1.16.2
megane-all-1.0.2+1.16-01606fe
modmenu-1.14.6+build.31
modupdater-1.1.11+1.16.2-rc2
NE-1.16.2-Fabric-1.1.4
NookBuild-1.0.1-(Fabric-1.16.2)
notenoughcrashes-2.1.4+1.16.2
NumericPing-1.0.2-fabric1.16.2
okzoomer-4.0.0+1.16.2
packages-1.16.2-1.1
Pal-1.2.1
Patchouli-1.16-40-FABRIC
phosphor-fabric-mc1.16.1-0.6.0+build.7
plantinajar-1.7.1+1.16.2
portaltags-2.0.0+1.16.2
PresenceFootsteps-r28+1.16.2.jar.disabled
quickshulker-1.1.6-1.16
RebornCore-1.16-4.4.1+build.69
repurposed_structures-1.16.2-1.5.2
rer-2.1.0
RoughlyEnoughItems-5.2.10
 rpgstats-2.3.0+1.16.2
shulkerboxtooltip-2.1.1+1.16.2
simpleteleporters-2.2.1
slotlink-1.2+minecraft-1.16.2
smootherbedrock-1.0.0
sodium-fabric-mc1.16.3-0.1.0
spark-fabric
TechReborn-1.16-3.5.2+build.110
trinkets-2.6.4
tweakeroo-fabric-1.16.2-0.10.0-dev.20200812.031359
vanilla-hammers-2.0.6-1.16.2
winged-1.16.2-1.4.0
Xaeros_Minimap_20.21.0_Fabric_1.16.2

**Comment by mrmangohands** [comment] 2020-10-03 02:30
it's included in the facility jar, and the breaks clause means the mods are explicitly labeled incompatible

**Comment by amnotbananaama** [comment] 2020-10-03 02:32
Duplicate of #318, which is in itself a duplicate of #5

**Closed as completed by amnotbananaama** 2020-10-03 02:32 UTC
Labels: E-duplicate, E-external, T-crash
