### ISSUE TITLE
Incompatibility with Requiem

### ISSUE THREAD

**Issue by Dual-Iron** [jellysquid3/Sodium#1174] opened 2022-02-10 00:32 UTC
### Version information

mc1.18.1-0.4.0-alpha6+build.14

### Expected Behavior

The texture for Requiem's activated rune blocks e.g. `requiem:tachylite/runic/penance` should render like so:

### Actual Behavior

The texture for Requiem's activate rune blocks render as missing textures:

### Reproduction Steps

1. Install Requiem (2.0.0-beta.7) and appropriate Sodium version.
2. Enter a world.
3. Run the command `/setblock ~ ~ ~ requiem:tachylite/runic/penance[activated=true]`.
4. Run the command again, to ensure the block is activated.
5. The block lacks a texxture.

### Java version

17.0.1 64bit

### CPU

Intel Core i7-9750H

### GPU

3.2.0 NVIDIA 462.30

### Additional information

Only relevant mods are Sodium, Requiem, and their dependencies.

![image](https://user-images.githubusercontent.com/31146412/153313677-4b8f5b52-4dbf-45e5-8433-77d1982579fc.png)

![image](https://user-images.githubusercontent.com/31146412/153313696-4438c646-35eb-4246-80fc-7aea48bd9b16.png)

**Comment by Dual-Iron** [comment] 2022-02-10 00:34
See also Ladysnake/Requiem/issues/488.

**Comment by Nekosha** [comment] 2022-02-10 12:15
Did you install [Indium](https://github.com/comp500/Indium)?

**Comment by silversquirl** [comment] 2022-02-16 06:23
Likely duplicate of #5

**Closed as completed by silversquirl** 2022-02-16 06:23 UTC
Labels: T-bug, E-duplicate, A-mods

**Comment by Dual-Iron** [comment] 2022-07-20 09:40
Ya, just required Indium. 👍
