### ISSUE TITLE
Fix for MC-165208?

### ISSUE THREAD

**Issue by Alpha-Flyte** [jellysquid3/Sodium#427] opened 2020-12-18 09:52 UTC
**Expected Behavior**
Night Vision makes the world brighter no matter the circumstance

**Actual Behavior**
Applying Night Vision during the night or when it is raining makes everything in the world and the UI go black

**Reproduction Steps**

- Apply night vision using a potion or a method from other mods
- Set time to night or set weather to rain
- World and UI go black

**Comment by Teh404Gal** [comment] 2020-12-18 10:40
umm can you edit your issue to use the bug template instead of the crash one

**Comment by Teh404Gal** [comment] 2020-12-18 10:41
also you said you had a bug that looks like MC-165208 well they might look the same but most of the time solving one doesnt solve the other

**Comment by Alpha-Flyte** [comment] 2020-12-23 09:06
Edited main issue to follow format. Thanks for telling me.

**Comment by Alpha-Flyte** [comment] 2020-12-23 09:08
Sidenote: Since there is no crashlog, this may not be Sodium's fault. It is entirely likely that this is the vanilla bug. However, I think it could be fixed either here or via Phosphor, since they revolve around lighting and optimization.

**Comment by amnotbananaama** [comment] 2021-01-03 19:27
I cannot reproduce this with the reproduction steps you described, with either `sodium-fabric-mc1.16.3-0.1.0.jar` or the latest commit to `1.16.x/next`. The vanilla bug MC-165208 does indeed occur if you have night vision and blindness. Marking this as a duplicate of #260, which has already been indicated it will not be worked on. You can encourage Mojang to fix the underlying vanilla issue

**Closed as completed by amnotbananaama** 2021-01-03 19:27 UTC
Labels: E-duplicate, T-enhancement
