### ISSUE TITLE
Crash when being teleported on a server: Unexpected error  java.lang.IllegalStateException: Tried to mark light data as ready for chunk [195, -1] but it hasn't been loaded yet

### ISSUE THREAD

**Issue by rowandevving** [jellysquid3/Sodium#1291] opened 2022-04-30 10:49 UTC
### Version information

Sodium v0.4.0-alpha+build.14

### Reproduction Steps

Get teleported (same dimension) in a server

### Crash Report file

[crash-2022-04-30_11.34.59-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/8596711/crash-2022-04-30_11.34.59-client.txt)

### Additional information

Around 1 second before the crash the player seemed to fall through the surface it was standing on

**Comment by amnotbananaama** [comment] 2022-05-21 00:13
Duplicate of #1016

**Closed as not planned by amnotbananaama** 2022-05-21 00:13 UTC
Labels: E-duplicate, T-crash
