### ISSUE TITLE
Water does not render correctly under water

### ISSUE THREAD

**Issue by ProGoofster** [jellysquid3/Sodium#1179] opened 2022-02-14 05:43 UTC
### Version information

1.18 latest version

### Expected Behavior

water should look how it does in vanilla minecraft

### Actual Behavior

water looks like this:
![2022-02-13_23 14 30](https://user-images.githubusercontent.com/59934842/153806483-d3f244b3-48a0-4531-ac7b-d509b32d6b24.png)

### Reproduction Steps

make glass air bubble under water, look up

### Java version

17

### CPU

17-8700

### GPU

1080 ti

**Comment by Nekosha** [comment] 2022-02-14 07:19
Duplicate of #38.

**Closed as completed** 2022-02-14 15:48 UTC
Labels: E-duplicate
