### ISSUE TITLE
Cacti in flower pots don't render fully

### ISSUE THREAD

**Issue by NoComment1105** [jellysquid3/Sodium#396] opened 2020-11-19 17:54 UTC
### Expected Behavior
Le cacti should be fully visible 

### Actual Behavior
Le cacti is business at the front, party out back, The front to faces only render the back two don't

### Reproduction Steps
1. Place a catci in a flower pot
2. Observe missing rear

### Attachments
![2020-11-19_17 44 58](https://user-images.githubusercontent.com/67918617/99704326-23403600-2a90-11eb-9e70-27e4bf5b746e.png)

### System Information
*I am using the pinned version in #sodium on the discord (sodium-fabric-mc1.16.4-0.1.1-SNAPSHOT.jar)*

- Java Version: [1.16.4 (java 14.0.2 64-bit]
- CPU: [Intel i5-5300U @2.3Ghz]
- GPU: [Intel HD Graphics 5500]

**Comment by amnotbananaama** [comment] 2021-01-03 18:50
Cannot reproduce this with the .jar I believe you are referring to (linked [here](https://discord.com/channels/602796788608401408/651120262129123330/772998383311781958), Sha1: `5cad7f323991d139d322a8a85b043697e7f78857`). 

![image](https://user-images.githubusercontent.com/6319658/103486079-102bc000-4dc9-11eb-8247-87e3ff110987.png)
### System Information
- Java Version: 1.8.0_51
- CPU: Intel i5-5500U
- GPU: Intel HD Graphics 5500

Sodium has had several commits to the `1.16.x/next` branch since this issue was opened. Can you test if you experience this issue with Sodium (and only Sodium) with the latest commit?

**Comment by NoComment1105** [comment] 2021-01-03 19:03
The very latest sodium Commit and it still doesn't render the upper part and is sodium only

![2021-01-03_19 02 26](https://user-images.githubusercontent.com/67918617/103486492-416eb500-4df6-11eb-8c95-744ae66e2f02.png)

**Comment by XfedeX** [comment] 2021-02-20 16:35
Try using `programmer-art` resource pack.
Not sure this will fix the bug, but even if it doesn't fix that, at least you'll have **true** minecraft, not the horrible game ruined by Microsoft.

**Comment by DragonEggBedrockBreaking** [comment] 2021-02-20 16:38
> Not sure this will fix the bug, but even if it doesn't fix that, at least you'll have **true** minecraft, not the horrible game ruined by Microsoft.

That's subjective, you cannot say that people's opinions (on minecraft textures) are incorrect.

**Comment by NoComment1105** [comment] 2021-02-20 16:40
> Try using `programmer-art` resource pack.
> Not sure this will fix the bug, but even if it doesn't fix that, at least you'll have **true** minecraft, not the horrible game ruined by Microsoft.

Ah right I will try it soon, but I'm not to bigger fan of programmer art, I feel the new textures look better, however I will still try

**Comment by fsharpseven** [comment] 2021-02-25 15:47
I've managed to reproduce this. It only occurs when there is a slab above the cactus.
![2021-02-25_10 46 14](https://user-images.githubusercontent.com/40721769/109178394-d044e180-7756-11eb-852e-975e3c5a5112.png)
![2021-02-25_10 48 36](https://user-images.githubusercontent.com/40721769/109178609-08e4bb00-7757-11eb-96cc-91b639eb4e3a.png)

**Comment by NoComment1105** [comment] 2021-02-25 16:03
Oh my god I hadn't  that that may influence it, I guess it happens because sodium thinks there is a full block on top of it therefore there should be no need to render the top and back because if thinks there is a full block above it. Sodium being resource saving I guess

**Comment by fsharpseven** [comment] 2021-02-25 16:26
Yes, I have a quick fix but I'm not sure if it's problematic/performance-degrading. The problem is in `BlockOcclusionCache.calculate`. The specific line is 65: `boolean ret = VoxelShapes.matchesAnywhere(selfShape, adjShape, BooleanBiFunction.ONLY_FIRST);`. Changing the predicate function to `BooleanBiFunction.FIRST` appears to fix it.
![2021-02-25_11 26 47](https://user-images.githubusercontent.com/40721769/109183850-5dd70000-775c-11eb-90be-f3364e64ab2d.png)

**Comment by NoComment1105** [comment] 2021-02-25 16:31
Thats very interesting. I will have a look and see if it works for me too. Could you please test with Oneshot 3.0 chunk renderer as my iGPU is blacklisted against 4.3

**Comment by amnotbananaama** [comment] 2021-02-25 19:27
@DasBundesland Thank you so much for reproducing this bug! I cannot articulate how happy I am to see this figured out, I spent MONTHS trying to reproduce without success

**Comment by fsharpseven** [comment] 2021-02-25 19:29
@amnotbananaama lol you're welcome!

**Comment by fsharpseven** [comment] 2021-02-25 22:23
Ok, so I am unsure what exactly what the different BiBooleanFunctions _do_ in the context of `VoxelShapes#matchEverywhere` and after some testing, there are some options that include the case where both culling faces are empty (FIRST and OR worked without breaking everything). Hopefully someone smarter than I am can provide insight.

**Comment by FlashyReese** [comment] 2021-03-02 06:09
Looks like a Vanilla bug :P [MC-195461](https://bugs.mojang.com/browse/MC-195461), it has been fixed on 20w46a apparently.
![2021-03-02_00 08 06](https://user-images.githubusercontent.com/30311066/109605877-742de480-7aeb-11eb-8918-e1ee5d04bde0.png)

**Comment by amnotbananaama** [comment] 2021-05-22 16:18
Closing as this is a (fixed) vanilla issue

**Closed as completed by amnotbananaama** 2021-05-22 16:18 UTC
Labels: T-bug, E-external

**Comment by NoComment1105** [comment] 2021-05-22 16:38
> Closing as this is a (fixed) vanilla issue

Okay, thanks. I feel bad now knowing I ate up your time with a vanilla when I thought it was sodium :/
