### ISSUE TITLE
Blocks flickering when placing and breaking blocks

### ISSUE THREAD

**Issue by Yeye175** [jellysquid3/Sodium#1306] opened 2022-05-19 03:14 UTC
### Version information

mc1.18.2-0.4.1+build.15.jar

### Expected Behavior

The game to run normally

### Actual Behavior

Whenever you break or place a block, the background seems to flicker for half a second, returning to normal soon after. 

https://user-images.githubusercontent.com/105774625/169196285-b0a9b666-6fd2-4a6a-b68d-26eda0e8f472.mp4

### Reproduction Steps

Break or place a block. Seems to happen when pistons are activated as well

### Java version

Java 17

### CPU

Intel Core i3-1005G1 GPU

### GPU

Intel UHD Graphics (Integrated Graphics)

### Additional information

I've tried what all the other people said to do. Also, it seems like this does not happen sometimes. I'd say there's a 25% chance on game startup that blocks will not flicker when you place or break them.

**Comment by Yeye175** [comment] 2022-05-19 03:14
ALSO, I know there are other mods on but I've tried this with ONLY the sodium mod and the problem still persists

**Comment by TGRichy** [comment] 2022-05-20 09:27
I have the same processor and I have the same issue too. Couldn't find anything how to fix this.

**Comment by edayot** [comment] 2022-05-29 15:39
Same bug, with the same processor

**Comment by bafgd** [comment] 2022-06-12 02:48
I have a intel core I-5 and it still persists but I learnt that it only flickers at a specific angle.
Kinda annoying as I gotta use optifabric

**Comment by Herator2** [comment] 2022-06-13 21:35
Can confirm that it is the sodium mod causing this issue. Only happens about 25% of the time and above y ~60. I have a intel Intel Core i3-1005G1 running windows 11 with the newest Drivers. I am having to live with this issue as to play the mods I like, I need sodium’s optimisation. Nothing on how to fix it. Seems to be similar bug reports on the same issue.

**Comment by Herator2** [comment] 2022-06-13 21:41
Actually just had a look around and found this https://github.com/CaffeineMC/sodium-fabric/issues/1235 . It seems to be a temporary fix to this bug which has to be redone every couple Minecraft launches.

**Comment by pajicadvance** [comment] 2023-05-10 16:57
Duplicate of #869.

**Closed as not planned by pajicadvance** 2023-05-10 16:57 UTC
Labels: T-bug, E-duplicate, A-drivers

**Comment by theTWIXhunter** [comment] 2024-05-09 16:05
this is not a duplicate of #869, I have the same issue and it does not flicker chunks but single blocks

**Comment by douira** [comment] 2024-05-09 16:21
This issue is about the entire chunk flickering as you can see in the video, which aligns with #869. If you have a different issue than what is described here, you can make a new issue report.
