### ISSUE TITLE
Translating Mod

### ISSUE THREAD

**Issue by Salih-Berat** [jellysquid3/Sodium#1648] opened 2023-03-03 07:36 UTC
If sodium would have multiple language support it would be really good. I am wanting translate this to turkish. But i dont lnow how to do. Can anyone help me?

**Comment by ghost** [comment] 2023-03-07 16:17
Fork the repository, create language_code.json like [this](https://github.com/CaffeineMC/sodium-fabric/blob/1.19.3/dev/src/main/resources/assets/sodium/lang/en_us.json), translate and finally just make pull request.

**Comment by Madis0** [comment] 2023-06-01 07:24
Duplicate of #44

**Closed as not planned** 2023-07-22 02:35 UTC
Labels: T-question
