### ISSUE TITLE
Rendering Issue

### ISSUE THREAD

**Issue by Pepeshki** [jellysquid3/Sodium#576] opened 2021-03-11 08:00 UTC
When i use the sodium mod these is a issue, rendering the terrain. Here is a demonstration: https://drive.google.com/file/d/1M-Xsnn1NC9HQEOn2AfeDbAIv1GsTgYiZ/view?usp=sharing
Also here is the log: https://paste.ee/p/cPlTf

**Comment by amnotbananaama** [comment] 2021-03-11 08:07
This is a duplicate of another issue, depending on the brand of your GPU. Your GPU doesn't support the 4.3 Multidraw renderer You can workaround this by going to `Options` -> `Video Settings` -> `Advanced` and setting "Chunk Renderer" to 3.0 or 2.1.

**Closed as completed by amnotbananaama** 2021-03-11 08:07 UTC
Labels: T-bug, E-duplicate
