### ISSUE TITLE
Bushy Leaves Don't Render Properly With Sodium

### ISSUE THREAD

**Issue by dophire** [jellysquid3/Sodium#2091] opened 2023-09-26 04:43 UTC
### Bug Description

When using any bushy leaves resourcepack, bushy leaves will appear to be shaded lighter than the actual leaves block. Doesn't happen without Sodium.

### Reproduction Steps

Get a bushy leaves resourcepack. In my case its "xali's Bushy Leaves". Set your mipmapping level to 4 to see the effect more clearly. It appears less apparent at mipmap level 0. And just look at the leaves in the distance.
The bug persists even on default settings with a clean install with only Sodium present in the mods folder.
1st Screenshot - Without Sodium
2nd Screenshot - With Sodium, Mipmap 4
3rd Screenshot - With Sodium, Mipmap 0
![2023-09-25_23 20 41](https://github.com/CaffeineMC/sodium-fabric/assets/38838633/dc48dd9b-b501-408f-83ea-6578860beece)
![2023-09-25_23 33 45](https://github.com/CaffeineMC/sodium-fabric/assets/38838633/178cff15-348b-4265-bffb-b6186fbe284b)
![2023-09-25_23 38 57](https://github.com/CaffeineMC/sodium-fabric/assets/38838633/1c0d077b-5c7c-47b7-a464-96e439493a23)

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12722127/latest.log)

### Crash Report

[crash-2023-09-25_23.41.04-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12722136/crash-2023-09-25_23.41.04-client.txt)

**Comment by dophire** [comment] 2023-09-26 22:43
Also, just look at how different the light level looks on these bushy leaves, making it look really weird as its not lit at the same light level as the actual leaves. You can see it in the 3rd screenshot.

![2023-09-26_17 39 01](https://github.com/CaffeineMC/sodium-fabric/assets/38838633/2dca37bc-5878-420b-b8fa-06275248143a)
![2023-09-26_17 39 01_edited](https://github.com/CaffeineMC/sodium-fabric/assets/38838633/53f8a5b5-4cfc-411d-84c4-5e7c2d3c29a0)
![2023-09-26_17 42 54](https://github.com/CaffeineMC/sodium-fabric/assets/38838633/e715ea1d-92ec-446c-85e7-a34c670daead)

**Comment by dophire** [comment] 2023-09-29 23:21
Seems to be the same issue as https://github.com/CaffeineMC/sodium-fabric/issues/1160

**Comment by silversquirl** [comment] 2023-09-30 16:15
Duplicate of #1160

**Closed as not planned by silversquirl** 2023-09-30 16:15 UTC
Labels: E-duplicate
