### ISSUE TITLE
Abrupt crash

### ISSUE THREAD

**Issue by Lentern** [jellysquid3/Sodium#592] opened 2021-03-18 23:48 UTC
### Reproduction Steps
It's very hard for me to explain anything here. I was playing Hypixel and after getting a kill, my game abruptly crashed. It didn't stop responding or anything, it just said "Saving world..." or something like that, and closed. The crash report was generated though, so that is attached.

### Crash Report File
[click here](https://gist.github.com/Lentern/ee66f9313c5473a152af9d95074c57c4)

### Additional Information
The build I was using was [this one.](https://github.com/CaffeineMC/sodium-fabric/suites/2257073374/artifacts/46971754)

**Comment by Genau6502** [comment] 2021-03-19 07:28
I believe this is a duplicate of #587

**Comment by Lentern** [comment] 2021-03-19 11:21
If I'm interpreting that bug correctly, this isn't a duplicate. I was above Y = 60.

**Comment by LucilleTea** [comment] 2021-03-19 12:35
If it wasn't you then it looks like another player fell below Y = 0 and caused the crash. Good to confirm it's caused by other players (/entities?), still the same crash though.

**Closed as completed by LucilleTea** 2021-03-19 12:35 UTC
Labels: E-duplicate, T-crash
