### ISSUE TITLE
Block Updates Trigger Flash With MiniHUD Installed

### ISSUE THREAD

**Issue by taniskint** [jellysquid3/Sodium#1224] opened 2022-03-13 03:58 UTC
### Version information

sodium-fabric-mc1.18.2-0.4.1+build.15

### Expected Behavior

Blocks should not flash on block updates.

### Actual Behavior

Non-full blocks (path blocks, slabs, stairs, panes, etc) flash for a frame or two when a block update occurs. This only occurs with MiniHUD (and its dependencies) installed, and does not occur if Sodium is the only mod installed. This is most noticeable when breaking or placing a block, but also happens when i.e. redstone devices trigger.

This is similar to issue #1048, but I believe it's distinct enough to warrant its own issue. Feel free to close/merge the issues if you don't agree.

### Reproduction Steps

1. Trigger a block update by breaking or placing a block.

### Java version

Java 17.0.1 64 bit

### CPU

Intel Core i5-1035G4

### GPU

Intel Iris Plus Graphics

### Additional information

The computer is a Surface Pro 7 8GB, so its specs are pretty standardized.
MiniHUD version: minihud-fabric-1.18.2-0.22.0
Malilib version: malilib-fabric-1.18.2-0.12.0
Fabric API version: fabric-api-0.47.10+1.18.2

**Comment by pajicadvance** [comment] 2023-05-10 16:55
Duplicate of #869.

**Closed as not planned by pajicadvance** 2023-05-10 16:55 UTC
Labels: T-bug, E-duplicate, A-drivers
