### ISSUE TITLE
Water y=62 stopping rendering

### ISSUE THREAD

**Issue by WiseNat** [jellysquid3/Sodium#844] opened 2021-08-20 17:28 UTC
### Version information

mc1.17.1-0.3.0+build.5

### Expected Behavior

When looking directly down in the water, it should look like you're just entering the water as per normal.

### Actual Behavior

When looking directly down and slowly going into water, a certain Y-level above the water will cause nothing to render. It makes it seem like a kind of flickering if you go down quickly.

### Reproduction Steps

1. Create or find a body of water at y=62
2. Swim above a body of water
2. Look directly down
3. Slowly fall into the water
4. At a certain Y-level above the water you'll notice nothing renders

### Java version

Java 16.0.1

### CPU

Intel Core i5-8600k

### GPU

Geforce Gtx 1060 6GB

### Additional information

I do have Indium installed but the bug persists without it; I tested with purely Sodium and the Fabric API outside of the screenshots to make sure.

![2021-08-20_18 22 31](https://user-images.githubusercontent.com/56839545/130270840-21a92b64-31cd-4aed-9a7c-3f7798328893.png)

![2021-08-20_18 23 53](https://user-images.githubusercontent.com/56839545/130270936-dd0bb1ef-9501-4ccc-8ea2-73b37e909ec6.png)

**Comment by magneticflux-** [comment] 2021-08-20 18:28
Duplicate of https://github.com/CaffeineMC/sodium-fabric/issues/750

**Closed as completed** 2021-08-20 18:40 UTC
Labels: E-duplicate
