### ISSUE TITLE
Mod not loading

### ISSUE THREAD

**Issue by Seed98** [jellysquid3/Sodium#346] opened 2020-10-09 22:14 UTC
### **Expected Behavior**
You should be able to run this mod on a good mod loader

### **Actual Behavior**
You can only run it on Fabric

### **Reproduction Steps**
 1. Download and Install Forge
 2. Download the mod and paste it in the mods folder
 3. It says "File sodium-fabric-mc1.16.3-0.1.0.jar is a Fabric mod and cannot be loaded"

### **Attachments**
https://prnt.sc/uwf9fx

### **System Information**
• Java Version: openjdk version "11.0.8" 2020-07-14
• CPU: Intel Celeron N2820
• GPU: Nvidia GeForce GTX 285

**Comment by amnotbananaama** [comment] 2020-10-09 22:21
Duplicate of #138 
JellySquid's mods (including Sodium) are for [Fabric Loader](https://fabricmc.net/use). You'll need to install Fabric, and use that with Jelly's mods. See [here](https://gist.github.com/amnotbananaama/e95458d65aaea646b7d3f55337287396) for a tutorial, or join JellySquid's discord if you have any questions getting Fabric set up.

**Closed as completed by amnotbananaama** 2020-10-09 22:21 UTC
Labels: E-duplicate, E-invalid
