### ISSUE TITLE
Water looks as if it was divided by borders/split into multiple sections.

### ISSUE THREAD

**Issue by DTM06** [jellysquid3/Sodium#873] opened 2021-08-30 16:16 UTC
### Version information

mc1.17.1-0.3.2+build.7

### Expected Behavior

![2021-08-30_11 49 48](https://user-images.githubusercontent.com/88454555/131370034-8ac163de-012a-4e0f-a879-7960594090a9.png)
![2021-08-30_11 49 46](https://user-images.githubusercontent.com/88454555/131370036-969fe271-1004-4b3b-bc45-d09715cf5302.png)
Water is connected as it should be.
Screenshots taken in Vanilla 1.17.1.

### Actual Behavior

![2021-08-30_12 05 20](https://user-images.githubusercontent.com/88454555/131370126-afa2ef73-15d4-49be-8e30-f71d607f2155.png)
![2021-08-30_12 02 30](https://user-images.githubusercontent.com/88454555/131370131-eb7d5932-b80d-4fdb-84fa-ef38087751fa.png)
As the title says, water seems to be divided by borders. 

### Reproduction Steps

My settings (if this is a factor) : https://imgur.com/a/DqGyBrl
1. Simply create a giant water pillar in a creative world.
If this step proves to be too difficult, download this world file I've prepared : 
[Water.zip](https://github.com/CaffeineMC/sodium-fabric/files/7078021/Water.zip)

### Java version

Java 16.0.1 64-bit (Bundled)

### CPU

Intel Core i5-10400F

### GPU

Radeon RX 5600 XT, Driver ver. 21.8.2

### Additional information

F3 Debug Menu : 
![image](https://user-images.githubusercontent.com/88454555/131370653-ad6dd38e-d6ea-4291-83b7-7939ed21ce7c.png)
In this screenshot I had multiple mods loaded in addition to Sodium MC, however this issue persists without them..

**Comment by Leo40Git** [comment] 2021-08-30 16:23
This is caused by Sodium's current lack of quad sorting for transparent rendering.

This issue is a duplicate of #38.

**Closed as completed** 2021-08-31 10:25 UTC
Labels: E-duplicate
