### ISSUE TITLE
Sodium completely disables some vanilla shaders & breaks resource packs

### ISSUE THREAD

**Issue by Azagwen** [jellysquid3/Sodium#2126] opened 2023-10-16 16:12 UTC
### Bug Description

With sodium installed/enabled, shaders such as `rendertype_solid` are completely ignored, and resource packs break because of this.
I did not test this much further as it annoyed be quite a lot already, but it is likely that this is affecting other vanilla shaders.

### Reproduction Steps

- Create a basic resource pack containing an edited version of the `rendertype_solid` fragment (fsh) shader, with `main()` edited as seen below:
```
void main() {
    fragColor = vec4(1.0, 0.0, 0.0, 1.0);
}
```
- Copy this pack in a vanilla instance to ensure that it works & join a world. The world should render partly bright red.
- Install Sodium and launch the game with the pack enabled, join a world.
- The world should no longer be red

### Log File

N/A

### Crash Report

N/A

**Comment by Lolothepro** [comment] 2023-10-16 16:13
duplicate of https://github.com/CaffeineMC/sodium-fabric/issues/1569

**Comment by Azagwen** [comment] 2023-10-16 16:16
> duplicate of #1569

Reading comments in this is a real massive bummer, Core shaders may be a bad implementation, but they are nontheless extremely useful, breaking them just makes Sodium unusable in many cases.
Sodium should either provide an alternative, or give users a way to re-enable them (however buggy or hard that may be)

**Comment by douira** [comment] 2023-10-16 16:17
There's plenty of justification in the posted thread as to why there's no support for them.

**Comment by Lolothepro** [comment] 2023-10-16 16:20
> > duplicate of #1569
> 
> Reading comments in this is a real massive bummer, Core shaders may be a bad implementation, but they are nontheless extremely useful, breaking them just makes Sodium unusable in many cases. Sodium should either provide an alternative, or give users a way to re-enable them (however buggy or hard that may be)

Sodium doesn't intentionally disable core-shaders, it's just that they don't work with Sodium, so they're not supported (same thing with OptiFine).

**Comment by douira** [comment] 2023-10-16 16:20
quoted from the other issue:
> They said there were technical limitations which makes it difficult (well, borderline impossible) for other mods to support. It's not that we don't want to support core shaders, it's that there is no good way to support a resource pack which is modifying internal details of a completely different renderer. The constructs that people expect in vanilla's "core shaders" simply do not exist in Sodium's renderer -- they work in completely different ways.

**Closed as not planned** 2023-10-16 17:25 UTC
Labels: E-duplicate

**Comment by Azagwen** [comment] 2023-10-16 17:33
guess I'll disable Sodium then, or find an alternative if I can, not having core shaders is just too much of an inconvenient for resource packs

**Comment by Felix14-v2** [comment] 2023-10-17 01:43
> guess I'll disable Sodium then, or find an alternative

https://github.com/CaffeineMC/sodium-fabric/issues/1569#issuecomment-1547833326
