### ISSUE TITLE
Lava top face is sometimes culled when it can be visible from under the lava blocks height

### ISSUE THREAD

**Issue by GibrielS** [jellysquid3/Sodium#1414] opened 2022-08-05 02:06 UTC
### Version information

sodium-fabric-mc1.17.1-0.3.4+build.13

### Expected Behavior

The top lava face should not be invisible because it is within sight

### Actual Behavior

The top lava face is invisible even though the player can see it

### Reproduction Steps

*this issue has not been reproduced in a vanilla singleplayer world
Go to the same location in Hypixel as shown in the screenshots.

### Java version

16.0.2

### CPU

8th gen Intel core i7 (i7-8700B)

### GPU

Intel UHD Graphics 630

### Additional information

Culling issue

**Comment by douira** [comment] 2024-05-12 15:51
your instructions are not very clear and I'm not sure what you actually mean. Do you mean the inner bottom face of the lava as seen missing in this screenshot? (Spectator mode makes it so there's no lava fog)

![Screenshot 2024-05-12 at 17 50 23](https://github.com/CaffeineMC/sodium-fabric/assets/17120022/fea9cbca-e2b9-494b-ab3d-14ce75d0c992)

**Comment by GibrielS** [comment] 2024-05-13 02:33
My bad, I really should have provided a screenshot. Here is a pretty good setup for it. Setup may have changed slightly since originally posted, version tested: 1.20.4 with the latest 1.20.3 sodium release as of posting this. (unrelated side note: thanks for contributing to one of my favorite minecraft mods!)

![2024-05-12_19 31 38](https://github.com/CaffeineMC/sodium-fabric/assets/71730208/6411deae-90d8-4f7e-985c-f4c827f722e7)

**Comment by GibrielS** [comment] 2024-05-13 02:39
In case the issue isn't obvious, here is a vanilla screenshot of the same location. (And my crosshair is conveniently on the exact mesh that is bugging in the other screenshot!)
![2024-05-12_19 38 48](https://github.com/CaffeineMC/sodium-fabric/assets/71730208/fd037c76-b9ea-4784-a44a-12ed03030f2d)

**Comment by GibrielS** [comment] 2024-05-13 02:41
important to note all the lava is source blocks

I also got a new PC which still suffers the same issue so it probably isn't a graphics driver bug.

the bug is that the culler assumes that the lava isn't bending downwards, when it is.

**Comment by GibrielS** [comment] 2024-05-13 02:59
Something weird is going on here. I can't seem to replicate the bug in a singleplayer world...

**Comment by douira** [comment] 2024-05-13 03:01
For this to be caused by block face culling I'm assuming the section boundary is right below the lowest lava block. It's fixable but either making those faces UNASSIGNED or not making them bend. (We might have an issue for bent fluids, though I'm not sure if this is related to those that have merit)

**Comment by GibrielS** [comment] 2024-05-13 03:02
cannot replicate in my single player world with litematica
![2024-05-12_20 01 14](https://github.com/CaffeineMC/sodium-fabric/assets/71730208/d02c6659-5e22-4e84-88c9-34ead8da1d26)

**Comment by douira** [comment] 2024-12-10 20:16
Fixed in 0.6 as far as I can tell. We changed whether faces are marked UNASSIGNED or POS_Y by looking at the actual corner heights.

**Closed as completed by douira** 2024-12-10 20:16 UTC
Labels: T-bug
