### ISSUE TITLE
1.19.2 sodium crashing when switching dimensions

### ISSUE THREAD

**Issue by CoffeeCupy** [jellysquid3/Sodium#1827] opened 2023-06-19 07:01 UTC
sodium-fabric-mc1.19.2-0.4.4+build.18

load into server
switch lobbies/dimensions
eventually you will crash

**Comment by pajicadvance** [comment] 2023-06-19 10:30
Please provide a client log.

**Comment by CoffeeCupy** [comment] 2023-06-19 12:02
> Please provide a client log.

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/11787857/latest.log)

**Comment by pajicadvance** [comment] 2023-06-19 12:10
Duplicate of #1486 . A potential workaround for this issue has been added, but is only available in Sodium versions for Minecraft 1.19.3 and above.

**Closed as not planned by pajicadvance** 2023-06-19 12:10 UTC
Labels: A-drivers, T-crash, T-native
