### ISSUE TITLE
Textures bugs with a ressource pack (DokuCraft Light)

### ISSUE THREAD

**Issue by LiderKonmils** [jellysquid3/Sodium#1359] opened 2022-06-24 08:40 UTC
### Version information

Minecraft 1.18.2
Fabric: 0.14.8-1.18.2
sodium-fabric-mc1.18.2-0.4.1+build.15

### Expected Behavior

To not glitch?

### Actual Behavior

Some textures dosen't work properly with DokuCraft Light pack and Sodium

### Reproduction Steps

1.Install Fabric (0.14.8-1.18.2)
2.Install Sodium in mods folder
3.Install Dokucraft Light (1.18.2-Dokucraft-Light https://dokucraft.co.uk/resource-packs/light/) as ressource pack
4.Look at Jack-O'Lantern and Bookshelf (Look at the pictures at the additionnal informations section for more info)

### Java version

17.0.1 64bit

### CPU

12x Intel(r) Core(TM) i7-10750H CPU @ 2.60GHz

### GPU

Nvidia GeForce RTX 2060/Pcie/SSE2

### Additional information
![EDIT2022-06-24_04 28 47](https://user-images.githubusercontent.com/1256145/175498216-ba8e5897-8c6a-4e9a-9cf8-5a05955dcc7d.png)
![EDIT2022-06-24_04 29 58](https://user-images.githubusercontent.com/1256145/175498219-aae2e4a2-a5dd-4c51-865b-a7bcd415b5ed.png)

**Comment by pajicadvance** [comment] 2023-05-09 16:22
The resource pack uses Optifine features, in this case emissive textures. Sodium doesn't support them out of the box, but you can use a mod like Continuity to add support for them.

**Comment by pajicadvance** [comment] 2023-05-10 18:02
This may also be a duplicate of #226, which was fixed in a later Sodium update. In any case, this issue should be closed.

**Closed as completed by pajicadvance** 2023-05-10 18:02 UTC
Labels: T-bug
