### ISSUE TITLE
Trial Spawners don't render properly

### ISSUE THREAD

**Issue by BigPhobos** [jellysquid3/Sodium#2540] opened 2024-06-14 03:27 UTC
### Bug Description

With Sodium installed, Trial Spawners and Vaults do not render properly with visual bugs/z-fighting when adjacent to other blocks.
![image](https://github.com/CaffeineMC/sodium-fabric/assets/76231975/68a462f5-a2f5-4ae6-9da8-d4a84de02761)

### Reproduction Steps

1. Run Sodium 0.5.9 on Minecraft 1.21
2. Place a Trial Spawner or Vault
3. Place a block next to the Spawner or Vault
4. Observe visual bugs

### Log File

[latest.log](https://github.com/user-attachments/files/15831138/latest.log)

### Crash Report

[crash-2024-06-13_22.25.17-client.txt](https://github.com/user-attachments/files/15831148/crash-2024-06-13_22.25.17-client.txt)

**Comment by Lolothepro** [comment] 2024-06-14 09:23
This bug is caused by two factors:
Minecraft bug [MC-266463](https://bugs.mojang.com/browse/MC-266463)
The compact vertex format

duplicate of https://github.com/CaffeineMC/sodium-fabric/issues/2004 & MC-266463
In my opinion, this is more a bug in Minecraft Vanilla than in Sodium.

**Comment by BigPhobos** [comment] 2024-06-14 20:33
https://github.com/CaffeineMC/sodium-fabric/assets/76231975/9a3a4e62-c85b-4a5d-9e53-a5d0e0801412

**Comment by jellysquid3** [comment] 2024-06-22 18:10
Probably the only thing that can be done about this is to wait for the improvements to the vertex encoding scheme to come in Sodium 0.6. There just isn't enough vertex precision to correctly render these things.

**Comment by PukPukov** [comment] 2024-07-14 15:56
For those who can't enjoy 1.21 update with that bug: there is a resourcepack that workarounds this issue.

https://modrinth.com/resourcepack/3d-trial-chambers

**Comment by jellysquid3** [comment] 2024-09-23 22:34
This should be resolved in Sodium 0.6.0 since the vertex format has a lot more precision.

**Closed as completed by jellysquid3** 2024-09-23 22:34 UTC
Labels: T-bug
