### ISSUE TITLE
Rendering in screen dissappears after pointing at a different angle.

### ISSUE THREAD

**Issue by Denanie** [jellysquid3/Sodium#1007] opened 2021-12-01 08:17 UTC
### Version information

sodium-fabric-mc1.18-0.4.0-alpha5+build.9

### Expected Behavior

The rendering should be normal at all angles.

### Actual Behavior

Actual in-screen rendering disappears, after looking at a certain angle/point.

### Reproduction Steps

https://user-images.githubusercontent.com/95127675/144196821-2149c42c-4967-4e08-8219-3ccb3f347ed1.mp4

### Java version

17.01

### CPU

Intel i7 8700k

### GPU

MSI 2080 TI X TRIO

**Comment by CyberSteve777** [comment] 2021-12-01 16:35
Experiencing same bug with same sodium and same java version.

![2021-12-01_19 26 46](https://user-images.githubusercontent.com/69720241/144273985-6cd4ec51-d075-4c32-b0dd-701c21a37a17.png)

also here's worldfile for bug review
https://drive.google.com/file/d/1DJ1Zm9oYbO0ADHYFoy1z9R1ak5EPL7lb/view?usp=sharing

**Comment by 3e2j** [comment] 2021-12-02 09:40
Same bug being experienced
![2021-12-02_17 36 50](https://user-images.githubusercontent.com/44019961/144396619-0fd31f23-c135-4c08-9a4d-86d1a771a2f3.png)
![2021-12-02_17 37 01](https://user-images.githubusercontent.com/44019961/144396627-a22fb6a2-cac9-4b8e-89aa-e31efe1f95e7.png)

**Comment by MeeniMc** [comment] 2023-05-11 04:30
duplicate of #872 or #722

**Comment by pajicadvance** [comment] 2023-05-11 11:51
Will mark as duplicate of #872.

**Closed as not planned by pajicadvance** 2023-05-11 11:51 UTC
Labels: T-bug, E-duplicate
