### ISSUE TITLE
Some blocks/chunks flashing

### ISSUE THREAD

**Issue by UsainSrht** [jellysquid3/Sodium#1006] opened 2021-11-29 16:02 UTC
### Version information

sodium-fabric-mc1.17.1-0.3.3+build.8

### Expected Behavior

Normal game without flashing

### Actual Behavior

Game flashing

### Reproduction Steps

1. join a world
2. fly around / rotate your head
3. see flashing

### Java version

Java 16

### CPU

Incel Core 2 Duo E7500

### GPU

AMD RADEON HD 5500

### Additional information

https://user-images.githubusercontent.com/59025999/143901243-858d51e2-739a-4d98-8982-4f67a5660a54.mp4

**Comment by lostopkk** [comment] 2021-11-30 19:02
version: Sodium 0.4.0-alpha5

java: AdoptJDK17

cpu: fx 6300

gpu: amd hd 8490


same here

https://user-images.githubusercontent.com/50776714/144110792-d33bc0ce-2786-4ac1-a31e-925feb9c3d65.mp4

**Comment by master7720** [comment] 2021-11-30 20:44
dis happens to me

**Comment by NerdieBirdieYT** [comment] 2021-12-01 18:49
Happens to me as well.

**Comment by master7720** [comment] 2021-12-01 21:55
> Happens to me as well.

yea it happens to my i thought it was a pc issue lol

**Comment by jellysquid3** [comment] 2021-12-01 22:10
Looks like the problem has to do with the player being located at extreme coordinate values.

**Comment by NerdieBirdieYT** [comment] 2021-12-01 23:07
I was several hundred thousand blocks away from spawn. Tried with the same mods near spawn in a singleplayer world and did not experience the issue.

**Comment by UsainSrht** [comment] 2021-12-02 15:36
> Looks like the problem has to do with the player being located at extreme coordinate values.

Yes you're right.

**Comment by Melvin3000** [comment] 2021-12-02 17:56
Checking `git bisect` showed it being caused by e7afa14b40edfd68bf0f4748ec9f73e5b50affc4, after some further testing it specifically seems to be related to the `frustum.intersectAab` part

https://github.com/CaffeineMC/sodium-fabric/blob/e7afa14b40edfd68bf0f4748ec9f73e5b50affc4/src/main/java/me/jellysquid/mods/sodium/client/render/chunk/region/RenderRegion.java#L129-L139

Setting `visflag` to always return `FrustumIntersection.INSIDE` does appear to completely stop all flashing, but this obviously has some performance implications, and I don't know enough about JOML or Sodium rendering to suggest a real fix.

**Comment by jellysquid3** [comment] 2021-12-02 18:03
We might just want to revert the problematic commit if it's indeed the culprit. The performance improvement was minor & it complicates rendering. A more complete solution in the future would be to use an octree for storing chunks & recursively check nodes against the frustum (an idea that has been on my radar for some time) but I haven't gotten around to it, like most other things...

**Comment by NerdieBirdieYT** [comment] 2021-12-02 19:57
Apologies for being technically illiterate, but will whatever fix you're thinking of be in a new version that I can see from Curseforge? Or is there something different I need to do?

**Comment by birdhimself** [comment] 2021-12-11 18:35
Just thought I'd add my 2 cents here as well. This flickering seems to increase gradually based on how far away the player is from x0 z0, it's pretty noticeable from x1,000,000 x1,000,000 onwards and basically happens constantly from around x10,000,000 y10,000,000 onwards.

Note that I'm using [Fabulously Optimized](https://github.com/Fabulously-Optimized/fabulously-optimized) 3.1.0-alpha.1 which uses Sodium 0.4.0-alpha5+build.9.

https://www.youtube.com/watch?v=PSM7XvzAMrw

_(Uploaded to YouTube because the file size was too big for GitHub, note that higher resolutions might still be processing on their side)_

**Comment by AerodinMC** [comment] 2021-12-14 17:26
https://www.youtube.com/watch?v=CjYvWDXC_vI

This is from an older version but the latest version 1.18.1, Java 17, latest Fabric API etc. still has this issue.  This makes Sodium unusable for me.  Please fix.

**Comment by jellysquid3** [comment] 2021-12-14 17:37
@AerodinMC @C0Nd3Mnd The issues you're talking about are a different problem entirely. See #1006.

**Comment by AerodinMC** [comment] 2021-12-14 18:02
Hmmmm my original issue i opened there was a comment that it was closed
because it said it was a duplicate of #1006 which is why I followed up
after a few weeks after updating to 1.18.1 from 1.17.1 and saw the same
issue.

**Comment by iconFehu** [comment] 2021-12-17 12:31
![image](https://user-images.githubusercontent.com/46149128/146545070-fb77d0f5-fb4d-4f04-8394-65135ede1794.png)

**Comment by lelumlama** [comment] 2022-01-02 03:31
> Checking `git bisect` showed it being caused by [e7afa14](https://github.com/CaffeineMC/sodium-fabric/commit/e7afa14b40edfd68bf0f4748ec9f73e5b50affc4), after some further testing it specifically seems to be related to the `frustum.intersectAab` part
> 
> https://github.com/CaffeineMC/sodium-fabric/blob/e7afa14b40edfd68bf0f4748ec9f73e5b50affc4/src/main/java/me/jellysquid/mods/sodium/client/render/chunk/region/RenderRegion.java#L129-L139
> 
> Setting `visflag` to always return `FrustumIntersection.INSIDE` does appear to completely stop all flashing, but this obviously has some performance implications, and I don't know enough about JOML or Sodium rendering to suggest a real fix.

uh how do i do this im dumb as shit lmao

**Comment by TBNRJediNinja** [comment] 2022-01-06 18:48
is there a way for me to fix this yet?

**Comment by tttsetsy** [comment] 2022-01-15 12:59
Use build 750 (if e7afa14 actually caused this issue)
Download from here: github.com/CaffeineMC/sodium-fabric/actions/runs/1491875735
I can upload my copy of the build if you can't download it

**Closed as completed** 2023-06-18 02:20 UTC
Labels: T-bug, P-high, S-confirmed, S-fixed
