### ISSUE TITLE
Video Settings crashing game

### ISSUE THREAD

**Issue by ConniBug** [jellysquid3/Sodium#211] opened 2020-07-30 00:31 UTC
### Reproduction Steps

1. Load mc
2. Click on video settings
3. Crash your mc client 

### Crash Report File
[GitHub Gist](https://gist.github.com/ConniTheKiwi/ef3f03ba4c4836122d9f549341cc14b6)

### Extra info  

also i get a diff crahs log when i try load into a mc server  [Gist](https://gist.github.com/ConniTheKiwi/24d97886cec8499ad6d932823aef0b95)

im using the mods
fabric-api-0.15.1+build.380-1.16.1
sodium-fabric-mc1.16.1-0.1.0

**Comment by 10884500** [comment] 2020-07-31 17:23
I'm having this issue too, same steps and extra info. Though I am on a mac:
<img width="276" alt="Screen Shot 2020-07-31 at 11 23 05 AM" src="https://user-images.githubusercontent.com/54329583/89060398-3633cc80-d320-11ea-93f7-4cd860b9e9a0.png">

**Comment by TheoCGaming** [comment] 2020-08-03 15:57
Hovering over an option in Video Settings causes:

java.lang.ClassCastException: net.minecraft.class_5481$$Lambda$3128/1151116982 cannot be cast to net.minecraft.class_5348
	at me.jellysquid.mods.sodium.client.gui.SodiumOptionsGUI.renderOptionTooltip(SodiumOptionsGUI.java:215)
	at me.jellysquid.mods.sodium.client.gui.SodiumOptionsGUI.method_25394(SodiumOptionsGUI.java:145)
	at net.minecraft.class_757.method_3192(class_757.java:603)
	at net.minecraft.class_310.method_1523(class_310.java:1020)
	at net.minecraft.class_310.method_1514(class_310.java:653)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

Full crash report below. It's been cleaned up a bit so it's readable.
[crash-2020-08-03_08.35.48-client.txt](https://github.com/jellysquid3/sodium-fabric/files/5016994/crash-2020-08-03_08.35.48-client.txt)

Edit: Using the latest version of windows 7.

**Comment by TheoCGaming** [comment] 2020-08-03 16:01
Might it be because we're using an earlier version of Java? (Java 8, which is somehow still supported)

Because at one point I got an UnsupportedOperation error.

**Comment by amnotbananaama** [comment] 2020-08-03 16:14
@TheoCGaming your crash is unrelated to this issue. This issue is identical to #219 , and is caused by a corrupt or invalid config file. The crash above will be fixed in the 0.2 milestone.

Your crash is caused by attempting to use Sodium—which is only supported for the latest stable release of Minecraft (currently 1.16.1) —on 1.16.2-Pre1. It crashes because there was a change to the item tooltips code. This is something that will be fixed when Sodium is updated to support 1.16.2. For now, you should only use Sodium on 1.16.1.

> Might it be because we're using an earlier version of Java? (Java 8, which is somehow still supported)

Java 8 is actually bundled with the Minecraft vanilla launcher, so there is no problem with using that version of Java. You can read [here](https://github.com/LWJGL/lwjgl/issues/119) and [here](https://gist.github.com/jellysquid3/8a7b21e57f47f5711eb5697e282e502e#but-shouldnt-newer-versions-of-java-perform-better) to learn more about why Mojang is still using Java 8, and [here ](https://blog.ippon.tech/comparing-java-lts-releases) to learn more about the concept of Long-Term Support (LTS) versions of software.

**Comment by TheoCGaming** [comment] 2020-08-03 17:10
Ah. Thanks!

**Comment by jellysquid3** [comment] 2020-08-15 00:25
Your config file is corrupted. Delete the `sodium-options.json` file from your game's `config` folder.

**Comment by jellysquid3** [comment] 2020-08-15 00:25
See #219.

**Closed as completed by jellysquid3** 2020-08-15 00:25 UTC
Labels: E-duplicate, T-crash
