### ISSUE TITLE
Water behind water is weirdly stripy 

### ISSUE THREAD

**Issue by SillyPuffin** [jellysquid3/Sodium#1137] opened 2022-01-16 06:53 UTC
### Version information

1.18-0.4.0 - alpha6-build14

### Expected Behavior

water would look normal and be one colour all the way down

### Actual Behavior

When water  in  a column is viewed through water it makes the water go stripy and the stripes change size depending on which angle you look at.

### Reproduction Steps

place a water source 15 block above the ground, look at the side of the waterfall which is created. It is recreated. As far as I can tell you can use any 1.18 sodium version.

### Java version

Java 17

### CPU

Ryzen 7 3700x

### GPU

Rtx 3070

### Additional information

![2022-01-16_06 53 13](https://user-images.githubusercontent.com/89728058/149650379-d9ea9954-64e7-477a-9d25-f692e7b41185.png)

**Comment by jellysquid3** [comment] 2022-01-19 00:23
Duplicate of #38.

**Closed as completed by jellysquid3** 2022-01-19 00:23 UTC
Labels: T-bug, S-needs-triage
