### ISSUE TITLE
Frequent lag spikes while moving around [Defer chunk updates: off]

### ISSUE THREAD

**Issue by Enchanted-Games** [jellysquid3/Sodium#1070] opened 2021-12-20 20:19 UTC
### Version information

sodium-fabric-mc1.18-0.4.0-alpha5+build.9

### Expected Behavior

No lag spikes should occur while moving

### Actual Behavior

Multiple lag spikes every second when moving around

### Reproduction Steps

1. Turn off "Always Defer Chunk Updates" and set render distance to about 12
2. Create a new worl with this seed: 8027300948549384115
3. TP to this location: /tp @s -247 118 -188
4. Press alt+f3
5. Move around and notice lag spikes while moving

### Java version

Java 17

### CPU

Intel Core 15-9600KF @ 2.70GHz

### GPU

NVIDIA GeForce GTX 1050 ti

### Additional information

Tested with and without Sodium (Iris shaders is not causing the issue) with the same settings and fabric loader version and the issue only happens while sodium is enabled.
Does not happen when "Defer Chunk Updates" is enabled.
The lag spikes are more noticeable with lots of terrain around the player.
Allocating more RAM to the game decreases the strength of the lag spikes but the issue still occurs.
The lag spikes do not occur while standing still.

Here's a screenshot of the F3 screen in case its useful
![image](https://user-images.githubusercontent.com/58823778/146827508-4dd1d4ae-8886-482b-9f28-dee07c27f6bd.png)

**Comment by jellysquid3** [comment] 2022-01-06 19:46
Duplicate of #1044.

**Closed as completed by jellysquid3** 2022-01-06 19:46 UTC
Labels: T-bug, E-duplicate
