### ISSUE TITLE
Sodium Version 0.5.2 causing issues with RTSS (Riva tuner statistics server)

### ISSUE THREAD

**Issue by TryhardTechy** [jellysquid3/Sodium#2071] opened 2023-09-11 17:41 UTC
### Bug Description

while running this version of sodium it is impossible to use RTSS as the game framerate slows down to 1 frame per 3 seconds even in the starting menu. the RTSS overlay never displays when on. once turning RTSS overlay off the game framerate returns to normal.

### Reproduction Steps

1. using multi mc create a new instance for Minecraft version 1.20.1
2. edit instance and install fabric
3. go to loader mods then drag and drop "sodium-fabric-mc1.20.1-0.5.2" in
4. launch the instance
5. when in the start menu press your RTSS "toggle on-screen display" default key
6. game will bog down until "hide on screen display" default key is pressed

### Log File

[2023-09-11-7.log.gz](https://github.com/CaffeineMC/sodium-fabric/files/12578968/2023-09-11-7.log.gz)

### Crash Report

[crash-2023-09-11_13.40.38-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12578984/crash-2023-09-11_13.40.38-client.txt)

**Comment by pajicadvance** [comment] 2023-09-11 17:42
Duplicate of #2048

**Closed as not planned by pajicadvance** 2023-09-11 17:42 UTC
Labels: E-duplicate
