### ISSUE TITLE
Portal error with sodium

### ISSUE THREAD

**Issue by MrPacha23** [jellysquid3/Sodium#1500] opened 2022-11-03 18:51 UTC
### Version information

sodium-fabric-mc1.19.2-0.4.4+build.18

### Expected Behavior

The game should work like a few days ago.

### Actual Behavior

The game don't work if I use sodium.

### Reproduction Steps

First I start my minecraft with fabric 0.14.10, then I get in my server. Everything goes well until I enter a portal, when I cross a portal and the game is loading, it closes and does not send a crash report. A few days ago everything was going well and suddenly it started giving me that error, I have a friend who has the same mods that I attached and this problem does not happen to her and she has a PC with worse components.

### Java version

Java 8 / 1.8.0_351-b10

### CPU

Intel Core i5 8400

### GPU

Nvidia Geforce GTX 1660S 6G

### Additional information

![image](https://user-images.githubusercontent.com/75518975/199807894-d442eff9-1d11-48a2-b8b1-1ba2fbfb3d40.png)

**Comment by Timolino456** [comment] 2022-11-03 21:30
Did you add or update any mods in the meantime? Try with only Sodium and if it doesn't happen anymore then, add one mod after another until you find the one that's causing it.

**Comment by Kronex6** [comment] 2022-11-05 09:05
same problem

**Comment by Kronex6** [comment] 2022-11-05 09:20
it is caused by litematica phosphor cant handel litematica pls fix

**Comment by Lesniak17** [comment] 2022-11-09 14:33
I'm having exactly the same issue. The game crashes everytime I switch dimensions using a Nether Portal, this applies to any kind of world, both offline and servers. I threw out all mods except Sodium and Litematica (plus its co-working library mod MaliLib). The game works fine with only one of them at a time.

EDIT: It turns out to be NVidia Driver's issue:

~ https://github.com/CaffeineMC/sodium-fabric/issues/1486

~ https://github.com/maruohon/litematica/issues/601

~ https://www.curseforge.com/minecraft/mc-mods/litematica?comment=2585

**Comment by jellysquid3** [comment] 2022-11-09 14:54
NVIDIA broke something in their graphics driver. We can't do anything to fix it. Submit a bug report to them, and downgrade your graphics driver.

Duplicate of #1486.

**Closed as completed by jellysquid3** 2022-11-09 14:54 UTC
Labels: T-bug, S-needs-triage
