### ISSUE TITLE
Minecraft crashing when joining a server

### ISSUE THREAD

**Issue by Intybyte** [jellysquid3/Sodium#442] opened 2020-12-25 10:51 UTC
### Reproduction Steps
First i joined a server: mc.gameuniverse.tk, using fabric with sodium, phosphor.
The game will first say joining then will say saving and finally crash.

### Crash Report File
https://gist.github.com/Intybyte/cd7d775040b81b4c9d4695ac22311740

### Additional Information
When joining a server without sodium everything works fine. It is not a fabric issue.
If I first join another server and then join the server with that entity that causes the crash, everything works fine.

**Comment by DIMMfour** [comment] 2021-01-05 04:34
(I saw your other post btw)
Ok, so I had the exact same problem.
For me, if I tried to go into my video settings, the game would still crash.
So it was clear that (for me at least) the problem was a bugged setting, that won't let the world render.

The easiest way to undo this is just to delete your sodium settings.
Ctrl F your .minecraft folder for "sodium" 
(or you could just look for it in your config folder in .minecraft)
There are two .json files called "sodium-mixins.properties" and "sodium-options.json"
I deleted both of them, restarted my game, and it was fixed.

Hopefully this works!

**Comment by NahFamilia** [comment] 2021-01-16 14:40
Hey
SO I did what you said and it worked!!
Thanks you!!
:)

**Comment by XfedeX** [comment] 2021-02-20 16:31
@Intybyte Can you please close this?

**Comment by silversquirl** [comment] 2021-02-20 16:54
Duplicate of #219

**Closed as completed by silversquirl** 2021-02-20 16:54 UTC
Labels: E-duplicate, T-crash
