### ISSUE TITLE
Ender Chest lid having a motion while in the Enderchest GUI. (Video samples of the bug included)

### ISSUE THREAD

**Issue by AdelinaM17n** [jellysquid3/Sodium#284] opened 2020-08-26 14:14 UTC
### Expected Behavior
Ender chest lid to be motionless while in the enderchest GUI

### Actual Behavior
Ender chest lid having motion while in the GUI.
https://drive.google.com/file/d/1r0tDSNelRvUmo8PJ41PIVnn3pDEBSp2h/view?usp=sharing  (video sample)
 
### Reproduction Steps
Place a ender chest and open it in a angle that you can view the enderchest Lid while being on the GUI.

### Attachments
https://drive.google.com/file/d/1r0tDSNelRvUmo8PJ41PIVnn3pDEBSp2h/view?usp=sharing  (Same Video sample given above)

### System Information
You can obtain this information from the in-game debug screen or through using [DxDiag](https://support.microsoft.com/en-us/help/4028644/windows-open-and-run-dxdiagexe) on Windows.

- Java Version: [14.0.2 (Issue can be reproduced in Java version 8 too)]
- CPU: [Intel i5 8250U (Has been tested in a PC with Ryzen 7 3700 too)]
- GPU: [ Nvidia mx150 (Has been tested in the PC mentioned above which has a RX Vega 54) ]

**Comment by amnotbananaama** [comment] 2020-09-08 20:17
I can't reproduce this with either the 0.1 release, or (1df506f) in singleplayer. What other mods are you using? It's possible another mod is causing this.

**Comment by AdelinaM17n** [comment] 2020-09-14 04:57
> I can't reproduce this with either the 0.1 release, or ([1df506f](https://github.com/jellysquid3/sodium-fabric/commit/1df506fd39dac56bb410725c245e6e51208ec732)) in singleplayer. What other mods are you using? It's possible another mod is causing this.

Other mods that was used was carpet mod and carpet extra mod
and voxelmap(it doesn't use fabric api so i can be certain i did not have fabric api)

**Comment by NoComment1105** [comment] 2020-09-28 15:45
This is a vanilla issue, itself, I had the issue regardless of what mods I used. It has been reported several times on the Minecraft bug trackers so it'll get noticed soon. I personally don't think it is that big of an issue, it's kind of funny to watch :P. (You can close it this if you want, but I don't have any authority over you so it doesn't matter :P.)

**Comment by ryleu** [comment] 2020-09-28 19:53
Same issue in Ubuntu with an ASUS x550za (Radeon R6 integrated graphics).

Not at all a major issue, and tbh it’s kinda fun to watch. Sometimes a similar thing happens where an EC will open and then stay open. I thought it was my WiFi, but I guess it’s just a weird vanilla thing.

**Comment by NoComment1105** [comment] 2020-09-29 15:34
Yeah, I agree :). This probably can be closed now as its not sodium related

**Closed as completed** 2020-09-29 15:36 UTC
Labels: T-bug, E-external
