### ISSUE TITLE
Stained Glass/Water Bug

### ISSUE THREAD

**Issue by edmib1** [jellysquid3/Sodium#439] opened 2020-12-24 14:38 UTC
Before i report this i try to change fabric api, uninstall other mods but it didnt work. On Optifine everything is ok.
![2020-12-24_15 25 20](https://user-images.githubusercontent.com/76562697/103094470-e40c8400-45fd-11eb-8908-9e4282ddaef9.png)

- Java Version: [1.8.0_51 64bit]
- CPU: [intel core i5-3570K]
- GPU: [GTX 960]

**Comment by amnotbananaama** [comment] 2020-12-24 15:34
Thanks for reporting this is a duplicate of #38

**Closed as completed by amnotbananaama** 2020-12-24 15:34 UTC
Labels: T-bug, E-duplicate
