### ISSUE TITLE
Fluid backfaces use wrong shape on slopes

### ISSUE THREAD

**Issue by fayer3** [jellysquid3/Sodium#2570] opened 2024-06-23 11:19 UTC
### Bug Description

Fluid back and front faces on slopes use a differnt triangle layout, which make them not allign and causes visual artefacts

![grafik](https://github.com/CaffeineMC/sodium-fabric/assets/8282299/6fbea58b-2846-45fc-9bc9-b325908fc554)

https://github.com/CaffeineMC/sodium-fabric/assets/8282299/1b2e5c1d-b48c-4323-a6fd-2409977b609e

### Reproduction Steps

easiest way to reproduce it, is to build a 2 block tall pyramid, and pour lava over it, the indented slopes will show the issue well when looking from slightly below.
![grafik](https://github.com/CaffeineMC/sodium-fabric/assets/8282299/b2539bce-0ed0-4c98-b260-97f76d999b99)
![grafik](https://github.com/CaffeineMC/sodium-fabric/assets/8282299/d4f0d3be-6ab2-4850-8a23-c695c965f414)

### Log File

[latest.log](https://github.com/user-attachments/files/15944296/latest.log)

### Crash Report

[crash-2024-06-23_13.19.04-client.txt](https://github.com/user-attachments/files/15944297/crash-2024-06-23_13.19.04-client.txt)

**Comment by fayer3** [comment] 2024-06-23 11:21
using latest 1.21 sodium `sodium-fabric-0.5.9+mc1.21.jar`

**Comment by douira** [comment] 2024-06-23 16:20
Thanks for letting us know the fix for this wasn't in 0.5. I implemented a fix for the duplicate of this issue https://github.com/CaffeineMC/sodium-fabric/issues/609 in dev a while back which has now been backported. This issue can be closed. (and maybe put in the 0.5.11 milestone)

**Closed as completed** 2024-06-23 17:41 UTC
Labels: E-duplicate
