### ISSUE TITLE
Fix light pixels on block edges visible in dark areas - MC-175333

### ISSUE THREAD

**Issue by LucilleTea** [jellysquid3/Sodium#578] opened 2021-03-14 04:00 UTC
[MC-175333](https://bugs.mojang.com/browse/MC-175333)

Sky-coloured pixels are sometimes visible on the edges of blocks, particularly noticeable in dark areas. This appears to be a vanilla issue that used to be hidden by Sodium's Compact Vertex Format (on my hardware?). CVF no longer hides the issue after 547c41cf0694fa1b3af5b047eb5f42b1916d3c33, and still not after 2fb1d28aa61680170e44a138c296f3b5534314e0.

This can be reproduced in Sodium by loading [this test world](https://cdn.discordapp.com/attachments/651120262129123330/820142367439978516/reproduction.zip) with FOV set to the minimum and a game resolution of 2476x1417, for me. With a different FOV or resolution you will have to set your mouse sensitivity low and move slowly until you find it.

[The bug seen in Sodium](https://cdn.discordapp.com/attachments/651120262129123330/820146147426304001/2021-03-13_14.36.58.png)
[The bug seen in Vanilla](https://cdn.discordapp.com/attachments/651120262129123330/820498450969264128/unknown.png)

**Comment by mrmangohands** [comment] 2021-07-11 07:14
Should be fixed by 0e73f35b2780a40f2c32303a5e815446df06d6d4

**Closed as completed by mrmangohands** 2021-07-11 07:14 UTC
Labels: T-enhancement

**Comment by Urshee** [comment] 2021-12-03 06:40
I'm experiencing what seems to be the same issue. Sky-colored pixels/rows of pixels appear on the edges of blocks and are most visible in dark areas, but are sometimes difficult to spot. When I was using Complementary Shaders with Iris Starline installed, which allowed me to enable anti-aliasing (both FXAA and TAA), the issue was much less noticeable. The issue is not present at all for me in vanilla. Below are the screenshots, which also show information on my system and Java/Sodium version via the F3 menu.

### Vanilla

![2021-12-03_01 25 01](https://user-images.githubusercontent.com/95390063/144555689-c9c99fd4-aeeb-47fc-aaa2-fe10b550af3e.png)

### Sodium (no AA)

![Just Sodium](https://user-images.githubusercontent.com/95390063/144556525-7ff7780c-f7ac-492d-a91a-6cf4fcc179e0.jpg)

### FXAA

![FXAA](https://user-images.githubusercontent.com/95390063/144556893-05bbd277-f2d5-4455-9084-a2206e3dbfd9.jpg)

### TAA

![2021-12-03_01 20 29](https://user-images.githubusercontent.com/95390063/144555900-22377097-618c-4a7a-b321-ade0e0bdd082.png)

**Comment by callmejay758** [comment] 2021-12-08 21:18
Also experiencing the above, also with complementary on. On AOF4, mining is pretty distracting.

Edit, noticed it happens without complementary on, its less noticeable.

**Comment by Dashiba** [comment] 2024-02-15 21:42
Having this issue as well, as long as Sodium and Iris are enabled, this happens to me, with or without shaders.

The thing I noticed is this is way... WAY more noticable depending on what mods I have enabled, I don't know why but "Twilight Forest" makes it happen everywhere, all the time.

**Comment by astridellensdottir** [comment] 2024-02-16 02:20
you are commenting this on an issue which was closed three years ago. it would be more useful to fill in a new issue with new logs, a crash report, and screenshots from your own issue, as it’s likely similar visually, but caused by something different from what was marked fixed three years ago and having no other reporters.

**Comment by Dashiba** [comment] 2024-02-16 13:34
> you are commenting this on an issue which was closed three years ago. it would be more useful to fill in a new issue with new logs, a crash report, and screenshots from your own issue, as it’s likely similar visually, but caused by something different from what was marked fixed three years ago and having no other reporters.


Yea I would gladly do that If i had any freaking idea on how GitHub works, I got here by searching it in google.
