### ISSUE TITLE
Portal rendering behind other portal

### ISSUE THREAD

**Issue by olafx** [jellysquid3/Sodium#1058] opened 2021-12-15 23:05 UTC
### Version information

sodium-fabric-mc1.18-0.4.0-alpha5+build.9

### Expected Behavior

There's a minor graphical bug rendering portals behind other portals.
See [this](https://imgur.com/a/ayvrBzE) screenshot for the correct vanilla rendering.

### Actual Behavior

See [this](https://imgur.com/a/e6JIAlJ) screenshot for the sodium rendering. Interestingly this seems to only happen when the observed portal is in the same chunk as the portal being looked through. If the portal being observed is in a different chunk than the portal being looked through, it renders fine.

### Reproduction Steps

Observe nether portal blocks through other nether portal blocks so that both are in the same chunk. Can also test with them being in other chunks to see that then the problem does not occur.

### Java version

Java 17

### CPU

Intel i9 9880h

### GPU

AMD 5500M

**Comment by Pectacular** [comment] 2021-12-16 04:45
I think this is a duplicate of #38

**Comment by LucilleTea** [comment] 2021-12-16 09:26
Yes, duplicate of #38

**Closed as completed by LucilleTea** 2021-12-16 09:26 UTC
Labels: T-bug, E-duplicate
