### ISSUE TITLE
Game Crashes When You Enter a New Demention with Litematica mod installed 

### ISSUE THREAD

**Issue by Zyloin** [jellysquid3/Sodium#1516] opened 2022-11-19 13:07 UTC
### Version information

mc1.19.2-0.4.4+build.18

### Reproduction Steps

Version 1.19.2
MODS: fabric api-0.66.0 (latest), Sodium 0.440 build.18(latest), malilib-fabric-1.19.2-0.13.0(latest), litematica-fabric-1.19.2-0.12.5(latest)
 
Replicating singelplayer:
Open Minecraft
make a new word (or open an old one)
make a nether portal
go through nether or end portal
GAME CRASHES

Multiplayer
Open Minecraft
select a server with lobbies and whatnot
go to a different lobby 
Game crashes

The game also crashes when reloading textures or changing texture packs

https://user-images.githubusercontent.com/118611163/202852292-566ef1ca-730a-4c87-b3c6-2b06eed1fe5d.mp4

### Crash Report file

[clientId.txt](https://github.com/CaffeineMC/sodium-fabric/files/10046996/clientId.txt)

**Comment by Wonkglorg** [comment] 2022-11-19 16:58
Same issue here. Started when updating nvidia drivers for me

**Comment by Scarlaid** [comment] 2022-11-19 17:31
same issue with #1486

**Comment by jellysquid3** [comment] 2022-11-19 17:32
Duplicate of #1486. Ask NVIDIA to stop breaking our stuff.

**Closed as completed by jellysquid3** 2022-11-19 17:32 UTC
Labels: T-crash, S-needs-triage
