### ISSUE TITLE
Game crashes on startup with no mods other than sodium (Possible solutions found, have 3rd gen intel processor)

### ISSUE THREAD

**Issue by Bytepop** [jellysquid3/Sodium#1278] opened 2022-04-20 02:20 UTC
### Version information

sodium-fabric-mc1.18.2-0.4.1+build.15

### Reproduction Steps

1. Install new fabric profile.
2. Install sodium in mods folder after downloading .jar file.
3. load up fabric profile in default vanilla launcher.

Game will load a small amount, then crash, always at the same loaded amount.

![image](https://user-images.githubusercontent.com/79096180/164133634-afcb3127-1759-47d8-a49f-5ee6735f9c37.png)

![image](https://user-images.githubusercontent.com/79096180/164133777-0f0acca7-023a-4422-b780-79f1c0a81ca4.png)

### Crash Report file

[22:02:51] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.13.3
[22:02:52] [main/WARN]: Warnings were found!
 - Mod 'Fabric Rendering Fluids (v1)' (fabric-rendering-fluids-v1) 2.0.1+54e5b2ecd2 recommends any version of fabric-textures-v0, which is missing!
	 - You should install any version of fabric-textures-v0 for the optimal experience.
[22:02:52] [main/INFO]: Loading 9 mods:
	- fabric-api-base 0.4.3+d7c144a8d2 via sodium
	- fabric-rendering-data-attachment-v1 0.3.6+d7c144a8d2 via sodium
	- fabric-rendering-fluids-v1 2.0.1+54e5b2ecd2 via sodium
	- fabric-resource-loader-v0 0.4.16+55dca1a4d2 via sodium
	- fabricloader 0.13.3
	- java 17
	- minecraft 1.18.2
	- org_joml_joml 1.10.2 via sodium
	- sodium 0.4.1+build.15
[22:02:52] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/nands/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.11.2+mixin.0.8.5/sponge-mixin-0.11.2+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[22:02:52] [main/INFO]: Compatibility level set to JAVA_16
[22:02:52] [main/INFO]: Compatibility level set to JAVA_17
[22:02:52] [main/INFO]: Loaded configuration file for Sodium: 29 options available, 0 override(s) found
[22:02:52] [main/INFO]: Trying to switch memory allocators to work around memory leaks present with Jemalloc 5.0.0 through 5.2.0 on Windows
[22:03:01] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[22:03:02] [Render thread/INFO]: Setting user: quantum_goat
[22:03:02] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 build 10
[22:03:05] [Render thread/INFO]: Narrator library for x64 successfully loaded
[22:03:05] [Render thread/INFO]: Reloading ResourceManager: Default, Fabric Mods (Fabric API Base, Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Resource Loader (v0), Fabric Loader, Sodium)

**Comment by Kroppeb** [comment] 2022-04-20 09:03
The "crash report" you copied is just a small (and unrelated) part of the log file.

**Comment by DragonoidOmega** [comment] 2022-04-21 13:11
What are the "Possible solutions"  you have found?

**Comment by jellysquid3** [comment] 2022-04-23 02:49
This issue is a duplicate of #899. Please see the instructions there on how to fix it.

**Closed as completed by jellysquid3** 2022-04-23 02:49 UTC
Labels: E-duplicate, T-crash
