### ISSUE TITLE
Fullscreen Resolution Setting Missing

### ISSUE THREAD

**Issue by Gamepro5** [jellysquid3/Sodium#2209] opened 2023-12-14 07:25 UTC
### Bug Description

Self explanatory. It's a vanilla setting.

### Reproduction Steps

n/a

### Log File

n/a

### Crash Report

n/a

**Comment by TheUserCreated** [comment] 2023-12-14 07:51
press shift+P while in the video settings to access the vanilla settings you need to change in that menu. Otherwise, this is a duplicate of #1380 .

**Closed as not planned** 2023-12-14 10:46 UTC
Labels: E-duplicate
