### ISSUE TITLE
Texture not loading any block mod Industrial Revolution

### ISSUE THREAD

**Issue by mr-feijao** [jellysquid3/Sodium#966] opened 2021-11-12 15:42 UTC
### Version information

mc 1.17.1

### Expected Behavior

the texture loading

### Actual Behavior

the texture of the mod is not loading
mod Industrial Revolution

### Reproduction Steps

just instaling mod and join a personal server

### Java version

java 17.0.1

### CPU

Xeon 1650 v0

### GPU

RX 570 4G Saphire Pulse

### Additional information

frist is with sodium
![Screenshot_1](https://user-images.githubusercontent.com/93002116/141493062-8ea35c22-add6-4548-8a33-dc02e5b62d07.png)
second is without sodium
![sem sodium](https://user-images.githubusercontent.com/93002116/141493065-61fb0ccf-34c7-4ed0-b661-bc34ffa10ca6.png)
config in game
![Screenshot_2](https://user-images.githubusercontent.com/93002116/141493398-d85651ff-f173-43c5-a8d4-02db15a6af82.png)
![Screenshot_3](https://user-images.githubusercontent.com/93002116/141493402-f1867c12-a8df-484c-a055-1870f16db583.png)
![Screenshot_4](https://user-images.githubusercontent.com/93002116/141493404-5bd4b3d1-4c44-4a5b-b85e-bcc9e349b80e.png)

**Comment by silversquirl** [comment] 2021-11-12 15:51
Duplicate of #5

**Closed as completed by silversquirl** 2021-11-12 15:51 UTC
Labels: E-duplicate
