### ISSUE TITLE
Custom Fullscreen Resolutions

### ISSUE THREAD

**Issue by Flannelator** [jellysquid3/Sodium#200] opened 2020-07-28 18:10 UTC
The first thing I noticed when Installing this on my Macbook Air (2018) was that I could not set a custom full screen resolution so I was stuck trying to play at 1600p (16:10 equivalent of 1440p) on an integrated GPU (and I think we can all guess how that went...) I would assume its a small and simple feature to add, however I may be wrong, I would just like to be able to use a custom resolution and I'm sure many others would too. Thanks!

**Comment by ghost** [comment] 2020-07-28 18:12
may i suggest trying out https://www.curseforge.com/minecraft/mc-mods/retino

**Comment by juster-0** [comment] 2020-07-30 14:48
> may i suggest trying out https://www.curseforge.com/minecraft/mc-mods/retino

I use Arch Linux with 4k display, and I can’t use the mod to change my full screen resolution.

**Comment by ghost** [comment] 2020-07-30 15:58
> > may i suggest trying out https://www.curseforge.com/minecraft/mc-mods/retino
> 
> I use Arch Linux with 4k display, and I can’t use the mod to change my full screen resolution.

ah well you did say you use mac so I wasnt aware lol

**Comment by juster-0** [comment] 2020-07-30 16:03
> > > may i suggest trying out https://www.curseforge.com/minecraft/mc-mods/retino
> > 
> > 
> > I use Arch Linux with 4k display, and I can’t use the mod to change my full screen resolution.
> 
> ah well you did say you use mac so I wasnt aware lol

We are different people, so check our nicknames, please.

**Comment by amnotbananaama** [comment] 2020-08-25 16:41
@ItzM4T7 for clarity, are you trying to access the "Fullscreen Resolution" option in Vanilla's Video Settings menu? If so this is a duplicate of #46.

Or do you essentially want the features of [retiNO](https://github.com/juliand665/retiNO) or [Resolution Control](https://github.com/juliand665/Resolution-Control) added to Sodium? If so this is a duplicate of #121.

**Comment by amnotbananaama** [comment] 2020-12-12 07:46
Closing after a significant period of inactivity. This is a duplicate of one of the issues I linked above

**Closed as completed by amnotbananaama** 2020-12-12 07:46 UTC
Labels: E-duplicate, T-enhancement
