### ISSUE TITLE
Chunk become invisible (at least) at specific position in specific seed

### ISSUE THREAD

**Issue by cloudy1552** [jellysquid3/Sodium#1584] opened 2023-01-23 11:20 UTC
### Version information

sodium-fabric-mc1.19.3-0.4.8+build.22

### Expected Behavior

Chunk should not become invisible.

### Actual Behavior

if i stand at specific position in specific seed and look down over angle 45 depression degrees, chunk become invisible.

### Reproduction Steps

make new world in seed -4327102225930669092
tp 341,96,914(position)
place a full block at 341,96,914(block you are looking at)
dig 342,96,911~914 342,95,9128(block you are looking at)
look north and toward block that you placed in no3 at depression angle 45 degrees
chunk next to me become invisible
![Inked2023-01-23_19 31 44](https://user-images.githubusercontent.com/121796704/214026779-4212375a-b1a1-444c-9a59-184063d8f4c2.jpg)

### Java version

java 17.0.3 64bit

### CPU

intel core i7-7700HQ

### GPU

intel hd graphics 630

### Additional information

i try same position in other seeds, but this didnt happed.

**Comment by Timolino456** [comment] 2023-01-23 21:56
Seems to be just a case of a chunk getting culled wrongly, this is known and should be fixed with the new culling system they're working on (that might still take a while).

**Comment by LucilleTea** [comment] 2023-01-26 00:35
Duplicate of #872 or #722 or similar

**Closed as completed by LucilleTea** 2023-01-26 00:35 UTC
Labels: T-bug, E-duplicate
