### ISSUE TITLE
Glass and Water faces causing visual bug

### ISSUE THREAD

**Issue by SSavitar1290** [jellysquid3/Sodium#2800] opened 2024-10-06 03:44 UTC
### Bug Description

![bug](https://github.com/user-attachments/assets/7e65b062-dc89-4234-a9cf-959b34b4b887)
![bug2](https://github.com/user-attachments/assets/b3822ff9-c0d6-466e-9129-9ec6be7d8e7c)

### Reproduction Steps

Have a wall of glass in the ocean with water behind the wall of glass, and blocks or air on the other sides of the glass

### Log File

https://paste.ee/p/pI9A3

### Crash Report

i dont have a crash report and the F3 + C keybind didn't work

**Comment by MCRcortex** [comment] 2024-10-06 03:44
Fixed in 0.6

**Comment by SSavitar1290** [comment] 2024-10-06 03:47
wdym by that?

**Comment by SSavitar1290** [comment] 2024-10-06 03:47
sorry didnt mean to close

**Comment by TheUserCreated** [comment] 2024-10-06 04:28
this is a duplicate of issue #38, which was fixed in sodium 0.6, which is currently in beta.

**Comment by ghost** [comment] 2024-10-06 06:44
> wdym by that?

You need to update Sodium and associated mods to their latest versions. The bug was fixed in Sodium 0.6.0.

**Closed as not planned** 2024-10-06 10:16 UTC
Labels: E-duplicate
