### ISSUE TITLE
I cant figure out how to change my fov because the video settings have a different menu

### ISSUE THREAD

**Issue by meliathequeer** [jellysquid3/Sodium#675] opened 2021-06-06 22:32 UTC

**Comment by pajicadvance** [comment] 2021-06-06 22:38
The FOV slider isn't even in the video settings menu, it's in the main options screen in the top left...

**Comment by amnotbananaama** [comment] 2021-06-06 22:40
If you mean the FOV effects slider, this is a duplicate of #46. Some settings are currently missing from Sodium's menu and need to be added.

As a workaround, you can use the `Shift + P` key combination while in Sodium's video settings to access the vanilla menu.

**Closed as completed by amnotbananaama** 2021-06-06 22:40 UTC
Labels: T-question
