### ISSUE TITLE
Breaking blocks glitches out Minecraft and I can see through blocks for a second.

### ISSUE THREAD

**Issue by Ved-151** [jellysquid3/Sodium#1801] opened 2023-06-10 12:49 UTC
### Version information

sodium-fabric-mc1.20-0.4.10+build.27

### Expected Behavior

When I break or place blocks, I shouldn't be able to see through blocks.

### Actual Behavior

When I break or place blocks, I can see through the blocks for a second or so. How can I fix it, it really annoys me! Please watch the video for a detailed explaination.

https://github.com/CaffeineMC/sodium-fabric/assets/136171834/e1858724-b132-4de1-9d4a-0e65cc391c50

### Reproduction Steps

IDK

### Java version

Java 17.0.3 & 64 Bits

### CPU

Intel Core i3-1005G1 CPU @ 1.20GHz (4 CPUs)

### GPU

Intel UHD Graphics.

### Additional information

I know its bad specs but without Sodium, the bug doesn't occur.

**Comment by pajicadvance** [comment] 2023-06-10 12:56
Duplicate of #869

**Closed as not planned by pajicadvance** 2023-06-10 12:56 UTC
Labels: T-bug, A-drivers
