### ISSUE TITLE
Applied Energistics 2 Cables Render Incorrectly

### ISSUE THREAD

**Issue by hexablend** [jellysquid3/Sodium#418] opened 2020-12-10 23:33 UTC
The Cable and Cable Facade Textures from AE2 aren't rendered correctly.
mod version: 0.1.0
fabric: 0.6.1.51
![bug](https://user-images.githubusercontent.com/75815676/101842299-07d4c200-3b48-11eb-9b2e-2e76c1c6434e.png)

- Java Version: [1.8.0_241]
- CPU: [i7 5820K]
- GPU: [R9 290x]
![bug](https://user-images.githubusercontent.com/75815676/101842324-0f946680-3b48-11eb-95c6-19812d6b181d.png)

**Comment by ImperatorStorm** [comment] 2020-12-10 23:35
Applied Energistics 2 appears to utilize the Fabric Rendering API

Fabric Rendering API support is not yet implemented in Sodium, see #5

**Comment by amnotbananaama** [comment] 2020-12-10 23:40
Closing as a duplicate of the aforementioned issue.

**Closed as completed by amnotbananaama** 2020-12-10 23:40 UTC
Labels: T-bug, E-duplicate
