### ISSUE TITLE
Improve performance of text and toolbar

### ISSUE THREAD

**Issue by xhmr** [jellysquid3/Sodium#487] opened 2021-01-21 16:58 UTC
**Is your feature request related to a problem? Please describe.**
Please improve performance of text rendering: chat, scoreboard, nicknames above players, holograms, toolbar and maybe bossbar. They take a lot of fps.

**Comment by amnotbananaama** [comment] 2021-01-21 21:03
You already made an issue about this, closing as a duplicate of #382

**Closed as completed by amnotbananaama** 2021-01-21 21:03 UTC
Labels: E-duplicate, T-enhancement

**Comment by xhmr** [comment] 2021-01-21 21:08
@amnotbananaama ye, nothing changed since november...
