### ISSUE TITLE
Immediate Crash on Launch (Linux, Nvidia)

### ISSUE THREAD

**Issue by Ilecyutal** [jellysquid3/Sodium#2635] opened 2024-08-05 01:30 UTC
### Bug Description

The game window opens as a blackscreen and closes shortly after.

### Reproduction Steps

Using the modpack Prominence 2 RPG installed using MultiMC from Modrinth, using Java 22 OpenJDK on KDE Plasma Wayland.
Launch the modpack from MultiMC.

### Log File

[latest.log](https://github.com/user-attachments/files/16489606/latest.log)

### Crash Report

I am unable to get to the main menu to generate a Crash Report using F3+C.
There is no crash report automatically generated

**Comment by jellysquid3** [comment] 2024-08-05 01:55
The message in the log file asking you to report the issue here is in error. We changed it in a future version to be less confusing for users.

The problem is likely that your user-mode driver is incompatible with the kernel-mode driver. This frequently happens on Linux distributions with the proprietary NVIDIA graphics driver.

Make sure your system is fully up-to-date and ensure that Minecraft can launch _without_ Sodium installed. If the problem happens without Sodium installed, you have a broken system configuration.

**Comment by jellysquid3** [comment] 2024-08-07 04:50
I'm closing this as the problem is likely nothing to do with Sodium, but rather a system misconfiguration. If you can launch Minecraft normally but not with Sodium, then please reach out to us [on our Discord server](https://caffeinemc.net/discord) so we can help you.

**Closed as not planned by jellysquid3** 2024-08-07 04:50 UTC
Labels: E-external, A-drivers, T-crash
