### ISSUE TITLE
problems with glass and water

### ISSUE THREAD

**Issue by EJK3903** [jellysquid3/Sodium#1417] opened 2022-08-07 18:41 UTC
### Version information

sodium-fabric-mc1.19-0.4.2+build.16.jar

### Expected Behavior

water should look normal when next to other streams of water aswell as through glass

### Actual Behavior

water that is next to each other borders each block as well as doing the same through glas
![2022-08-07_19 10 34](https://user-images.githubusercontent.com/91976235/183306058-5b43caf3-01c4-4f15-85c6-119e9db0409f.png)
![2022-08-07_19 40 24](https://user-images.githubusercontent.com/91976235/183306104-e05838ee-cd6c-4b54-a721-38206328170a.png)
![2022-08-07_19 40 28](https://user-images.githubusercontent.com/91976235/183306107-e2c037de-9e2f-42d1-90f0-8ef02d18ca59.png)
s

### Reproduction Steps

look at water that is flowing or behind glass

### Java version

16

### CPU

i5 9600k

### GPU

1060 6gb

**Comment by hexadecimal233** [comment] 2022-08-11 03:55
#38

**Comment by LambdAurora** [comment] 2022-08-12 00:45
As pointed out this is a duplicate of issue 38.

**Closed as not planned by LambdAurora** 2022-08-12 00:45 UTC
Labels: T-bug, E-duplicate
