### ISSUE TITLE
Marker armor stands on fire not staying lit.

### ISSUE THREAD

**Issue by xEmberx** [jellysquid3/Sodium#645] opened 2021-04-27 17:44 UTC
### Version Information

sodium-fabric-mc1.16.4-0.1.1+build.351

### Expected Behavior

The marker armor stand is on fire thus rendering lit up.

![image](https://user-images.githubusercontent.com/74155501/116286702-8465e700-a75d-11eb-8ec2-a939efc072fa.png)

### Actual Behavior

The armor stand is not rendered as though it's lit up from the fire, even though it is on fire.

Example: ![image](https://user-images.githubusercontent.com/74155501/116286619-6b5d3600-a75d-11eb-9f5e-c75fb7b00eb7.png)

### Reproduction Steps

`setblock ~ ~ ~ stone`
Then, standing on the stone block, `summon armor_stand ~ ~-1 ~ {Marker:1,Fire:10000}`

### System Information

Java Version: 1.8.0_51 64bit
CPU: Intel Core i5-9600k @ 3.7
GPU: GeForce RTX 2070 Super

**Comment by LucilleTea** [comment] 2021-04-28 06:42
Duplicate of #68

**Closed as completed by LucilleTea** 2021-04-28 06:42 UTC
Labels: T-bug, E-duplicate
