### ISSUE TITLE
Resource packs don't change video settings assets

### ISSUE THREAD

**Issue by Lentern** [jellysquid3/Sodium#481] opened 2021-01-16 14:39 UTC
### Expected Behavior
A resource pack that I made will change the "Bright" brightness setting to say "+100%"

### Actual Behavior
Brightness says "Bright" instead, as if nothing changed. This bug does not occur in the vanilla video settings menu.

### Reproduction Steps
1) Download the attached resource pack (Brightness Options Fix.zip) and apply it on 1.16.2 or above.
2) Head to video settings, and press Shift + P to see the vanilla settings menu.
3) Set your brightness to what would usually say "Bright" and it will instead say +100%. This is intended.
4) Head back to the sodium video settings menu, and it will say "Bright" instead.

- Java Version: AdoptOpenJDK 11.0.10.9
- CPU: Intel Core i7 9700F 3 GHz
- GPU: GeForce GTX 1650
- Fabric 0.10.8
- Sodium 0.1.0

### Attachments
[Brightness Options Fix.zip](https://github.com/jellysquid3/sodium-fabric/files/5824538/Brightness.Options.Fix.zip)
[Vanilla Video Settings Menu](https://user-images.githubusercontent.com/73498459/104814716-7d365100-57de-11eb-9c13-10db2113a06b.png)
[Sodium Video Settings Menu](https://user-images.githubusercontent.com/73498459/104814725-81fb0500-57de-11eb-915f-43ce4815bea9.png)

**Comment by fsharpseven** [comment] 2021-01-21 23:50
As I understand it, recent builds of sodium don't support translation (see #482), and by extension your resource pack. This is planned to be added at some point. Sorry for the inconvenience.

**Comment by Lentern** [comment] 2021-01-24 12:31
> As I understand it, recent builds of sodium don't support translation

Yeah, vanilla's resource pack stuff isn't perfect either, there still isn't a way to change what it says for gamma values above 1.0.

**Comment by LucilleTea** [comment] 2021-03-01 11:09
This is a duplicate of #44, a feature request for localization support. Changing English text via resource pack will be possible once localization is implemented.

**Closed as completed by LucilleTea** 2021-03-01 11:09 UTC
Labels: T-bug, E-duplicate
