### ISSUE TITLE
Crash when joining into the world

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#1517] opened 2022-11-20 12:53 UTC
### Version information

sodium-fabric-mc1.17.1-0.3.4+build.13-1

### Reproduction Steps

1. Create worlds
2. Join the world
3. Minecraft crashes

### Crash Report file

[crash-2022-11-20_12.46.03-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/10049712/crash-2022-11-20_12.46.03-client.txt)
[latestlog.txt](https://github.com/CaffeineMC/sodium-fabric/files/10049713/latestlog.txt)

**Comment by thboehi** [comment] 2022-11-21 14:34
I've the same issue but on a multiplayer Proxy server.

When I change server through portal, the game crash. It happens only with sodium activate.

**Comment by afrigge** [comment] 2022-11-23 11:02
I have the same issue as [thomaboehi](https://github.com/thomaboehi).
I works fine as long as I don't use a portal. Walk into portal = game crash.
Everything works without sodium though.

**Comment by afrigge** [comment] 2022-11-23 11:07
Removed Litematica and it works with Sodium. Might be something with the two mods together.

**Comment by afrigge** [comment] 2022-11-23 11:35
https://github.com/maruohon/litematica/issues/621#issuecomment-1322726566
This might just be a GeForce issue for you too.
I downgraded my recently updated GPU-drivers and it fixed it.
Installed version 522.25

**Comment by pajicadvance** [comment] 2023-05-10 17:25
Duplicate of #1486.

**Closed as not planned** 2023-05-12 17:52 UTC
Labels: E-duplicate, A-drivers, T-crash
