### ISSUE TITLE
[Bug/Request] Fabric rendering API support (or so I'm told)

### ISSUE THREAD

**Issue by MechanosG** [jellysquid3/Sodium#370] opened 2020-10-30 19:25 UTC
When using the mod [Modern Industrialization](https://www.curseforge.com/minecraft/mc-mods/modern-industrialization), their machine textures show up in purple and black checker.  There's a discussion about it in the [comments](https://www.curseforge.com/minecraft/mc-mods/modern-industrialization?comment=27) saying the problem is Sodium not supporting the Fabric API (yet, but in the works) and includes a screenshot in REI, which I'll link below.

Sodium helps my FPS so much that playing without it isn't really an option for me now.  But that also means mods like Modern Industrialization are currently barred from use.  So I figured I would post an issue about it.  I apologize if this is something that gets asked a lot or anything, as I didn't see any open issues related to this but I assume this is a pretty big milestone.  Anyway, thank you for such an awesome mod.

### Expected Behavior
Machine blocks with textures.

### Actual Behavior
Machine blocks without textures.

### Reproduction Steps
1. Install Fabric, Sodium, Roughly Enough Items, and Modern Industrialization.
2. Search @Modern in REI

### Attachments
https://i.imgur.com/XPeNuNa.png

- Java Version: [1.8.0_241]
- CPU: [Athlon 2 x4 640] (yes it's ancient, but it still works)
- GPU: [AMD Radeon R9 290X]

**Comment by LambdAurora** [comment] 2020-10-30 19:50
Fabric rendering API support is planned.

Duplicate of #5.

**Closed as completed by LambdAurora** 2020-10-30 19:50 UTC
Labels: T-bug, E-duplicate

**Comment by MechanosG** [comment] 2020-10-30 22:16
Do you happen to know if there's any progress?  The original thread is from March.  I didn't realize this goes back 7 months.

**Comment by LambdAurora** [comment] 2020-10-30 22:18
There's a big refactor incoming, so until that is finished there shouldn't be any work done on this.
And there's no ETA.

**Comment by MechanosG** [comment] 2020-10-30 22:25
That's unfortunate.  I suppose I'll have to avoid mods incompatible with Sodium for the time being.  Thanks for the info.
