### ISSUE TITLE
Entity Distance does not save

### ISSUE THREAD

**Issue by NoComment1105** [jellysquid3/Sodium#65] opened 2020-07-08 10:28 UTC
### Expected Behavior
When altering entity distance you set it to what you want and click apply

### Actual Behavior
It just resets to 100% each time

### Reproduction Steps
Not exactly causing a crash just what I noticed

1. Go into settings
2. Alter entity distance, click apply and leave settings
3. go back into settings and see 100%

### System Information

- Java Version: [1.8.0_51 64-bit]
- CPU: [Intel i5 5300 U @2.30GHz]
- GPU: [Intel HD Graphics 5500]
- DirectX: [Version 12]
- RAM: [8 GB]

**Comment by amnotbananaama** [comment] 2020-07-13 01:24
@NoComment1105 Are you still able to reproduce this? I can't reproduce the issue, the value is saved properly for me.

**Comment by NoComment1105** [comment] 2020-07-13 08:57
> @NoComment1105 Are you still able to reproduce this? I can't reproduce the issue, the value is saved properly for me.

Yes i am still able to reproduce, however it is only when you lower the entity distance and not when you raise it

**Comment by amnotbananaama** [comment] 2020-07-13 14:04
Confirmed on the latest commit (currently https://github.com/jellysquid3/sodium-fabric/commit/885222a476b7054ae428031d72c0b47fa579872a). ![](https://i.imgur.com/X2zEF1E.png)

**Analysis**
It looks like the problematic line of code is the `Math.round()` function [here](https://github.com/jellysquid3/sodium-fabric/blob/d4939573d2a7b4699d379b24e8222630a441ecf2/src/main/java/me/jellysquid/mods/sodium/client/gui/SodiumGameOptionPages.java#L200). Since the values for Entity Distance 50% and 75% are converted to 0.5 and 0.75 respectively, the `Math.round()` function rounds them to the nearest integer (which would be  1.0 or 100%). This has the effect of the option _appearing_ not to save even though it is saving a rounded result. I'm not sure what the best fix for this would be, as I'm not  sure of Jelly's preferences or alternative rounding operations to use.

**Comment by NoComment1105** [comment] 2020-07-13 14:45
> Confirmed on the latest commit (currently [885222a](https://github.com/jellysquid3/sodium-fabric/commit/885222a476b7054ae428031d72c0b47fa579872a)). ![](https://camo.githubusercontent.com/1497bb5dc9d58f6d7314aba5804021daffe30b89/68747470733a2f2f692e696d6775722e636f6d2f58327a454631452e706e67)
> 
> **Analysis**
> It looks like the problematic line of code is the `Math.round()` function [here](https://github.com/jellysquid3/sodium-fabric/blob/d4939573d2a7b4699d379b24e8222630a441ecf2/src/main/java/me/jellysquid/mods/sodium/client/gui/SodiumGameOptionPages.java#L200). Since the values for Entity Distance 50% and 75% are converted to 0.5 and 0.75 respectively, the `Math.round()` function rounds them to the nearest integer (which would be 1.0 or 100%). This has the effect of the option _appearing_ not to save even though it is saving a rounded result. I'm not sure what the best fix for this would be, as I'm not sure of Jelly's preferences or alternative rounding operations to use.

OK, thanks for still looking into it even though you couldn't reproduce initially, will this be fixed for the next version?

**Closed as completed** 2020-07-13 17:39 UTC
Labels: T-bug, S-confirmed

**Comment by CalXee** [comment] 2020-10-22 15:59
In 1.16.2+, you can save it above 100%. It just won't do anything.
