### ISSUE TITLE
Stained glass not filled

### ISSUE THREAD

**Issue by MCDoerfi** [jellysquid3/Sodium#422] opened 2020-12-16 19:56 UTC
I have sodium installed and the stained glass is fully transparent like normal glass. Without sodium it works fine.

**Comment by Chronoken** [comment] 2020-12-17 18:04
Known issue, will be fixed in the future but there is no ETA.

**Comment by amnotbananaama** [comment] 2020-12-24 17:36
Closing as a duplicate of #38

**Closed as completed by amnotbananaama** 2020-12-24 17:36 UTC
Labels: T-bug, E-duplicate
