### ISSUE TITLE
Improper culling of tinted and stained glass block faces and non-full water blocks, through tinted and stained glass, and block selection outline. (chunky?)

### ISSUE THREAD

**Issue by pobblebonkq** [jellysquid3/Sodium#2612] opened 2024-07-21 03:04 UTC
### Bug Description

It's really hard for me to put to words what exactly is going on here, because it seems whatever glitch is causing this is very convoluted and frankly I think the pictures do a better job speaking for themselves, but I will attempt to describe what I think is happening to the best of my ability.

It looks like whatever weird culling is going on has to do with 3 things, chunks, and faces, and the direction you are facing relative to the world. Some faces from some orientations render things appropriately, and others not so much, and then in a different position the same faces might have swapped or both render normal or not, idk there's a lot going on and it feels like I'm looking through a kaleidoscope any time I'm looking down into my stray grinder. Something of note visible in the first picture in the stray grinder below the tinted glass floor on the right with the waterlogged signs, source water blocks that are not flowing, either literally not flowing or not deformed by flowing, are properly rendered from all angles. Normal glass also does not appear to have any issues.

![2024-07-20_22 00 49](https://github.com/user-attachments/assets/90c6f925-d258-41b5-ad38-2a007b556827)
![2024-07-20_22 43 46](https://github.com/user-attachments/assets/b0fbe9d7-04a9-40e9-b5ea-b3f342341f80)

This issue also is apparent with dropped item entities of stained and tinted glass blocks, got a better screenshot demonstrating this with the first person mod instead of having to perfectly drop the two glass items w/o picking them up by accident.

![2024-07-20_22 44 27](https://github.com/user-attachments/assets/fc15581e-c9e9-4adc-a3c2-6878dbda64f7)

I'm not 100% sure if this is just a mod issue but I ran this with no mods a the sodium only install, and everything minecraft/fabric/iris/sodium and video card driver related is up to date. I've also searched and seen somewhat similar issues relating to water and glass, just wondering if anyone else has had this issue or this particular iteration of this issue is known of.

My version is sodium-fabric-0.5.11+mc1.21.jar

### Reproduction Steps

1.) Build a 4x4x3 cube out of tinted or any color stained glass, with flowing water in the 2x2x1 volume in the middle, between more than 1 chunk
2. ) Build a roof of tinted or any color stained glass over the pit
3. ) Observe

### Log File

[latest.log](https://github.com/user-attachments/files/16322942/latest.log)

### Crash Report

No crash associated with this issue, manual crash log generated here.

[crash-2024-07-20_23.03.45-client.txt](https://github.com/user-attachments/files/16322945/crash-2024-07-20_23.03.45-client.txt)

**Comment by Lolothepro** [comment] 2024-07-21 03:42
Duplicate of https://github.com/CaffeineMC/sodium-fabric/issues/38 (?)

**Comment by douira** [comment] 2024-07-21 12:32
The issue with the blocks is #38. For the hand rendering, that's not #38 but might just get fixed by using fabulous mode (?). You can join our discord server to try out Test builds of sodium 0.6 in which a solution to #38 (translucency sorting) is implemented.

**Comment by jellysquid3** [comment] 2024-07-23 05:22
Closing as a duplicate of the aforementioned issues.

**Closed as not planned by jellysquid3** 2024-07-23 05:22 UTC
Labels: T-bug, E-duplicate
