### ISSUE TITLE
Render error

### ISSUE THREAD

**Issue by Fix3dll** [jellysquid3/Sodium#477] opened 2021-01-10 16:45 UTC
![Screenshot_7](https://user-images.githubusercontent.com/10743391/104128937-55c52b80-537b-11eb-9932-28890bb23478.png)

When i select OpenGL 4.3 render errors start with it. With or without starlight result same.

- Other Mods: 
![Screenshot_6](https://user-images.githubusercontent.com/10743391/104129103-3a0e5500-537c-11eb-933e-0834c964f8ae.png)

- Java Version:
 openjdk version "15.0.1" 2020-10-20
 OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.1+9)
 OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.1+9, mixed mode, sharing)

- CPU: i7 960
- GPU: HD 5870

**Comment by Fix3dll** [comment] 2021-01-11 00:19
When i try to open game with Linux Mint Mesa driver,
![IMG_20210111_025117](https://user-images.githubusercontent.com/10743391/104139296-980e5d00-53bb-11eb-8ed5-6004fdbcee29.jpg)
System start to freeze after than graphic driver close itself. Screen goes blackscreen. I have to restart the computer. This one which i try to open game with OpenGL 4.3.

**Comment by Fix3dll** [comment] 2021-01-11 00:26
When i try open game with OpenGL 3 after then change version to 4.3 ingame,
https://user-images.githubusercontent.com/10743391/104139447-a3ae5380-53bc-11eb-8474-d9c59e6530a9.mp4
Firstly sorry for quality. When i change it to 4.3 screen starts blinking white and freezes.

**Comment by Fix3dll** [comment] 2021-01-11 00:30
![IMG_20210111_030942](https://user-images.githubusercontent.com/10743391/104139545-4961c280-53bd-11eb-91d3-8108942f7dba.jpg)
This one for see driver name better. I am not good with linux. Just do it for testing.

**Comment by fsharpseven** [comment] 2021-01-21 23:52
Duplicate of #24. Unfortunately, you will have to continue using the 3.0 renderer as you have been.

**Closed as completed** 2021-02-23 23:18 UTC
Labels: T-bug, E-duplicate
