### ISSUE TITLE
Stutter and Insane spikes

### ISSUE THREAD

**Issue by DarkShardGamer** [jellysquid3/Sodium#1083] opened 2021-12-25 16:38 UTC
### Version information

sodium-fabric-mc1.18-0.4.0-alpha5+build.9

### Expected Behavior

Just function normally

### Actual Behavior

When I join a specific server, it starts stutters and causing lag spikes all over the place. If I join another server, it doesn't occur

### Reproduction Steps

1. Join server A
2. Stutter

1. Join server B
2. No Stutter

### Java version

Latest

### CPU

8x 11th Gen Intel(R) Core(TM) i7-1165G7  2.80Ghz

### GPU

Intel(R) Iris(R) Xe Graphics

**Comment by ThimothyXYZ123** [comment] 2021-12-26 06:20
I think Server A spawn has alot of entities so it lags your computer

**Comment by ghost** [comment] 2021-12-26 13:39
You are literally saying on one server it lags and on another it doesn't. The problem is related to server, there might be too many entities at server's spawn.

**Comment by jellysquid3** [comment] 2022-01-06 19:29
Provide frame times graphs (see ALT+F3) and/or information about the server, along with a client log file.

Without this information it is impossible to know what issue you are running into or for us to have any hope of reproduce it.

**Comment by jellysquid3** [comment] 2023-07-22 02:22
Per changes in policy on our issue tracker, we are closing issues which are general inquiries about performance issues and such. If you are experiencing performance issues and need help, then please use the [Discord server](https://caffeinemc.net/discord).

**Closed as not planned by jellysquid3** 2023-07-22 02:22 UTC
Labels: T-bug, S-info-needed
