### ISSUE TITLE
Terrain is almost entirely invisible

### ISSUE THREAD

**Issue by Myxter06** [jellysquid3/Sodium#1150] opened 2022-01-21 00:17 UTC
### Version information

mc1.18.1-0.4.0-alpha6+build.14

### Expected Behavior

Terrain should be visible.

### Actual Behavior

Almost all terrain is invisible, except for some blocks in caves, some sandy areas, and some trees.
![2022-01-20_15 36 54](https://user-images.githubusercontent.com/92181482/150440079-2fe4cf5b-2376-4925-8ba2-3447c41e9d2c.png)
![2022-01-20_13 31 01](https://user-images.githubusercontent.com/92181482/150440135-6574460f-0fa7-483d-8b0c-1e47ff1f5bc6.png)

### Reproduction Steps

This happens regardless of whether or not I'm using any other mods, resource packs, or shaders.  It doesn't matter what world I'm playing on.  It only happens when I use Sodium 1.18.1 Alpha 6.

### Java version

Java 8

### CPU

Intel Core i7-9750H

### GPU

NVIDIA GeForce RTX 2070 with Max-Q Design

### Additional information

Log:
[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/7909270/latest.log)

**Comment by Vultaz** [comment] 2022-01-29 01:14
Radeon RX580, I get invisible faces on occasion.
version - sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14

![image](https://user-images.githubusercontent.com/92063761/151641335-0fc22f34-f09b-4ef5-98cc-670929d9d71b.png)

**Comment by imcasper** [comment] 2022-02-04 12:19
![изображение](https://user-images.githubusercontent.com/23495732/152528061-08c96886-222a-4028-8c6b-87002d0230bb.png)


I'm guessing I have a similar problem. Although I play with different mods.

Game: 1.18.1
Fabric-api 0.46.0 
Java: 17

.../fabric-api-0.46.0+1.18.jar
.../lithium-fabric-mc1.18.1-0.7.7.jar
.../sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14.jar
.../starlight-1.0.0+fabric.d0a3220.jar

This screenshot is from a desktop PC.
Also tested on a weak laptop. There are no blocks at all. I can add details if that helps.

**Comment by imcasper** [comment] 2022-02-04 12:25
![изображение](https://user-images.githubusercontent.com/23495732/152528996-7ee92139-146e-4672-9130-7ef6e3d93789.png)

![изображение](https://user-images.githubusercontent.com/23495732/152528418-515538bc-7bf0-4ccb-8ad2-e0bb20f0057e.png)
Also, part of the caves disappears and appears depending on the direction of view. Can't identify patterns for hide grass-surface. It seems absolutely random that there are simply no pieces

**Comment by imcasper** [comment] 2022-03-07 17:39
Good news everyone...
I still don't know what the problem is. Nevertheless, the error can be temporarily stopped without visible rendering problems:

![изображение](https://user-images.githubusercontent.com/23495732/157087983-616a4f6b-55c9-487e-9793-7b989c655a64.png)

Self exception:

[20:33:58] [Chunk Render Task Executor #0/INFO] (Minecraft) [STDERR]: java.lang.NullPointerException: Cannot invoke "net.minecraft.util.Identifier.toString()" because "targetBiomeId" is null
[20:33:58] [Chunk Render Task Executor #0/INFO] (Minecraft) [STDERR]: 	at retr0.bedrockwaters.WaterPropertiesReplacer.getBiomeWaterProperties(WaterPropertiesReplacer.java:26)
[20:33:58] [Chunk Render Task Executor #0/INFO] (Minecraft) [STDERR]: 	at retr0.bedrockwaters.BedrockWaters.lambda$onInitializeClient$3(BedrockWaters.java:29)
[20:33:58] [Chunk Render Task Executor #0/INFO] (Minecraft) [STDERR]: 	at me.jellysquid.mods.sodium.client.world.biome.BlockColorCache.gatherColorsXZ(BlockColorCache.java:91)
[20:33:58] [Chunk Render Task Executor #0/INFO] (Minecraft) [STDERR]: 	at me.jellysquid.mods.sodium.client.world.biome.BlockColorCache.getColor(BlockColorCache.java:62)
[20:33:58] [Chunk Render Task Executor #0/INFO] (Minecraft) [STDERR]: 	at me.jellysquid.mods.sodium.client.world.WorldSlice.getColor(WorldSlice.java:263)
[20:33:58] [Chunk Render Task Executor #0/INFO] (Minecraft) [STDERR]: 	at net.minecraft.client.color.world.BiomeColors.getColor(BiomeColors.java:14)
[20:33:58] [Chunk Render Task Executor #0/INFO] (Minecraft) [STDERR]: 	at net.minecraft.client.color.world.BiomeColors.getWaterColor(BiomeColors.java:26)
[20:33:58] [Chunk Render Task Executor #0/INFO] (Minecraft) [STDERR]: 	at net.fabricmc.fabric.impl.client.rendering.fluid.FluidRenderHandlerRegistryImpl$1.getFluidColor(FluidRenderHandlerRegistryImpl.java:92)
[20:33:58] [Chunk Render Task Executor #0/INFO] (Minecraft) [STDERR]: 	at me.jellysquid.mods.sodium.client.render.pipeline.FluidRenderer$FabricFluidColorizerAdapter.getColor(FluidRenderer.java:474)
[20:33:58] [Chunk Render Task Executor #0/INFO] (Minecraft) [STDERR]: 	at me.jellysquid.mods.sodium.client.render.pipeline.FluidRenderer$FabricFluidColorizerAdapter.getColor(FluidRenderer.java:461)
[20:33:58] [Chunk Render Task Executor #0/INFO] (Minecraft) [STDERR]: 	at me.jellysquid.mods.sodium.client.model.quad.blender.LinearColorBlender.getBlockColor(LinearColorBlender.java:28)
[20:33:58] [Chunk Render Task Executor #0/INFO] (Minecraft) [STDERR]: 	at me.jellysquid.mods.sodium.client.model.quad.blender.LinearColorBlender.getVertexColor(LinearColorBlender.java:53)
[20:33:58] [Chunk Render Task Executor #0/INFO] (Minecraft) [STDERR]: 	at me.jellysquid.mods.sodium.client.model.quad.blender.LinearColorBlender.getColors(LinearColorBlender.java:20)
[20:33:58] [Chunk Render Task Executor #0/INFO] (Minecraft) [STDERR]: 	at me.jellysquid.mods.sodium.client.render.pipeline.FluidRenderer.calculateQuadColors(FluidRenderer.java:379)
[20:33:58] [Chunk Render Task Executor #0/INFO] (Minecraft) [STDERR]: 	at me.jellysquid.mods.sodium.client.render.pipeline.FluidRenderer.render(FluidRenderer.java:211)
[20:33:58] [Chunk Render Task Executor #0/INFO] (Minecraft) [STDERR]: 	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.performBuild(ChunkRenderRebuildTask.java:109)
[20:33:58] [Chunk Render Task Executor #0/INFO] (Minecraft) [STDERR]: 	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder.processJob(ChunkBuilder.java:254)
[20:33:58] [Chunk Render Task Executor #0/INFO] (Minecraft) [STDERR]: 	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:294)
[20:33:58] [Chunk Render Task Executor #0/INFO] (Minecraft) [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Myxter06** [comment] 2022-04-08 22:39
> Good news everyone... I still don't know what the problem is. Nevertheless, the error can be temporarily stopped without visible rendering problems:
> 
> ![изображение](https://user-images.githubusercontent.com/23495732/157087983-616a4f6b-55c9-487e-9793-7b989c655a64.png)
> 
> Self exception:
> 
> [20:33:58] [Chunk Render Task Executor #0/INFO] (Minecraft) [STDERR]: java.lang.NullPointerException: Cannot invoke "net.minecraft.util.Identifier.toString()" because "targetBiomeId" is null [20:33:58] [Chunk Render Task Executor #0/INFO] (Minecraft) [STDERR]: at retr0.bedrockwaters.WaterPropertiesReplacer.getBiomeWaterProperties(WaterPropertiesReplacer.java:26) [20:33:58] [Chunk Render Task Executor #0/INFO] (Minecraft) [STDERR]: at retr0.bedrockwaters.BedrockWaters.lambda$onInitializeClient$3(BedrockWaters.java:29) [20:33:58] [Chunk Render Task Executor #0/INFO] (Minecraft) [STDERR]: at me.jellysquid.mods.sodium.client.world.biome.BlockColorCache.gatherColorsXZ(BlockColorCache.java:91) [20:33:58] [Chunk Render Task Executor #0/INFO] (Minecraft) [STDERR]: at me.jellysquid.mods.sodium.client.world.biome.BlockColorCache.getColor(BlockColorCache.java:62) [20:33:58] [Chunk Render Task Executor #0/INFO] (Minecraft) [STDERR]: at me.jellysquid.mods.sodium.client.world.WorldSlice.getColor(WorldSlice.java:263) [20:33:58] [Chunk Render Task Executor #0/INFO] (Minecraft) [STDERR]: at net.minecraft.client.color.world.BiomeColors.getColor(BiomeColors.java:14) [20:33:58] [Chunk Render Task Executor #0/INFO] (Minecraft) [STDERR]: at net.minecraft.client.color.world.BiomeColors.getWaterColor(BiomeColors.java:26) [20:33:58] [Chunk Render Task Executor #0/INFO] (Minecraft) [STDERR]: at net.fabricmc.fabric.impl.client.rendering.fluid.FluidRenderHandlerRegistryImpl$1.getFluidColor(FluidRenderHandlerRegistryImpl.java:92) [20:33:58] [Chunk Render Task Executor #0/INFO] (Minecraft) [STDERR]: at me.jellysquid.mods.sodium.client.render.pipeline.FluidRenderer$FabricFluidColorizerAdapter.getColor(FluidRenderer.java:474) [20:33:58] [Chunk Render Task Executor #0/INFO] (Minecraft) [STDERR]: at me.jellysquid.mods.sodium.client.render.pipeline.FluidRenderer$FabricFluidColorizerAdapter.getColor(FluidRenderer.java:461) [20:33:58] [Chunk Render Task Executor #0/INFO] (Minecraft) [STDERR]: at me.jellysquid.mods.sodium.client.model.quad.blender.LinearColorBlender.getBlockColor(LinearColorBlender.java:28) [20:33:58] [Chunk Render Task Executor #0/INFO] (Minecraft) [STDERR]: at me.jellysquid.mods.sodium.client.model.quad.blender.LinearColorBlender.getVertexColor(LinearColorBlender.java:53) [20:33:58] [Chunk Render Task Executor #0/INFO] (Minecraft) [STDERR]: at me.jellysquid.mods.sodium.client.model.quad.blender.LinearColorBlender.getColors(LinearColorBlender.java:20) [20:33:58] [Chunk Render Task Executor #0/INFO] (Minecraft) [STDERR]: at me.jellysquid.mods.sodium.client.render.pipeline.FluidRenderer.calculateQuadColors(FluidRenderer.java:379) [20:33:58] [Chunk Render Task Executor #0/INFO] (Minecraft) [STDERR]: at me.jellysquid.mods.sodium.client.render.pipeline.FluidRenderer.render(FluidRenderer.java:211) [20:33:58] [Chunk Render Task Executor #0/INFO] (Minecraft) [STDERR]: at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.performBuild(ChunkRenderRebuildTask.java:109) [20:33:58] [Chunk Render Task Executor #0/INFO] (Minecraft) [STDERR]: at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder.processJob(ChunkBuilder.java:254) [20:33:58] [Chunk Render Task Executor #0/INFO] (Minecraft) [STDERR]: at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:294) [20:33:58] [Chunk Render Task Executor #0/INFO] (Minecraft) [STDERR]: at java.base/java.lang.Thread.run(Thread.java:833)

So what exactly does this mean?  Can it be fixed?  If so, how?

**Comment by imcasper** [comment] 2022-04-09 15:25
How should I know. I didn't write this mod. I can only assume that this is due to version incompatibility. The error itself is somewhere in the bowels of the core of the game, probably.
It seems to me a good idea to test the mod with specific versions of lithium, indium, sodium, and write about it.
For myself, I picked up a working version on version 1.18.1.

PS Try the latest version of the game (1.18.1). If that's not possible, play around with mod versions (indium, lithium, etc).

**Comment by Myxter06** [comment] 2022-05-05 19:02
Alright everyone, I figured out how to solve the issue (at least in my case) and it's a strange but simple fix.  It has something to do with Sodium's biome blend setting.  What I didn't realize is that the maximum value is usually 7, but mine was set far above that.  Probably because I used to use a better biome blend mod that allowed for greater values, and I guess the higher value was still present in a config or something, which caused issues.  Just drag the biome blend slider to 0 and back again, and you should be good to go.

**Comment by MeeniMc** [comment] 2023-05-11 23:20
Issue contains a blend of reports duplicate of #872 and some new issue with setting invalid values for the biome blending (user issue resolved by unsetting the invalid option).

Consider whether it is worth adding a sanity check on the max value of biome blending.

**Closed as not planned** 2023-09-17 17:40 UTC
Labels: E-external
