### ISSUE TITLE
Sodium Light Error Crash - "Tried to mark light data as ready for chunk but it hasn't been loaded yet"

### ISSUE THREAD

**Issue by serioos** [jellysquid3/Sodium#1177] opened 2022-02-13 00:25 UTC
### Version information

sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14

### Reproduction Steps

I don't know how to reproduce it. I was attacking a cow when I suddenly crashed out of nowhere.
I was playing on a multiplayer server with my friend. She didn't crash.

### Crash Report file

https://pastebin.com/rXnHp44j

**Comment by Kroppeb** [comment] 2022-02-13 01:22
Do you know if there are any mods/plugins on the server?

**Comment by Speeder323** [comment] 2022-02-13 18:17
Seems to be the same as/ related to #1016

**Comment by serioos** [comment] 2022-02-13 18:33
@kroppeb

Yes it is a modded server. The same mods are on it that are in my log with the exception of some of the mods that are client only.

**Comment by silversquirl** [comment] 2022-02-16 06:20
Duplicate of #1016

**Closed as completed by silversquirl** 2022-02-16 06:20 UTC
Labels: E-duplicate, T-crash
