### ISSUE TITLE
I cant play mc using sodium it freezes on startup when loading in the buttons of the start menu

### ISSUE THREAD

**Issue by kr1viah** [jellysquid3/Sodium#903] opened 2021-09-13 13:45 UTC
### Version information

1.17.1 or 1.17

### Reproduction Steps

Startup mc
Loading in the buttons(multiplayer, single, etc.)
Freeze

### Crash Report file

I doesnt crash so yeeeaaaaaaaaa

### Additional information

(i need to close it with task mannager)

**Comment by jellysquid3** [comment] 2021-09-16 20:31
Duplicate of #899.

**Closed as completed by jellysquid3** 2021-09-16 20:31 UTC
