### ISSUE TITLE
Sodium crashing my game

### ISSUE THREAD

**Issue by Dev421** [jellysquid3/Sodium#976] opened 2021-11-18 06:59 UTC
### Version information

sodium-fabric-mc1.17.1-0.3.2+build.7 

### Reproduction Steps

I am using windows 11 and whenever i run fabric without sodium it works but when i place sodium in the mods folder the game crashes

### Crash Report file

[Log File.txt](https://github.com/CaffeineMC/sodium-fabric/files/7560668/Log.File.txt)

### Additional information

yesterday when i was running fabric with sodium the game started and all things were normal suddenly i turned off m computer due to some problem but when i loaded my fabric loader today i was getting this error but when i removed sodium from mods folder the game crashed again the log file is provided pls help me.

**Comment by Leo40Git** [comment] 2021-11-18 10:53
Your config file is corrupted. Delete the file `(your minecraft directory)/config/sodium-options.json`.

**Comment by amnotbananaama** [comment] 2021-11-18 19:27
I'm going to close this as a duplicate of #219. The next release of Sodium will catch this and not crash

**Closed as completed by amnotbananaama** 2021-11-18 19:27 UTC
Labels: E-duplicate, T-crash
