### ISSUE TITLE
invisible chunks flashing when i break/place blocks

### ISSUE THREAD

**Issue by froggytato** [jellysquid3/Sodium#1048] opened 2021-12-13 00:59 UTC
### Version information

sodium-fabric-mc1.18-0.4.0-alpha5+build.9

### Expected Behavior

the block should just break, without me seeing through it or anything

### Actual Behavior

i get a frame of seeing through an area near the block i just mined

here's a video of what i'm seeing
[https://www.youtube.com/watch?v=H-QJ6yuQLcU](url)
(in the video i'm using extra sodium options as well, but i reinstalled sodium on a new directory with ONLY sodium, and i'm still getting the same issue)

### Reproduction Steps

1. download mc1.18-0.4.0-alpha5 of sodium
2. fabric installer 0.10.2
3. fabric api 0.44.0
4. join a server (i haven't tested the issue in singleplayer)
5. break or place a block in an enclosed area (you may need to do this multiple times) -> the bug doesn't happen when i'm on the surface
6. the bug happens

### Java version

Java 17.0.1 64bit

### CPU

Intel Core i5-1035G1 CPU @ 1.00GHz

### GPU

Intel UHD Graphics

### Additional information

![2021-12-12_12 14 54](https://user-images.githubusercontent.com/96029811/145737210-ead78289-699e-4ec0-8c23-69969d5ae991.png)
an example of what's happening

**Comment by yichenethan** [comment] 2021-12-13 05:29
Yeah it seems like intel drivers just... do not play well.

I'm having a similar issue, septically when I break or place blocks in the overworld surface.

**Comment by ThatMG393** [comment] 2021-12-17 02:09
Me too, it flashes when I break or place blocks.

**Comment by FreezePhoenix** [comment] 2021-12-17 02:25
Any chunk update causes this flashing to occur - blocks spreading, etc.

**Comment by Genau6502** [comment] 2021-12-19 22:23
> Any chunk update causes this flashing to occur - blocks spreading, etc.

Seems to be caused by chunk rebuilds - which explains why I get the same effect while using LDL

**Comment by Tippysiamang** [comment] 2021-12-20 07:23
me 2
lol

**Comment by Tippysiamang** [comment] 2021-12-20 07:27
when i load the mod for first time it doesnt happen 
but after closing mc and again opening it starts to happen
sodium gives me best fps!!!! 
:(

**Comment by ghost** [comment] 2021-12-23 12:45
I can confirm this occurs in single player as well, and it also occurs on the surface for me. I have the exact same cpu and integrated graphics with no fabric api and on the latest fabric loader.

**Comment by pajicadvance** [comment] 2023-05-10 16:49
Duplicate of #869.

**Closed as not planned by pajicadvance** 2023-05-10 16:49 UTC
Labels: T-bug, E-duplicate, A-drivers
