### ISSUE TITLE
Falling into the void causing game crashes

### ISSUE THREAD

**Issue by campbebj** [jellysquid3/Sodium#631] opened 2021-04-12 20:46 UTC
### Version

Sodium-fabric-mc1.16.4-0.1.1-SNAPSHOT (using a snapshot with the pending pullrequest for immersive portals)

### Reproduction Steps
Fall into the void

> Provide information on how to reproduce this game crash. You can either fill this section in like the example below
> or do something else -- just make sure your instructions are minimal and clear, as other people will need to be able
> to replicate your issue.
>
> Example:
> 1. Place a Redstone Lamp in front of a Redstone Repeater
> 2. Use a Lever to activate the Redstone Repeater
> 3. Nothing happens

### Crash Report File
First this appears in my log
```
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 16
	at me.jellysquid.mods.sodium.client.render.chunk.ChunkRenderColumn.getRender(ChunkRenderColumn.java:33) ~[sodium-fabric-mc1.16.4-0.1.1-SNAPSHOT.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.ChunkRenderManager.getRender(ChunkRenderManager.java:250) ~[sodium-fabric-mc1.16.4-0.1.1-SNAPSHOT.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.ChunkRenderManager.isChunkVisible(ChunkRenderManager.java:399) ~[sodium-fabric-mc1.16.4-0.1.1-SNAPSHOT.jar:?]
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.isEntityVisible(SodiumWorldRenderer.java:372) ~[sodium-fabric-mc1.16.4-0.1.1-SNAPSHOT.jar:?]
	at net.minecraft.class_897.handler$zzk000$preShouldRender(class_897.java:537) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_897.method_3933(class_897.java:58) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_898.method_3950(class_898.java:247) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1188) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:727) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_757.redirect$znj000$redirectRenderingWorld(class_757.java:2052) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:546) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1048) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:681) [intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-minecraft-1.16.5-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.3.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```
then i get this crash report
```

Time: 12/3/20, 1:36 PM
Description: Container click

java.lang.IndexOutOfBoundsException: Index 45 out of bounds for length 39
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:459)
	at net.minecraft.class_1703.method_30010(class_1703.java:353)
	at net.minecraft.class_1703.method_7593(class_1703.java:177)
	at net.minecraft.class_636.method_2906(class_636.java:398)
	at net.minecraft.class_465.redirect$zho000$clickSlotTryOffhandStack(class_465.java:1279)
	at net.minecraft.class_465.method_25402(class_465.java:358)
	at net.minecraft.class_489.method_25402(class_489.java:100)
	at net.minecraft.class_312.method_1611(class_312.java:92)
	at net.minecraft.class_437.method_25412(class_437.java:435)
	at net.minecraft.class_312.method_1601(class_312.java:92)
	at net.minecraft.class_312.method_22686(class_312.java:162)
	at net.minecraft.class_1255.execute(class_1255.java:94)
	at net.minecraft.class_312.method_22684(class_312.java:162)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:102)
	at net.minecraft.class_1041.method_15998(class_1041.java:308)
	at net.minecraft.class_310.method_1523(class_310.java:1068)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:459)
	at net.minecraft.class_1703.method_30010(class_1703.java:353)

-- Click info --
Details:
	Menu Type: minecraft:furnace
	Menu Class: net.minecraft.class_3858
	Slot Count: 39
	Slot: 45
	Button: 12
	Type: SWAP
Stacktrace:
	at net.minecraft.class_1703.method_7593(class_1703.java:177)
	at net.minecraft.class_636.method_2906(class_636.java:398)
	at net.minecraft.class_465.redirect$zho000$clickSlotTryOffhandStack(class_465.java:1279)
	at net.minecraft.class_465.method_25402(class_465.java:358)
	at net.minecraft.class_489.method_25402(class_489.java:100)
	at net.minecraft.class_312.method_1611(class_312.java:92)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_3873
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:435)
	at net.minecraft.class_312.method_1601(class_312.java:92)
	at net.minecraft.class_312.method_22686(class_312.java:162)
	at net.minecraft.class_1255.execute(class_1255.java:94)
	at net.minecraft.class_312.method_22684(class_312.java:162)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:102)

-- Affected level --
Details:
	All players: 1 total; [class_746['campbebj'/29781, l='ClientLevel', x=3198.79, y=36.00, z=15954.74]]
	Chunk stats: SodiumChunkCache: 1692
	Level dimension: minecraft:overworld
	Level spawn location: World: (3868,64,15889), Chunk: (at 12,4,1 in 241,993; contains blocks 3856,0,15888 to 3871,255,15903), Region: (7,31; contains chunks 224,992 to 255,1023, blocks 3584,0,15872 to 4095,255,16383)
	Level time: 27375402 game time, 13295605 day time
	Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.16-R0.4-SNAPSHOT:9c078b7:1539) <- fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2239)
	at net.minecraft.class_310.method_1514(class_310.java:699)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```
### Additional Information
This happens upon re-loggin as well if i dont move myself out of the void quick enough / instantly (i have had to use a command as the OP to move a player out of the void between logging in and rendering starting.

**Comment by DragonEggBedrockBreaking** [comment] 2021-04-12 22:46
This issue has already been fixed in sodium. Please ask the maintainer of the immersive portals fork to update the fork, and please close this issue.

**Comment by campbebj** [comment] 2021-04-12 23:11
There is an outstanding pullrequest https://github.com/CaffeineMC/sodium-fabric/pull/429 to pull that into sodium. which would also fix my issue. Is that something someone can look into?

**Comment by silversquirl** [comment] 2021-04-13 07:38
Duplicate of #587

**Closed as completed by silversquirl** 2021-04-13 07:38 UTC
Labels: E-duplicate, T-crash
