### ISSUE TITLE
Game gets stuck on Mojang loading screen and is marked as "not responding"

### ISSUE THREAD

**Issue by Miguelrogenmoser4562** [jellysquid3/Sodium#1193] opened 2022-02-24 22:05 UTC
### Version information

sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14.jar

### Reproduction Steps

I loaded the game and I gets stuck.

### Crash Report file

https://pastebin.com/YM3nvwSw

### Additional information

The only mod that I am using is sodium. I am using fabric-loader-0.13.3-1.18.1. The game works fine with the fabric loader, but it gets stuck when I add sodium

**Comment by jellysquid3** [comment] 2022-02-24 22:33
Duplicate of #899.

**Closed as completed by jellysquid3** 2022-02-24 22:33 UTC
Labels: T-crash, S-needs-triage

**Comment by 7seasking** [comment] 2023-06-14 14:17
> Duplicate of #899.

But when I try installing the driver version 15.33.53.5161 it does not update my driver to 15.33.53.5161 my driver update stays at 10. Smth numbers I can't remember. Is there any way to update to 15.33.53.5161?
