### ISSUE TITLE
Incorrect water cull facing

### ISSUE THREAD

**Issue by Bruh-Chan** [jellysquid3/Sodium#1054] opened 2021-12-14 16:37 UTC
### Version information

sodium-fabric-mc1.18.1-rc1-0.4.0-alpha5+build.824

### Expected Behavior

Water to render through a stained glass block

![2021-12-13_22 58 25](https://user-images.githubusercontent.com/90088049/146039742-174ea6bd-b658-4889-af02-0bc947dc5453.png)

### Actual Behavior

Water doesn't render through a stained glass block

![2021-12-13_22 58 58](https://user-images.githubusercontent.com/90088049/146039887-47593d35-3d23-4c30-9456-44c784cbe09c.png)

### Reproduction Steps

1. Place water next to a stained glass block
2. Notice one of the sides of water block is invisible through a stained glass block

### Java version

Java 17.0.1

### CPU

Intel Core i5-4460

### GPU

NVIDIA GeForce GTX 1050

**Comment by jellysquid3** [comment] 2021-12-14 16:39
This is a duplicate of #38. While yes, only some of the faces are invisible, this is due to how Sodium groups geometry by their facing, and the happen-stance ordering of this particular scene.

**Closed as completed by jellysquid3** 2021-12-14 16:39 UTC
Labels: T-bug, E-duplicate
