### ISSUE TITLE
Add "Refresh rate" in Video Settings Fullscreen option

### ISSUE THREAD

**Issue by ChristopherJ123** [jellysquid3/Sodium#1435] opened 2022-08-26 10:35 UTC
**Is your feature request related to a problem? Please describe.**
Earlier I had a problem with the refresh rate on Minecraft while on full screen with sodium installed. My laptop has 144hz refresh rate. While Minecraft is on full screen, the max refresh rate is capped to 60hz for unknown reason, while on windowed mode it's back to normal at 144hz. I was confused on how to fix this.

Then I tried to launch Minecraft without sodium and figured out the issue. The Refresh rate was capped at 60 from the Fullscreen video settings (as seen in the picture). Then I changed the Fullscreen video setting to "Current" and relaunched Minecraft with Sodium and everything worked fine with 144hz.

**Describe the solution you'd like**
A way to choose the refresh rate from the video settings menu (30hz, 60hz, 144hz, etc).

**Describe alternatives you've considered**

**Additional context**
![Picture1](https://user-images.githubusercontent.com/86960084/186885685-015f70ea-b2e8-4814-ad6c-8da0f04ffdbd.png)

**Comment by ghost** [comment] 2022-09-14 14:36
You can use Shift+P to access the default Minecraft settings menu

**Comment by silversquirl** [comment] 2022-09-15 10:35
Duplicate of #1380

**Closed as completed by silversquirl** 2022-09-15 10:35 UTC
Labels: E-duplicate, T-enhancement
