### ISSUE TITLE
Fog Occlusion causes chunks the player is not in to not render under lava

### ISSUE THREAD

**Issue by saltyseadoggo** [jellysquid3/Sodium#322] opened 2020-09-30 05:31 UTC
### Expected behaviour
When the player is **swimming in lava** and **using the Fire Resistance effect to see**, and they **have Fog Occlusion turned on** in the graphics settings, nearby chunks that the player is not in should render, as they do in vanilla.

### Actual behaviour
When the player is swimming in lava and using the Fire Resistance effect to see, and they have Fog Occlusion turned on in the graphics settings, all chunks that the player is not in do not render at all. This causes areas potentially very close to the player to be invisible until the player sets foot in them, and makes navigating under lava difficult.

### Reproduction steps
- Ensure that **Fog Occlusion** is turned on in the graphics settings.
- Create a new world of any type in Creative mode.
- Press F3 and G to see chunk boundaries
- Construct this between at least two chunks:
![2020-09-29_22 18 14](https://user-images.githubusercontent.com/69029346/94646139-753fb900-02a2-11eb-8df7-275c90766b58.png)
- Use the Creative menu to obtain a Potion of Fire Resistance and drink it, or obtain the effect via /effect.
- Enter the lava pool. Blocks near the player are visible due to the Fire Resistance effect, but ones beyond the chunk boundaries shown by F3-G are not.

### Attachments
![2020-09-29_22 17 51](https://user-images.githubusercontent.com/69029346/94646327-debfc780-02a2-11eb-96cb-7c09c1eef126.png)
![2020-09-29_22 18 06](https://user-images.githubusercontent.com/69029346/94646329-df585e00-02a2-11eb-9bd3-058cb4c2da09.png)
![2020-09-29_22 18 07](https://user-images.githubusercontent.com/69029346/94646330-dff0f480-02a2-11eb-8f0f-cd8ee9ffca3c.png)

### System Information
- Java Version: 11.0.8 64bit
- CPU: 4x Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz
- GPU: Mesa DRI Intel(R) HD Graphics 3000 (SNB GT2)

**Comment by fsharpseven** [comment] 2020-10-20 21:10
Pretty sure this is a duplicate of #35, just with lava.

**Comment by jellysquid3** [comment] 2020-11-06 23:37
Closing as duplicate of #35.

**Closed as completed by jellysquid3** 2020-11-06 23:37 UTC
Labels: T-bug, E-duplicate
