### ISSUE TITLE
Very specific but repeatable crash with a sticky piston

### ISSUE THREAD

**Issue by ChristianASkinner** [jellysquid3/Sodium#670] opened 2021-06-01 23:45 UTC
Never done something like this before, so I hope I didn't leave anything important out.

### Version
0.1.0
sodium-fabric-mc1.16.3-0.1.0

running on fabric loader 0.11.3

### Reproduction Steps
Not sure how you would reproduce this.

I powered a sticky piston in a specific part of my base. Happens every time in that specific spot, both with a torch and a lever, and I made sure it wasn't powering anything else. Powering the piston in other parts of the base did not do this. Removing sodium stopped it from crashing.

Here's a video of me recreating the crash.
https://youtu.be/BvjiViaYkJM

It did not generate a crash report file.

**Comment by amnotbananaama** [comment] 2021-06-01 23:57
Thank you for the report. Can you provide a list of mods + versions you are using? Additionally, can you provide the `latest.log` file or whichever log file when the crash occurred.

Please also check for the presence of an `hs_err_pid####.log` in your `.minecraft` folder, and upload one if it was created by the crash. This would indicate that the crash occurred at a low level, and contains helpful diagnostic information.

If none of the above is helpful in diagnosing this issue, we may have you share a small portion of the world to help reproduce the issue

**Comment by ChristianASkinner** [comment] 2021-06-02 01:11
Here's a modlist, I just copied the jar file names.

<!DOCTYPE html>
<head>
<head>
</head>
<body>
    <details>
        <summary>Modlist</summary>
artifacts-3.2.1+fabric<br />
banner_capes-0.2.1<br />
bewitchment-1.16.5-12<br />
bunch-o-trinkets-1.0.1<br />
cloth-config-4.11.26-fabric<br />
extraalchemy-fabric-1.16.5-1.4.4<br />
fabric-api-0.34.2+1.16<br />
fabric-carpet-1.16.5-1.4.36+v210512<br />
Hwyla-fabric-1.16.2-1.9.23-79<br />
icarus-1.2<br />
Impersonate-2.2.1<br />
Patchouli-1.16.4-50-FABRIC<br />
Pehkui-2.1.0+21w18a<br />
RoughlyEnoughItems-5.11.218<br />
sodium-fabric-mc1.16.3-0.1.0<br />
somnus-fabric-0.0.11-1.16.5<br />
trinkets-2.6.7
    </details>     
</body>
</html>

The only one of these I could see changing pistons in any way is cloth, but I never actually activated any of its functions on this world and removing it did not stop the crash.

There were a few older hs_err log files from something unrelated over a month ago, but nothing related to this issue. 

[Here is a log file where I reproduce the issue and it crashes](https://github.com/CaffeineMC/sodium-fabric/files/6581285/latest.log)

**Comment by LucilleTea** [comment] 2021-06-02 01:26
Thanks for the log, looks the same as #621 - so should be fixed by #581 or similar. I believe an alternative fix/optimization is being worked on.
Not sure I want to close this as duplicate, since it's a bit neater and more informative than the other issue...

**Comment by jellysquid3** [comment] 2021-06-30 19:28
Does this still occur with [Sodium 0.2](https://github.com/CaffeineMC/sodium-fabric/releases/tag/mc1.16.5-0.2.0)?

**Comment by ChristianASkinner** [comment] 2021-06-30 20:28
Just tested it and I didn't get a crash! Also, I found out a few days ago I was also getting a crash when placing a scaffolding block on another scaffolding block. I didn't do much testing with that, but it seemed pretty consistent, and that's fixed now too.

**Comment by jellysquid3** [comment] 2021-06-30 20:38
Happy to hear it. I will close this issue as resolved then.

**Closed as completed by jellysquid3** 2021-06-30 20:38 UTC
Labels: T-crash
