### ISSUE TITLE
Increase render distance?

### ISSUE THREAD

**Issue by bluesillybeard** [jellysquid3/Sodium#758] opened 2021-07-13 20:41 UTC
Minecraft version: 1.16.5
Sodium version: mc1.16.3-0.1.0

**Is your feature request related to a problem? Please describe.**
I basically just like to be able to see insane distances.

**Describe the solution you'd like**
I would like to be able to set my render distance greater than 32, at least to 64. 

(>300 chunks would be great, as that's about as far as a person can se irl - obviously, that's not a reasonable goal)

**Describe alternatives you've considered**
Maybe it doesn't have to be accessible in the video settings, setting it in the config file works too.

**Additional context**
When I manually set the render distance to 64 by directly editing the settings file, the chunks still unload as if it were still 32 (I can only move 25 chunks away before they unload), even though Sodium recognizes that I set it to 64 (the settings menu says 64 chunks)

I would consider this a low priority. It's not exactly a huge issue, and there are much more important issues to focus on.

I might dig around in the code myself to find the cause of the issue, but I'm not exactly an expert in the internal workings of Sodium or Minecraft so I don't expect to get very far.

**Comment by Kroppeb** [comment] 2021-07-13 20:50
This is out of scope for Sodium, however there is this mod called [Bobby](https://modrinth.com/mod/bobby) that does what you want.

**Comment by silversquirl** [comment] 2021-07-13 22:21
Duplicate of #178

**Closed as completed by silversquirl** 2021-07-13 22:21 UTC
Labels: E-duplicate, T-enhancement, E-will-not-fix
