### ISSUE TITLE
Building does not work.

### ISSUE THREAD

**Issue by PQCraft** [jellysquid3/Sodium#313] opened 2020-09-27 00:38 UTC
Building does not produce any usable jar files.

**Comment by amnotbananaama** [comment] 2020-09-27 00:48
Cannot reproduce. It would be best if you joined [Jelly’s discord](https://jellysquid.me/discord), so we can offer you technical support rather than spamming the tracker. 

Going to close this as it’s a configuration issue.

**Closed as completed by amnotbananaama** 2020-09-27 00:48 UTC
Labels: S-cannot-repro
