### ISSUE TITLE
Flashing Blocks (prob chunk refreshing) whenever block update occurs

### ISSUE THREAD

**Issue by PhantomFran05** [jellysquid3/Sodium#1825] opened 2023-06-18 11:30 UTC
### Version information

rubidium-0.5.6

### Expected Behavior

Chunks refresh normally without visual glitches whenever block update occurs (eg. block breaking)

### Actual Behavior

Chunks refreshing constantly whenever there is a block update in a way that makes surrounding blocks (in certain surrounding chunks) to blink in and out of existence. 

### Reproduction Steps

Don't know how to reproduce this bug...
Here are my sodium/rubidium video settings: 
![image](https://github.com/CaffeineMC/sodium-fabric/assets/111361184/70af7d9e-3e2a-4236-8efd-e9055cffa837)
![image](https://github.com/CaffeineMC/sodium-fabric/assets/111361184/4beb183a-76d5-4c21-a3ea-beffaea3ec7b)
![image](https://github.com/CaffeineMC/sodium-fabric/assets/111361184/5de990f9-1d94-43d9-b168-4a18c45bd510)
![image](https://github.com/CaffeineMC/sodium-fabric/assets/111361184/78b8f5c9-b101-4fa3-b1f5-a4e26672a81c)

### Java version

Java 8

### CPU

Intel

### GPU

Intel UHD Graphics

### Additional information

Although i said that the issue is with rubidium, in fact, it is with normal sodium as well, at least for me. Im using rubidium with modpack, but the issues are the same with sodium in vanilla.
 I dont know if it has something to do with settings but it is an issue that ONLY happens with sodium related mods.
 Video of me playing ATFC curseforge modpack: https://medal.tv/games/minecraft/clips/1ebuhDMCYmnrVK/BvdMVsFSLSdG?invite=cr-MSxYeEwsMTgwNTYwNTE2LA
 
 I have tried tweaking around with the sodium/rubidium settings and i dont rlly know what is causing this to happen. Whether its an incompatibility with another client side modpack.

**Comment by Lolothepro** [comment] 2023-06-18 11:32
Duplicate of #869

**Closed as not planned** 2023-06-18 11:40 UTC
Labels: T-bug, S-needs-triage
