### ISSUE TITLE
Frequent Lag spikes and micro stutters

### ISSUE THREAD

**Issue by sunias** [jellysquid3/Sodium#380] opened 2020-11-05 13:56 UTC
I get lag spikes or micro stutters every ~5-10 seconds

**Comment by sjx233** [comment] 2020-11-05 14:07
Sounds like GC. Not sure though. You may want to look at [zgc-and-friends.md](https://gist.github.com/jellysquid3/8a7b21e57f47f5711eb5697e282e502e).

**Comment by Teh404Gal** [comment] 2020-11-05 14:11
also happens to me
i was using zgc and then came back to the default in minecraft and still stutters
started when i use the 1.16.4 sodium snapshot

**Comment by amnotbananaama** [comment] 2020-11-05 14:22
Please properly fill out the issue template. It exists so that we can more easily help you, and don’t have to make guesses about your configuration. We have no idea what other mods you are running, what version of Minecraft, or even if you have Sodium installed.

This is almost certainly a support issue as opposed to a bug, but I will leave this issue open for now to see what the preliminary information you provide is. The issue tracker is *not* a support forum however, this is only because a lot of code changes have been made to Sodium recently. Please copy and paste the information from [the issue template](https://github.com/jellysquid3/sodium-fabric/issues/new?assignees=&labels=bug&template=bug_report.md&title=) and fill it in properly.

**Comment by sunias** [comment] 2020-11-05 16:02
![image](https://user-images.githubusercontent.com/74004670/98264810-97ef7c80-1f88-11eb-989d-dce76b4497db.png) 
i am using 1.16.3

**Comment by matthewperiut** [comment] 2020-11-09 02:23
I can tell you right now; the issue is that there isn't enough memory allocated to Minecraft. The lag spikes are due to the garbage collector suddenly cleaning up excess ram. Go into your Minecraft launcher, under installations click on the fabric loader, and press "more options." In JVM arguments change -Xmx2G to -Xmx4G
Of course you need more ram in your computer than how much you set, but this will fix the "Frequent Lag spikes and micro stutters"

**Comment by KastroMugnaio** [comment] 2020-11-14 11:58
> I can tell you right now; the issue is that there isn't enough memory allocated to Minecraft. The lag spikes are due to the garbage collector suddenly cleaning up excess ram. Go into your Minecraft launcher, under installations click on the fabric loader, and press "more options." In JVM arguments change -Xmx2G to -Xmx4G
> Of course you need more ram in your computer than how much you set, but this will fix the "Frequent Lag spikes and micro stutters"

the game keeps making microstutters

**Comment by Kichura** [comment] 2020-11-14 17:15
Have you tried using sodium ONLY before using your own modpack to see if this issue would go away?

**Comment by Genau6502** [comment] 2020-11-29 21:13
I think this should be closed, doesn't seem like an issue with sodium

**Comment by Teh404Gal** [comment] 2020-12-04 09:57
i think this is linked with a problem i have when some times when launching minecraft with sodium, puts a hard 30-39 mb cap on the vram 
but this rarely happens

**Comment by amnotbananaama** [comment] 2020-12-04 17:22
Closing as a question, since this is a [support issue](https://jellysquid.me/discord).

**Closed as completed by amnotbananaama** 2020-12-04 17:22 UTC
Labels: T-question
