### ISSUE TITLE
No opengl 4.3 even though the card supports it

### ISSUE THREAD

**Issue by NanKillBro** [jellysquid3/Sodium#894] opened 2021-09-11 05:54 UTC
I don't have opengl 4.3 even though i have a GPU that supports opengl 4.6. It only show Oneshot 3.0 and Oneshot 2.0
![image](https://user-images.githubusercontent.com/72297072/132937573-820ac042-2cec-4d21-9e6e-675370e829da.png)

Sodium version: sodium-fabric-mc1.16.3-0.1.0.jar
GPU: AMD Radeon HD 8600M Series
CPU: i5 4200u
Java 16

i'm don't good at English lol

Link info my GPU: https://www.techpowerup.com/gpu-specs/radeon-hd-8670m.c2391

**Comment by LucilleTea** [comment] 2021-09-11 05:58
This is intentional in sodium 0.1.0, [update to sodium 0.2.0.](https://modrinth.com/mod/sodium)
Duplicate of #24

**Closed as completed by LucilleTea** 2021-09-11 05:58 UTC
Labels: E-duplicate
