### ISSUE TITLE
Sodium crash when reding a wierdly generated sodium-options.json

### ISSUE THREAD

**Issue by Fox2Code** [jellysquid3/Sodium#243] opened 2020-08-08 16:41 UTC
### Reproduction Steps
Having this configuration file
[SodiumOptions.zip](https://github.com/jellysquid3/sodium-fabric/files/5045638/SodiumOptions.zip)
```Json
{
  "quality": {
    "cloud_quality": "DEFAULT",
    "weather_quality": "DEFAULT",
    "enable_vignette": false,
    "enable_clouds": false,
    "smooth_lighting": "LOW"
  },
  "advanced": {
    "chunk_renderer_backend": "GL43",
    "animate_only_visible_textures": true,
    "use_advanced_entity_culling": true,
    "use_particle_culling": true,
    "use_fog_occlusion": true,
    "use_compact_vertex_format": true,
    "use_chunk_face_culling": true,
    "use_memory_intrinsics": true,
    "disable_driver_blacklist": true
  },
  "file": {
    "separator_char": "/",
    "separator": "/",
    "path_separator_char": ":",
    "path_separator": ":"
  },
  "gson": {
    "d_e_f_a_u_l_t__j_s_o_n__n_o_n__e_x_e_c_u_t_a_b_l_e": false,
    "d_e_f_a_u_l_t__l_e_n_i_e_n_t": false,
    "d_e_f_a_u_l_t__p_r_e_t_t_y__p_r_i_n_t": false,
    "d_e_f_a_u_l_t__e_s_c_a_p_e__h_t_m_l": true,
    "d_e_f_a_u_l_t__s_e_r_i_a_l_i_z_e__n_u_l_l_s": false,
    "d_e_f_a_u_l_t__c_o_m_p_l_e_x__m_a_p__k_e_y_s": false,
    "d_e_f_a_u_l_t__s_p_e_c_i_a_l_i_z_e__f_l_o_a_t__v_a_l_u_e_s": false
  }
}
```

### Crash Report File
[CrashReport](https://paste.ee/p/oKC6r)

### Additional Information
It seems sodium generated a file with "file" and "gson" and Gson try to set final properties after  

I think The best thing to do is to remove theses keys if detected before reading the json  

I have currently no idea of why and how sodium generated this file and it may be a bug on the Gson library

**Comment by amnotbananaama** [comment] 2020-08-08 16:56
(Probably) a duplicate of https://github.com/jellysquid3/sodium-fabric/issues/219

**Comment by jellysquid3** [comment] 2020-08-08 17:41
This is caused by Fabric Zero hacking at everything in the classpath, it seems. I've opened an issue with them [here](https://github.com/Fox2Code/FabricZero/issues/4). There's nothing we can do to protect ourselves from it.

**Closed as completed by jellysquid3** 2020-08-08 17:41 UTC
Labels: E-external, A-mods, E-will-not-fix, T-crash
