### ISSUE TITLE
Going underwater and then leaving turns parts of my screen black and random blocks start rendering as if they were the water itself (Only on Multidraw)

### ISSUE THREAD

**Issue by InfiniteX1** [jellysquid3/Sodium#275] opened 2020-08-21 21:34 UTC
### Expected Behavior
I should be able to see normally while I'm above the water

### Actual Behavior
Random blocks start rendering as if the were the water itself and a good part of the screen goes black.
The bug goes away when i'm fully underwater.

### Reproduction Steps
1.  Set the Chunk Renderer to Multidraw
2.  Jump into any body of water that's at least three blocks deep
3.  Get out of the water while facing a block
4.  Jump back in

### Attachments
![2020-08-22_00 02 26](https://user-images.githubusercontent.com/68203408/90935285-942d6e80-e40b-11ea-8c2c-df5b642d247c.png)
![2020-08-22_00 02 37](https://user-images.githubusercontent.com/68203408/90935289-95f73200-e40b-11ea-8bfa-f02fe1b2e5df.png)
![2020-08-22_00 03 05](https://user-images.githubusercontent.com/68203408/90935290-95f73200-e40b-11ea-8cac-c441c70bfdda.png)

### System Information
- Java Version: 8 Update 261 (build 1.8.0_261-b12)
- CPU: Intel I3 3240
- GPU: Intel HD 2500

**Comment by nodeiwnl** [comment] 2020-08-22 01:52
Multidraw should only be for dedicated GPU's I'm pretty sure so integrated graphics cards might have rendering issues, just revert back to Oneshot.

**Comment by InfiniteX1** [comment] 2020-08-22 14:06
Ok. Thank you. Should i close this issue?

**Comment by amnotbananaama** [comment] 2020-08-25 06:34
Duplicate of #179

**Closed as completed by amnotbananaama** 2020-08-25 06:34 UTC
Labels: T-bug, E-duplicate
