### ISSUE TITLE
Crash when rendering trader tower combined with Bewitchment

### ISSUE THREAD

**Issue by Scotterrr** [jellysquid3/Sodium#638] opened 2021-04-19 11:00 UTC
Newest version of fabric/minecraft/sodium/bewitchment

[12:54:11] [Chunk Render Task Executor #0/INFO]: [STDERR]: java.lang.ArrayIndexOutOfBoundsException: -267
[12:54:11] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.world.WorldSlice.method_8320(WorldSlice.java:232)
[12:54:11] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at net.minecraft.class_4970$class_4971.handler$cni000$getCollisionShape(class_4970.java:4067)
[12:54:11] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at net.minecraft.class_4970$class_4971.method_26194(class_4970.java)
[12:54:11] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at net.minecraft.class_4970$class_4971.method_26220(class_4970.java:793)
[12:54:11] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at net.minecraft.class_4970$class_4971.method_26234(class_4970.java:985)
[12:54:11] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at net.minecraft.class_4970.method_9575(class_4970.java:304)
[12:54:11] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at net.minecraft.class_4970$class_4971.method_26210(class_4970.java:723)
[12:54:11] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.model.light.data.LightDataAccess.compute(LightDataAccess.java:67)
[12:54:11] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.model.light.cache.ArrayLightDataCache.get(ArrayLightDataCache.java:56)
[12:54:11] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.model.light.data.LightDataAccess.get(LightDataAccess.java:39)
[12:54:11] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.model.light.smooth.AoFaceData.initLightData(AoFaceData.java:62)
[12:54:11] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.model.light.smooth.SmoothLightPipeline.getCachedFaceData(SmoothLightPipeline.java:182)
[12:54:11] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.model.light.smooth.SmoothLightPipeline.applyAlignedFullFace(SmoothLightPipeline.java:171)
[12:54:11] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.model.light.smooth.SmoothLightPipeline.calculate(SmoothLightPipeline.java:79)
[12:54:11] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.pipeline.BlockRenderer.renderQuadList(BlockRenderer.java:102)
[12:54:11] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.pipeline.BlockRenderer.renderModel(BlockRenderer.java:73)
[12:54:11] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.pipeline.context.ChunkRenderContext.renderBlock(ChunkRenderContext.java:43)
[12:54:11] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.performBuild(ChunkRenderRebuildTask.java:93)
[12:54:11] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:347)
[12:54:11] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at java.lang.Thread.run(Unknown Source)
[12:54:11] [main/INFO]: Loaded 1736 advancements
[12:54:11] [Chunk Render Task Executor #5/INFO]: [STDERR]: java.lang.ArrayIndexOutOfBoundsException: -256
[12:54:11] [Chunk Render Task Executor #5/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.world.WorldSlice.method_8320(WorldSlice.java:232)
[12:54:11] [Chunk Render Task Executor #5/INFO]: [STDERR]: 	at net.minecraft.class_4970$class_4971.handler$cni000$getCollisionShape(class_4970.java:4067)
[12:54:11] [Chunk Render Task Executor #5/INFO]: [STDERR]: 	at net.minecraft.class_4970$class_4971.method_26194(class_4970.java)
[12:54:11] [Chunk Render Task Executor #5/INFO]: [STDERR]: 	at net.minecraft.class_4970$class_4971.method_26220(class_4970.java:793)
[12:54:11] [Chunk Render Task Executor #5/INFO]: [STDERR]: 	at net.minecraft.class_4970$class_4971.method_26234(class_4970.java:985)
[12:54:11] [Chunk Render Task Executor #5/INFO]: [STDERR]: 	at net.minecraft.class_4970.method_9575(class_4970.java:304)
[12:54:11] [Chunk Render Task Executor #5/INFO]: [STDERR]: 	at net.minecraft.class_4970$class_4971.method_26210(class_4970.java:723)
[12:54:11] [Chunk Render Task Executor #5/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.model.light.data.LightDataAccess.compute(LightDataAccess.java:67)
[12:54:11] [Chunk Render Task Executor #5/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.model.light.cache.ArrayLightDataCache.get(ArrayLightDataCache.java:56)
[12:54:11] [Chunk Render Task Executor #5/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.model.light.data.LightDataAccess.get(LightDataAccess.java:39)
[12:54:11] [Chunk Render Task Executor #5/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.model.light.smooth.AoFaceData.initLightData(AoFaceData.java:62)
[12:54:11] [Chunk Render Task Executor #5/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.model.light.smooth.SmoothLightPipeline.getCachedFaceData(SmoothLightPipeline.java:182)
[12:54:11] [Chunk Render Task Executor #5/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.model.light.smooth.SmoothLightPipeline.applyAlignedPartialFace(SmoothLightPipeline.java:151)
[12:54:11] [Chunk Render Task Executor #5/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.model.light.smooth.SmoothLightPipeline.applyComplex(SmoothLightPipeline.java:114)
[12:54:11] [Chunk Render Task Executor #5/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.model.light.smooth.SmoothLightPipeline.calculate(SmoothLightPipeline.java:81)
[12:54:11] [Chunk Render Task Executor #5/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.pipeline.BlockRenderer.renderQuadList(BlockRenderer.java:102)
[12:54:11] [Chunk Render Task Executor #5/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.pipeline.BlockRenderer.renderModel(BlockRenderer.java:73)
[12:54:11] [Chunk Render Task Executor #5/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.pipeline.context.ChunkRenderContext.renderBlock(ChunkRenderContext.java:43)
[12:54:11] [Chunk Render Task Executor #5/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.performBuild(ChunkRenderRebuildTask.java:93)
[12:54:11] [Chunk Render Task Executor #5/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:347)
[12:54:11] [Chunk Render Task Executor #5/INFO]: [STDERR]: 	at java.lang.Thread.run(Unknown Source)
[12:54:11] [Chunk Render Task Executor #3/INFO]: [STDERR]: java.lang.ArrayIndexOutOfBoundsException: -69
[12:54:11] [Chunk Render Task Executor #3/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.world.WorldSlice.method_8320(WorldSlice.java:232)
[12:54:11] [Chunk Render Task Executor #3/INFO]: [STDERR]: 	at net.minecraft.class_4970$class_4971.handler$cni000$getCollisionShape(class_4970.java:4067)
[12:54:11] [Chunk Render Task Executor #3/INFO]: [STDERR]: 	at net.minecraft.class_4970$class_4971.method_26194(class_4970.java)
[12:54:11] [Chunk Render Task Executor #3/INFO]: [STDERR]: 	at net.minecraft.class_4970$class_4971.method_26220(class_4970.java:793)
[12:54:11] [Chunk Render Task Executor #3/INFO]: [STDERR]: 	at net.minecraft.class_4970$class_4971.method_26234(class_4970.java:985)
[12:54:11] [Chunk Render Task Executor #3/INFO]: [STDERR]: 	at net.minecraft.class_4970.method_9575(class_4970.java:304)
[12:54:11] [Chunk Render Task Executor #3/INFO]: [STDERR]: 	at net.minecraft.class_4970$class_4971.method_26210(class_4970.java:723)
[12:54:11] [Chunk Render Task Executor #3/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.model.light.data.LightDataAccess.compute(LightDataAccess.java:67)
[12:54:11] [Chunk Render Task Executor #3/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.model.light.cache.ArrayLightDataCache.get(ArrayLightDataCache.java:56)
[12:54:11] [Chunk Render Task Executor #3/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.model.light.data.LightDataAccess.get(LightDataAccess.java:33)
[12:54:11] [Chunk Render Task Executor #3/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.model.light.smooth.AoFaceData.initLightData(AoFaceData.java:105)
[12:54:11] [Chunk Render Task Executor #3/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.model.light.smooth.SmoothLightPipeline.getCachedFaceData(SmoothLightPipeline.java:182)
[12:54:11] [Chunk Render Task Executor #3/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.model.light.smooth.SmoothLightPipeline.applyAlignedFullFace(SmoothLightPipeline.java:171)
[12:54:11] [Chunk Render Task Executor #3/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.model.light.smooth.SmoothLightPipeline.calculate(SmoothLightPipeline.java:79)
[12:54:11] [Chunk Render Task Executor #3/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.pipeline.BlockRenderer.renderQuadList(BlockRenderer.java:102)
[12:54:11] [Chunk Render Task Executor #3/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.pipeline.BlockRenderer.renderModel(BlockRenderer.java:73)
[12:54:11] [Chunk Render Task Executor #3/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.pipeline.context.ChunkRenderContext.renderBlock(ChunkRenderContext.java:43)
[12:54:11] [Chunk Render Task Executor #3/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.performBuild(ChunkRenderRebuildTask.java:93)
[12:54:11] [Chunk Render Task Executor #3/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:347)
[12:54:11] [Chunk Render Task Executor #3/INFO]: [STDERR]: 	at java.lang.Thread.run(Unknown Source)
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:pillager_factory
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:killer_bunny_castle
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:villager_tower
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:barn_house
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:tavern
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:villager_market
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:abandoned_church
[12:54:12] [Server thread/ERROR]: Unknown structure start: repurposed_structures:stronghold_stonebrick
[12:54:12] [Server thread/ERROR]: Unknown structure start: repurposed_structures:igloo_grassy
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:pillager_factory
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:killer_bunny_castle
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:villager_tower
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:barn_house
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:tavern
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:villager_market
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:abandoned_church
[12:54:12] [Server thread/ERROR]: Unknown structure start: repurposed_structures:stronghold_stonebrick
[12:54:12] [Server thread/ERROR]: Unknown structure start: repurposed_structures:igloo_grassy
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:pillager_factory
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:killer_bunny_castle
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:villager_tower
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:barn_house
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:tavern
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:villager_market
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:abandoned_church
[12:54:12] [Server thread/ERROR]: Unknown structure start: repurposed_structures:stronghold_stonebrick
[12:54:12] [Server thread/ERROR]: Unknown structure start: repurposed_structures:igloo_grassy
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:pillager_factory
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:killer_bunny_castle
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:villager_tower
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:barn_house
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:tavern
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:villager_market
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:abandoned_church
[12:54:12] [Server thread/ERROR]: Unknown structure start: repurposed_structures:stronghold_stonebrick
[12:54:12] [Server thread/ERROR]: Unknown structure start: repurposed_structures:igloo_grassy
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:pillager_factory
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:killer_bunny_castle
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:villager_tower
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:barn_house
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:tavern
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:villager_market
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:abandoned_church
[12:54:12] [Server thread/ERROR]: Unknown structure start: repurposed_structures:stronghold_stonebrick
[12:54:12] [Server thread/ERROR]: Unknown structure start: repurposed_structures:igloo_grassy
[12:54:12] [Server thread/ERROR]: Unknown structure start: repurposed_structures:village_oak
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:killer_bunny_castle
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:villager_tower
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:tavern
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:villager_market
[12:54:12] [Server thread/ERROR]: Unknown structure start: repurposed_structures:mansion_oak
[12:54:12] [Server thread/ERROR]: Unknown structure start: repurposed_structures:stronghold_stonebrick
[12:54:12] [Server thread/ERROR]: Unknown structure start: repurposed_structures:outpost_oak
[12:54:12] [Server thread/ERROR]: Unknown structure start: repurposed_structures:igloo_grassy
[12:54:12] [Server thread/ERROR]: Unknown structure start: repurposed_structures:witch_hut_oak
[12:54:12] [Server thread/WARN]: @Final field field_25883:Lnet/minecraft/class_4970$class_4973; in charm.mixins.json:AreaHelperMixin should be final
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:pillager_factory
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:killer_bunny_castle
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:villager_tower
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:barn_house
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:tavern
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:villager_market
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:abandoned_church
[12:54:12] [Server thread/ERROR]: Unknown structure start: repurposed_structures:stronghold_stonebrick
[12:54:12] [Server thread/ERROR]: Unknown structure start: repurposed_structures:igloo_grassy
[12:54:12] [Worker-Main-11/INFO]: Created new marker #26"Village"@(-505, -1783)
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:pillager_factory
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:killer_bunny_castle
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:villager_tower
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:barn_house
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:tavern
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:villager_market
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:abandoned_church
[12:54:12] [Server thread/ERROR]: Unknown structure start: repurposed_structures:stronghold_stonebrick
[12:54:12] [Server thread/ERROR]: Unknown structure start: repurposed_structures:igloo_grassy
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:pillager_factory
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:killer_bunny_castle
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:villager_tower
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:barn_house
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:tavern
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:villager_market
[12:54:12] [Server thread/ERROR]: Unknown structure start: mostructures:abandoned_church
[12:54:12] [Server thread/ERROR]: Unknown structure start: repurposed_structures:stronghold_stonebrick
[12:54:12] [Server thread/ERROR]: Unknown structure start: repurposed_structures:igloo_grassy
[12:54:14] [Chunk Render Task Executor #10/INFO]: [STDERR]: java.lang.ArrayIndexOutOfBoundsException
[12:54:14] [Chunk Render Task Executor #6/INFO]: [STDERR]: java.lang.ArrayIndexOutOfBoundsException
Exception in thread "Chunk Render Task Executor #0" Exception in thread "Chunk Render Task Executor #5" Exception in thread "Chunk Render Task Executor #3" Exception in thread "Chunk Render Task Executor #10" Exception in thread "Chunk Render Task Executor #6"

**Comment by Kroppeb** [comment] 2021-04-19 11:13
What version of sodium is this?

**Comment by Scotterrr** [comment] 2021-04-19 11:19
Sodium mc1.16.3-0.1.0

**Comment by phiwijo** [comment] 2021-04-22 05:57
#5

**Comment by LucilleTea** [comment] 2021-05-10 08:31
Looks like a duplicate of #621.

**Closed as completed by LucilleTea** 2021-05-10 08:31 UTC
Labels: T-bug, E-duplicate
