### ISSUE TITLE
Custom fluid render bug

### ISSUE THREAD

**Issue by shiftthedev** [jellysquid3/Sodium#310] opened 2020-09-19 07:12 UTC
### Expected Behavior
Custom Fluid to render with custom texture.

### Actual Behavior
Custom Fluid renders with water texture

### Reproduction Steps
Create a custom fluid using the fabric wiki tutorial.
Change texture to a custom texture.

### Attachments
![without_sodium](https://user-images.githubusercontent.com/29488158/93661443-bab4e880-fa4f-11ea-8c05-76d5326d2885.png)
![with_sodium](https://user-images.githubusercontent.com/29488158/93661444-bc7eac00-fa4f-11ea-8e99-a3a97fc78a3f.png)

### System Information
- Java Version: 1.8.0_51 64bit
- CPU: i7-8700K
- GPU: GTX 1080Ti

**Comment by amnotbananaama** [comment] 2020-09-19 07:14
Duplicate of #5

**Closed as completed by amnotbananaama** 2020-09-19 07:14 UTC
Labels: T-bug, E-duplicate
