### ISSUE TITLE
Stuck in Loading Screen

### ISSUE THREAD

**Issue by Soroxik** [jellysquid3/Sodium#1292] opened 2022-04-30 11:32 UTC
### Version information

sodium-fabric-mc1.18.2-0.4.1+build.15

### Reproduction Steps

1.Drag Sodium mod to mods file 
2.Launch game and it gets stuck at loading screen
3.Delete Sodium mod from mods file
4.Launch game and it loads 

### Crash Report file

Don't have crash report cause it doesn't even launch the game 

### Additional information

Every other mod works fine , but when i try to launch game with Sodium it just doesn't load.

**Comment by IcedDog** [comment] 2022-05-23 06:53
I have the same problem, and it seems to be occuring randomly after every restart. Sometimes the game can load normally, and sometimes it cannot, and the outcome stays the same until next restart.

**Comment by x-0D** [comment] 2022-06-07 17:53
Confirmed. I have the same issue. here is my logs
[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/8855434/latest.log)

**Comment by pajicadvance** [comment] 2023-05-09 21:47
Duplicate of #899

**Closed as not planned** 2023-05-10 18:21 UTC
Labels: E-duplicate, A-drivers, T-crash
