### ISSUE TITLE
the compiled version crashes on startup

### ISSUE THREAD

**Issue by Miros77** [jellysquid3/Sodium#229] opened 2020-08-03 00:07 UTC
### Reproduction Steps
crash when starting the game

### Crash Report File
[crash-2020-08-03_03.04.25-client.txt](https://github.com/jellysquid3/sodium-fabric/files/5013204/crash-2020-08-03_03.04.25-client.txt)

### Additional Information
fabric-loader-0.8.9+build.203-1.16.1

JDK
jdk-11

Java
jre1.8.0_251

detailed

==============================================================================================
> [03:12:06] [main/INFO]: Loading for game Minecraft 1.16.1
> [03:12:07] [main/INFO]: [FabricLoader] Loading 4 mods: minecraft@1.16.1, sodium@0.1.0-SNAPSHOT, fabric-resource-loader-v0@0.2.5+059ea86602, fabricloader@0.9.0+build.204
> [03:12:07] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/D:/%d0%bf%d0%b0%d0%bf%d0%ba%d0%b8/%d0%bc%d0%b0%d0%b9%d0%bd/.minecraft/libraries/net/fabricmc/sponge-mixin/0.8+build.18/sponge-mixin-0.8+build.18.jar Service=Knot/Fabric Env=CLIENT
> [03:12:07] [main/INFO]: Loaded configuration file for Sodium: 23 options available, 0 override(s) found
> [03:12:22] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', name='PROD'
> [03:12:22] [main/INFO]: Setting user: RadimirDandi
> [03:12:23] [main/INFO]: Backend library: LWJGL version 3.2.2 build 10
> [03:12:34] [main/INFO]: Narrator library for x64 successfully loaded
> [03:12:35] [main/INFO]: Reloading ResourceManager: Default, Sodium, Fabric Resource Loader (v0), Fabric Loader
> [03:12:51] [Realms Notification Availability checker #1/INFO]: Could not authorize you against Realms server: Invalid session id
> [03:12:57] [main/INFO]: OpenAL initialized.
> [03:12:57] [main/INFO]: Sound engine started
> [03:12:57] [main/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
> [03:12:58] [main/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
> [03:12:58] [main/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
> [03:12:58] [main/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
> [03:12:58] [main/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
> [03:12:58] [main/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
> [03:12:58] [main/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
> [03:13:01] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
> [03:13:01] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
> [03:13:01] [main/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
> [03:13:05] [main/FATAL]: Reported exception thrown!
> net.minecraft.class_148: Rendering screen
> 	at net.minecraft.class_757.method_3192(class_757.java:612) ~[intermediary-fabric-loader-0.9.0+build.204-1.16.1.jar:?]
> 	at net.minecraft.class_310.method_1523(class_310.java:1021) ~[intermediary-fabric-loader-0.9.0+build.204-1.16.1.jar:?]
> 	at net.minecraft.class_310.method_1514(class_310.java:654) [intermediary-fabric-loader-0.9.0+build.204-1.16.1.jar:?]
> 	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-fabric-loader-0.9.0+build.204-1.16.1.jar:?]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
> 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
> 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [fabric-loader-0.9.0+build.204.jar:?]
> 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-loader-0.9.0+build.204.jar:?]
> 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.9.0+build.204.jar:?]
> Caused by: java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
> 	at net.minecraft.class_287.method_1341(class_287.java:1536) ~[intermediary-fabric-loader-0.9.0+build.204-1.16.1.jar:?]
> 	at net.minecraft.class_1921.method_23012(class_1921.java:583) ~[intermediary-fabric-loader-0.9.0+build.204-1.16.1.jar:?]
> 	at net.minecraft.class_4597$class_4598.method_22994(class_4597.java:86) ~[intermediary-fabric-loader-0.9.0+build.204-1.16.1.jar:?]
> 	at net.minecraft.class_4597$class_4598.method_24213(class_4597.java:65) ~[intermediary-fabric-loader-0.9.0+build.204-1.16.1.jar:?]
> 	at java.util.Optional.ifPresent(Unknown Source) ~[?:1.8.0_201]
> 	at net.minecraft.class_4597$class_4598.method_22993(class_4597.java:62) ~[intermediary-fabric-loader-0.9.0+build.204-1.16.1.jar:?]
> 	at net.minecraft.class_327.method_27520(class_327.java:101) ~[intermediary-fabric-loader-0.9.0+build.204-1.16.1.jar:?]
> 	at net.minecraft.class_327.method_1720(class_327.java:55) ~[intermediary-fabric-loader-0.9.0+build.204-1.16.1.jar:?]
> 	at net.minecraft.class_332.method_25300(class_332.java:113) ~[intermediary-fabric-loader-0.9.0+build.204-1.16.1.jar:?]
> 	at net.minecraft.class_442.method_25394(class_442.java:250) ~[intermediary-fabric-loader-0.9.0+build.204-1.16.1.jar:?]
> 	at net.minecraft.class_757.method_3192(class_757.java:603) ~[intermediary-fabric-loader-0.9.0+build.204-1.16.1.jar:?]
> 	... 10 more
> ---- Minecraft Crash Report ----
> // You're mean.
> 
> Time: 03.08.20 3:13
> Description: Rendering screen
> 
> java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
> 	at net.minecraft.class_287.method_1341(class_287.java:1536)
> 	at net.minecraft.class_1921.method_23012(class_1921.java:583)
> 	at net.minecraft.class_4597$class_4598.method_22994(class_4597.java:86)
> 	at net.minecraft.class_4597$class_4598.method_24213(class_4597.java:65)
> 	at java.util.Optional.ifPresent(Unknown Source)
> 	at net.minecraft.class_4597$class_4598.method_22993(class_4597.java:62)
> 	at net.minecraft.class_327.method_27520(class_327.java:101)
> 	at net.minecraft.class_327.method_1720(class_327.java:55)
> 	at net.minecraft.class_332.method_25300(class_332.java:113)
> 	at net.minecraft.class_442.method_25394(class_442.java:250)
> 	at net.minecraft.class_757.method_3192(class_757.java:603)
> 	at net.minecraft.class_310.method_1523(class_310.java:1021)
> 	at net.minecraft.class_310.method_1514(class_310.java:654)
> 	at net.minecraft.client.main.Main.main(Main.java:215)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
> 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
> 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Render thread
> Stacktrace:
> 	at net.minecraft.class_287.method_1341(class_287.java:1536)
> 	at net.minecraft.class_1921.method_23012(class_1921.java:583)
> 	at net.minecraft.class_4597$class_4598.method_22994(class_4597.java:86)
> 	at net.minecraft.class_4597$class_4598.method_24213(class_4597.java:65)
> 	at java.util.Optional.ifPresent(Unknown Source)
> 	at net.minecraft.class_4597$class_4598.method_22993(class_4597.java:62)
> 	at net.minecraft.class_327.method_27520(class_327.java:101)
> 	at net.minecraft.class_327.method_1720(class_327.java:55)
> 	at net.minecraft.class_332.method_25300(class_332.java:113)
> 	at net.minecraft.class_442.method_25394(class_442.java:250)
> 
> -- Screen render details --
> Details:
> 	Screen name: net.minecraft.class_442
> 	Mouse location: Scaled: (0, 0). Absolute: (0.000000, 0.000000)
> 	Screen size: Scaled: (463, 265). Absolute: (925, 530). Scale factor of 2.000000
> Stacktrace:
> 	at net.minecraft.class_757.method_3192(class_757.java:603)
> 	at net.minecraft.class_310.method_1523(class_310.java:1021)
> 	at net.minecraft.class_310.method_1514(class_310.java:654)
> 	at net.minecraft.client.main.Main.main(Main.java:215)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
> 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
> 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.16.1
> 	Minecraft Version ID: 1.16.1
> 	Operating System: Windows 7 (amd64) version 6.1
> 	Java Version: 1.8.0_201, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 288760344 bytes (275 MB) / 559628288 bytes (533 MB) up to 1932787712 bytes (1843 MB)
> 	CPUs: 2
> 	JVM Flags: 5 total; -Xmn128M -Xmx1856M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+UseConcMarkSweepGC
> 	Launched Version: fabric-loader-0.9.0+build.204-1.16.1
> 	Backend library: LWJGL version 3.2.2 build 10
> 	Backend API: GeForce GT 620M/PCIe/SSE2 GL version 4.6.0 NVIDIA 388.13, NVIDIA Corporation
> 	GL Caps: Using framebuffer using OpenGL 3.0
> 	Using VBOs: Yes
> 	Is Modded: Definitely; Client brand changed to 'fabric'
> 	Type: Client (map_client.txt)
> 	Resource Packs: 
> 	Current Language: Русский (Россия)
> 	CPU: 2x Intel(R) Pentium(R) CPU B960 @ 2.20GHz
> #@!@# Game crashed! Crash report saved to: #@!@# D:\папки\майн\.minecraft\crash-reports\crash-2020-08-03_03.13.05-client.txt
> AL lib: (EE) alc_cleanup: 1 device not closed
Here I am!
[VersionManager] Refreshing versions locally...
[VersionManager] Versions has been refreshed (51 ms)
[Launcher] Minecraft closed with exit code: -1
[Launcher] [Crash] Found crash report file: D:\папки\майн\.minecraft\crash-reports\crash-2020-08-03_03.13.05-client.txt
[Crash] Found crash report file: D:\папки\майн\.minecraft\crash-reports\crash-2020-08-03_03.13.05-client.txt
[Launcher] Launcher exited.

**Comment by amnotbananaama** [comment] 2020-08-03 00:35
Duplicate of #16 

Make sure you are using the latest version of the official Minecraft launcher or the MultiMC launcher

**Comment by Miros77** [comment] 2020-08-03 01:07
is this for snapshots?

**Comment by amnotbananaama** [comment] 2020-08-03 01:13
> is this for snapshots?

No, Sodium only targets the latest stable release of Minecraft (currently 1.16.1)

**Comment by Miros77** [comment] 2020-08-03 13:09
[libs.zip](https://github.com/jellysquid3/sodium-fabric/files/5016103/libs.zip)

**Comment by Miros77** [comment] 2020-08-03 13:16
maybe I compiled it incorrectly???

**Comment by Miros77** [comment] 2020-08-05 12:21
Java update?

**Comment by jellysquid3** [comment] 2020-08-06 01:36
This issue is caused by compiling the mod using a newer version of the Java JDK than the game's runtime.

**Closed as completed by jellysquid3** 2020-08-06 01:36 UTC
Labels: E-duplicate, T-crash

**Comment by Miros77** [comment] 2020-08-06 01:43
> This issue is caused by compiling the mod using a newer version of the Java JDK than the game's runtime.

**Comment by Miros77** [comment] 2020-08-06 01:43
> This issue is caused by compiling the mod using a newer version of the Java JDK than the game's runtime.

What version of JDK is needed?

**Comment by amnotbananaama** [comment] 2020-08-06 01:47
> What version of JDK is needed?

See #16. You need to build with JDK 8 if you want to use the launcher's bundled Java 8 Runtime.

**Comment by Miros77** [comment] 2020-08-06 02:10
Thanks
