### ISSUE TITLE
Visual glitch with stained glass

### ISSUE THREAD

**Issue by eitifrie** [jellysquid3/Sodium#2224] opened 2023-12-27 19:26 UTC
### Bug Description

It's basically a visual glitch when looking west in to stained glass arranged in a certain way. Look at the screenshot and reproduction steps, it's hard to explain otherwise.
[Screenshot from a survival world](https://github.com/CaffeineMC/sodium-fabric/assets/155013255/051ea0b1-3235-4ba1-9a61-5579fe06d1b4)

### Reproduction Steps

1. Create a large stained glass wall (any colour it seems) spanning from south to north, not too close to the nearest chunk border on the west side.
2. Create a large stained glass floor (also any colour I think) at the bottom on west side of the stained glass wall.
3. Look west in to the stained glass wall with the stained glass floor facing away from you and you'll see that the chunk borders are seen through where you can and can not see the stained glass floor through the stained glass wall.

[Screenshot from recreation in creative world](https://github.com/CaffeineMC/sodium-fabric/assets/155013255/4a0f30f1-00e6-454a-880c-281a5ff89dc3)

### Log File

https://mclo.gs/f1jbboO

### Crash Report

[crash-2023-12-27_20.22.28-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/13780744/crash-2023-12-27_21.22.28-client.txt)

**Comment by pajicadvance** [comment] 2023-12-27 19:26
Duplicate of #38

**Closed as not planned by pajicadvance** 2023-12-27 19:26 UTC
Labels: E-duplicate
