### ISSUE TITLE
Sides of light-emitting blocks that touch tinted glass appear dim

### ISSUE THREAD

**Issue by kevcomedia** [jellysquid3/Sodium#781] opened 2021-07-19 09:30 UTC
### Version information

sodium-fabric-mc1.17.1-0.3.0+build.5

### Expected Behavior

When tinted glass is placed next to a light-emitting block, the side touching the tinted glass should still appear bright.

### Actual Behavior

The side of the block appears completely dim.

### Reproduction Steps

1. Place a light-emitting block (sea lantern, redstone lamp, etc.).
2. Place tinted glass on any side of the block.
3. The side touching the tinted glass appears dim.

### Java version

Java 16.0.1 64bit (integrated)

### CPU

Intel Core i5-3210M

### GPU

Intel HD Graphics 4000 (IVB GT2)

### Additional information

Expected behavior:

![2021-07-19_16 58 27](https://user-images.githubusercontent.com/17902987/126134215-019616a5-4629-4cb0-b131-64662af11787.png)

Actual behavior:

![2021-07-19_17 01 34](https://user-images.githubusercontent.com/17902987/126134591-258b4cd1-737d-4dc2-882f-6422ce0484f2.png)

You should be able to reproduce this bug with just sodium in the mods folder, but just in case, these are the contents of my mods folder:

![image](https://user-images.githubusercontent.com/17902987/126136978-efed0f6b-a962-4265-af06-9050dffe6921.png)

**Comment by alfphaderp** [comment] 2021-07-23 00:12
Can confirm. I'm able to reproduce this issue on sodium-fabric-mc1.17.1-0.3.0+build.5 with openjdk 15.0.2 running an Intel Core i7-8565U with a GTX 1050. The only mods I have installed are sodium and fabric-api-0.37.0+1.17.

Would very much like to see this fixed ^^

**Comment by Rajbir98** [comment] 2021-07-25 13:51
i also having this problem now

**Comment by Rajbir98** [comment] 2021-07-25 13:51
i am using the latest build of actions build 529

**Comment by silversquirl** [comment] 2021-10-10 13:28
Looks like tinted glass is treated as an opaque block for the purposes of ambient occlusion, whereas it should be treated the same as glass.

**Comment by MESLewis** [comment] 2021-10-19 19:50
It's worth noting that magma blocks are handled as expected in sodium.

Current sodium:
![image](https://user-images.githubusercontent.com/597053/137980277-4b97ef2e-5d22-491d-a364-981fcd2914c2.png)

**Comment by IMS212** [comment] 2023-02-20 00:29
This seems to have been fixed by Sodium 0.4.3.

**Closed as completed by IMS212** 2023-02-20 00:29 UTC
Labels: T-bug, S-needs-testing, A-vanilla-parity
