### ISSUE TITLE
Found conflicting mods

### ISSUE THREAD

**Issue by papa3boyz** [jellysquid3/Sodium#318] opened 2020-09-28 10:44 UTC
[18:33:07] [main/INFO]: Loading for game Minecraft 1.16.2
[18:33:15] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Found conflicting mods: exotic-matter breaks {sodium @ [*]}
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:190) ~[fabric-loader-0.9.3+build.207.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:604) ~[fabric-loader-0.9.3+build.207.jar:?]
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:202) ~[fabric-loader-0.9.3+build.207.jar:?]
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:192) [fabric-loader-0.9.3+build.207.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:127) [fabric-loader-0.9.3+build.207.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.9.3+build.207.jar:?]
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:187) ~[fabric-loader-0.9.3+build.207.jar:?]
	... 5 more

mods: exotic-matter in facility-mc116-0.11.184.jar

**Comment by LucilleTea** [comment] 2020-09-28 11:03
> Found conflicting mods: exotic-matter breaks {sodium @ [*]}

This is an intentional error message, the author of exotic matter has specified that you can't use it with Sodium.
The lack of FRAPI support may be one reason, tracked in #5.

**Comment by amnotbananaama** [comment] 2020-09-28 15:40
As Lucy said, this is a temporary measure that mod’s author [has added](https://github.com/grondag/exotic-matter-2/issues/2#issuecomment-674281140) until Sodium and Exotic Matter are compatible. When FRAPI support is added, they will be compatible.

Until then, there’s nothing we can do, Exotic Matter is basically saying “crash if Sodium is present”. I’m going to close this as a duplicate of the issue Lucy mentioned.

**Closed as completed by amnotbananaama** 2020-09-28 15:40 UTC
Labels: T-bug, E-duplicate, A-mods
