### ISSUE TITLE
Fog and Shaders

### ISSUE THREAD

**Issue by MicheleAwada** [jellysquid3/Sodium#412] opened 2020-12-05 06:00 UTC
Please Just add a option to remove fog and also Shaders compatibility that is it!

**Comment by amnotbananaama** [comment] 2020-12-05 07:46
> Please Just add a option to remove fog  

Duplicate of #262. There is an option to disable Overworld fog on the `1.16.x/dev` branch, I don't know if that's coming to the `1.16.x/stable` branch.

>  and also Shaders compatibility

Duplicate of #164

**Closed as completed by amnotbananaama** 2020-12-05 07:46 UTC
Labels: E-duplicate, T-enhancement
