### ISSUE TITLE
Game crash when entering nether

### ISSUE THREAD

**Issue by HAXDK** [jellysquid3/Sodium#1534] opened 2022-12-10 16:28 UTC
### Version information

sodium-fabric-mc1.19.2-0.4.4+build.18

### Expected Behavior

That i would be able to enter the nether with no issues?

### Actual Behavior

The game crashes when entering nether and get error code. 1

### Reproduction Steps

Enter nether. Crash.

### Java version

Java 17.0.3 64 bit

### CPU

i7 11700k

### GPU

RTX 3080 Ti

### Additional information

- BetterF3-1.4.0-Fabric-1.19.2
- camerautils-1.19.2-1.0.2
- fabric-api-0.62.0+1.19.2
- fabric-carpet-1.19.1-1.4.83+v220727
- freecam-1.1.6+1.19
- itemscroller-fabric-1.19.2-0.17.1
- litematica-fabric-1.19.2-0.12.5
- lithium-fabric-mc1.19.2-0.8.3
- malilib-fabric-1.19.2-0.13.0
- minihud-fabric-1.19.2-0.23.3
- modmenu-4.0.6
- NoFog-1.3.1_1.16.5-1.19.2-fabric
- shulkerboxtooltip-forge-3.2.2+1.19.2
- tweakeroo-fabric-1.19.2-0.14.3
- worldedit-mod-7.2.12

Nvidia driver version 527.56
Windows version Windows 11 Pro, 22H2, 22621.819, Windows Feature Experience Pack 1000.22636.1000.0

**Comment by p256ah** [comment] 2022-12-11 01:56
I'm also having this problem, but my game crashes any time I go through any portal (affects nether and end portals), and also when I change my render and simulation distance. Same sodium version as above. 

core i9-10900K

RTX 3080 ti

I also use bobby mod, which might be affecting this, but I didn't see any related issues on that forum, only here. Was wondering if related.

**Comment by ThunderStorm0203** [comment] 2022-12-11 07:24
I am having the same problem. I have almost all the mods above and some extras. I think one of the mods might cause this because I have the same mods. I hope we can solve this.

**Comment by Cheos137** [comment] 2022-12-11 10:26
probably related to #1486
try downgrading your nvidia drivers to version 522.25 and see if it works

**Comment by HAXDK** [comment] 2022-12-11 14:15
Yes 522.25 works.

**Comment by shrimpsolution** [comment] 2022-12-13 17:16
To be clear it happens whenever going through a dimension.

**Comment by pajicadvance** [comment] 2023-05-10 17:22
Duplicate of #1486.

**Closed as not planned by pajicadvance** 2023-05-10 17:22 UTC
Labels: T-bug, E-duplicate, A-drivers
