### ISSUE TITLE
crashing shortly after loading into world and running around and also when changing settings (like render distance)

### ISSUE THREAD

**Issue by mrwubs42069** [jellysquid3/Sodium#1510] opened 2022-11-17 11:34 UTC
### Version information

1.19.2

### Reproduction Steps

i just walk around the world 
then after about a minute it crashes 

### Crash Report file

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2022-11-16 23:13:53
Description: Unexpected error

java.nio.BufferUnderflowException
	at me.jellysquid.mods.sodium.client.gl.util.MultiDrawBatch$UnsafeMultiDrawBatch.add(MultiDrawBatch.java:155)
	at me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer.addDrawCall(RegionChunkRenderer.java:190)
	at me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer.redirect$bgk000$cullleaves$fixTransparentBlockFaceCulling(RegionChunkRenderer.java:541)
	at me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer.buildDrawBatches(RegionChunkRenderer.java:113)
	at me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer.render(RegionChunkRenderer.java:82)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.renderLayer(RenderSectionManager.java:289)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.drawChunkLayer(SodiumWorldRenderer.java:221)
	at net.minecraft.class_761.method_3251(class_761.java:14539)
	at net.minecraft.class_761.invokeRenderChunkLayer(class_761.java)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:422)
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:754)
	at net.minecraft.class_761.handler$cod000$iris$renderTerrainShadows(class_761.java:8034)
	at net.minecraft.class_761.method_22710(class_761.java:1240)
	at net.minecraft.class_757.method_3188(class_757.java:1039)
	at net.minecraft.class_757.method_3192(class_757.java:816)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.jellysquid.mods.sodium.client.gl.util.MultiDrawBatch$UnsafeMultiDrawBatch.add(MultiDrawBatch.java:155)
	at me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer.addDrawCall(RegionChunkRenderer.java:190)
	at me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer.redirect$bgk000$cullleaves$fixTransparentBlockFaceCulling(RegionChunkRenderer.java:541)
	at me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer.buildDrawBatches(RegionChunkRenderer.java:113)
	at me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer.render(RegionChunkRenderer.java:82)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.renderLayer(RenderSectionManager.java:289)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.drawChunkLayer(SodiumWorldRenderer.java:221)
	at net.minecraft.class_761.method_3251(class_761.java:14539)
	at net.minecraft.class_761.invokeRenderChunkLayer(class_761.java)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:422)
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:754)
	at net.minecraft.class_761.handler$cod000$iris$renderTerrainShadows(class_761.java:8034)
	at net.minecraft.class_761.method_22710(class_761.java:1240)
	at net.minecraft.class_757.method_3188(class_757.java:1039)

-- Affected level --
Details:
	All players: 1 total; [class_746['mrwubs420'/11, l='ClientLevel', x=1604.78, y=78.00, z=-565.78]]
	Chunk stats: 1024, 545
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,68,0), Section: (at 0,4,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 550838 game time, 733636 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:792)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, SmoothFont_1.19.X.zip, 1.19_BetterBookshelves_V1.4.zip, Invisible-Item-Frames-V4.zip, continuity/glass_pane_culling_fix, continuity/default, Better+Leaves+Addon+V2.9-1.19.zip, Supplementaries Generated Pack, Fancy, GUI Overhaul v0.1.2.7.zip, Stay_True_1.19.zip

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1370633664 bytes (1307 MiB) / 3386900480 bytes (3230 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 24
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 9 5900X 12-Core Processor            
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 24
	Graphics card #0 name: NVIDIA GeForce RTX 3070
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2488
	Graphics card #0 versionInfo: DriverVersion=31.0.15.2686
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 37557.05
	Virtual memory used (MB): 19620.56
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 60.90
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Fabric Mods: 
		alternate-current: Alternate Current 1.4.0
		ambientenvironment: Ambient Environment 8.0+3
		appleskin: AppleSkin 2.4.1+mc1.19
		architectury: Architectury 6.3.49
		auditory: Auditory 0.0.4-1.19.x
		badpackets: Bad Packets 0.2.1
		bclib: BCLib 2.1.3
		betterdeserttemples: YUNG's Better Desert Temples 1.19.2-Fabric-2.2.1
		betterdungeons: YUNG's Better Dungeons 1.19.2-Fabric-3.2.1
		betterend: Better End 2.1.1
		betterf3: BetterF3 4.0.0
		bettermineshafts: YUNG's Better Mineshafts 1.19.2-Fabric-3.2.0
		betternether: Better Nether 7.1.2
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.19.2-Fabric-2.1.0
		betterstrongholds: YUNG's Better Strongholds 1.19.2-Fabric-3.2.0
		betterwitchhuts: YUNG's Better Witch Huts 1.19.2-Fabric-2.1.0
		bookshelf: Bookshelf 16.1.11
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.9.0
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.9.0
			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.2.0+alpha.9.0
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.9.0
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.9.0
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.9.0
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.9.0
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.9.0
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.9.0
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.9.0
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.9.0
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.9.0
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.9.0
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.9.0
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.9.0
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.9.0
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.9.0
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.9.0
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.9.0
			c2me-threading-scheduling: Concurrent Chunk Management Engine (Threading/Scheduling) 0.2.0+alpha.9.0
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.9.0
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			com_ibm_async_asyncutil: asyncutil 0.1.0
			net_objecthunter_exp4j: exp4j 0.4.8
			org_threadly_threadly: threadly 7.0
		cameraoverhaul: Camera Overhaul 1.3.1-fabric-universal
		camerautils: Camera Utils 1.19.2-1.0.2
		chunkpregen: Fabric Chunk Pregenerator 0.3.3
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 9.0.0+11
		completeconfig: CompleteConfig 2.0.0
			coat: Coat 1.0.0-beta.17+mc22w17a
			completeconfig-base: completeconfig-base 2.0.0
			completeconfig-gui-cloth: completeconfig-gui-cloth 2.0.0
			completeconfig-gui-coat: completeconfig-gui-coat 2.0.0
		connectivity: Connectivity Mod 1.19-3.3
		continuity: Continuity 2.0.1+1.19
		controlling: Controlling For Fabric 10.0+7
		cullleaves: Cull Leaves 3.0.0
			midnightlib: MidnightLib 1.0.0
		debugify: Debugify 2.8.0
			com_github_llamalad7_mixinextras: mixinextras 0.1.0
		diagonalfences: Diagonal Fences 4.2.3
		disable_custom_worlds_advice: Disable Custom Worlds Advice 3.0
		dsurround: Dynamic Surroundings: Remastered Fabric Edition 0.1.1
			org_openjdk_nashorn_nashorn-core: nashorn-core 15.3
		dynamiccrosshair: Dynamic Crosshair 3.11+1.19.2
			fabric-api-base: Fabric API Base 0.4.12+93d8cb8290
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.22+aaaf9d3390
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.1+93d8cb8290
		dynamicfps: Dynamic FPS 2.2.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		eatinganimationid: Eating Animation 1.9
		effective: Effective 1.4
		enchdesc: EnchantmentDescriptions 13.0.3
		enhancedblockentities: Enhanced Block Entities 0.7.2+1.19.2
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.2
			spruceui: SpruceUI 4.0.0+1.19
		entityculling: EntityCulling-Fabric 1.5.2-mc1.19
			com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT
		extrasounds: ExtraSounds 2.3.1+1.19.2-1.19.1
			soundcategories: Sound Categories 1.2.4+1.19
		fabric-api: Fabric API 0.66.0+1.19.2
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.10+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.18+c6af733c90
			fabric-block-api-v1: Fabric Block API (v1) 1.0.0+12bfe4ea90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.21+c6af733c90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.2+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.12+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.1.8+93d8cb8290
			fabric-commands-v0: Fabric Commands (v0) 0.2.29+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.35+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.4.1+6064db2a90
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.2+93d8cb8290
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.6+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.2.3+b598f4ac90
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.32+0dd10df690
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.0+a1d87cb890
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.29+c6af733c90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.29+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.22+c6af733c90
			fabric-item-api-v1: Fabric Item API (v1) 1.5.8+93d8cb8290
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.33+70efcffe90
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.20+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.0+33ffe9ec90
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.7+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.10+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.4+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.18+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.18+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.5+c6af733c90
			fabric-networking-v0: Fabric Networking (v0) 0.3.22+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.1.0+06e0e25190
			fabric-particles-v1: Fabric Particles (v1) 1.0.11+79adfe0a90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.26+c6af733c90
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.13+12bfe4ea90
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.15+aeb40ebe90
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.21+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.16+12bfe4ea90
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.8+c6af733c90
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.23+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.11.0+73145abb90
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.0+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.7.3+3e1ba48e90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.27+93d8cb8290
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.1+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.0+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.21+aeb40ebe90
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.1+42d99c3290
		fabricloader: Fabric Loader 0.14.10
		fallingleaves: Falling Leaves 1.12.4+1.19.2
		fallingtree: FallingTree 3.10.0
		faster_entity_animations: FastAnim 1.5.6
		fastload: Fast Load 2.3.5
		ferritecore: FerriteCore 4.2.1
		forgeconfigapiport: Forge Config API Port 4.2.6
		fpsdisplay: FPS-Display 1.5.0+1.19
		fpsreducer: FPS Reducer 1.19.2-2.1
		iceberg: Iceberg 1.0.46
		indium: Indium 1.0.9+mc1.19.2
		inventorysorter: Inventory Sorter 1.8.10-1.19
			kyrptconfig: Kyrpt Config 1.4.14-1.19
		invmove: InvMove 0.8.1
		iris: Iris 1.4.0
			io_github_douira_glsl-transformer: glsl-transformer 1.0.0-pre21.2
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.10.1
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 11.4.0.286
		journeymap: Journeymap 5.9.0beta2
			journeymap-api-fabric: JourneyMap API 1.19.1-1.9-fabric-SNAPSHOT
		krypton: Krypton 0.2.1
			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT
		lambdynlights: LambDynamicLights 2.1.2+1.19
			pride: Pride Lib 1.1.2+1.19
		lazydfu: LazyDFU 0.1.3
		legendarytooltips: Legendary Tooltips 1.3.3
		litematica: Litematica 0.12.5
		lithium: Lithium 0.10.2
		logical_zoom: Logical Zoom 0.0.17
		lucky: Lucky Block 1.19.2-13.0
		malilib: MaLiLib 0.13.0
		minecraft: Minecraft 1.19.2
		modmenu: Mod Menu 4.1.0
		moonlight: Moonlight 1.19.2-2.1.9
		mousetweaks: Mouse Tweaks 2.22
		naturescompass: Nature's Compass 1.19.2-2.0.4-fabric
		nullscape: Nullscape 1.2
		presencefootsteps: Presence Footsteps 1.6.3
			kirin: Kirin UI 1.11.1
		prism: Prism 1.0.3
		puzzleslib: Puzzles Lib 4.3.12
			cardinal-components-base: Cardinal Components API (base) 5.0.2
			cardinal-components-block: Cardinal Components API (blocks) 5.0.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.2
			cardinal-components-entity: Cardinal Components API (entities) 5.0.2
			cardinal-components-world: Cardinal Components API (worlds) 5.0.2
		reeses-sodium-options: Reese's Sodium Options 1.4.7+mc1.19.2-build.59
		rottencreatures: Rotten Creatures 1.0.1
			reach-entity-attributes: Reach Entity Attributes 2.3.0
		satin: Satin 1.9.0
		smoothboot: Smooth Boot 1.19-1.7.1
		smoothchunk: Smooth chunk save Mod 1.19.1-2.0
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		sodium-extra: Sodium Extra 0.4.12+mc1.19.2-build.72
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		stack-to-nearby-chests: Stack to Nearby Chests 0.2.1
			libgui: LibGui 6.3.0+1.19
				jankson: Jankson 4.1.1+j1.2.1
					blue_endless_jankson: jankson 1.2.1
				libninepatch: LibNinePatch 1.1.0
		starlight: Starlight 1.1.1+fabric.ae22326
		supplementaries: Supplementaries 1.19.2-2.2.20
		terralith: Terralith 2.3
		toastmanager: Toast Manager 1.0.1
		unstructured: Unstructured 0.5.3+1.19.2
		wthit: wthit 5.13.4
		yet-another-config-lib: YetAnotherConfigLib 1.7.1
		yungsapi: YUNG's API 1.19.2-Fabric-3.8.2
			org_javassist_javassist: javassist 3.28.0-GA
			org_reflections_reflections: reflections 0.10.2
		yungsextras: YUNG's Extras 1.19.2-Fabric-3.1.0
	Loaded Shaderpack: ComplementaryShaders_v4.6.zip
		Profile: Custom (+35 options changed by user)
	Launched Version: fabric-loader-0.14.10-1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3070/PCIe/SSE2 GL version 3.2.0 NVIDIA 526.86, NVIDIA Corporation
	Window size: 3440x1440
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, file/SmoothFont_1.19.X.zip, file/1.19_BetterBookshelves_V1.4.zip, file/Invisible-Item-Frames-V4.zip, continuity/glass_pane_culling_fix, continuity/default, file/Better+Leaves+Addon+V2.9-1.19.zip, Supplementaries Generated Pack, file/Fancy, GUI Overhaul v0.1.2.7.zip, file/Stay_True_1.19.zip
	Current Language: English (US)
	CPU: 24x AMD Ryzen 9 5900X 12-Core Processor 
	Server Running: true
	Player Count: 1 / 8; [class_3222['mrwubs420'/11, l='ServerLevel[hmmmmmmmmmmmmm]', x=1604.78, y=78.00, z=-565.78]]
	Data Packs: vanilla, Fabric Mods, Supplementaries Generated Pack
	World Generation: Experimental

### Additional information

I have zero to little information on it and haven't been able to find help.
I cant play and cant figure out why.
like I said ill be running around the world for about a minute or two and then till just crash
the launcher doesn't pop back up either and doesn't give me a crash report. mc will also be still running in the background based on the fact that the curseforge modpack loader says that the game is still running when I try to open it again.
other times ill be changing video settings like render distance. that one crashes my game almost every time and sometimes if I disable or enable my shaders it does the same thing. 
and the game will do the exact same thing where the launcher wont pop up but the game will just randomly close. 
I've tried reinstalling sodium and deleting the options.txt file but that didn't work.

**Comment by Keoxxa** [comment] 2022-11-18 09:28
Have the same issue, crashed while exploring. Crashed as soon as it loaded a certain chunk. Seems to do so consistently.
Disabling Iris seems to fix the issue, something isn't working correctly with sodium and iris when using shaders. Using complementary shader 4.6

Reported the issue over at iris as well, in case the problem is on that side.

Time: 2022-11-18 02:48:49
Description: Unexpected error

java.nio.BufferUnderflowException
	at Not Enough Crashes deobfuscated stack trace.(1.19.2+build.24)
	at me.jellysquid.mods.sodium.client.gl.util.MultiDrawBatch$UnsafeMultiDrawBatch.add(MultiDrawBatch.java:155)
	at me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer.addDrawCall(RegionChunkRenderer.java:190)
	at me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer.buildDrawBatches(RegionChunkRenderer.java:141)
	at me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer.render(RegionChunkRenderer.java:82)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.renderLayer(RenderSectionManager.java:289)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.drawChunkLayer(SodiumWorldRenderer.java:221)
	at net.minecraft.client.render.WorldRenderer.renderLayer(WorldRenderer:18539)
	at net.minecraft.client.render.WorldRenderer.invokeRenderChunkLayer(WorldRenderer)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:423)
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:754)
	at net.minecraft.client.render.WorldRenderer.handler$gho000$iris$renderTerrainShadows(WorldRenderer:10534)
	at net.minecraft.client.render.WorldRenderer.render(WorldRenderer:1240)
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer:1039)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:816)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1177)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:768)
	at net.minecraft.client.main.Main.main(Main:244)
	at net.minecraft.client.main.Main.main(Main:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

Full crash-log (large modpack):
https://pastebin.com/kKmWiebk

**Comment by thboehi** [comment] 2022-11-21 14:35
I've the same issue but on a multiplayer Proxy server.

When I change server through portal, the game crash. It happens only with sodium activated.

I disabled Iris and it still does the same

**Comment by FractalGeodes** [comment] 2022-12-16 08:14
This is technically a duplicate of #1509, but this thread has more information, I just thought I'd link the two while exploring this issue. I don't think shaders make a difference on the error, either.

**Comment by Keoxxa** [comment] 2022-12-17 09:47
Hello! I remember I reported this over at the Iris hub as well, and they discovered it was caused by "CullLeaves 3.0" and since I updated cullleaves I have had no futher crashes related to this issue.
If you do not use cullleaves, I apologize, but that seemed to fix my issue. But maybe it will help in the diagnosis.

**Comment by metzger100** [comment] 2023-01-28 18:29
Thats true. Cull leaves 3.0 does cause the crash. Updating the Mod fixed it.
If that fixes your issue please close it. @mrwubs42069

**Closed as completed** 2023-05-10 17:31 UTC
Labels: A-mods, T-crash
