### ISSUE TITLE
Incompatibility with Vanadium and Continuity together: crash with UnsupportedOperationException

### ISSUE THREAD

**Issue by CPTProgrammer** [jellysquid3/Sodium#2221] opened 2023-12-26 11:12 UTC
### Bug Description

Game version: 1.20.1
Fabric version: 0.15.3

### Mod list (minimum):
- Cloth config 11.1.118
- Continuity 3.0.0-beta.4+1.20.1
- Indium 1.0.27+mc1.20.1
- Sodium 0.5.3
- Vanadium 0.1.675
- fabric-api-0.91.0+1.20.1

### Description
Sodium doesn't support custom ColorResolver (`net.minecraft.world.biome.ColorResolver`) and may throw an UnsupportedOperationException error if attempted.

### Reproduction Steps

1. Install the above-mentioned mods
2. Load the `Default Connected Textures` resource pack from Continuity and any resource pack containing a custom colormap property file (`/assets/minecraft/optifine/colormap/blocks/{any}.properties`). For instance, you can use [Patrix 32x](https://www.curseforge.com/minecraft/texture-packs/patrix-32x)
3. Enter a world
4. The game will then crash

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/13770939/latest.log)

### Crash Report

[crash-2023-12-26_18.41.27-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/13770941/crash-2023-12-26_18.41.27-client.txt)

**Comment by jellysquid3** [comment] 2023-12-30 07:00
This is a duplicate of #2166, so I'm going to close this in favor of the other issue.

**Closed as completed by jellysquid3** 2023-12-30 07:00 UTC
Labels: E-duplicate
