### ISSUE TITLE
Sodium 0.5.2 not responding on startup

### ISSUE THREAD

**Issue by Jilmoire** [jellysquid3/Sodium#2021] opened 2023-08-18 05:13 UTC
### Bug Description

This did not happened prior to today's minecraft small update or patch but now trying to start minecraft with the mod will not load the game and will get stuck at the loading screen then proceeds to not respond after. 

### Reproduction Steps

I removed the other mods then placed them again one by one to see the issue, after putting in sodium the game crashed or rather did not respond.
![image](https://github.com/CaffeineMC/sodium-fabric/assets/142565539/d938998d-af9e-44c2-b1bc-6acc06fb4dc7)
![image](https://github.com/CaffeineMC/sodium-fabric/assets/142565539/2d7ce4ac-d5d9-4fb2-8fcc-c689a005b46c)

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12375527/latest.log)

### Crash Report

[crash-2023-08-18_13.09.54-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12375579/crash-2023-08-18_13.09.54-client.txt)

**Comment by IshaanBhaiOp** [comment] 2023-08-18 05:45
same problem

**Comment by hexadecimal233** [comment] 2023-08-18 05:50
Update your intel driver, seems a duplicate of #899

**Comment by jellysquid3** [comment] 2023-08-18 05:52
The problem is always out of date graphics drivers... see #899.

**Closed as not planned by jellysquid3** 2023-08-18 05:52 UTC
Labels: A-drivers
