### ISSUE TITLE
Multi-Layered textures don't be rendering

### ISSUE THREAD

**Issue by arcanoren** [jellysquid3/Sodium#606] opened 2021-03-25 00:26 UTC
... Like a Kibe item Entangled Bag

**Comment by dbl7id** [comment] 2021-03-25 00:40
Next time please try to either use the provided issue templates or elaborate more on the issue that you are having.
I'm assuming that this is a duplicate of #5.

**Comment by LucilleTea** [comment] 2021-03-25 00:42
It is, we just had this particular example come up in #603 too.

**Closed as completed by LucilleTea** 2021-03-25 00:42 UTC
Labels: E-duplicate

**Comment by arcanoren** [comment] 2021-03-25 00:43
yes, is it... Sorry
