### ISSUE TITLE
my game doesn't even load up 

### ISSUE THREAD

**Issue by iiAbusing** [jellysquid3/Sodium#388] opened 2020-11-09 16:17 UTC
Not sure why it's happening i just downloaded sodium 1.16.3 fabric mod and added it to my fabric mod folder and started the game and it won't load up it says:

The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'imm_ptl_core'!
Exit Code: -1

[crash-2020-11-09_16.06.21-client.txt](https://github.com/jellysquid3/sodium-fabric/files/5511761/crash-2020-11-09_16.06.21-client.txt)

Kind regards

**Comment by ReperakDev** [comment] 2020-11-09 16:56
Unfortunately Sodium and Immersive Portals are both incompatible with each other due to how rendering works. You'll have to make a choice of which one you'd like to keep.

**Comment by FlashyReese** [comment] 2020-11-09 17:55
You can use [qouteall/sodium-fabric](https://github.com/qouteall/sodium-fabric/releases/tag/ipc1161_1), it's a fork by the creator of Immersive Portals. Just keep in mind if you run into any issues. You should open an issue at quoteall's repository not the official one.

**Comment by amnotbananaama** [comment] 2020-11-09 19:02
Closing as a duplicate of #15. You’ll either need to use an unofficial fork, or wait for compatibility.

**Closed as completed by amnotbananaama** 2020-11-09 19:02 UTC
Labels: E-duplicate, T-crash
