### ISSUE TITLE
Applied Energistics

### ISSUE THREAD

**Issue by StormyRiley1** [jellysquid3/Sodium#564] opened 2021-03-03 12:11 UTC
### Expected Behavior
The texture would load without sodium 

### Actual Behavior
The texture don’t load with sodium 

### Reproduction Steps
1.Get the ME drive 
2.Put it down
3. The texture doesn’t load

**Comment by dbl7id** [comment] 2021-03-03 12:18
Duplicate of #5

**Closed as completed** 2021-03-03 12:21 UTC
Labels: T-bug, E-duplicate
