### ISSUE TITLE
FREX Render API is still not compatible, making rendering with shaders using the Replay mod and iris shaders impossible (answered)

### ISSUE THREAD

**Issue by EmqsaGit** [jellysquid3/Sodium#1105] opened 2022-01-05 22:22 UTC
### Version information

sodium-fabric-mc1.18-0.4.0-alpha5+build.9

### Expected Behavior

Being able to run iris and render using the Replay mod with iris shaders (it needs Sodium to work, btw)

### Actual Behavior

The "Render" button in the Replay mod shows an error: Your Sodium version is not compatible with FREX and you cant export if you dont update or remove sodium entirelly. (Not actual message)

### Reproduction Steps

1: Use sodium and the Replay mod togheter
2: Enter a world and start recording a test clip on the Replay mod
2.1: Press stop recording and leave the world when ready, and click the replay viewer button on the main menu
3: Try to render the replay by pressing the icon near the bottom bar
4: See the error

### Java version

Java 17.0.1 (Built-in)

### CPU

Intel Xeon CPU E5-2650 v2 @2.60GHz (16 CPUs), ~2.6GHz

### GPU

NVIDIA GeForce GTX 960 (4GB, soon to be upgraded)

### Additional information

I'm using the following mods along with Sodium, Iris and the Replay mod: (Ignore *.jara and *.CADEACOMPATIBILIDADECOMFREXPORRA ones since i just renamed them to not be loaded)

![image](https://user-images.githubusercontent.com/89603679/148297945-af6c1faa-6516-454b-ba00-b5e7fbc49da2.png)

**Comment by DioEgizio** [comment] 2022-01-06 14:22
Wdym. Replay requires a special version of sodium, that works with iris...

**Comment by snaco** [comment] 2022-01-06 16:31
@DioEgizio is right but it is annoying, it would be nice if the FREX api was available in the official sodium. @EmqsaGit here is the download for the patched sodium for 1.18: https://www.replaymod.com/download/sodium-fabric-mc1.18-0.4.0-alpha5+rev.76d0e6e.jar

**Comment by DioEgizio** [comment] 2022-01-06 17:04
FREX support is planned on sodium actually

**Comment by jellysquid3** [comment] 2022-01-06 19:34
This is not a bug, you are asking for functionality to be added so that other mods will be supported.

**Comment by EmqsaGit** [comment] 2022-01-13 18:21
> @DioEgizio is right but it is annoying, it would be nice if the FREX api was available in the official sodium. @EmqsaGit here is the download for the patched sodium for 1.18: https://www.replaymod.com/download/sodium-fabric-mc1.18-0.4.0-alpha5+rev.76d0e6e.jar

thank you

**Comment by EmqsaGit** [comment] 2022-01-13 18:22
> This is not a bug, you are asking for functionality to be added so that other mods will be supported.

oh ok

**Comment by EmqsaGit** [comment] 2022-01-13 18:23
> FREX support is planned on sodium actually

that's why it works on previous versions..?

**Comment by DioEgizio** [comment] 2022-01-13 18:24
> > FREX support is planned on sodium actually
> 
> that's why it works on previous versions..?

It doesn't

**Comment by DioEgizio** [comment] 2022-01-13 18:24
You still need custom sodium for replaymod

**Comment by ryanccn** [comment] 2022-08-09 10:18
Is the custom Sodium closed-source? I don't see it in the ReplayMod org anywhere

**Comment by DioEgizio** [comment] 2022-08-09 10:22
https://github.com/Johni0702/sodium-fabric/branches

**Comment by ryanccn** [comment] 2022-08-09 14:42
Oh, thanks

**Comment by IMS212** [comment] 2022-08-24 17:00
Fixed in https://github.com/CaffeineMC/sodium-fabric/commit/abadfe6f5fccdcc478b5ade300801cdcbb28476b.

**Closed as completed by IMS212** 2022-08-24 17:00 UTC
Labels: T-enhancement

**Comment by SpeastTV** [comment] 2022-10-16 11:43
> @DioEgizio is right but it is annoying, it would be nice if the FREX api was available in the official sodium. @EmqsaGit here is the download for the patched sodium for 1.18: https://www.replaymod.com/download/sodium-fabric-mc1.18-0.4.0-alpha5+rev.76d0e6e.jar

Do you have a version for the 1.16.5?

**Comment by DioEgizio** [comment] 2022-10-16 12:16
https://www.replaymod.com/download/sodium-fabric-mc1.16.5-0.2.0+rev.f42b4ca.jar should work

**Comment by SpeastTV** [comment] 2022-10-16 12:19
> 

Thanks!

**Comment by MagShadowLight** [comment] 2023-03-26 07:15
> @DioEgizio is right but it is annoying, it would be nice if the FREX api was available in the official sodium. @EmqsaGit here is the download for the patched sodium for 1.18: https://www.replaymod.com/download/sodium-fabric-mc1.18-0.4.0-alpha5+rev.76d0e6e.jar

do you have a version for 1.18.2
