### ISSUE TITLE
crashing because of placed player heads i think

### ISSUE THREAD

**Issue by S0apyy** [jellysquid3/Sodium#2054] opened 2023-08-30 20:29 UTC
### Bug Description

somehow for some reason my game crashes when loading in player heads. i don't know if its placed or actual player heads crashing the game

### Reproduction Steps

i don't know if this can be reproduced without the specific modpack I'm using right now, but all i did was join my server and after some time it just gives the crash log below. i also don't know if this is an issue with sodium in general or just a mod i installed causing this.

### Log File

[2023-08-30-7.log](https://github.com/CaffeineMC/sodium-fabric/files/12479894/2023-08-30-7.log)

### Crash Report

[crash-2023-08-30_22.11.57-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12479901/crash-2023-08-30_22.11.57-client.txt)

**Comment by MeeniMc** [comment] 2023-08-31 14:25
If your error occurs only with a particular modpack, maybe ask the modpack support channel for help. This is probably not a bug in Sodium.

**Comment by S0apyy** [comment] 2023-08-31 14:29
yeah ive already found out the issue and its due to figura, it hasnt happend to me again yet with the figura mod updated but i guess if it happens again ill have to wait for figura to update.

**Comment by alekso56** [comment] 2023-08-31 17:53
Duplicate of #2032

**Closed as not planned** 2023-09-09 15:40 UTC
Labels: E-duplicate
