### ISSUE TITLE
Forge port PLEASE!!!!

### ISSUE THREAD

**Issue by HGDaviD0002** [jellysquid3/Sodium#760] opened 2021-07-14 12:11 UTC
Please add a forge port to the mod i have really low fps with modpacks which is for forge and i need to increase my fps! Please add a forge port!

**Comment by LucilleTea** [comment] 2021-07-14 12:13
Duplicate of #138 - we will not port sodium to forge.

**Closed as completed by LucilleTea** 2021-07-14 12:13 UTC
Labels: E-duplicate
