### ISSUE TITLE
Can not change the Resolution of Minecraft

### ISSUE THREAD

**Issue by TuPutaMadre69** [jellysquid3/Sodium#541] opened 2021-02-23 22:38 UTC
The option to change the resolution of Minecraft is missing

**Comment by amnotbananaama** [comment] 2021-02-23 23:14
Duplicate of #46. In the meantime, please use the shortcut `Shift` + `P` to temporarily access the vanilla Video settings menu and set the desired resolution.

**Closed as completed by amnotbananaama** 2021-02-23 23:14 UTC
Labels: T-bug, E-duplicate
