### ISSUE TITLE
Empty chunks

### ISSUE THREAD

**Issue by gnilobaiter** [jellysquid3/Sodium#1759] opened 2023-05-13 14:01 UTC
### Version information

mc1.19.4-0.4.10

### Expected Behavior

No empty chunk

### Actual Behavior

Chunks are missing in the corner of the screen. I checked on pure minecraft and only with Sodium. There is no problem on pure minecraft

### Reproduction Steps

1. Came to the mine
2. I saw a bug

### Java version

JDK 17

### CPU

Intel Core i7-10700k

### GPU

GTX 1080

### Additional information

![javaw_4mwnXVvaax](https://github.com/CaffeineMC/sodium-fabric/assets/104412752/1e461b58-ae26-487c-b51d-2e382b8c5dff)

If you turn a little, it disappears. Infuriating bug, constantly flickering chunks in the mine :(
![javaw_ObdKedlNeQ](https://github.com/CaffeineMC/sodium-fabric/assets/104412752/5d27b5b4-eeff-4f38-a367-1d8292b825e3)

**Comment by gnilobaiter** [comment] 2023-05-13 14:03
Minecraft 1.19.4 + Fabric 0.14.19

**Comment by gnilobaiter** [comment] 2023-05-13 14:04
I also forgot to say, I tried all sorts of combinations of Sodium settings, it didn't help

**Comment by Timolino456** [comment] 2023-05-13 14:32
Duplicate of #872

**Closed as not planned** 2023-05-13 14:38 UTC
Labels: T-bug, E-duplicate
