### ISSUE TITLE
issue rendering stained glass behind stained glass on chunk border

### ISSUE THREAD

**Issue by Euan213** [jellysquid3/Sodium#1655] opened 2023-03-07 01:23 UTC
![Capture](https://user-images.githubusercontent.com/123749465/223294632-8de094ba-fdb9-44b0-b49a-324c045cbe53.PNG)
for some reason the cyan glass faces arent being rendered behind the light blue faces. issue persists with all other mods removed.

using sodium 0.4.2 for minecraft 1.19

CPU details: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz   2.59 GHz

**Comment by voidrinix** [comment] 2023-03-09 17:18
I think it's duplicate of #38

**Comment by IMS212** [comment] 2023-05-08 17:47
Correct, duplicate of #38.

**Closed as not planned by IMS212** 2023-05-08 17:47 UTC
Labels: E-duplicate
