### ISSUE TITLE
There is no title for this

### ISSUE THREAD

**Issue by BoTheBanana** [jellysquid3/Sodium#444] opened 2020-12-26 01:47 UTC
### Expected Behavior
I want it to not do this.

### Actual Behavior
It dose this
https://www.loom.com/share/1c79768fe5e8432b933d875bb7e49cac
### Reproduction Steps
I don't know
### Attachments
Add any relevant screenshots or videos to this issue as you feel necessary to explain the issue.

### System Information
Chromebook

- Java Version: 8
- CPU: Dont know
- GPU:Dont know

**Comment by LucilleTea** [comment] 2020-12-26 01:53
Go to video settings > advanced and set the chunk renderer to Oneshot (GL 3.0).
This is because your computer does not support Multidraw properly, it's not a bug in sodium.
In the future it would be better to use [our Discord server](https://jellysquid.me/discord) for tech support.

**Comment by BoTheBanana** [comment] 2020-12-26 01:54
ok. Thank You

**Comment by amnotbananaama** [comment] 2020-12-26 02:03
Closing as a duplicate of either #24 or #179.

> CPU: Dont know 
> GPU:Dont know  
  
In the future, a screenshot of the F3 debug screen (or even better a screenshot of the Alt + F3 debug screen) will provide us this information

**Closed as completed by amnotbananaama** 2020-12-26 02:03 UTC
Labels: T-bug, E-duplicate
