### ISSUE TITLE
Stuck on loading screen

### ISSUE THREAD

**Issue by MrDotUnknown0050** [jellysquid3/Sodium#1502] opened 2022-11-06 13:28 UTC
### Version information

1.19.2

### Expected Behavior

I was expecting to play Minecraft normally

### Actual Behavior

I recently download 1.19.2 mods (like 4-5 days) including sodium but when I try to open Minecraft with the sodium mod the game gets stuck on the loading screen, and it doesn't respond. The bar fills up like 10-20 percent.

### Reproduction Steps

Downloaded latest version of sodium and it didn't work

### Java version

Version 8 Update 351

### CPU

Intel(R) Core(TM) i3-3120M CPU

### GPU

Intel(R) HD graphics 4000

### Additional information

![Screenshot 2022-11-06 185715](https://user-images.githubusercontent.com/117577815/200173441-18bb9012-e57e-4d83-b491-06c06ad28a3e.png)
![Screenshot 2022-11-06 185008](https://user-images.githubusercontent.com/117577815/200173442-8073e309-76fc-421e-9ef7-dd53c4a1ee2c.png)

**Comment by shawala978** [comment] 2022-11-08 16:53
me too did u find any anwser

**Comment by jellysquid3** [comment] 2022-11-09 14:55
Duplicate of #899.

**Closed as completed by jellysquid3** 2022-11-09 14:55 UTC
Labels: T-bug, S-needs-triage

**Comment by MrDotUnknown0050** [comment] 2022-11-13 18:36
> Duplicate of #899.
Sorry for the late reply.
Thank you so much it fixed the problem <3
