### ISSUE TITLE
Purple Textures With Industrial Revolution & Modern Industrialisation

### ISSUE THREAD

**Issue by jimmytrouser** [jellysquid3/Sodium#550] opened 2021-02-28 18:06 UTC
### Expected Behavior
All blocks from Industrial Revolution (1.8.11) & Modern Industrialisation (0.3.14) should render properly when placed and in REI recipe menu .

### Actual Behavior
Some blocks from Industrial Revolution & Modern Industrialisation were invisible or see through when placed and when I looked in the REI menu some had purple and black textures (textures were missing).

### Reproduction Steps
Loaded game several times with and without sodium to replicate the bug.  Without sodium the textures appeared normal; with sodium they did not.

I also tried the different renderer types, but nothing solved the issue.

### Attachments
With Sodium Mod Installed
![Sodium Bug 2](https://user-images.githubusercontent.com/7896905/109428373-d7861c80-79ee-11eb-8474-a8fbf696150f.png)
![Sodium Bug](https://user-images.githubusercontent.com/7896905/109428375-d81eb300-79ee-11eb-904a-773921cfa99a.png)
Without Sodium Mod Installed
![2021-02-28_18 01 03](https://user-images.githubusercontent.com/7896905/109428437-0e5c3280-79ef-11eb-9a01-72543f3ab859.png)

### System Information
[DxDiag.txt](https://github.com/CaffeineMC/sodium-fabric/files/6057395/DxDiag.txt)

- Java Version: [Version 8 Update 281]
- CPU: [i7 4790K 4.00 GHz]
- GPU: [GTX 980]

**Comment by NoComment1105** [comment] 2021-02-28 18:17
Duplicate of #5
Currently sodium does not include the fabric rendering api which is requrired by some of the mods in that pack.
Inclusion is planned but there is no ETA

**Closed as completed** 2021-02-28 19:10 UTC
Labels: T-bug, E-duplicate

**Comment by GiorgoSprat** [comment] 2022-11-08 21:13
For anyone finding this thread even years after it was originally created, to solve this problem, make sure to use a mod called lithium, which adds compatiblity with fabric rendering api to sodium. adding this support to sodium itself is not planned as of right now.

**Comment by wolfsanker** [comment] 2025-03-11 16:51
have same problems(except that the block placing cause crashes) with MI, delete Sodium, install embeddium, everything fixes
