### ISSUE TITLE
Block Breaking glitch

### ISSUE THREAD

**Issue by PhantomFran05** [jellysquid3/Sodium#1424] opened 2022-08-16 12:57 UTC
### Version information

mc1.19-0.4.2+build.16

### Expected Behavior

When breaking or placing a block nothing should be affected by that action.

### Actual Behavior

Whenever i break or place blocks, some of the terrain glitches out for a split second after breaking the block. I have no idea if this has to do with chunk settings, chunk loading or visual glitches, but it glitches terrain, as if i were using piston+composter xray glitch.

### Reproduction Steps

I have no idea how to reproduce this, since i dont know if it only happens to me or if its a setting ive messed with. I believe the video settings are set to default. This has only affected me in the latest version of sodium for minecraft 1.19.2.

### Java version

Java 8

### CPU

Intel Core i5-1035G1

### GPU

Intel UHD Graphics

**Comment by VigilantGamingYT** [comment] 2022-08-17 18:19
same happening with me also but in 1.17.1

**Comment by pajicadvance** [comment] 2023-05-09 16:57
Duplicate of #869.

**Closed as not planned** 2023-05-10 16:58 UTC
Labels: T-bug, E-duplicate, A-drivers
