### ISSUE TITLE
Incorrect texture rendering

### ISSUE THREAD

**Issue by kwvanderlinde** [jellysquid3/Sodium#309] opened 2020-09-18 21:23 UTC
### Expected Behavior
Block textures should be rendered seamlessly.

### Actual Behavior
Certain non-vanilla texture packs (e.g., VanillaBDCraft, PureBDCraft) have odd edge rendering in the east-west direction. It looks like the texture isn't quite rendered all the way to the edge of the block.

### Reproduction Steps

1. Checkout the latest code on `1.16.x/dev` (this is f577eb2 at the time).
2. Run `./gradlew runClient` to get a client running.
3. Add the 1.16.1 PureBDCraft resource pack and apply it.
4. Create/load a superflat world.
5. Look at the ground blocks.

### Attachments
This is what my world looked like with the PureBDCraft textures: ![2020-09-18_14 06 17](https://user-images.githubusercontent.com/7492219/93645644-53e4f000-f9b9-11ea-98a3-30486522852c.png)
Notice the artifacts at the edge of the blocks heading in the east-west direction.

On a hunch, I reverted the change in #122 and loaded the world back up. Here it looks normal: ![2020-09-18_14 05 47](https://user-images.githubusercontent.com/7492219/93645687-72e38200-f9b9-11ea-8254-30f24320f7d1.png)

It's worth noting that I've never found an issue with the BDCraft texture packs in other installations, just with the latest sodium. It's also interesting that the vanilla textures render just fine.

### System Information

- Java Version: 1.8.0_265 64 bit
- CPU: 6x Intel(R) Core(TM) i5-9400 CPU @ 2.90 GHz
- GPU: GeForce GTX 1050/PCIe/SSE2  4.6.0 NVIDIA 440.100

**Comment by MeeniMc** [comment] 2020-11-03 08:54
Still present in 0.1.1-1.16.4 SNAPSHOT; 

There is also a thin red outline around transparent block textures (like flowers that are made of two flat textures in a cross).

![2020-11-03_03 51 26](https://user-images.githubusercontent.com/68366846/97965323-2cd75780-1d88-11eb-9996-f11a78096d4d.png)


As said above, what appears to cause the issue is using high-res texture pack (256px). Looks like a rounding error.

**Comment by MeeniMc** [comment] 2020-11-04 05:32
Following a comment from JellySquid:

    does it go away if you disable Video Settings > Advanced > Use Compact Vertex Format?

Yes, yes it does.

**Comment by CalXee** [comment] 2021-03-03 02:05
After commit 547c41c, this issue is mostly fixed. You can still reproduce it by getting a resource pack that adds more 3D models though. For example, there are still white dots rendering on the edges of doors if you get Vanilla Tweak's 3D doors and trapdoors pack, whereas they don't render the dots with the option turned off.
Video demonstrating the issue: https://www.youtube.com/watch?v=p3udEdvZ_cM

**Comment by MeeniMc** [comment] 2021-03-03 08:16
The 3d door models from VT have the issue w/o sodium as well. It appears to be a problem with VT itself.

Issue appears fixed by MrMangoHands patch in my testings with Sphax 256px on AMD Rx580 (CVF on, MultiDraw 4.3)

**Comment by MeeniMc** [comment] 2021-04-24 07:02
Issue is completely fixed in sodium/next

**Closed as completed** 2021-07-08 14:05 UTC
Labels: T-bug, S-confirmed
