### ISSUE TITLE
Game crashing

### ISSUE THREAD

**Issue by zatalk** [jellysquid3/Sodium#1639] opened 2023-02-23 20:29 UTC
### Version information

sodium-fabric-mc1.19.3-0.4.9+build.23

### Reproduction Steps

I don't know how to reproduce but the crash happenes in a frozen ocean biome

### Crash Report file

The game crashed whilst rendering item
Error: java.lang.ClassCastException: class com.anthonyhilyard.iceberg.renderer.VertexCollector$1 cannot be cast to class me.jellysquid.mods.sodium.client.render.vertex.VertexBufferWriter (com.anthonyhilyard.iceberg.renderer.VertexCollector$1 and me.jellysquid.mods.sodium.client.render.vertex.VertexBufferWriter are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @429bd883)

**Comment by pajicadvance** [comment] 2023-02-23 21:13
Duplicate of #1602.

**Closed as not planned** 2023-05-08 17:48 UTC
Labels: E-external, T-crash
