### ISSUE TITLE
when im in launcher and launch fabric loader and game launches  after a few second it says crash report and  says entrypoint stage 'client' due to errors, provided by 'imm_ptl_core'!

### ISSUE THREAD

**Issue by JoeHasClout** [jellysquid3/Sodium#363] opened 2020-10-27 01:53 UTC
### Reproduction Steps
Provide information on how to reproduce this game crash. This step is critical for ensuring that your crash can be debugged by other developers. You can either fill in the example below or do something else -- just make sure your instructions are minimal and clear. If applicable, provide a Minecraft save containing a minimal example on how to reproduce this crash as a compressed ZIP file.

1. Place a Redstone Lamp beside a Redstone Repeater
2. Use a Lever to activate the Redstone Repeater
3. The game crashes

### Crash Report File
Please upload your crash report as a file to [GitHub Gist](https://gist.github.com/) and replace this text with a link to the uploaded report.

### Additional Information
Provide any additional information or context which may be relevant to the issue. If you have none to add, you can remove this section.

**Comment by FlashyReese** [comment] 2020-10-27 02:01
If you can hop on Jelly's [Discord](https://jellysquid.me/discord), so we can assist you with the troubleshooting.

**Comment by amnotbananaama** [comment] 2020-10-27 17:58
Please properly fill out the issue template. It exists so that we can more easily help you, and don’t have to make guesses about your configuration.

> **Please upload your crash report as a file to [GitHub Gist](https://gist.github.com)**

Please provide a full crash log with Sodium running, and see if the error doesn’t occur when Sodium is disabled. Otherwise this is a configuration issue (not a bug), and you should join the discord for support.

**Comment by amnotbananaama** [comment] 2020-10-29 18:23
This is a duplicate of #15

**Closed as completed by amnotbananaama** 2020-10-29 18:23 UTC
Labels: E-duplicate, T-crash
