### ISSUE TITLE
Render threads freeze while joining server left through "return to title screen" button on death screen

### ISSUE THREAD

**Issue by dark-fedora** [jellysquid3/Sodium#1289] opened 2022-04-28 00:12 UTC
### Version information

sodium-fabric-mc1.18.2-0.4.1+build.15.jar

### Expected Behavior

The game should put me at the respawn screen.

### Actual Behavior

You will be stuck on a loading screen. Your position will exist, as well as you, but you will only be able to hear things, and must force-close the game one way or another.

### Reproduction Steps

1. Die on a Minecraft server, reaching the death screen.
2. When prompted to respawn or return to title screen, return to the title screen, confirming your choice.
3. Attempt to rejoin the server.

### Java version

Java 17.0.1 64-bit

### CPU

16x Intel(R) Core(TM) i7-1080-H CPU @ 2.20GhZ

### GPU

GeForce RTX 3050 Ti Laptop GPU/PCIe/SSE2

### Additional information

Tested this with several mods, one at a time. Adding sodium with any other mods, or no other mods, would result in this issue every time.

**Comment by MeeniMc** [comment] 2023-05-12 00:28
duplicate of #1225

**Comment by jellysquid3** [comment] 2023-07-22 02:40
This should be fixed in the latest version of Sodium. If not, open a new issue...

**Closed as not planned by jellysquid3** 2023-07-22 02:40 UTC
Labels: T-bug, S-needs-triage
