### ISSUE TITLE
Cull leaves/allow leaves to cull other blocks in fast graphics

### ISSUE THREAD

**Issue by muzikbike** [jellysquid3/Sodium#936] opened 2021-10-10 17:47 UTC
Vanilla bug https://bugs.mojang.com/browse/MC-179383. A close relative of #858 and #859.

For whatever reason, leaves in the Fast graphics mode do not cull the faces of adjacent leaves blocks, completely defeating the purpose of fast graphics altogether to my knowledge. These faces are meant to never be seen in this specific graphics mode, so having them all render anyway makes no sense.
![2021-10-10_18 43 26](https://user-images.githubusercontent.com/52297970/136707349-0c7e1cd9-6300-47dd-b6fa-370e5087f431.png)

**Comment by jellysquid3** [comment] 2021-10-10 17:51
Duplicate of #280.

**Closed as completed by jellysquid3** 2021-10-10 17:51 UTC
Labels: E-duplicate, A-vanilla-issue

**Comment by muzikbike** [comment] 2021-10-10 17:53
Evidently I didn't see that one, my mistake
