### ISSUE TITLE
soduim crash problem

### ISSUE THREAD

**Issue by gnougnou12** [jellysquid3/Sodium#1933] opened 2023-08-03 21:59 UTC
### Bug Description

When lunching sodium it just loads like 1/5 of the bar and my game crashes
i tried to search it online they say you need to delete .fabric file and it work but a week later it does it again and i tried to delete the .fabric file and it didnt work
They also say to update your graphic card but i don't have one in my computer (old computer)
I check my updates and there was none so please help me :)

### Reproduction Steps

load sodium

### Log File

[17:56:25] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.14.22
[17:56:25] [main/INFO]: Loading 81 mods:
	- chestesp 1.0-MC1.20.1-Fabric
	- cloth-config 11.1.106
	   \-- cloth-basic-math 0.6.1
	- cullleaves 3.1.0
	   \-- midnightlib 1.4.1
	- entityculling 1.6.2-mc1.20
	- fabric-api 0.83.1+1.20.1
	   |-- fabric-api-base 0.4.29+b04edc7a77
	   |-- fabric-api-lookup-api-v1 1.6.34+4d8536c977
	   |-- fabric-biome-api-v1 13.0.10+b3afc78b77
	   |-- fabric-block-api-v1 1.0.9+e022e5d177
	   |-- fabric-blockrenderlayer-v1 1.1.39+b3afc78b77
	   |-- fabric-client-tags-api-v1 1.0.20+b3afc78b77
	   |-- fabric-command-api-v1 1.2.32+f71b366f77
	   |-- fabric-command-api-v2 2.2.11+b3afc78b77
	   |-- fabric-commands-v0 0.2.49+df3654b377
	   |-- fabric-containers-v0 0.1.61+df3654b377
	   |-- fabric-content-registries-v0 4.0.7+b3afc78b77
	   |-- fabric-convention-tags-v1 1.5.3+b3afc78b77
	   |-- fabric-crash-report-info-v1 0.2.18+aeb40ebe77
	   |-- fabric-data-generation-api-v1 12.1.11+b3afc78b77
	   |-- fabric-dimensions-v1 2.1.51+b3afc78b77
	   |-- fabric-entity-events-v1 1.5.21+b3afc78b77
	   |-- fabric-events-interaction-v0 0.6.0+b3afc78b77
	   |-- fabric-events-lifecycle-v0 0.2.61+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.38+b04edc7a77
	   |-- fabric-item-api-v1 2.1.26+b3afc78b77
	   |-- fabric-item-group-api-v1 4.0.7+b3afc78b77
	   |-- fabric-key-binding-api-v1 1.0.36+fb8d95da77
	   |-- fabric-keybindings-v0 0.2.34+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.20+b3afc78b77
	   |-- fabric-loot-api-v2 1.1.37+b3afc78b77
	   |-- fabric-loot-tables-v1 1.1.41+9e7660c677
	   |-- fabric-message-api-v1 5.1.6+b3afc78b77
	   |-- fabric-mining-level-api-v1 2.1.47+b3afc78b77
	   |-- fabric-models-v0 0.3.35+b3afc78b77
	   |-- fabric-networking-api-v1 1.3.8+b3afc78b77
	   |-- fabric-networking-v0 0.3.48+df3654b377
	   |-- fabric-object-builder-api-v1 11.0.6+b3afc78b77
	   |-- fabric-particles-v1 1.0.28+b3afc78b77
	   |-- fabric-recipe-api-v1 1.0.18+b3afc78b77
	   |-- fabric-registry-sync-v0 2.2.6+b3afc78b77
	   |-- fabric-renderer-api-v1 3.0.1+b3afc78b77
	   |-- fabric-renderer-indigo 1.3.1+b3afc78b77
	   |-- fabric-renderer-registries-v1 3.2.44+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.33+b3afc78b77
	   |-- fabric-rendering-fluids-v1 3.0.26+b3afc78b77
	   |-- fabric-rendering-v0 1.1.47+df3654b377
	   |-- fabric-rendering-v1 3.0.6+b3afc78b77
	   |-- fabric-resource-conditions-api-v1 2.3.5+ea08f9d877
	   |-- fabric-resource-loader-v0 0.11.7+f7923f6d77
	   |-- fabric-screen-api-v1 2.0.6+b3afc78b77
	   |-- fabric-screen-handler-api-v1 1.3.27+b3afc78b77
	   |-- fabric-sound-api-v1 1.0.12+b3afc78b77
	   |-- fabric-transfer-api-v1 3.2.2+b3afc78b77
	   \-- fabric-transitive-access-wideners-v1 4.2.0+b3afc78b77
	- fabricloader 0.14.22
	- fpsreducer 1.20-2.5
	- freecam 1.2.1+1.20
	- fullbright-1-19 1.0.2
	- immediatelyfast 1.1.15+1.20.1
	   |-- com_github_llamalad7_mixinextras 0.2.0-beta.8
	   \-- net_lenni0451_reflect 1.1.0
	- java 17
	- lazydfu 0.1.3
	- litematica 0.15.3
	- lithium 0.11.2
	- malilib 0.16.1
	   \-- fabric-resource-loader-v0 0.11.7+f7923f6d77
	- memoryleakfix 1.1.1
	- minecraft 1.20.1
	- modmenu 7.2.1
	- name_visibility 1.1
	- no_fog 1.3.4+1.16.5-1.20.1
	- reeses-sodium-options 1.6.3+mc1.20.1-build.92
	- replaymod 1.20.1-2.6.13
	   |-- fabric-api-base 0.4.29+b04edc7a77
	   |-- fabric-key-binding-api-v1 1.0.36+fb8d95da77
	   |-- fabric-networking-api-v1 1.3.8+b3afc78b77
	   |-- fabric-resource-loader-v0 0.11.7+f7923f6d77
	   \-- fabric-screen-api-v1 2.0.6+b3afc78b77
	- sodium 0.4.10+build.27
	- sodium-extra 0.4.23+mc1.20.1-build.106
	   |-- caffeineconfig 1.3.0+1.17
	   \-- crowdin-translate 1.4+1.19.3
	- starlight 1.1.2+fabric.dbc156f
	- wi_zoom 1.4-MC1.20.1
[17:56:26] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/Usager/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[17:56:26] [main/INFO]: Compatibility level set to JAVA_17
[17:56:27] [main/INFO]: OptiFine was NOT detected.
[17:56:27] [main/INFO]: OptiFabric was NOT detected.
[17:56:27] [main/INFO]: Loaded configuration file for Lithium: 115 options available, 0 override(s) found
[17:56:27] [main/WARN]: Reference map 'mixins.nonmmlauncher.replaymod.refmap.json' for mixins.nonmmlauncher.replaymod.json could not be read. If this is a development environment you can ignore this message
[17:56:27] [main/INFO]: Loaded configuration file for Sodium: 33 options available, 0 override(s) found
[17:56:27] [main/INFO]: Loaded configuration file for Sodium Extra: 31 options available, 1 override(s) found
[17:56:28] [main/INFO]: bre2el.fpsreducer.mixin.MinecraftClientMixin will be applied.
[17:56:28] [main/INFO]: bre2el.fpsreducer.mixin.KeyboardMixin will be applied.
[17:56:28] [main/INFO]: bre2el.fpsreducer.mixin.RenderSystemMixin will be applied.
[17:56:28] [main/INFO]: bre2el.fpsreducer.mixin.WindowMixin will NOT be applied because OptiFine was NOT detected.
[17:56:29] [main/WARN]: Force-disabling mixin 'fog.MixinBackgroundRenderer' as option 'mixin.fog' (added by mods [no_fog]) disables it and children
[17:56:29] [main/INFO]: [MemoryLeakFix] Will be applying 3 memory leak fixes!
[17:56:29] [main/INFO]: [MemoryLeakFix] Currently enabled memory leak fixes: [targetEntityLeak, biomeTemperatureLeak, hugeScreenshotLeak]
[17:56:29] [main/WARN]: Error loading class: net/optifine/render/ChunkVisibility (java.lang.ClassNotFoundException: net/optifine/render/ChunkVisibility)
[17:56:29] [main/WARN]: Error loading class: shadersmod/client/ShadersRender (java.lang.ClassNotFoundException: shadersmod/client/ShadersRender)
[17:56:29] [main/WARN]: Error loading class: net/optifine/shaders/ShadersRender (java.lang.ClassNotFoundException: net/optifine/shaders/ShadersRender)
[17:56:29] [main/WARN]: Error loading class: net/coderbot/iris/uniforms/CommonUniforms (java.lang.ClassNotFoundException: net/coderbot/iris/uniforms/CommonUniforms)
[17:56:29] [main/WARN]: Error loading class: net/coderbot/iris/Iris (java.lang.ClassNotFoundException: net/coderbot/iris/Iris)
[17:56:46] [Render thread/INFO]: Launching a new process to probe the system configuration!
[17:56:47] [Render thread/INFO]: OpenGL Vendor: Intel
[17:56:47] [Render thread/INFO]: OpenGL Renderer: Intel(R) HD Graphics 4000
[17:56:47] [Render thread/INFO]: OpenGL Version: 3.3.0 - Build 10.18.10.4425
[17:56:48] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[17:56:48] [Render thread/INFO]: Setting user: QueenRuby
[17:56:48] [Render thread/INFO]: Starting ChestESP...
[17:56:49] [Render thread/INFO]: Loaded Fullbright 1.19 Mod!
[17:56:49] [Render thread/INFO]: [STDOUT]: Starting WI Zoom v1.4-MC1.20.1
[17:56:49] [Render thread/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[17:56:49] [Render thread/INFO]: Loading ImmediatelyFast 1.1.15+1.20.1
[17:56:50] [Worker-Main-1/INFO]: Checking mod updates...
[17:56:50] [Worker-Main-1/INFO]: Update available for 'immediatelyfast@1.1.15+1.20.1', (-> 1.1.24+1.20.1)
[17:56:50] [Worker-Main-1/INFO]: Update available for 'sodium-extra@0.4.23+mc1.20.1-build.106', (-> mc1.20.1-0.4.25)
[17:56:50] [Worker-Main-1/INFO]: Update available for 'fabric-api@0.83.1+1.20.1', (-> 0.86.1+1.20.1)
[17:56:52] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 SNAPSHOT
[17:56:53] [Render thread/WARN]: Missing metadata in pack file/Fire Glint (Obtrusive).zip
[17:56:53] [Render thread/WARN]: Missing metadata in pack file/l-6no-4fire-6overlay.zip
[17:56:53] [Render thread/INFO]: Found non-pack entry 'C:\Users\Usager\AppData\Roaming\.minecraft\resourcepacks\Totem.png', ignoring
[17:56:53] [Render thread/WARN]: Static binding violation: PRIVATE @Overwrite method method_23182 in sodium.mixins.json:features.item.MixinItemRenderer from mod sodium cannot reduce visibiliy of PUBLIC target method, visibility will be upgraded.
[17:56:55] [Render thread/INFO]: Reloading ResourceManager: vanilla, file/VisibleOres2.7.zip, file/QueenRuby-Totem-pv9 (1).zip, file/LowOnFire_1.20.1.zip, file/Note Block Tuner [1.19].zip, file/Newwind Pack 2.3 (Emojis Only).zip, file/old-sounds-default-version-e1680.zip, cullleaves:smartleaves, fabric (caffeineconfig, chestesp, cloth-config, cullleaves, entityculling, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-containers-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-crash-report-info-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-events-lifecycle-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-tables-v1, fabric-message-api-v1, fabric-mining-level-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-networking-v0, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, fpsreducer, freecam, fullbright-1-19, immediatelyfast, lazydfu, litematica, lithium, malilib, midnightlib, modmenu, name_visibility, no_fog, reeses-sodium-options, replaymod, sodium, sodium-extra, starlight, wi_zoom), replaymod_lang
[17:56:55] [Worker-Main-2/INFO]: Found unifont_all_no_pua-15.0.06.hex, loading
[17:56:56] [Worker-Main-3/WARN]: Invalid path in datapack: minecraft:textures/block/gold_ore (1).png, ignoring

### Crash Report

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12255359/latest.log)

**Comment by pajicadvance** [comment] 2023-08-03 22:38
Duplicate of #899, you need to update your Intel graphics driver, found [here](https://www.intel.com/content/www/us/en/download/18606/intel-graphics-driver-for-windows-15-33.html).

**Closed as not planned by pajicadvance** 2023-08-03 22:38 UTC
Labels: T-bug, A-drivers
