### ISSUE TITLE
Stained Glass Color Layering Broken in Certain Directions

### ISSUE THREAD

**Issue by Pokepowerz** [jellysquid3/Sodium#2190] opened 2023-11-29 23:04 UTC
### Bug Description

When looking in certain directions through layers of different colored stained glass, the layering effect that is supposed to happen does not.

https://github.com/CaffeineMC/sodium-fabric/assets/55008105/1e025de7-b058-4c10-9636-76774842b619

### Reproduction Steps

Just make a glass wall with different layer colors and look at them through different angles 

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/13506291/latest.log)

### Crash Report

[crash-2023-11-29_16.49.34-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/13506281/crash-2023-11-29_16.49.34-client.txt)

**Comment by TheUserCreated** [comment] 2023-11-29 23:18
Duplicate of #38 
A fix is being worked on.

**Closed as not planned** 2023-11-29 23:58 UTC
Labels: E-duplicate
