### ISSUE TITLE
Could you add DLSS and Ray tracing support 

### ISSUE THREAD

**Issue by Thunderrock424242** [jellysquid3/Sodium#2611] opened 2024-07-20 18:22 UTC
### Request Description

adding this would provide a HUGE boost of performance and I think its possible.

**Comment by jellysquid3** [comment] 2024-07-20 18:44
Duplicate of #796, #707, #2520, #1075, etc...

There is an open issue #2362 here about implementing render scaling.

**Closed as not planned by jellysquid3** 2024-07-20 18:44 UTC
Labels: E-duplicate, T-enhancement

**Comment by xboct02** [comment] 2024-10-04 09:52
The developer does not have the money to implement the algorithm of the leading company, but he can make his own compatible version.
