### ISSUE TITLE
big render problems

### ISSUE THREAD

**Issue by theSwarog** [jellysquid3/Sodium#475] opened 2021-01-10 06:45 UTC
![image](https://user-images.githubusercontent.com/57653995/104116324-90ea3f00-5328-11eb-9db1-800db29f9855.png)

**Comment by fsharpseven** [comment] 2021-01-10 21:39
Can you give more relevant information (e.g. your graphics card, version of sodium)?

**Comment by theSwarog** [comment] 2021-01-11 11:48
![image](https://user-images.githubusercontent.com/57653995/104178873-113d9c80-541c-11eb-892b-a975ce9b089e.png)
![image](https://user-images.githubusercontent.com/57653995/104178889-18fd4100-541c-11eb-98a1-0746db7e7f6e.png)
last version of Sodium

**Comment by fsharpseven** [comment] 2021-01-12 00:08
This is a known issue with some AMD GPUs (including the one you have). Currently, the best solution is to go into sodium's "Advanced Settings" tab and set your chunk renderer to Oneshot 3.0/2.0. I believe a fix for this being worked on, however it is largely at the mercy of drivers iirc.

**Comment by amnotbananaama** [comment] 2021-01-18 23:40
Closing as a duplicate of #24

**Closed as completed by amnotbananaama** 2021-01-18 23:40 UTC
Labels: T-bug, E-duplicate
