### ISSUE TITLE
IDK what this is ?

### ISSUE THREAD

**Issue by GoodDay360** [jellysquid3/Sodium#906] opened 2021-09-14 05:38 UTC
### Version information

Sodium 0.3.2 for Minecraft 1.17.1

### Expected Behavior

Fix it ?

### Actual Behavior

Weird thing in the sky

### Reproduction Steps

I don't know.
Just Fix it?

### Java version

Java 16

### CPU

Core i5-7200U 4-Core

### GPU

AMD R7M-440

### Additional information

![2021-09-14_12 30 49](https://user-images.githubusercontent.com/59399625/133200928-de86817d-22d2-4efe-a376-635c384f4650.png)

**Comment by jellysquid3** [comment] 2021-09-16 20:33
Duplicate of #870. The AMD drivers are not my favorite.

**Closed as completed by jellysquid3** 2021-09-16 20:33 UTC
