### ISSUE TITLE
The game crashes at Startup 

### ISSUE THREAD

**Issue by DiegoRG11** [jellysquid3/Sodium#2564] opened 2024-06-21 01:34 UTC
### Bug Description

When I start minecraft, sodium crashes with the following error.

A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'sodium'!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'sodium'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
	... 2 more
Caused by: java.lang.IllegalArgumentException: NTFS ADS separator (':') in file name is forbidden.
	at org.apache.commons.io.FilenameUtils.indexOfExtension(FilenameUtils.java:955)
	at org.apache.commons.io.FilenameUtils.removeExtension(FilenameUtils.java:1427)
	at me.jellysquid.mods.sodium.client.platform.windows.api.d3dkmt.D3DKMT.getOpenGlIcdName(D3DKMT.java:210)
	at me.jellysquid.mods.sodium.client.platform.windows.api.d3dkmt.D3DKMT$WDDMAdapterInfo.getOpenGlIcdName(D3DKMT.java:199)
	at me.jellysquid.mods.sodium.client.compatibility.checks.PreLaunchChecks.findIntelDriverMatchingBug899(PreLaunchChecks.java:83)
	at me.jellysquid.mods.sodium.client.compatibility.checks.PreLaunchChecks.onGameInit(PreLaunchChecks.java:24)
	at me.jellysquid.mods.sodium.client.SodiumPreLaunch.onPreLaunch(SodiumPreLaunch.java:12)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 3 more

### Reproduction Steps

I Start Mincraft through Modrinth App. with fabric loader 0.15.11, and only 2 mods, Fabric API 0.100.1+1.21 and Sodium MC1.21-0.5.7

### Log File

[latest.log](https://github.com/user-attachments/files/15921698/latest.log)

### Crash Report

no crash report generated

**Comment by jellysquid3** [comment] 2024-06-21 01:54
Duplicate of #2545.

**Closed as not planned by jellysquid3** 2024-06-21 01:54 UTC
Labels: E-duplicate
