### ISSUE TITLE
When Changing Render Distance Game Chrashes

### ISSUE THREAD

**Issue by bebingga** [jellysquid3/Sodium#1701] opened 2023-04-20 19:29 UTC
### Version information

fabric-api-0.66.0+1.19.2.jar

### Reproduction Steps

Whenever I go to change my render distance with sodium installed and click apply my game crashes

### Crash Report file

[crash report.txt](https://github.com/CaffeineMC/sodium-fabric/files/11289761/crash.report.txt)

### Additional information

The game does not crash if I change the render distance in the main menu

**Comment by Lolothepro** [comment] 2023-04-22 09:18
use Minecraft 1.19.4

**Comment by pajicadvance** [comment] 2023-05-11 17:58
Seems to be a duplicate of #1486.

**Closed as not planned by pajicadvance** 2023-05-11 17:58 UTC
Labels: E-duplicate, A-drivers, T-crash
