### ISSUE TITLE
Add option to adjust chunk update/render speed similar to OptiFine

### ISSUE THREAD

**Issue by TrunkLock** [jellysquid3/Sodium#818] opened 2021-08-05 00:28 UTC
I am using the mod on a Intel i3 laptop, which I assume to be a bad one to use but got the game to work sort of stable with a handful of other performance mods. The laptop cannot catch up with the chunk update causing stutters. It takes a few minutes to stabilize the framerate.

Perhaps a similar option to OptiFine's chunks updated at a time or bring back the option to choose a GPU setting(?), one with "multidraw 3.0" among those.

Thank you, very much. I might have not described the situation properly... Cheers.

**Comment by Altirix** [comment] 2021-08-05 16:31
sodium is a mod focused on the rendering engine. chunk loading you will want to look at some other mods that improve chunk loading itself or the lighting engine. like overworld2, starlight, phosphor, tictacs (caution) etc

**Comment by TrunkLock** [comment] 2021-08-06 02:40
I see. Thank you very much.

**Comment by LucilleTea** [comment] 2021-08-16 06:44
i'm going to close this as a duplicate of #836 since it's a bit clearer about the specific request

**Closed as completed by LucilleTea** 2021-08-16 06:44 UTC
Labels: E-duplicate
