### ISSUE TITLE
Weird crash in multiplayer

### ISSUE THREAD

**Issue by Taiyou06** [jellysquid3/Sodium#1016] opened 2021-12-02 15:34 UTC
### Version information

mc1.18-0.4.0-alpha5+build.9

### Reproduction Steps

1.Join a 1.18 server
2.Load a lot of chunks at once
2.1 or just wait few minutes

### Crash Report file

[crash-2021-12-02_18.29.27-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/7643143/crash-2021-12-02_18.29.27-client.txt)

**Comment by JonathanTippy** [comment] 2021-12-03 21:02
i have the same issue.

**Comment by TechnicallyCoded** [comment] 2021-12-06 23:56
I've experienced the same issue too

**Comment by LuanSeverinodoSantos** [comment] 2021-12-07 12:37
Também acontece a mesma coisa na 1.16.5

**Comment by Texbio** [comment] 2021-12-16 16:12
why is this closed when the previous thread is closed

**Comment by Texbio** [comment] 2021-12-16 16:13
I am having the same "Tried to mark light data as ready" issue too

**Comment by Millsonhub** [comment] 2022-01-15 13:50
Same issue, please fix in the next version

**Comment by silversquirl** [comment] 2022-02-01 17:59
I can reproduce this easily by going back and forth between two end gateways rapidly. Happens in singleplayer as well.

**Comment by cardanawandra** [comment] 2022-02-25 07:55
it's only happen with plugin "fartherviewdistance" wich is faking the server's render distance. completely natural in vanilla

**Comment by cootshk** [comment] 2022-02-26 19:51
Same issue
Crash report: https://crashy.net/WjYJQrDZB3E2QCus955w

**Comment by jellysquid3** [comment] 2022-03-03 18:20
Does this issue still occur with [version 0.4.1 for Minecraft 1.18.2](https://github.com/CaffeineMC/sodium-fabric/releases/tag/mc1.18.2-0.4.1)?

**Comment by Pectacular** [comment] 2022-03-07 15:43
> Does this issue still occur with [version 0.4.1 for Minecraft 1.18.2](https://github.com/CaffeineMC/sodium-fabric/releases/tag/mc1.18.2-0.4.1)?

For me it still does.

**Comment by mfn003** [comment] 2022-03-29 18:28
Still happening with me as well.

**Comment by Rimapus** [comment] 2022-04-14 18:55
Any solution for this problem ? 
Its very annoying
😐

**Comment by ZeroCaty** [comment] 2022-04-20 04:59
The bug occurs in single player.
I can not accurately determine the sequence of actions leading to the crash.
It seems to have something to do with the teleportation of the player at the time of the light update in the chunks.

**Comment by Rimapus** [comment] 2022-04-20 06:36
> The bug occurs in single player. I can not accurately determine the sequence of actions leading to the crash. It seems to have something to do with the teleportation of the player at the time of the light update in the chunks.

Oh... for me it happen also in multiplayer

**Comment by LaysDragon** [comment] 2022-05-03 05:56
yeah...I have playing with friends with a 1.18.1 dungeon pve map, it's always crash my game while I dead. It indeed will teleport player after death. So I guess the problem is really related to teleporting. :/
I'm also using iris with shader pack.

so do we have any workaround here?

**Comment by ChildishGiant** [comment] 2022-06-14 21:58
[crash-2022-06-14_22.53.35-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/8904163/crash-2022-06-14_22.53.35-client.txt)

**Comment by Tomasz4414** [comment] 2022-06-23 11:12
Still having this issue in 1.19, please fix

**Comment by magnus-ISU** [comment] 2022-06-24 22:42
Alright, I'll say what I said on my own issue here.

I changed the code that throws the illegal state exception into a print and so far, it hasn't caused issues. So until an actual fix is pushed by someone who knows how sodium works, this might be useful to some people.

[Here is a repository where I uploaded the code](https://github.com/magnus-ISU/sodium-fabric-hacky-fix-please-dont-use). I don't know the structure of sodium or the proper way I should have done this, checkout the master branch if you want to compile it yourself.
[Here is the diff](https://github.com/magnus-ISU/sodium-fabric-hacky-fix-please-dont-use/commit/4bdb6c9e752c082a5f997c78569f864d13c812c6)
[Here is a repository where the binary is hosted](https://github.com/magnus-ISU/clientside-mods/); here [is the jar you can use](https://github.com/magnus-ISU/clientside-mods/blob/master/mods/sodium-fabric-mc1.19-0.4.2%2Brev.f039f75-dirty.jar).

I hope this is acceptable - I understand that you don't want people posting binaries of forks in the issue tracker or something; on the other hand, please fix an apparently 6-month-old crash bug with an issue title and description that say nothing about the crash itself.

**Comment by cardanawandra** [comment] 2022-06-26 20:17
thats just works... like charm... thx

**Comment by wifi-left** [comment] 2022-08-11 02:18
I tried to make a mod using mixin and modified the code to refresh the light source
Replace the original crashing code with console output
This problem seems to be fixed on my computer.
[Here is the modrinth link for the mod](https://modrinth.com/mod/sodium-crash-fix)

**Comment by Altener** [comment] 2022-08-16 09:11
I can consistently reproduce this crash using a create contraption that moves me at extremely high speeds (literally a stick with a seat attached to one end and a mechanical bearing spinning it from the other). No matter what options i change it always happens

**Comment by nyaNezt** [comment] 2022-08-17 00:01
It happened to me when I set up 2 command blocks with buttons on them which teleport a player facing the button to the other command block. Holding right-click which means pushing the buttons constantly crashed the game with the same error

**Comment by Tom3k44** [comment] 2022-08-25 04:38
Still not fixed as in 1.19.2

**Comment by xparadoxical** [comment] 2022-09-12 00:32
10 months and counting 🕙
Thank you @wifi-left for your mod, it fixes this for me

**Comment by xparadoxical** [comment] 2022-09-12 01:32
Updating from 0.4.2 to 0.4.4 resolved this for me

**Comment by jellysquid3** [comment] 2023-07-22 02:25
This shouldn't happen any longer in recent versions of Sodium...

**Closed as completed by jellysquid3** 2023-07-22 02:25 UTC
Labels: T-crash, S-confirmed

**Comment by iKARY19** [comment] 2024-06-22 13:56
same issue 
crash : 
[crash-2024-06-22_15.55.46-client.txt](https://github.com/user-attachments/files/15936952/crash-2024-06-22_15.55.46-client.txt)

**Comment by Poopooracoocoo** [comment] 2024-06-22 14:15
@iKARY19 you've just got an old version of Indium that was not compatible with Fabric API 0.89 and above. You need to update Indium. You'll also need to update Sodium and any other dependent mods such as Sodium Extra and Iris

**Comment by iKARY19** [comment] 2024-06-22 16:38
thanks i will try

**Comment by iKARY19** [comment] 2024-06-22 16:51
@Poopooracoocoo its doesent work its not compatible to other my mods

**Comment by iKARY19** [comment] 2024-06-22 16:52
can u send me the versions on the mods ? i will try

**Comment by jellysquid3** [comment] 2024-06-22 16:53
This is not a support forum, and your issue has nothing to do with what's described above. Use [the Discord server](https://caffeinemc.net/discord) if you want help from the community.
