### ISSUE TITLE
Changing fullscreen resolution

### ISSUE THREAD

**Issue by David-W-Farrell** [jellysquid3/Sodium#386] opened 2020-11-09 07:36 UTC
Vanilla minecraft allows you to change the fullscreen resolution, this helps in getting fps up. However, it is accessed via the video settings in vanilla, and does not appear as an option. It also does not seem to work when changed in the options file in the .minecraft folder

I would like the option of changing full screen resolution added as it exists in the vanilla game

**Comment by amnotbananaama** [comment] 2020-11-09 07:43
Duplicate of #46

**Closed as completed by amnotbananaama** 2020-11-09 07:43 UTC
Labels: E-duplicate, T-enhancement
