### ISSUE TITLE
Side / bottom faces of ice do not render behind water, and reverse

### ISSUE THREAD

**Issue by VisMGA** [jellysquid3/Sodium#83] opened 2020-07-14 05:20 UTC
### Expected Behavior
Ice can be seen through water, water can be seen through the sides of submerged ice.

### Actual Behavior
Ice behind water is invisible. 

### Attachments
![2020-07-13_22 16 30](https://user-images.githubusercontent.com/35517046/87386985-9bcd3e00-c556-11ea-828f-d1df071eca3e.png)
![2020-07-13_22 16 35](https://user-images.githubusercontent.com/35517046/87386989-a12a8880-c556-11ea-933c-1dce63a7e1a3.png)
![2020-07-13_21 53 36](https://user-images.githubusercontent.com/35517046/87387071-ca4b1900-c556-11ea-994a-130a125c6cfd.png)

### Reproduction Steps
look at the side or bottom of ice through water
place ice at the surface of water and look through the ice at the water

### System Information
- Java Version: 1.8.0_
- CPU: 8x Intel Core i7-4770k @ 3.50Gz
- GPU: Nvidia GeForce GTX 660/PCIe/SSE2

**Comment by jellysquid3** [comment] 2020-07-14 19:08
Duplicate of #38.

**Closed as completed by jellysquid3** 2020-07-14 19:08 UTC
Labels: T-bug, E-duplicate
