### ISSUE TITLE
Certain Animated Resource-Pack textures are broken.

### ISSUE THREAD

**Issue by melechdaviid** [jellysquid3/Sodium#1263] opened 2022-04-08 23:44 UTC
### Version information

sodium-fabric-mc1.18.2-0.4.1+build.15

### Expected Behavior

The leaves should be waving, and the water should be A: clear, and B: wavy.

### Actual Behavior

The above does not happen.

### Reproduction Steps

1: Install a VanillaTweaks Resource Pack with the Wavy Leaves and Wavy Water components (Link to the site: https://vanillatweaks.net/picker/resource-packs/), and select it in the Resource Packs menu
2: Load up a world
3: Find a tree or river
You shall find the bug. And maybe a nest of bugs, depending on the biome. 

I have already hypothesised that this is an issue with Sodium replacing (or nearly replacing) the vanilla rendering engine (or whatever the name is), meaning that the Resource Packs can't find the part or parts they use to animate the textures. 

### Java version

Java 16

### CPU

Intel Core i7-9750H

### GPU

Nvidia GEForce RTX 2060

### Additional information

![2022-04-08_18 34 37](https://user-images.githubusercontent.com/103229195/162546961-3d7e5439-834a-404a-8b6f-1c8cb70f13c3.png)
![2022-04-08_18 34 32](https://user-images.githubusercontent.com/103229195/162546966-57aaa5e9-aa9d-4ee4-8adc-206c266bf57e.png)

**Comment by violet-sh** [comment] 2022-04-09 20:10
This seems to be a duplicate of #754. Sodium does not support core shaders which VanillaTweaks uses to animate textures. See [this comment](https://github.com/CaffeineMC/sodium-fabric/issues/754#issuecomment-879172873) specifcally.

**Comment by melechdaviid** [comment] 2022-04-11 01:09
It is. I'm using Sildur's Fantastic Shaders, I believe.

**Comment by melechdaviid** [comment] 2022-04-11 01:10
And the (non-default) enchantment animation is broken, as that's an animated resource pack texture as well.

**Comment by melechdaviid** [comment] 2022-04-11 01:25
This is coming from a non-coder, but could there be a way to trick the resource packs to use Sodium instead?

**Comment by jellysquid3** [comment] 2022-04-23 02:52
Unfortunately, no, there isn't a way to make the resource packs work. The issue is that they are trying to modify vanilla shader code, which we completely replace with a different system entirely. Not only are these systems separate, the way they do things are very different, which would mean that Fabulous resource packs would need to be rewritten entirely.

**Closed as completed by jellysquid3** 2022-04-23 02:52 UTC
Labels: T-bug, E-duplicate
