### ISSUE TITLE
sodium crash

### ISSUE THREAD

**Issue by t4eitachi** [jellysquid3/Sodium#2220] opened 2023-12-25 13:34 UTC
### Bug Description

i cant open minecraft when ever i put sodium in mod folder it crashes 

### Reproduction Steps

![image](https://github.com/CaffeineMC/sodium-fabric/assets/154814067/29520fb2-94ef-4b53-a6be-10f59089aaee)

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/13766194/latest.log)

### Crash Report

[crash-2023-12-25_10.36.59-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/13766195/crash-2023-12-25_10.36.59-client.txt)

**Comment by pajicadvance** [comment] 2023-12-25 13:49
Duplicate of #899 , download and install the driver linked in [this comment](https://github.com/CaffeineMC/sodium-fabric/issues/899#issuecomment-1025203807) to fix the issue.

**Closed as not planned by pajicadvance** 2023-12-25 13:49 UTC
Labels: E-duplicate
