### ISSUE TITLE
Breaking any blocks would cause it to render very dark until relog

### ISSUE THREAD

**Issue by CalXee** [jellysquid3/Sodium#327] opened 2020-09-30 18:31 UTC
This happens in combination with PhilPro's Lighting Fixes mod.

This bug causes lighting to never update after joining a world or server. For example if it's dark at night, and you place a torch, the torch won't light up its surroundings until you relog. Similarly, after you relog, breaking the torch causes light to still be there.
Obviously, if a block is covered by other blocks, it'll be rendered very dark since no light is touching it. Normally, when you remove the block the light would update and cause the exposed block to be bright. That updating process seems to be absent with this mod.

### Expected Behavior
Blocks render bright as it's exposed to skylight

### Actual Behavior
Breaking a block that uncovers another block causes it to be extremely dark.

### Reproduction Steps
1. Go into any world
2. Break a block
Results: There is a very dark shadow

![2020-09-30_14 30 42](https://user-images.githubusercontent.com/68349758/94725343-98617b80-0329-11eb-8018-d06e62cf75fe.png)
![2020-10-04_15 41 51](https://user-images.githubusercontent.com/68349758/95025531-623d3800-0658-11eb-820e-f37926a8f378.png)
![2020-10-04_15 41 59](https://user-images.githubusercontent.com/68349758/95025532-623d3800-0658-11eb-9105-7fa84bddb363.png)

**Comment by yezhiyi9670** [comment] 2020-10-03 13:06
How does it happen? I cannot reproduce it (maybe because of phosphor).

**Comment by CalXee** [comment] 2020-10-04 19:40
I do not use phosphor.
I also noticed that this bug is caused by lighting not updating ever after joining a world or server. For example if it's dark at night, and you place a torch, the torch won't light up its surroundings until you relog. Similarly, after you relog, breaking the torch causes light to still be there.

**Comment by CalXee** [comment] 2020-12-15 02:48
This has been fixed on Phosphor's end in https://github.com/jellysquid3/phosphor-fabric/pull/26. Should probably close this.

**Comment by LucilleTea** [comment] 2021-03-01 11:05
If this bug report was referring to lighting-fixes as it says, it seems like this was addressed there before it was even reported here - see https://github.com/PhiPro95/mc-fixes/issues/1
In brief testing I can't reproduce the issue (using Sodium's next branch), so closing this now.

**Closed as completed by LucilleTea** 2021-03-01 11:05 UTC
Labels: T-bug, A-mods
