### ISSUE TITLE
crash when run

### ISSUE THREAD

**Issue by z3roco01** [jellysquid3/Sodium#540] opened 2021-02-21 04:04 UTC
### Reproduction Steps
1.put [fabric api 0.30.3+1.16](https://www.curseforge.com/minecraft/mc-mods/fabric-api/) in mods
2.put [sodium 0.10](https://www.curseforge.com/minecraft/mc-mods/sodium/) in mods
3.put [immersive portals 0.65](https://www.curseforge.com/minecraft/mc-mods/immersive-portals-mod) in mods
4.run [fabric loader 0.11.1 1.16.5](https://fabricmc.net/use/)

### Crash Report File
https://gist.github.com/Unknown-User2/66f60939b8bca94d61e20c12288b9b6c

**Comment by LucilleTea** [comment] 2021-02-21 04:05
Duplicate of #15 
Sodium is currently incompatible with Immersive Portals.

**Closed as completed by LucilleTea** 2021-02-21 04:05 UTC
Labels: E-duplicate, T-crash
