### ISSUE TITLE
Redstone lamp in 3D texture pack turns black on sodium

### ISSUE THREAD

**Issue by Soggy-Pancake** [jellysquid3/Sodium#896] opened 2021-09-11 22:32 UTC
### Version information

Sodium 0.3.2

### Expected Behavior

Using optifine in this screenshot
![2021-09-11_14 56 02](https://user-images.githubusercontent.com/54160598/132962753-f08de6eb-519b-4edb-b6d3-b2007e83e2b2.png)

### Actual Behavior

![2021-09-11_14 25 24](https://user-images.githubusercontent.com/54160598/132962763-aba894f7-65c8-41d4-ac7d-5b4f56ffabbc.png)

### Reproduction Steps

Turn on a redstone lamp with Faithful 3D active.

### Java version

Java 16

### CPU

Ryzen 5 1600 af

### GPU

AMR Radeon RX 590

### Additional information

Using Faithful 3D texture pack (https://www.faithful3d.team)
The lamp texture is indented where it is meant to glow. Only the on state is broken though.
Models were checked and seem fine
Culling was disabled and it still turned black

**Comment by MeeniMc** [comment] 2021-09-12 04:38
This is probably a duplicate of #226

This is currently resolved in dev versions, so it's only a matter of time before it hits a release :)

**Comment by jellysquid3** [comment] 2021-09-13 00:01
Closing as a duplicate of #226... But is currently fixed with the in-development versions of 0.4.

**Closed as completed by jellysquid3** 2021-09-13 00:01 UTC
