### ISSUE TITLE
Mod forces monitor to run at 60Hz

### ISSUE THREAD

**Issue by MrRetr0** [jellysquid3/Sodium#1318] opened 2022-05-28 19:49 UTC
### Version information

mc1.18.2-0.4.1+build.15

### Expected Behavior

I expected that my FPS would simply be boosted.

### Actual Behavior

FPS got boosted, but my monitor was forced to 60Hz.

### Reproduction Steps

1. Download Sodium
2. Place inside "mods" folder
3. Run game
4. Check monitor Hz

### Java version

Java 17.0.1

### CPU

AMD Ryzen 5 3600

### GPU

Nvidia RTX 2060

**Comment by Kutaren-Kraterboy** [comment] 2022-06-01 21:57
There is also no way to change the fullscreen resolution or fps with the mod enabled

**Comment by MeeniMc** [comment] 2022-06-02 03:36
You can change the resolution with the 'shift-p' keybind to call-in the default video config screen. 

You need to unclick 'vsync' and/or the 'max fps' setting in the Sodium options to have more than 60 fps.

**Comment by Kutaren-Kraterboy** [comment] 2022-06-02 13:31
Vsync wasnt the problem. Id still get 59-60fps with or without vsync, and the frame limiter. Also i dont recall the shift-p being mentioned in the faq or anywhere on the page. Someone literally made a mod to do what the shift-p keybind does. 

The problem is i was tryna run Minecraft at 1440p resolution fullscreen, which typically with optifine id reach my 160  (moniter RR) or higher. Thats quite a large difference. For 1.5x more pixels i get over 4 times less of the framerate. 
On my 1080p screen i get over 250fps fullscreen. 

If anyone else is having this issue, i think take into consideration how many pixels youre trying to run. If youre not getting any better fps bc youre on a 4k panel, running MC at native 4k, well theres your problem!

**Comment by silversquirl** [comment] 2022-09-15 10:35
Duplicate of #1380

**Closed as completed by silversquirl** 2022-09-15 10:35 UTC
Labels: T-bug, E-duplicate
