### ISSUE TITLE
Stained glass not rendered correctly through another stained glass (or glass pane)

### ISSUE THREAD

**Issue by i0xHeX** [jellysquid3/Sodium#1371] opened 2022-07-03 19:13 UTC
### Version information

mc1.19-0.4.2+build.16

### Expected Behavior

![2022-07-03_21 48 25](https://user-images.githubusercontent.com/33582973/177053931-a6d0fa4e-1e51-4d70-89bf-0a5163e7a99f.png)

### Actual Behavior

![2022-07-03_21 51 20](https://user-images.githubusercontent.com/33582973/177053940-2f60160e-af07-4d2e-a103-fa4243f852d3.png)

Also if you look through stained glass pane with same conditions as on the screen (facing for example) - stained glass will not be rendered at all:
![2022-07-03_21 51 51](https://user-images.githubusercontent.com/33582973/177053969-95652d0d-48e6-44df-9d86-b64fb80ffccb.png)

### Reproduction Steps

1. Join the world
2. Build stained glass walls (color does not matter)
3. Look through it

![2022-07-03_22 05 38](https://user-images.githubusercontent.com/33582973/177053995-754364ff-4fee-4266-843a-e9410c422764.png)

### Java version

JDK 17.0.3.1

### CPU

Intel Core i3-4005U

### GPU

Intel HD Graphics 4400

**Comment by Anslean** [comment] 2022-07-10 00:10
I don't have time to post a formal issue yet, but I think this might be related to a water rendering bug I found today. A single column of falling water produces the issue. Looking at a downward angle causes the far face of the lower block to render improperly. I'll post a formal issue later. But if they happen to be the same root cause, this may help in isolating it. And water rendering might be considered higher priority than stained glass anyway 🤷, so if it is the same maybe this gets a boost lol. The main reason I suspect it's the same issue is because it's back-face culling (and similar rendering processes) with regards to transparent block types.

**Comment by magneticflux-** [comment] 2022-07-10 00:55
This and @Anslean's water issue are both duplicates: https://github.com/CaffeineMC/sodium-fabric/issues/38

**Comment by burgerindividual** [comment] 2022-07-25 23:19
Marking as duplicate of #38

**Closed as not planned by burgerindividual** 2022-07-25 23:19 UTC
Labels: E-duplicate
