### ISSUE TITLE
Sodium freezes desktop completely and causes graphical issues in minecraft

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#1831] opened 2023-06-21 13:44 UTC
### Version information

1.18.2-1.20.1

### Expected Behavior

1. Install sodium on PrismLauncher
2. Start minecraft
3. Open/create a world
4. Game functions properly

### Actual Behavior

My entire desktop freezes and every now and then stutters forward. minecraft has several graphical issues

### Reproduction Steps

1. Install sodium on PrismLauncher
2. Start minecraft
3. Open/create a world
4. Once loaded my entire desktop freezes and minecraft has several graphical issues

### Java version

Java 17

### CPU

Ryzen 5 2600x

### GPU

Vega 56

### Additional information

I have a rather unique environment running minecraft in a bubblewrapped container as to sandbox Minecraft as it is a proprietary game. This used to be fine, and I was able to play Minecraft 1.9.x a few months ago. Recently I have done a reinstall of my entire system (void linux) and now I wanted to try out 1.20.x, but was not able to play Minecraft with Sodium installed at all.
[bug.webm](https://github.com/CaffeineMC/sodium-fabric/assets/136582106/c07a744f-4f9a-4972-b798-0cbdb54632ed)
Oddly enough, the graphical glitches and freezing in this recording are not the same as what was happening on my screen, but they are similar.

**Comment by Felix14-v2** [comment] 2023-06-21 14:25
Choose the Angle renderer in the instance settings to launch Minecart with Sodium. GL4ES does not contain the necessary functions for Sodium.
![Screenshot_20230621-172527](https://github.com/CaffeineMC/sodium-fabric/assets/75726196/c411b4e6-db76-4c3e-ab60-f917211428fa)
![Screenshot_20230621-172523](https://github.com/CaffeineMC/sodium-fabric/assets/75726196/dd9293b3-8c7d-43ca-8d91-bb83468cc08c)

**Comment by ghost** [comment] 2023-06-22 00:10
@Felix14-v2 I do not believe this can be done on PrismLauncher

**Comment by Felix14-v2** [comment] 2023-06-22 07:06
> @Felix14-v2 I do not believe this can be done on PrismLauncher

Omg, my deepest apologies... I read "PojavLauncher" for some reason, sorry

**Comment by pajicadvance** [comment] 2023-06-23 16:00
Can you try disabling the option "Use Persistent Mapping" in Video Settings -> Advanced?

**Comment by ghost** [comment] 2023-06-23 19:09
Disabling "Use Persistent Mapping" does not impact this issue. Maybe it is just a driver issue?

**Comment by pajicadvance** [comment] 2023-06-26 09:07
I'm not sure. You should upload your client log, in any case.

**Comment by ghost** [comment] 2023-06-30 15:40
heres the log
[minecraft.log](https://github.com/CaffeineMC/sodium-fabric/files/11918162/minecraft.log)

**Comment by luka-devnull** [comment] 2023-07-09 03:54
having similar issues with similar hardware since 1.19 i think? it wasn't present probably about a year ago and was running 1.19 then. also remember running it in 1.18 days but it worked then too and don't feel like testing that far back. it's present in all versions since 1.19 with only sodium and (quilted) fabric api loaded, or any number of other client mods.

Launcher: PolyMC
Minecraft Version: 1.20.1 (currently), 1.19 (tested), 1.19.2 (tested)
Sodium Version: 0.4.10+build.27 (currently), 0.4.2+build.16 (tested), also tested another one i forgor
JVM: OpenJDK 17, Oracle JDK 19 (tested)
CPU: AMD Threadripper Pro 3945WX, Intel Xeon E5-2670 v2 (historically), Intel Core i7-10750H (tested)
GPU: AMD Radeon Instinct MI25 (Vega 64-like), AMD Radeon RX 580 (historically), NVidia Quadro T1000 (tested)
Loader: Quilt 0.19.2 with QFAPI 7.0.5 and 2.0.0 (tested on 1.19), Fabric 0.14.21 with FAPI 0.85.0 (tested)
OS: Arch Linux 6.4.1-arch2-1, Windows 11 22H2 (tested)

Description: extremely slow whenever you look up, and some various graphical issues as it bounces between 0 fps for a few seconds and 120fps for a few more before restarting the cycle. totally locks up the desktop while it's frozen. if you look down at the ground, the fps stabilizes enough for you to close the game and disable sodium x.x

seems to affect AMD GPUs? works fine on the laptop, which has a NVidia GPU, but it's also Windows so maybe that also has something to do with it....

if need be, i have access to a intel/nvidia system running arch and can test it there too, but i expect it'll work there lol

**Comment by ghost** [comment] 2023-07-17 09:45
@luka-devnull did you manage to find anything? I sadly only have AMD GPUs in my systems.

**Comment by wingedseahorse** [comment] 2023-07-19 05:51
I've been experiencing the same issue with Sodium starting early June. This bug appeared 'overnight' and renders the game unplayable with frequent 0 fps drops and graphical glitches (large geometric shapes on the horizon displaying various block and item textures). 

The timing of my issue and OPs report matches up, I'm also on Arch Linux so have reason to believe the cause was some kind of system/driver update but I don't have any know-how to identify it. I was hoping it would have resolved itself in the month I've been away but post system update the behaviour persists exactly as before. Frames weren't so bad in my creative flatworld so I was able to fly around and get right up in the graphics glitch lol [imgur](https://imgur.com/a/oHBje0n )

Launcher: Multi MC
Versions: 1.19.2, 1.20.1, 1.18.2 (fabric, tried to launch an old quilt instance and the save failed to launch all together)
Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
CPU: 16x AMD Ryzen 7 2700X Eight-Core Processor

**Comment by jellysquid3** [comment] 2023-07-20 00:33
This issue is likely a duplicate of #1792... It seems like the graphics stack for the Vega 56/64 (along the professional cards of that series) are just completely broken when used with Sodium.

**Closed as not planned by jellysquid3** 2023-07-20 00:33 UTC
Labels: T-bug, A-drivers

**Comment by ZIDI228** [comment] 2023-07-25 15:58
фикс фризов при прогрузке чанков поставьте в-синк в положение включено и вручную частоту кадров на 60, должно помочь. аналогично если 144 герц монитор то в-синк и 144 кадров вручную.

fix friezes when loading chunks, set v-sync to on and manually set the frame rate to 60, it should help. similarly, if the monitor is 144 hertz, then v-sync and 144 frames manually.

修复加载块时的条纹，将垂直同步设置为打开并手动将帧速率设置为 60，这应该会有所帮助。 同样，如果显示器为 144 赫兹，则手动进行垂直同步和 144 帧。

perbaiki friezes saat memuat potongan, setel v-sync ke aktif dan atur frame rate secara manual ke 60, itu akan membantu. sama halnya, jika monitor 144 hertz, maka v-sync dan 144 frame secara manual.

corrigez les frises lors du chargement de morceaux, activez v-sync et réglez manuellement la fréquence d'images sur 60, cela devrait aider. de même, si le moniteur est de 144 hertz, puis v-sync et 144 images manuellement.

corrija los frisos al cargar fragmentos, active v-sync y configure manualmente la velocidad de fotogramas en 60, debería ayudar. del mismo modo, si el monitor es de 144 hercios, entonces v-sync y 144 fotogramas manualmente.

**Comment by Felix14-v2** [comment] 2023-07-25 17:09
@ZIDI228 this won't fix anything. Also, wrong place for such message.
