### ISSUE TITLE
[1.20.1] Crash with: [23:22:02] [Render thread/ERROR]: Error executing task on Client 

### ISSUE THREAD

**Issue by SkiTTbicepS** [jellysquid3/Sodium#1947] opened 2023-08-05 21:41 UTC
### Bug Description

The application launches, but crashes when loading/connecting to a world.

Was not a problem with Sodium 0.4.10. 

Short desc:
[23:33:52] [Render thread/ERROR]: Error executing task on Client
java.lang.NullPointerException: Cannot invoke "me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.scheduleRebuild(int, int, int, boolean)" because "this.renderSectionManager" is null

Any ideas what could cause this issue? Maybe a mod?

Thanks for your help!! :) 

Other than this it is an absolutely AMAZING MOD!! 👍 

### Reproduction Steps

Full mod list is present in latest.log.

Other than mods and resource packs I have nothing else. Surely, I turned off resource packs, and tried again.
But still crashes.

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12268260/latest.log)

### Crash Report

[crash-2023-08-05_23.33.55-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12268269/crash-2023-08-05_23.33.55-client.txt)

**Comment by pajicadvance** [comment] 2023-08-05 23:25
Try disabling Better Fps - Render Distance and Cull Leaves.

**Comment by SkiTTbicepS** [comment] 2023-08-05 23:43
I am currently working on getting out every performance mod from my
modpack. Will try it and let you know. :)
Thank you.

**Comment by SkiTTbicepS** [comment] 2023-08-06 00:36
I got it working fine, but..
The performance is awful.. made a completely clean modpack, with only using
sodium, lithium, IRIS.
Started the game aaand. 35 fps where I had 110 before. Started adding other
perf mods, I got 45 fps max. So I just went back to the older sodium and
other fps mods.

**Comment by Fnige** [comment] 2023-08-06 00:41
Are you able to send the log file?

**Comment by pajicadvance** [comment] 2023-08-06 00:46
> Started the game aaand. 35 fps where I had 110 before. Started adding other
perf mods, I got 45 fps max. So I just went back to the older sodium and
other fps mods.

That's definitely not intended. If you want to, you can join our [Discord server](https://caffeinemc.net/discord) and create a thread on our support forum so we can diagnose the unexpected performance loss - it would be more convenient than sending back and forth messages here on GitHub. I am closing this report as the original issue was caused by an external mod.

**Closed as completed by pajicadvance** 2023-08-06 00:46 UTC
Labels: E-external, A-mods, T-crash

**Comment by SkiTTbicepS** [comment] 2023-08-06 01:01
Yes, here is the latest .log file. I got it from the "recycle bin" :D


ne 6. 8. 2023 o 2:41 Fnige ***@***.***> napísal(a):

**Comment by egormanga** [comment] 2026-01-31 16:18
Same issue on Fabric 1.21.8 with Sodium 0.7.3.
