### ISSUE TITLE
Lava And Water not displaying correctly at different angles

### ISSUE THREAD

**Issue by Gasrim** [jellysquid3/Sodium#217] opened 2020-07-31 10:20 UTC
Should be "smooth" flowing

Graphical Glitch  
-----Recreation-----
1. Make water or lava flow

![2020-07-31_18 09 59](https://user-images.githubusercontent.com/69037960/89026015-8596ee80-d35a-11ea-9752-dee23f8b044c.png)

![2020-07-31_18 16 23](https://user-images.githubusercontent.com/69037960/89026032-89c30c00-d35a-11ea-9e6b-9afdc2af8467.png)

- Java Version: 1.8.0_51
- CPU: Intel i7-2600 @3.40GHz
- GPU: Nvidia Geforce 770 GTX

**Comment by Kroppeb** [comment] 2020-07-31 11:16
Duplicate 9f #171, this will be fixed in the next version :)

**Comment by FishyFissh** [comment] 2020-08-17 19:01
> Duplicate 9f #171, this will be fixed in the next version :)

so then this can be closed?

**Comment by amnotbananaama** [comment] 2020-08-27 04:29
Closing as a duplicate of the aforementioned issue

**Closed as completed by amnotbananaama** 2020-08-27 04:29 UTC
Labels: T-bug, E-duplicate
