### ISSUE TITLE
light emitting blocks renders dark when using custom models

### ISSUE THREAD

**Issue by boshyXD32** [jellysquid3/Sodium#1217] opened 2022-03-06 00:12 UTC
### Version information

mc1.16.5-0.2.0+build4,mc1.17.1-0.3.4+build13,mc1.18.1-0.4.0-alpha6+build14,mc1.18.2-0.4.1+build15

### Expected Behavior

the block should render fully bright when placed on the ground like this
![2022-03-05_18 05 55](https://user-images.githubusercontent.com/84370921/156903766-35c200fd-0096-4efa-a1ea-7c98ed6573ac.png)

### Actual Behavior

it just renders black
![2022-03-05_16 25 28](https://user-images.githubusercontent.com/84370921/156903773-04778889-d280-4cb5-9bb5-390ab8c47174.png)

### Reproduction Steps

1: take any resource pack that features 3D models for light emitting blocks
2: activate it
3: place those blocks 

best example redstone lamp on the 3D default pack

### Java version

java 8,java 16

### CPU

intel celeron g1820

### GPU

Nvidia GT 730

### Additional information

this bug seems to affect every sodium version i only reffer to releases made for major versions such as 1.16.5 or 1.18.1. in order to not extend the list too much. if possible please fix it for all of those

**Comment by MeeniMc** [comment] 2022-03-14 05:28
Possibly a duplicate of issue #226

**Comment by pajicadvance** [comment] 2023-05-10 18:03
As said above, duplicate of #226, and fixed in a later Sodium version.

**Closed as completed by pajicadvance** 2023-05-10 18:03 UTC
Labels: T-bug, S-fixed
