### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Dootama** [jellysquid3/Sodium#1958] opened 2023-08-07 00:50 UTC
### Bug Description

game crashing
all mods are up to date

![image](https://github.com/CaffeineMC/sodium-fabric/assets/138728098/b96c8429-4ecc-4931-88ba-b0ac79d597c5)

![Screenshot (2)](https://github.com/CaffeineMC/sodium-fabric/assets/138728098/b71282a8-b9d8-48fc-8e0c-e064337962f4)
Yeah ik, I have a lot of mods lmao

### Reproduction Steps

Idk it happens randomly as far as I can tell, but it did occur while playing in someone's world with the Essentials Mod.

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12271022/latest.log)

### Crash Report

The game crashed whilst rendering item
Error: java.lang.IllegalArgumentException: The class com.anthonyhilyard.iceberg.renderer.VertexCollector$1 does not implement interface VertexBufferWriter, which is required for compatibility with Sodium (see: https://github.com/CaffeineMC/sodium-fabric/issues/1620)

-1

[crash-2023-08-06_20.40.58-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12271021/crash-2023-08-06_20.40.58-client.txt)

**Comment by pajicadvance** [comment] 2023-08-07 01:00
Duplicate of #1954

**Closed as not planned by pajicadvance** 2023-08-07 01:00 UTC
Labels: E-duplicate
