### ISSUE TITLE
Please make this mod for 1.15.2 too

### ISSUE THREAD

**Issue by Bobrokus** [jellysquid3/Sodium#374] opened 2020-11-02 09:46 UTC
I'm have server with my friends on 1.15.2 and I have low-end pc, so my fps is around 40 and 50. I wish I could have more, It's really hard to play with that FPS. Thx!

**Comment by FlashyReese** [comment] 2020-11-02 09:54
There is an 1.15 branch you can build yourself or alternatively you can use [mrmangohands/sodium-fabric](https://github.com/mrmangohands/sodium-fabric/actions/runs/338981617) which is an update version for 1.15. This isn't officially endorsed.

**Comment by silversquirl** [comment] 2020-11-02 09:55
Sodium only supports the latest version of Minecraft. You can either use an unofficial fork as @FlashyReese suggested, or connect using a 1.16 client with [multiconnect](https://github.com/Earthcomputer/multiconnect/)

**Comment by amnotbananaama** [comment] 2020-11-02 18:59
Marking as a duplicate of #111 . As others have said, there are no plans to backport Sodium at this time. Anyone can fork and backport an unofficial version of Sodium under the terms of the license, so I would suggest you look into that.

**Closed as completed by amnotbananaama** 2020-11-02 18:59 UTC
Labels: E-duplicate, T-enhancement

**Comment by Bobrokus** [comment] 2020-11-04 07:23
> There is an 1.15 branch you can build yourself or alternatively you can use [mrmangohands/sodium-fabric](https://github.com/mrmangohands/sodium-fabric/actions/runs/338981617) which is an update version for 1.15. This isn't officially endorsed.

Thank you!
