### ISSUE TITLE
Looking straight down when Y coordinate is between 62.380001 and 62.429991 causes rendering issues

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#813] opened 2021-08-02 03:03 UTC
### Version information

mc1.17.1-0.3.0+build.5

### Expected Behavior

Rendering works when at any Y level

### Actual Behavior

Rendering breaks when looking straight down and Y level is between 62.380001 and 62.429991

### Reproduction Steps

Enter a world
/tp ~ 62.380001 ~
See nothing

### Java version

Java 16.0.1

### CPU

AMD Ryzen 3600

### GPU

NVIDIA GTX 1650 Super

### Additional information

![b2](https://user-images.githubusercontent.com/48411594/127798948-42ee68ff-0a5f-475f-a10e-446c2466ae46.PNG)
![b1](https://user-images.githubusercontent.com/48411594/127798958-d5975da9-a9a5-4cbd-b224-ac100e58665e.PNG)
![i1](https://user-images.githubusercontent.com/48411594/127799041-a0ad2320-0094-41f9-9f55-cb27c3c913cb.PNG)

**Comment by amnotbananaama** [comment] 2021-08-02 03:24
Thank you for the report! I'm going to close this as a duplicate of #750, just because of the similar symptoms and reproduction steps

**Closed as completed by amnotbananaama** 2021-08-02 03:24 UTC
Labels: E-duplicate
