### ISSUE TITLE
flywhell support

### ISSUE THREAD

**Issue by Cuteistfox** [jellysquid3/Sodium#2093] opened 2023-09-28 14:18 UTC
basicly just putting Jozufozu/Flywheel#198 in case its on your side

**Comment by pajicadvance** [comment] 2023-09-30 17:55
From what I understand, the issue is to be fixed on Flywheel's side.

**Closed as completed by pajicadvance** 2023-09-30 17:55 UTC
Labels: E-external

**Comment by Cuteistfox** [comment] 2023-10-09 14:53
i thut so too but wasnt sure
