### ISSUE TITLE
Room for improvement

### ISSUE THREAD

**Issue by Mercenarioo** [jellysquid3/Sodium#1763] opened 2023-05-14 05:42 UTC
Hello, I ran the Spark profiler with Sodium and many optimizations mods installed, I thought that I will share the results here and ask if is it possible to get some more optimizations added? Great mod btw, it makes huge difference and 1.19 is finally playable! :) Let me know if you have questions or anything. :)
![image](https://github.com/CaffeineMC/sodium-fabric/assets/107449914/3d993c7b-29ce-40b5-8726-a771da6725ef)
![image](https://github.com/CaffeineMC/sodium-fabric/assets/107449914/d8304c72-c190-405b-8d74-bf3d40cf263d)
![image](https://github.com/CaffeineMC/sodium-fabric/assets/107449914/0337775e-0c9f-496f-8a4f-e79dcd0ad3d8)
![image](https://github.com/CaffeineMC/sodium-fabric/assets/107449914/f8af2320-107a-4e62-879d-94d222f70520)
![image](https://github.com/CaffeineMC/sodium-fabric/assets/107449914/4e7d7e2b-13cc-415b-aaa8-a2b3bb8d19b0)
![image](https://github.com/CaffeineMC/sodium-fabric/assets/107449914/ce69901f-3b96-42c9-ad17-fc5ed058394e)
![image](https://github.com/CaffeineMC/sodium-fabric/assets/107449914/946fd183-7797-4e43-81b6-f7855bbca8f7)
![image](https://github.com/CaffeineMC/sodium-fabric/assets/107449914/2e31d457-edf6-45df-b786-cfcff77c3113)
![image](https://github.com/CaffeineMC/sodium-fabric/assets/107449914/fef6bb7e-f5b6-4a12-84c8-ce11f528367a)

**Comment by douira** [comment] 2023-05-14 11:16
Thanks for the effort, however I can assure you that various contributors and the maintainers of Sodium have spent plenty of time looking at profiler results such as this one. Additional performance optimizations continue to be worked on and you may see them released in the future.

**Closed as completed** 2023-05-14 11:19 UTC
Labels: T-enhancement

**Comment by Mercenarioo** [comment] 2023-05-14 22:03
I believe it very much, but I think it will be good to save this issue to maybe take a look into it. :) I think there are som pull requests that may help with it too, but I'm not sure.
https://github.com/CaffeineMC/sodium-fabric/pull/1626
https://github.com/CaffeineMC/sodium-fabric/pull/1548

**Comment by Felix14-v2** [comment] 2023-05-15 09:00
> ask if is it possible to get some more optimizations added?

 What is your GPU?

**Comment by Mercenarioo** [comment] 2023-06-25 02:57
> **[Felix14-v2](/Felix14-v2) ** commented

I have gtx 1060, can't wait to see some more performance improvements :)

**Comment by Felix14-v2** [comment] 2023-06-25 10:31
> gtx 1060

Your GPU may be affected by performance regression caused by Nvidia's broken "optimizations" in their driver. Sodium 0.4.11 will have a workaround for this problem and some new optimizations, so performance on your system will probably be better.
