### ISSUE TITLE
Glass rendering error

### ISSUE THREAD

**Issue by xiaowine** [jellysquid3/Sodium#238] opened 2020-08-06 14:26 UTC
Glass rendering error
![2020-08-06_22 17 07](https://user-images.githubusercontent.com/68009112/89543749-e2e7df80-d833-11ea-96c4-423c26deea21.png)

**Comment by amnotbananaama** [comment] 2020-08-06 14:28
Duplicate of #38

**Comment by xiaowine** [comment] 2020-08-06 14:30
> [＃38的](https://github.com/jellysquid3/sodium-fabric/issues/38)重复项[](https://github.com/jellysquid3/sodium-fabric/issues/38)

thanks

**Closed as completed** 2020-08-15 00:15 UTC
Labels: T-bug, E-duplicate
