### ISSUE TITLE
Smooth lighting doesn't work on grass path and farmland

### ISSUE THREAD

**Issue by Skullfury111** [jellysquid3/Sodium#527] opened 2021-02-13 12:22 UTC
### Expected Behavior
_Smooth light should work on grass path and farmland, as in vanilla._

### Actual Behavior
_Smooth lighting doesn't work on grass path and farmland._

### Reproduction Steps
1. Set the smooth light to maximum.
2. Place a farmland or grass path in the middle of solid blocks.
3. Notice that smooth light does not work on farmland and grass path.

### Attachments
![2021-02-13_11 36 07](https://user-images.githubusercontent.com/79005131/107849212-18304400-6dfa-11eb-8905-36f7ea84fb4c.png)
![2021-02-13_11 34 02](https://user-images.githubusercontent.com/79005131/107849213-19fa0780-6dfa-11eb-86a9-ced4e8e42fc0.png)

### System Information
- Java Version: [1.16.5]
- CPU: [4x Intel(R) Core(TM) i76500U CPU @ 2.50GHz]
- GPU: [NVIDIA GeForce 940M]

**Comment by Kroppeb** [comment] 2021-02-13 12:36
See #50 and #242

**Comment by LambdAurora** [comment] 2021-02-13 15:24
Duplicate of #50 and #242 and as stated in those issues already this is intended behavior (Sodium casts 1/16th of a shadow instead of the full block of shadow Vanilla casts, which is considered a bug)

As a result this will not be fixed.

**Closed as completed by LambdAurora** 2021-02-13 15:24 UTC
Labels: E-duplicate, E-will-not-fix
