### ISSUE TITLE
Rendering block entity/CrashReport

### ISSUE THREAD

**Issue by theOfficalKamiii** [jellysquid3/Sodium#1356] opened 2022-06-22 21:25 UTC
### Version information

MCversion 1.18.2 on All of Fabric 5 v. 1.3.0

### Reproduction Steps

[crash-2022-06-22_11.39.25-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/8961370/crash-2022-06-22_11.39.25-client.txt)
Gives the step but on loading into the world it would crash almost immediately.

### Crash Report file

[crash-2022-06-22_11.39.25-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/8961371/crash-2022-06-22_11.39.25-client.txt)
![Minecraft client error](https://user-images.githubusercontent.com/108031588/175141292-cf6b0963-fc84-4299-9674-032f8a87f795.png)

### Additional information

This crash was persistent with 5 other people as well.

**Comment by xmadb4x** [comment] 2022-06-27 04:10
this happened to me too, but on 1.19

**Comment by zeldaking** [comment] 2022-07-15 13:26
same

**Comment by SolarReflect** [comment] 2022-07-17 19:40
same thing with me

**Comment by pajicadvance** [comment] 2023-05-10 18:12
Duplicate of #1352.

**Closed as not planned** 2023-05-10 18:12 UTC
Labels: E-duplicate, A-mods, T-crash
