### ISSUE TITLE
Crash Sodium in server

### ISSUE THREAD

**Issue by RedneTwo** [jellysquid3/Sodium#621] opened 2021-04-05 15:57 UTC
### Version

> Replace this text with the exact version of the mod you are using. Every part of the version is important! If you
> do not know what version you are using, look at the file name in your "mods" folder.
>
> Example: sodium-fabric-mc1.16.3-0.1.0.jar
Fabric 1.16.5

### Mods
https://imgur.com/KG9nns7

> Example:
> 1. Join Server with mods and sodium client
> 2. Place Scaffolding up
> 3. crash for server and user

### Crash Report File
https://pastebin.com/XWEhdBtb

**Comment by NoComment1105** [comment] 2021-04-05 16:05
To clarify, is this when sodium is installed on the server or when you are trying to join a server?

**Comment by Genau6502** [comment] 2021-04-05 16:23
You’ve removed massive parts of the log, so nothing can really be deduced from them

**Comment by MeeniMc** [comment] 2021-04-05 17:10
It is very unlikely to be related in any form with Sodium.

You are getting some errors because you appear to not be using the same mods on the server and client (missing item types etc). I'd start by looking into these messages about missing items to discover what it is that you are missing. The most problematic error message is about `Lnet` being received as a `net`. 

One of these missing mods causes a network handshake to fail (RSA error). I suppose we are looking at the client log, but if the server has the same error, that would crash the server. This is a bug in said mod, you should report it to them, but should go away if you have the mod on both sides.

**Comment by DragonEggBedrockBreaking** [comment] 2021-04-07 12:06
'Info needed' tag?

**Comment by coderbot16** [comment] 2021-04-09 23:48
Appears to be another issue with out-of-bounds WorldSlice accesses, which will be fixed by https://github.com/CaffeineMC/sodium-fabric/pull/581

**Comment by ryleu** [comment] 2021-04-28 15:27
This 100% needs more information. What version are you using? Have you tried it on the latest version? How can we reproduce it?

**Comment by LucilleTea** [comment] 2021-06-02 01:49
Closing in favour of #670 as a more informative report.

**Closed as completed by LucilleTea** 2021-06-02 01:49 UTC
Labels: E-duplicate, T-crash
