### ISSUE TITLE
Water rendering issue

### ISSUE THREAD

**Issue by Begnom** [jellysquid3/Sodium#1570] opened 2023-01-10 19:59 UTC
### Version information

mc1.19.2-0.4.4+build.18

### Expected Behavior

The water to be clear

### Actual Behavior

The walls of the water block is less transparent than the rest of the water.
![2023-01-10_18 24 37](https://user-images.githubusercontent.com/76882765/211649779-a7de02c8-184e-4da7-9fdc-d33cd52184a4.png)

### Reproduction Steps

1. Download Sodium
2. Place water and make it flow
3. This happens.

### Java version

Java SE 8

### CPU

AMD Ryzen 2600

### GPU

GeForce 1660 Super

**Comment by Timolino456** [comment] 2023-01-23 11:10
Duplicate of #38

**Closed as completed** 2023-01-26 00:28 UTC
Labels: T-bug, E-duplicate
