### ISSUE TITLE
Ghost block,water is clear and land and water turn black. PS is there a way to make it work on intel celeron (

### ISSUE THREAD

**Issue by Boogaton** [jellysquid3/Sodium#220] opened 2020-07-31 19:20 UTC
### Expected Behavior
I saw this mod on youtube and i wanna record videos but fps is my issue and i cant afford a better computer so i got it the mod installed since im told its better than optifine and i see this, i first went on hypixel to test it and i was walking though everything.
_Example: The Piston should extend._

### Actual Behavior
Blackness, water invisible, a bit glitchy
![2020-07-31_16 05 14](https://user-images.githubusercontent.com/69055697/89069553-5c1d9900-d341-11ea-98fc-2b3c6386523c.png)
![2020-07-31_16 05 18](https://user-images.githubusercontent.com/69055697/89069557-5cb62f80-d341-11ea-806a-c20dadcde335.png)
![2020-07-31_16 05 36](https://user-images.githubusercontent.com/69055697/89069559-5f188980-d341-11ea-8400-6bc5bc8b6b00.png)
![2020-07-31_16 05 54](https://user-images.githubusercontent.com/69055697/89069561-5f188980-d341-11ea-9075-21e39961b4a9.png)
![2019-08-25_14 40 05](https://user-images.githubusercontent.com/69055697/89069573-650e6a80-d341-11ea-88e8-816b25d34e1c.png)

.
_Example: The Piston does not extend._

### Reproduction Steps
Provide information on how to reproduce this game crash. You can either fill in the example below or do something else -- just make sure your instructions are minimal and clear! If applicable, please provide a world file as a compressed ZIP which contains a minimally reproducible example of the issue. 

1. Place a Redstone Lamp beside a Redstone Repeater
2. Use a Lever to activate the Redstone Repeater
3. Nothing happens

### Attachments
Add any relevant screenshots or videos to this issue as you feel necessary to explain the issue.

### System Information
You can obtain this information from the in-game debug screen or through using [DxDiag](https://support.microsoft.com/en-us/help/4028644/windows-open-and-run-dxdiagexe) on Windows.

- Java Version: [fill me in]
- CPU: [fill me in]
- GPU: [fill me in]

**Comment by Boogaton** [comment] 2020-07-31 19:22
ignore the last image please my bad
and please if there is a way for the mod to support ancient computer processors id appreciate it

**Comment by LucilleTea** [comment] 2020-08-01 02:49
Duplicate of #179
You can work around the issue by disabling the Multi-Draw chunk renderer in the Advanced tab of the video settings.

**Comment by Boogaton** [comment] 2020-08-01 02:55
Ok thank you I will try it out

**Closed as completed** 2020-08-15 00:15 UTC
Labels: T-bug, E-duplicate
