### ISSUE TITLE
fps stutters when moving between chunks

### ISSUE THREAD

**Issue by JonathanTippy** [jellysquid3/Sodium#804] opened 2021-07-28 19:41 UTC
### Version information

mc1.17.1-0.3.0+build.529.jar

### Expected Behavior

fps should stay the same when moving between chunks

### Actual Behavior

fps momentarily drops when moving between chunks

### Reproduction Steps

press alt + f3 to show fps graph. press f3 + g to show chunk borders. move through a chunk border. there will be a momentary fps drop.

### Java version

Java 16

### CPU

Intel Core-i5 4440

### GPU

Nvidia GTX 1060 3GB

### Additional information

this can be reproduced using just sodium and fabric api.

**Comment by Rajbir98** [comment] 2021-07-29 04:05
its a problem that was from starting in sodium

**Comment by Rajbir98** [comment] 2021-07-29 04:06
But i belive that sodium will be much more better than optifine and soon will fix all of these

**Comment by JonathanTippy** [comment] 2021-07-29 04:11
> its a problem that was from starting in sodium

i don't understand what this means.

**Comment by pranshuthegamer** [comment] 2021-08-01 15:48
i have the same problem when breaking blocks and it also becomes transparent

**Comment by ghost** [comment] 2021-08-04 04:20
people from just about every hardware vendor have been reporting this. known issue, if you want an alternative that MIGHT increase perf compared to vanilla, try canvas

**Comment by Rajbir98** [comment] 2021-08-04 04:20
> > its a problem that was from starting in sodium
> 
> I don't understand what this means.

it means for the sodium first release I have this issue it is not quite stable but now in the latest builds in actions it is quite more stable than before whereas optifine gives fewer fps but it's stable but still good

**Comment by JonathanTippy** [comment] 2021-08-04 14:23
> people from just about every hardware vendor have been reporting this. known issue, if you want an alternative that MIGHT increase perf compared to vanilla, try canvas

so there isn't a plan to fix this issue?

**Comment by amnotbananaama** [comment] 2021-08-04 20:35
> so there isn't a plan to fix this issue?

That hasn't been said or implied, we're all just quite busy. It's also not clear if your report is just a duplicate of the infamous vanilla bug [MC-162253](https://bugs.mojang.com/browse/MC-162253).

**Comment by JonathanTippy** [comment] 2021-08-04 22:05
> > so there isn't a plan to fix this issue?
> 
> That hasn't been said or implied, we're all just quite busy. It's also not clear if your report is just a duplicate of the infamous vanilla bug [MC-162253](https://bugs.mojang.com/browse/MC-162253).

i think the vanilla bug only happens in specific circumstances, while this happens at any chenk border. it seems to be more likely to happen if you travel many chunks in one direction.

**Comment by jellysquid3** [comment] 2021-08-29 18:40
Sodium 0.3.1 should have resolved a lot of this frame rate instability. However, we still have issues where we're overloading the CPU with chunk building, which #691 and #836 cover. As those issues go into more detail about the problems here, I will instead close this one and link back to them instead.

**Closed as completed by jellysquid3** 2021-08-29 18:40 UTC

**Comment by TimBim-jpg** [comment] 2023-07-13 15:05
I have so many stuttering, it makes the game unplayable. When i move between already generated chunks everything is smooth as butter, but once i load new chunks, my game literally goes down to 1 fps for a second, please fix this, or give some advice to improve the situation, tell me how to make chunks load slow to prevent stutter, please

**Comment by Felix14-v2** [comment] 2023-07-13 15:30
> once i load new chunks, my game literally goes down to 1 fps

This isn't a graphite engine fault. See [MC-166005](https://bugs.mojang.com/browse/MC-166005) for details

> please fix this, or give some advice to improve the situation

This isn't something that Sodium should fix, since the issue isn't related to graphics, but you can still use other mods to improve the result. For example, [ThreadTweaks]( https://modrinth.com/mod/threadtweak) to minimize  internal server priority.

**Comment by TimBim-jpg** [comment] 2023-07-13 15:37
> > once i load new chunks, my game literally goes down to 1 fps
> 
> This isn't a graphite engine fault. See [MC-166005](https://bugs.mojang.com/browse/MC-166005) for details
> 
> > please fix this, or give some advice to improve the situation
> 
> This is out of scope of Sodium, but you can still use other mods to improve the result. For example, [ThreadTweaks](https://modrinth.com/mod/threadtweak) to minimize priority of internal server.

thanks, already using it, is there a way to make chunks load a bit slower?

**Comment by TimBim-jpg** [comment] 2023-07-13 15:38
because in one of the 1.18 snapshots mojang made chunk load faster, therefore terrible stuttering

**Comment by TimBim-jpg** [comment] 2023-07-13 15:39
the mod "Hold that chunk" improved situation by a little tho
