### ISSUE TITLE
Animation Distance slider

### ISSUE THREAD

**Issue by GameParrot** [jellysquid3/Sodium#1280] opened 2022-04-20 22:49 UTC
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A slider to allow for animated textures farther than a certain distance (in chunks, like render and sim distance) to not be animated.

**Describe alternatives you've considered**
Don't animate textures more than 16 chunks from the player

**Additional context**
It could improve performance on high render distances if you could have a 32 render distance, but only animate textures within 16 chunks for example.

**Comment by jellysquid3** [comment] 2022-04-23 02:50
Have you determined that animated textures are still a source of slowness in Sodium? We already disable animated textures where they can't be seen, which generally makes this a non-issue.

**Comment by GameParrot** [comment] 2022-04-23 12:45
It could probably improve performance a little on a 32 chunk render distance. A lot of fire can definitely create lag.

**Comment by MeeniMc** [comment] 2023-05-12 00:24
duplicate of #741

**Closed as not planned** 2023-07-22 02:33 UTC
Labels: T-enhancement, S-needs-triage
