### ISSUE TITLE
Chunks being unloaded from some viewing angles

### ISSUE THREAD

**Issue by BennettFourr** [jellysquid3/Sodium#1426] opened 2022-08-16 20:45 UTC
### Version information

sodium-fabric-mc1.19-0.4.2+build.16

### Expected Behavior

chunk to stay renderd

### Actual Behavior

chunk was not renderd

### Reproduction Steps

Have most of a chunk out of view and all of it will unload 

### Java version

17.0.3

### CPU

Intel i7 11700

### GPU

RTX 3060ti

### Additional information

![2022-08-16_16 38 15](https://user-images.githubusercontent.com/94060774/184982001-768220e8-fa84-4b08-87d6-0cc4e9298630.png)

![2022-08-16_16 51 53](https://user-images.githubusercontent.com/94060774/184982941-97d548bc-cb13-411d-aa24-1eba46dca529.png)

**Comment by burgerindividual** [comment] 2022-08-22 05:45
This is a known bug with occlusion culling. I *think* this is fixed in the development branch, but refactors are still going on, so I'll have to keep this example in mind when testing before release.

**Comment by pajicadvance** [comment] 2023-05-10 17:45
Duplicate of #872.

**Closed as not planned** 2023-05-10 17:45 UTC
Labels: T-bug, E-duplicate
