### ISSUE TITLE
Sodium breaking animations cut off/not appearing.

### ISSUE THREAD

**Issue by avnothdmi** [jellysquid3/Sodium#232] opened 2020-08-04 10:00 UTC
## Expected Behaviour:

When you normally break a block, you would expect a breaking animation to occur.

## Actual Behaviour
When using Sodium, the breaking animations are sometimes cut off/not there.

## Versions:

fabric-loader-0.9.0+build.204-1.16.1
sodium-fabric-mc1.16.1-0.1.0.jar

## How to replicate:

Just look at a block at certain angles to see it cut off. If you look straight down at a block below you, the block's breaking animation does not appear.

## System Information

You can obtain this information from the in-game debug screen or through using DxDiag on Windows.

Java Version: 13.0.1
CPU: i5-7400 3GHz
GPU: Radeon Pro 555X 2GB

**Comment by QPCrummer** [comment] 2020-08-11 15:50
I have the same problem too.

**Comment by LucilleTea** [comment] 2020-08-11 15:57
Duplicate of #36 - fixed in the development branch.

**Comment by Ultra03** [comment] 2020-08-12 00:40
It's not actually a duplicate, it still occurs even with that fix (although the looking straight down issue is fixed).

![issue](https://user-images.githubusercontent.com/20672260/89962611-193daa00-dbfa-11ea-8d75-bc080ff90362.gif)
(this is the compiled from the dev branch, latest commit 1df506f)

**Comment by jellysquid3** [comment] 2020-11-03 02:08
Fixed by a9a783f1.

**Closed as completed by jellysquid3** 2020-11-03 02:08 UTC
Labels: T-bug, S-confirmed
