### ISSUE TITLE
Entity distance setting dosent save

### ISSUE THREAD

**Issue by Kiriyashiki** [jellysquid3/Sodium#186] opened 2020-07-26 10:20 UTC
### Expected Behavior
The entity distance setting should save when changed and clicking apply

### Actual Behavior
If you change the entity distance setting, after clicking apply and closing, reopening the video settings tab, its back default 100%

### Reproduction Steps
Open video settings
Edit the entity distance setting
Apply changes
Close video settings
Open video settings
Entity distance is back to default value

### Attachments

https://cdn.discordapp.com/attachments/667790176184958976/736889579164139520/2020-07-26_12-10-04.flv

### System Information
- 8, default java version provided by launcher
- CPU: Intel core i5 2520M @ 2.5 ghz (4 cpus)
- GPU: Intel HD graphics 3000

**Comment by NoComment1105** [comment] 2020-07-26 10:25
Hello, i discovered this issue too, it has been fixed in the latest dev versions, update to one of them if you desperately need this fix

**Comment by amnotbananaama** [comment] 2020-08-25 05:38
Duplicate of #65, fixed in https://github.com/jellysquid3/sodium-fabric/commit/b9c2ad3c38b16275cf2f1a81dcfb2fee1563905b. You can compile yourself or wait for the next release.

**Closed as completed by amnotbananaama** 2020-08-25 05:38 UTC
Labels: T-bug, E-duplicate
