### ISSUE TITLE
Sodium Crashing on 1.19.3

### ISSUE THREAD

**Issue by rzpwr** [jellysquid3/Sodium#1545] opened 2022-12-19 21:29 UTC
### **Version information**
sodium-fabric-mc1.19.3-0.4.6+build.20

### **Reproduction Steps**
Teleport to a player who's in a different dimension

### **Java version**
Java 17.0.5 64 bit

### **Crash Report File**
https://hastebin.com/ivazomedan.yaml

**Comment by jellysquid3** [comment] 2022-12-19 21:33
Duplicate of #1486.

**Closed as completed by jellysquid3** 2022-12-19 21:33 UTC
