### ISSUE TITLE
Rendering Issue

### ISSUE THREAD

**Issue by BFUR64** [jellysquid3/Sodium#513] opened 2021-02-03 13:45 UTC
### Expected Behavior
Nothing should happen, and everything should work as intended.

### Actual Behavior
Random blocks appear on my screen, and are random. It switches from that to normal but rendering issues like portal frames and water blocks dont exist.

### Reproduction Steps
Switching from Oneshot 3.0, to Multidraw 4.3

### Attachments
![image](https://user-images.githubusercontent.com/78485623/106754520-09ae9380-6668-11eb-86eb-b932d38bcd47.png)
![image](https://user-images.githubusercontent.com/78485623/106754547-116e3800-6668-11eb-8e57-bb8e21506624.png)
![image](https://user-images.githubusercontent.com/78485623/106756794-965a5100-666a-11eb-862e-c055141eeb3e.png)
![image](https://user-images.githubusercontent.com/78485623/106756835-a2dea980-666a-11eb-9707-8c070297fffe.png)
![image](https://user-images.githubusercontent.com/78485623/106756866-aa9e4e00-666a-11eb-9568-0aea1d49d6f4.png)

### System Information

- System Model: HP 2000 Notebook PC
- Java Version: 1.8.0_281
- CPU: Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz (4 CPUs), ~2.6GHz
- GPU: Intel(R) HD Graphics 4000 10.18.10.5161

**Comment by Genau6502** [comment] 2021-02-03 15:20
Are you using 1.16.x/next?

**Comment by fsharpseven** [comment] 2021-02-03 18:31
This is a duplicate of #179, and currently the only workaround is to use the 3.0/2.0 renderer.

**Closed as completed** 2021-02-03 18:33 UTC
Labels: T-bug, E-duplicate
