### ISSUE TITLE
Conflict with optifabric

### ISSUE THREAD

**Issue by BjornHK1** [jellysquid3/Sodium#132] opened 2020-07-21 09:24 UTC
### Reproduction Steps

1. start the game

### Crash Report File
https://gist.github.com/BjornHK1/5970246481337bd74be28458a3800a50

### Additional Information
I think one of the biggest usage of this mod is playing shader packs please fix this and I love your mod so much, thanks

**Comment by np22-jpg** [comment] 2020-07-21 09:26
Optifabric support could never happen. Not only does optifabric break many other mods, but it isn't even updated anymore.

Additionally, both optifine and sodium target the renderer, which makes them inheritly incompatible (hence the error saying sodium breaks optifine).

Edit: Also optifine is closed source, and trying to decompile software to get the patches isn't exactly fun afaik.

Edit 2: this is also a dupe of issue #13

**Closed as completed** 2020-07-25 17:49 UTC
Labels: E-duplicate, E-will-not-fix, T-crash
