### ISSUE TITLE
The glass and the water is showing an error 

### ISSUE THREAD

**Issue by alvinqwq** [jellysquid3/Sodium#1489] opened 2022-10-29 13:37 UTC
### Version information

minecraft version1.19.2  fabric version 0.14.9

### Expected Behavior

The glass should look blurry like the picture  and the water should be pure blue 

![2022-10-15_14 07 30](https://user-images.githubusercontent.com/116953395/198834561-2f8c10b9-217e-4a98-8bae-06a400b934db.png)

### Actual Behavior

The glass is displayed as transparent and there are magenta stripes on the chunk border（picture 1）
The water shows strange black stripes（picture2 and 3）
![2022-10-15_14 07 26](https://user-images.githubusercontent.com/116953395/198830771-f470ba35-c533-42e8-88f7-31a4491dc9eb.png)
![2022-10-17_18 00 33](https://user-images.githubusercontent.com/116953395/198830778-9c8a96d7-af59-4630-862b-461e74c3c9dc.png)
![7337FBC680B35C68F0CCF2C8B9AF86FB](https://user-images.githubusercontent.com/116953395/198830968-83f6131b-3b6b-4046-9913-2896d5852a4f.png)

### Reproduction Steps

I converted my archive from forge to fabric and installed Sodium and that's it

### Java version

java18

### CPU

amd ryzen 5 2500u

### GPU

amd radeon vega 8 graphics

### Additional information

![2022-10-29_21 32 43](https://user-images.githubusercontent.com/116953395/198834495-8560490b-b71b-4d64-8d37-858820f296c2.png)
![2022-10-29_21 32 47](https://user-images.githubusercontent.com/116953395/198834510-9b66172d-ee88-4484-beef-89577b10ed56.png)
![2022-10-29_21 32 50](https://user-images.githubusercontent.com/116953395/198834516-b0bf6845-00d6-4d70-a691-f588e3c99776.png)

**Comment by alvinqwq** [comment] 2022-10-29 14:01
The image in Expected Behavior does not load, i resend it
![2022-10-15_14 07 30](https://user-images.githubusercontent.com/116953395/198835699-1b914e6e-8723-4f51-a553-7a1da1348eac.png)

**Comment by alvinqwq** [comment] 2022-10-29 14:05
Supplementing the glass error in the Actual Behavior, only the glass on the ceiling shows the error, and the glass on the floor is normal

**Comment by Timolino456** [comment] 2022-11-01 12:12
Looks like a duplicate of #38

**Comment by code004Accepted** [comment] 2022-12-21 14:35
Can confirm in latest version (1.19.3, 0.4.6+build.20) . The glitch also happens with ice directly above water. Chunk borders appear as lines in the ice.

**Comment by Timolino456** [comment] 2022-12-21 15:03
This bug is known since the beginning. A fix (or rather the implementation of the necessary feature for this to not happen anymore) is planned for Sodium 0.5.

**Comment by sedyh** [comment] 2023-03-17 10:53
I'm having the same issue, minecraft 1.18.2 + sodium-fabric-mc1.18.2-0.4.1+build.15.jar
![image](https://user-images.githubusercontent.com/19890545/225885166-e735921e-5705-451c-9c5d-cb9c74a13b39.png)

**Comment by piuvas** [comment] 2023-05-03 00:10
should be closed as duplicate.

**Comment by pajicadvance** [comment] 2023-05-10 17:37
Duplicate of #38.

**Closed as not planned by pajicadvance** 2023-05-10 17:37 UTC
Labels: T-bug, E-duplicate
