### ISSUE TITLE
add support for forge

### ISSUE THREAD

**Issue by Be1acProgrammer** [jellysquid3/Sodium#2825] opened 2024-10-20 21:28 UTC
would really love to see if support could be added for forge, 1.8.9 and 1.12.2. I understand people might have a backlash towards this request, but
I use old hardware that works well with both of those older versions of minecraft. The current versions has lots of stuttering and lagging for me. I have no coding knowledge, so I'm just submitting this to see what the community or developers would say. This may not even be possible. I understand that this was originally made for fabric. But once that I saw the support for neoforge, I really want to know if it's possible to write it for 1.8.9 version with forge.

Best Regards From Zaga.

**Comment by Lolothepro** [comment] 2024-10-20 21:30
Duplicate of https://github.com/CaffeineMC/sodium-fabric/issues/111

**Comment by douira** [comment] 2024-10-20 21:31
Consider coming to the discord server so you can get help with using modern versions of sodium on your device, if compatible. Modern Minecraft with Sodium has significantly less stuttering than vanilla.

**Closed as not planned by douira** 2024-10-20 21:31 UTC
Labels: E-duplicate, T-enhancement
