### ISSUE TITLE
Stained glass panes + ice blocks render incorrectly

### ISSUE THREAD

**Issue by thescyphozoa** [jellysquid3/Sodium#1907] opened 2023-07-23 04:57 UTC
### Bug Description

https://streamable.com/sfj7sn
https://streamable.com/622vg2

**Expected behaivor**

Placing stained glass panes in front of ice blocks will let you see the ice through the stained glass panes.

**Actual behavior**

Placing stained glass panes in front of ice blocks appears to make the mass of ice blocks stop rendering, letting you see "directly" behind the ice, with your view only obstructed by the glass.

### Reproduction Steps

**Reproduction steps**

Find or make an area of ice blocks. Place stained glass panes in front of, on top of, or around the ice. Position yourself to see the ice through the glass. Under most circumstances, the ice should disappear and you should see the blocks behind/under the ice more clearly through the stained glass panes.

You must use stained glass panes. Any color. Non-stained glass panes don't cause the bug. Stained glass blocks don't cause the bug.

Chunk borders seem to have an effect on which ice blocks will or will not be hidden by which panes, but only in the X and Z directions. In the Y direction, there seem to be arbitrary borders, not subchunk height borders, that affect this. 

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12138031/latest.log)

### Crash Report

[crash-2023-07-22_21.57.26-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12138035/crash-2023-07-22_21.57.26-client.txt)

**Comment by hexadecimal233** [comment] 2023-07-23 05:05
Duplicate of #38

**Comment by Octol1ttle** [comment] 2023-07-23 05:07
Duplicate of #38

**Closed as not planned** 2023-07-25 17:41 UTC
Labels: E-duplicate
