### ISSUE TITLE
Screen flickers when I broke or placed a block

### ISSUE THREAD

**Issue by ffllyy404** [jellysquid3/Sodium#968] opened 2021-11-14 15:15 UTC
### Version information

mc1.17.1-0.3.0+build.7

### Expected Behavior

Nothing should go wrong

### Actual Behavior

When I break or place a block, my screen flickers.

### Reproduction Steps

When I first time installed the mod, everything was fine.
But when I second time opened the launcher and entered the game, something went wrong.
Just as I mentioned above, my screen flickered for some reason.
I tried to use other versions of sodium, but it didn't solve my problem.

### Java version

java 16.0.1

### CPU

Intel i5-1035G1

### GPU

Intel UHD graphic G1

### Additional information

Other mod using: lithium-fabric-mc1.17.1-0.7.5
I tried to remove lithium, but it didn't help.

video:
https://user-images.githubusercontent.com/94237423/141688078-3287b6b7-c698-46f4-9033-f71c4ed07196.mp4

.

**Comment by RubiiJet** [comment] 2021-11-15 22:59
I have the same problem, I thought it was Starlight but that ain't it. It happens every time a block breaks or is placed. I just broke a tree and the leaf decay also makes the screen flicker. It appears to also happen when sheep eat too, I haven't tried redstone to see if it happens every time a block updates.

**Comment by Andromeda110K** [comment] 2021-11-16 17:14
I also have the same issue since Sodium 0.3.0, I thought it was my GPU but it seems it isn't, it happens also when I reload all chunks, use redstone things such as pistons, observers and trapdoors, when there's a block update and also when opening doors.

**Comment by MESLewis** [comment] 2021-11-18 18:55
Please update your graphics drivers and report back with your driver version, and on if the problem persists.

**Comment by ffllyy404** [comment] 2021-11-19 12:16
> Please update your graphics drivers and report back with your driver version, and on if the problem persists.
Ok I will try

**Comment by ffllyy404** [comment] 2021-11-19 12:17
Ok I will try

**Comment by ffllyy404** [comment] 2021-11-19 12:44
Still doesn't help.
version: Intel Graphics Driver 30.0.101.1069

**Comment by ffllyy404** [comment] 2021-11-19 12:48
Updated launcher too

**Comment by RubiiJet** [comment] 2021-11-19 13:06
System: Windows 11 21H2 Home Edition (64 bit laptop)
CPU: Intel(R) Core(TM) i3-1005G1
GPU: Intel(R) UHD Graphics (it's the iGPU)

No driver updates are to be found. I am using the latest version of Sodium I can find on Curseforge. The other performance mods I use is Starlight and Lithium. The flickering is still indeed there. It use fancy textures but it also flickers with fast textures.

If there are any more suggestions I'd be more than happy to also try it when I'm free.

**Comment by No-Longer-Active** [comment] 2021-11-23 23:59
Also experiencing this issue
System: Windows 10 Pro 20H2 (64 bit)
CPU: Intel(R) Core(TM) i5-1035G1
GPU: Intel(R) UHD Graphics

Checked my driver and updated it, still experiencing the flickering.

**Comment by LucilleTea** [comment] 2021-11-25 03:29
This looks like a duplicate of #853 and #869

**Closed as completed by LucilleTea** 2021-11-25 03:29 UTC
Labels: E-duplicate
