### ISSUE TITLE
FluidRenderHandler implementation is ignored for water blocks

### ISSUE THREAD

**Issue by MehVahdJukaar** [jellysquid3/Sodium#2298] opened 2024-01-31 07:32 UTC
### Bug Description

WaterColorProvider class does not refer to water fluid FluidRenderHandler registered via Fabric fluid API as it should.
This makes it so registering any of those render handlers for water does not override vanilla colors making it hard to modify it.

### Reproduction Steps

tested in dev environment. Vanilla FluidRenderHandler is never called for water while it is called for lava

### Log File

no log needed.

### Crash Report

no crash occurred

**Comment by jellysquid3** [comment] 2024-01-31 08:33
The problem is that Sodium registers its own custom color provider for water so that it can make use of smooth blending (something which Fabric API does not support.)

But it's hard to detect whether a mod is overriding the default fluid handler... Fabric API returns a registry entry regardless of it being the default or provided by another mod. So we don't know _when_ it's the default implementation.

**Comment by jellysquid3** [comment] 2024-01-31 08:35
I guess we need to ask Fabric to either expose `FluidRenderHandlerRegistryImpl#getOverride` or to provide some way for us to obtain the default implementation for comparison purposes.

**Comment by jellysquid3** [comment] 2024-01-31 08:51
I don't want to depend on internal details of Fabric API (as those are not stable), so I've opened a pull request [here](https://github.com/FabricMC/fabric/pull/3558) to expose the necessary function to public code.

**Comment by MehVahdJukaar** [comment] 2024-01-31 09:00
I see. related to that would it be possible to register other color BlenderColorProviders directly to sodium to benefit from better blending?

**Comment by jellysquid3** [comment] 2024-01-31 09:07
Sodium does not expose a public interface for doing that. The registrations are handled internally. We need to work out those details. If you really wanted to, look at an example like `GrassColorProvider<T>` (which pulls the color directly out of the grass color map for each vertex) and register it in `ColorProviderRegistry.installOverrides()` via mixin.

Though, again, I don't recommend doing that until we have a stable way to interact with it.

**Comment by MehVahdJukaar** [comment] 2024-01-31 09:08
alright, I'll wait for a proper api then

**Comment by jellysquid3** [comment] 2024-02-01 09:52
Blocked on upstream changes; pulling it out of the milestone.

**Comment by jellysquid3** [comment] 2024-02-10 12:36
The related PR was merged in Fabric API, and has been published with [version 0.96.0](https://github.com/FabricMC/fabric/releases/tag/0.96.0%2B1.20.4).

**Comment by MehVahdJukaar** [comment] 2024-07-28 19:36
any update on this? This change makes custom colormap for water not possible and customize water color is quite a big thing people want to do

**Comment by IMS212** [comment] 2024-07-28 19:41
This should be already fixed in Sodium 0.6 Alpha 2.

**Comment by jellysquid3** [comment] 2024-07-28 19:42
I don't see the commit which fixes this linked to this issue. @IMS212 Can you x-ref & update the labels if this is solved in Sodium 0.6?

**Comment by IMS212** [comment] 2024-07-28 19:47
Ah, I misunderstood what was said. This will be fixed in Alpha 3; is there a test pack I can use to confirm this?

**Comment by jellysquid3** [comment] 2024-09-23 01:54
This should be fixed in Sodium 0.6.0-beta.2. Please let us know if you see any other issues with the fluid rendering.

**Closed as completed by jellysquid3** 2024-09-23 01:54 UTC
Labels: T-bug, S-confirmed
