### ISSUE TITLE
cant open sodium video settings

### ISSUE THREAD

**Issue by ZP-Gaming** [jellysquid3/Sodium#2783] opened 2024-09-30 12:43 UTC
### Bug Description

i tried to open sodiums video settings and it just crashes, have to leave the better sodium options button to be able to access normal video settings. heres a pic of attached mod list, was testing out a modpack when it happened. also without the better sodium options button mod, it just doesnt let you go into settings and crashes after clicking video settings.
![image_2024-09-30_084018786](https://github.com/user-attachments/assets/7bfc84d9-3f68-4201-87f5-88714034d4f7)

### Reproduction Steps

launch minecraft with mod list in desc, open settings, open sodiums video settings

### Log File

[latest.log](https://github.com/user-attachments/files/17189852/latest.log)

### Crash Report

[crash-2024-09-30_08.32.28-client.txt](https://github.com/user-attachments/files/17189856/crash-2024-09-30_08.32.28-client.txt)

**Comment by rilakuma123** [comment] 2024-09-30 13:03
Does this happen without "Sodium Options API"?

**Comment by samuel-odinware** [comment] 2024-09-30 23:43
I have been experiencing the same issue. From my testing, both _Reese's Sodium Options_ and _Sodium Dynamic Lights_ (uses RSO under the hood) cause the game to crash when opening video settings. Down the rabbit hole I went and stumbled upon this [issue](https://github.com/FlashyReese/reeses-sodium-options/issues/98#issuecomment-2308722165) where _Controlify_ is mixing into _Reese's Sodium Options_. While I do not see _Controlify_ in your mod list, it may help in finding your issue. I currently have everything working on the latest versions after removing _Controlify_.

**Comment by ZP-Gaming** [comment] 2024-10-01 17:23
> Does this happen without "Sodium Options API"?

yes, sodium options just adds a button specifically for sodium options in settings and seperate minecraft video settings from sodiums, without it, the video settings tab just crashes when clicked. otherwise with it, it just crashes when clicking the sodium options button

**Comment by ZP-Gaming** [comment] 2024-10-01 17:25
> I have been experiencing the same issue. From my testing, both _Reese's Sodium Options_ and _Sodium Dynamic Lights_ (uses RSO under the hood) cause the game to crash when opening video settings. Down the rabbit hole I went and stumbled upon this [issue](https://github.com/FlashyReese/reeses-sodium-options/issues/98#issuecomment-2308722165) where _Controlify_ is mixing into _Reese's Sodium Options_. While I do not see _Controlify_ in your mod list, it may help in finding your issue. I currently have everything working on the latest versions after removing _Controlify_.

ill test it without dynamic lights but would be really nice to be able to use it because dynamic lights are nice, if anything ill try to find a resource pack or shaders that do it instead

**Comment by ZP-Gaming** [comment] 2024-10-01 17:27
if needed, game ver is 1.21.1

**Comment by ZP-Gaming** [comment] 2024-10-01 17:48
ok so i disabled dynamic lights and it works so its a problem with dynamic lights, might try changing its version later to see if that fixes it, if not ill just find a shader for it

**Comment by rilakuma123** [comment] 2024-10-01 22:01
Now that you've identified the cause, you should close this issue and open an issue on the "Sodium Dynamic Lights" issue tracker: https://github.com/txnimc/SodiumDynamicLights/issues

There are other dynamic lights mods you could try such as RyoamicLights

**Closed as not planned** 2024-10-02 13:57 UTC
Labels: E-external
