### ISSUE TITLE
fabric 1.19.3 sodium crashing when switching dimensions

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#1755] opened 2023-05-12 17:49 UTC
### Version information

sodium-fabric-mc1.19.3-0.4.9+build.23

### Reproduction Steps

load into server
switch lobbies/dimensions
eventually you will crash

### Crash Report file

[hs_err_pid19432.log](https://github.com/CaffeineMC/sodium-fabric/files/11466608/hs_err_pid19432.log)

**Comment by pajicadvance** [comment] 2023-05-12 17:54
Can you provide your mod list? Does the Minecraft window title say "Minecraft (version hidden from driver)" when you launch the game?

**Comment by ghost** [comment] 2023-05-12 18:19
the window title says Minecraft 1.19.3 when i launch and here is a mod list from a log file

[21:30:02] [main/INFO]: Loading 97 mods:
	- adaptive-tooltips 1.1.1
	- advancedchatcore 1.19.3-1.5.9
	- advancedchathud 1.19.3-1.3.7
	- advancedchatlog 1.19-1.2.2
	- betterf3 5.1.0
	- blur 2.6.1
	- chime 1.4.0
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-config 9.0.94
	- com_electronwill_night-config_core 3.6.5 via advancedchatcore
	- com_electronwill_night-config_json 3.6.5 via darkkore
	- com_electronwill_night-config_toml 3.6.5 via advancedchatcore
	- com_github_darkkronicle_konstruct_addons 2.0.3-build1 via advancedchatcore
	- com_github_darkkronicle_konstruct_core 2.0.3-build1 via advancedchatcore
	- com_github_llamalad7_mixinextras 0.1.1 via adaptive-tooltips
	- com_moandjiezana_toml_toml4j 0.7.2 via dynamicfps
	- crowdin-translate 1.4+1.19.3 via worldtime
	- dark-loading-screen 1.6.13
	- darkkore 0.3.4-1.19.3
	- dynamicfps 2.2.0
	- fabric-api 0.73.2+1.19.3
	- fabric-api-base 0.4.21+70be179c85 via fabric-api
	- fabric-api-lookup-api-v1 1.6.20+49abcf7e85 via fabric-api
	- fabric-biome-api-v1 12.1.1+b5d379b085 via fabric-api
	- fabric-block-api-v1 1.0.5+e022e5d185 via fabric-api
	- fabric-blockrenderlayer-v1 1.1.30+c6af733c85 via fabric-api
	- fabric-client-tags-api-v1 1.0.12+1134c5b885 via fabric-api
	- fabric-command-api-v1 1.2.22+f71b366f85 via fabric-api
	- fabric-command-api-v2 2.2.1+3fc4752e85 via fabric-api
	- fabric-commands-v0 0.2.39+df3654b385 via fabric-api
	- fabric-containers-v0 0.1.47+df3654b385 via fabric-api
	- fabric-content-registries-v0 3.5.1+1d37d50285 via fabric-api
	- fabric-convention-tags-v1 1.2.2+8e4e694f85 via fabric-api
	- fabric-crash-report-info-v1 0.2.14+aeb40ebe85 via fabric-api
	- fabric-data-generation-api-v1 11.2.1+06937c4b85 via fabric-api
	- fabric-dimensions-v1 2.1.41+48349a3f85 via fabric-api
	- fabric-entity-events-v1 1.5.7+b83334a085 via fabric-api
	- fabric-events-interaction-v0 0.4.40+3baeb27a85 via fabric-api
	- fabric-events-lifecycle-v0 0.2.44+df3654b385 via fabric-api
	- fabric-game-rule-api-v1 1.0.30+99f9db8085 via fabric-api
	- fabric-item-api-v1 2.1.10+312c329485 via fabric-api
	- fabric-item-group-api-v1 2.1.12+1134c5b885 via fabric-api
	- fabric-key-binding-api-v1 1.0.31+bc01e09785 via fabric-api
	- fabric-keybindings-v0 0.2.29+df3654b385 via fabric-api
	- fabric-lifecycle-events-v1 2.2.10+23a79c8a85 via fabric-api
	- fabric-loot-api-v2 1.1.20+75e9821185 via fabric-api
	- fabric-loot-tables-v1 1.1.24+9e7660c685 via fabric-api
	- fabric-message-api-v1 5.0.14+6ede1da985 via fabric-api
	- fabric-mining-level-api-v1 2.1.31+49abcf7e85 via fabric-api
	- fabric-models-v0 0.3.27+11ba9c3b85 via fabric-api
	- fabric-networking-api-v1 1.2.17+4017a8cb85 via fabric-api
	- fabric-networking-v0 0.3.34+df3654b385 via fabric-api
	- fabric-object-builder-api-v1 5.4.1+eb2a3ba985 via fabric-api
	- fabric-particles-v1 1.0.20+f1e4495b85 via fabric-api
	- fabric-recipe-api-v1 1.0.1+5176f73d85 via fabric-api
	- fabric-registry-sync-v0 2.0.5+1134c5b885 via fabric-api
	- fabric-renderer-api-v1 2.2.1+9f179aa185 via fabric-api
	- fabric-renderer-indigo 0.7.1+9f179aa185 via fabric-api
	- fabric-renderer-registries-v1 3.2.30+df3654b385 via fabric-api
	- fabric-rendering-data-attachment-v1 0.3.25+afca2f3e85 via fabric-api
	- fabric-rendering-fluids-v1 3.0.18+f1e4495b85 via fabric-api
	- fabric-rendering-v0 1.1.33+df3654b385 via fabric-api
	- fabric-rendering-v1 1.12.1+eb2a3ba985 via fabric-api
	- fabric-resource-conditions-api-v1 2.2.3+1134c5b885 via fabric-api
	- fabric-resource-loader-v0 0.10.5+a91e48b785 via fabric-api
	- fabric-screen-api-v1 1.0.41+f1e4495b85 via fabric-api
	- fabric-screen-handler-api-v1 1.3.13+99f9db8085 via fabric-api
	- fabric-sound-api-v1 1.0.8+75e9821185 via fabric-api
	- fabric-transfer-api-v1 2.1.15+ccd377ba85 via fabric-api
	- fabric-transitive-access-wideners-v1 2.3.1+5b9a588b85 via fabric-api
	- fabricloader 0.14.14
	- gbfabrictools 1.3.4+1.19.3 via worldtime
	- io_github_maowimpl_owo 2.0.0 via advancedchatcore
	- java 17
	- kronhud 1.19.3-2.2.4
	- malilib 0.14.0
	- meteordevelopment_discord-ipc 1.1 via skyblocker
	- midnightlib 1.1.0 via blur
	- minecraft 1.19.3
	- modmenu 5.0.2
	- no-telemetry 1.7.0
	- notenoughanimations 1.6.3
	- org_apache_commons_commons-csv 1.8 via advancedchatcore
	- org_eclipse_jgit_org_eclipse_jgit 6.4.0.202211300538-r via skyblocker
	- org_mariuszgromada_math_mathparser_org-mxparser 4.4.2 via advancedchatcore
	- pling 1.6.0
	- satin 1.10.0 via blur
	- screenshotclipboard 1.0.9
	- skinlayers 1.5.3-mc1.19.3
	- skyblocker 1.8.3-beta-beta-71d1c24+1.19.3
	- skyblockmod 1.7.7
	- sodium 0.4.9+build.23
	- sound_physics_remastered 1.19.3-1.1.0
	- wi_zoom 1.4-MC1.19.3
	- worldedit 7.2.13+46576cc
	- worldtime 1.19.3-fabric0.68.1-1.3.1
	- yet-another-config-lib 2.2.0

**Comment by pajicadvance** [comment] 2023-05-12 18:36
Can you send the full log file?

**Comment by ghost** [comment] 2023-05-12 19:07
[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/11467028/latest.log)

**Comment by CoffeeCupy** [comment] 2023-06-19 07:02
Same thing happening to me

**Comment by jellysquid3** [comment] 2023-06-22 06:09
Duplicate of #1816. You can try to use a different launcher to workaround the faulty NVIDIA drivers for the time being.

**Closed as not planned by jellysquid3** 2023-06-22 06:09 UTC
Labels: E-duplicate, T-crash
