### ISSUE TITLE
Stained glass does not render water/modded_glass within its own chunk. (#38)

### ISSUE THREAD

**Issue by TheRealEaglebird** [jellysquid3/Sodium#1623] opened 2023-02-15 01:10 UTC
### Version information

v0.4.4+build.18,

### Expected Behavior

#38
Expectation: Water and mod glass should be rendered behind glass pane:
<img width="960" alt="Expected behavior" src="https://user-images.githubusercontent.com/18298288/218899102-b931bd52-8321-4dc1-bc72-947a60d4fadb.png"/>
<img width="960" alt="How AE2 glass should look" src="https://user-images.githubusercontent.com/18298288/218897268-938a1e76-579c-4075-b464-a4904a16eebb.png"/>

### Actual Behavior

Actual: Water and modded glass within the same chunk as the glass pane is rendered invisible, water in other chunks is rendered correctly.
<img width="960" alt="chunkissues" src="https://user-images.githubusercontent.com/18298288/218896845-8e550ef8-4680-4598-b8fb-e77f6ffd749a.png"/>
<img width="960" alt="Special glass not rendered behind other special glass" src="https://user-images.githubusercontent.com/18298288/218897310-adbd5919-18db-4f9a-bb13-2ddbc5d31a88.png"/>

### Reproduction Steps

Place a stained glass pane or certain mod glass blocks and check for transparency issues from other transparent blocks within its chunk. 
Pretty sure this has been something that's being worked on, referring to #38 

### Java version

java 19.0.1

### CPU

11th Gen Intel(R) Core(TM) i7-11700KF @ 3.60GHz   3.60 GHz

### GPU

nVidia GeForce RTX 3070

### Additional information

Minecraft 1.19.2 with Quilt Loader 0.18.1-beta.43
qfapi-4.0.0-beta.27_qsl-3.0.0-beta.29_fapi-0.73.0_mc-1.19.2
sodium-fabric-mc1.19.2-0.4.4+build.18
<details>
<summary>Mod List</summary>

```
Mods:
  [📁]  (folder)
  [✔️] ad_astra-fabric-1.19.2-1.12.2
  [✔️] AdditionalAdditions-5.1.0
  [✔️] AdvancedReborn-1.19-1.1.2
  [✔️] advancementinfo-1.19.1-fabric0.58.5-1.3.1
  [✔️] almostunified-fabric-1.19.2-0.3.3
  [✔️] alternate-current-mc1.19-1.4.0
  [✔️] Amplified_Nether_v1.2
  [✔️] animatica-0.5+1.19
  [✔️] antighost-1.19.1-fabric0.58.5-1.1.5
  [✔️] appleskin-fabric-mc1.19-2.4.1
  [✔️] appliedenergistics2-fabric-12.9.2
  [✔️] architectury-6.4.62-fabric
  [✔️] authme-mc1.19.2-4.2.0
  [✔️] bactromod-1.3
  [✔️] badpackets-fabric-0.2.1
  [✔️] bclib-2.1.5
  [✔️] beenfo-1.19.1-fabric0.58.5-1.3.3-spigot
  [✔️] betterbeds-1.2.0
  [✔️] betterbiomeblend-1.19.0-1.3.6-fabric
  [✔️] BetterF3-4.0.0-Fabric-1.19.2
  [✔️] BetterMod-1.4.1
  [✔️] BetterPingDisplay-Fabric-1.19.2-1.1.1
  [✔️] Blanket Client tweaks-1.1.2
  [✔️] blur-2.6.0
  [✔️] book-of-experience-v3.0.0
  [✔️] borderless-mining-1.1.5+1.19
  [✔️] Botania-1.19.2-436-FABRIC
  [✔️] botarium-fabric-1.19.2-1.8.2
  [✔️] c2me-fabric-mc1.19.2-0.2.0+alpha.9.5
  [✔️] Capes-1.4.5+1.19
  [✔️] carpet-fixes-1.19-1.12.2
  [✔️] cc-restitched-1.101.2
  [✔️] Chunky-1.3.38
  [✔️] cloth-config-8.2.88-fabric
  [✔️] collective-1.19.2-6.43
  [✔️] completeconfig-2.1.0
  [✔️] conjuring-1.0.26+1.19
  [✔️] create_crystal_clear-1.0+1.19.2
  [✔️] create-fabric-0.5.0g-796+1.19.2
  [✔️] Debugify-2.8.0
  [✔️] deeperdarker-fabric-1.1.6-fabric
  [✔️] DisableCustomWorldsAdvice-3.0
  [✔️] discerning-furnace-1.0.9+MC1.19-1.19.2
  [❌] DistantHorizons-1.6.9a-1.19.2.jar (disabled)
  [✔️] do-a-barrel-roll-2.6.2+1.19.2-fabric
  [✔️] DripSounds-1.19-0.3.0
  [✔️] dynamiccrosshair-5.0+1.19.2-fabric
  [✔️] dynamiccrosshair-compat-3.1+1.19.2
  [✔️] dynamic-fps-2.2.0
  [✔️] easiercrafting-1.19.1-fabric0.58.5-1.7
  [✔️] eden-ring-0.6.4
  [✔️] emotecraft-for-MC1.19.2-2.2.7-b.build.47-fabric
  [✔️] emuno-1.0.0
  [✔️] enhancedblockentities-0.7.2+1.19.2
  [✔️] EnhancedQuarries-1.19-1.2.3-alpha
  [✔️] Entity_Collision_FPS_Fix-fabric-1.19-2.0.0.0
  [✔️] entityculling-fabric-1.5.2-mc1.19
  [✔️] entity-view-distance-1.0.2+1.19
  [✔️] essential_commands-0.30.0-mc1.19.2
  [✔️] exordium-fabric-1.0.2-mc1.19.2
  [✔️] ExtendedDrawers-1.3.6+mc.1.19.2
  [✔️] fabric-carpet-1.19.2-1.4.84+v221018
  [✔️] fabriccrossdimtpfix-0.3.1
  [✔️] fabric-language-kotlin-1.9.0+kotlin.1.8.0
  [✔️] fallingleaves-1.13.0+1.19.2
  [✔️] FallingTree-1.19.2-3.10.0
  [✔️] Fastload+1.19.2-2.6.10
  [✔️] ferritecore-5.0.3-fabric
  [✔️] feytweaks-1.19-1.2.3
  [✔️] forgetmechunk-1.0.4-1.18.X-1.19.X
  [✔️] ftb-chunks-fabric-1902.3.14-build.218
  [✔️] ftb-library-fabric-1902.3.11-build.166
  [✔️] ftb-teams-fabric-1902.2.12-build.95
  [✔️] Gamma-Utils-1.6.10-mc1.19.2
  [✔️] geckolib-quilt-1.19-3.1.40
  [✔️] graves-2.1.3+1.19.2
  [✔️] ImmediatelyFast-1.1.8+1.19
  [✔️] indium-1.0.9+mc1.19.2
  [✔️] indrev-1.15.1-BETA
  [✔️] infusion-table-mod-1.1.0
  [✔️] inventory-control-tweaks-1.3.18+MC1.19-1.19.2
  [✔️] ironchests-3.1.1-fabric
  [✔️] journeymap-1.19.2-5.9.2-fabric
  [✔️] krypton-0.2.1
  [✔️] kubejs-fabric-1902.6.0-build.140
  [✔️] lazydfu-0.1.3
  [✔️] letmedespawn-1.18.x-1.19.x-fabric-1.0.2
  [✔️] lightestlamp-3.0.0+1.19
  [✔️] linkedstorage-1.5.1-1.19
  [✔️] lithium-fabric-mc1.19.2-0.10.4
  [✔️] lunade-fastanim-1.5.7
  [✔️] mcpitanlibarch-1.3.5-1.19-fabric
  [✔️] megane-8.3.0
  [✔️] midnightlib-quilt-1.0.0-patch1
  [✔️] MiningDimensions_Fabric-1.19.2-1.4.27
  [✔️] mixintrace-1.1.1+1.17
  [✔️] modelfix-1.3-universal
  [✔️] Modern-Dynamics-0.3.4-beta
  [✔️] Modern-Industrialization-1.6.2-beta
  [✔️] modmenu-4.1.2
  [✔️] moreculling-1.19.1-0.15.0
  [✔️] MouseTweaks-fabric-mc1.19-2.22
  [✔️] NoChatReports-FABRIC-1.19.2-v1.13.12
  [✔️] no-telemetry-1.6.0
  [✔️] nounusedchunks-1.4
  [✔️] noweathereffects-1.4.0
  [✔️] noxesium-0.1.2
  [✔️] observable-3.3.1
  [✔️] ok_zoomer-5.0.0-beta.9+1.19
  [✔️] optigui-2.0.0-alpha.3
  [✔️] owo-lib-0.9.3+1.19
  [✔️] palette256-1.19.x-1.0.0
  [✔️] Patchouli-1.19.2-77-FABRIC
  [✔️] PetOwner-1.8.3-1.19+
  [✔️] picturesign-1.4.1
  [✔️] plantinajar-2.5.0
  [✔️] polymer-all-0.2.25+1.19.2
  [✔️] purpeille-3.2.3+fabric-1.19
  [✔️] qdwarp-1.3
  [✔️] qfapi-4.0.0-beta.27_qsl-3.0.0-beta.29_fapi-0.73.0_mc-1.19.2
  [✔️] quickpaths-1.19.2-3.0
  [✔️] quilt_loading_screen-4.0.0+1.19
  [✔️] quiltgoslightlyfasterlol-0.0.3
  [✔️] RebornCore-5.4.0
  [✔️] reeses_sodium_options-1.4.9+mc1.19.2-build.67
  [✔️] resourcefulconfig-fabric-1.19.2-1.0.18
  [✔️] resourcefullib-1.1.20
  [✔️] revelationary-1.3.0
  [✔️] rhino-fabric-1902.2.2-build.264
  [✔️] RoughlyEnoughItems-9.1.587
  [✔️] RoughlyEnoughLootTables-1.19-1.0
  [✔️] smoothboot-fabric-1.19-1.7.1
  [✔️] sodium-extra-0.4.16+mc1.19.2-build.90
  [✔️] sodium-fabric-mc1.19.2-0.4.4+build.18
  [✔️] Sort-1.0.2
  [✔️] soundphysics-fabric-1.19.2-1.0.18
  [✔️] spectrum-1.6.5-1.19.2-leisure_time
  [✔️] starlight-1.1.1+fabric.ae22326
  [✔️] technomodel-1.0.3
  [✔️] TechReborn-5.4.0
  [✔️] thorium-1.3.2
  [✔️] tooltipfix-1.1.1-1.19
  [✔️] toomanyplayers-1.19-1.1.4
  [✔️] trinkets-3.4.2
  [✔️] visuality-0.5.5
  [✔️] voicechat-quilt-1.19.2-2.3.27
  [✔️] whats-that-slot-fabric-1.3.1+1.19.2
  [✔️] whereisit-1.19.2-1.14.13
  [✔️] whoami-1.0
  [✔️] wired-redstone-0.4.14+1.19.2
  [✔️] WorldEditCUI-1.19.2+01
  [✔️] worldedit-mod-7.2.12
  [✔️] worldtime-1.19.1-fabric0.58.5-1.3.1
  [✔️] wthit-quilt-5.13.5
  [✔️] YetAnotherConfigLib-2.2.0-for-1.19.2
```
</details>

**Comment by jellysquid3** [comment] 2023-02-15 18:09
Why did you open a new issue if you already found the existing one which describes this problem exactly?

This is a duplicate of #38.

**Closed as completed by jellysquid3** 2023-02-15 18:09 UTC
Labels: T-bug, E-duplicate
