### ISSUE TITLE
Visual bug with stained glass

### ISSUE THREAD

**Issue by Wadzim01** [jellysquid3/Sodium#777] opened 2021-07-18 20:50 UTC
![2021-07-18_15 45 48](https://user-images.githubusercontent.com/79426110/126081729-de28822c-9891-4015-9dc3-946e2d82e66d.png)

Water will not render behind stained glass

**Comment by Kroppeb** [comment] 2021-07-18 21:50
Duplicate of #38

**Closed as completed** 2021-07-18 22:03 UTC
Labels: E-duplicate
