### ISSUE TITLE
Crashing when going below 0

### ISSUE THREAD

**Issue by Bendimester23** [jellysquid3/Sodium#632] opened 2021-04-14 10:10 UTC
### Version

> sodium-fabric-mc1.16.4-0.1.1-SNAPSHOT

### Reproduction Steps

> 1. Go under y = 0

### Crash Report File

> [crash-2021-04-14_12.03.26-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/6310071/crash-2021-04-14_12.03.26-client.txt)

**Comment by DragonEggBedrockBreaking** [comment] 2021-04-14 10:24
This has been fixed, please update your sodium version. This is also a duplicate. Please close the issue report.

**Closed as completed** 2021-04-14 10:37 UTC
Labels: E-duplicate, T-crash

**Comment by silversquirl** [comment] 2021-04-14 15:32
Duplicate of #587
