### ISSUE TITLE
Bedrock-esque Eye-Candy Chunk Rendering

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#255] opened 2020-08-14 17:02 UTC
In the Bedrock Edition I think we all understand that its much less taxing to render at a render distance of something like 72 chunks out instead of Java's 32-chunk limit, while still retaining solid, high FPS.

As far as I know, Bedrock achieves this by separating the loaded chunks into ticking and non-ticking chunks, so distant chunks don't load entities or process anything, and are just eye-candy.

In java you can crank the render distance up to 72 using a text editor, but entities seem to be at least loaded into the game all the way up to the border of your full rendering distance. After messing around with CarpetMod while making a mob switch in my SP world, I noticed that the mobcap maxing out was dependent on my render distance, that those entities would load the instant they crossed into whatever the border of my render distance was.

Is it not possible to add a new slider like in Bedrock that controls a secondary render distance, so you can independently control how many chunks you're ticking and how far out your eye-candy chunks go?

Can Sodium achieve something like this? Its honestly the only feature that Bedrock has going for it imo, 

Side note: I also noticed that if I artificially adjust the render distance to 72 in options.txt, Sodium recognizes that it is 72, but chunks are still limited to the 32-chunk render-distance. Possibly another, smaller feature request?

**Comment by Titaniumtown** [comment] 2020-08-14 17:05
On the server side, I know there is something like this for paper. I have the actual "ticked" distance as 4 chunks. and the non-ticked as 24

**Comment by amnotbananaama** [comment] 2020-08-14 17:19
(Partial) duplicate of #178. From Jelly there:
> This is not being considered. The game can't even properly handle a 32 chunk render distance on a reasonable computer.

In my opinion, one of the greatest things about Jelly's mods is that they don't "do less" than vanilla, but rather **optimize** vanilla's code. (In theory) someone could install all 3 of Jelly's mods and notice no difference from vanilla except performance improvements. So far, all of Sodium's optimization are [side-agnostic](https://fabricmc.net/wiki/tutorial:side), and work whether the player is in singleplayer or multiplayer. This would be a deviation from that.

> Side note: I also noticed that if I artificially adjust the render distance to 72 in options.txt, Sodium recognizes that it is 72, but chunks are still limited to the 32-chunk render-distance. Possibly another, smaller feature request?

The 32 chunk limit is hard-coded into a considerable amount of vanilla's code. This would require a considerable amount of effort, and would almost certainly break compatibility with any mod that expects the hard-coded limit.

**Comment by jellysquid3** [comment] 2020-08-21 17:28
Sodium is a rendering-specific mod, and as such making changes to the integrated server to split load and simulation distances is not on the table. There are also additional issues as amnotbananaama points out above that make this especially difficult in the context of Minecraft's recent chunk loading changes.

**Closed as completed by jellysquid3** 2020-08-21 17:28 UTC
Labels: T-enhancement, E-will-not-fix
