### ISSUE TITLE
Transparent blocks like water, slime blocks and glass have rendering issues

### ISSUE THREAD

**Issue by BeastyBoss-303** [jellysquid3/Sodium#2141] opened 2023-10-26 01:27 UTC
### Bug Description

![2023-10-26_12 18 44](https://github.com/CaffeineMC/sodium-fabric/assets/72542382/d8f223a8-e580-46fd-a12f-7374d17842a8)

### Reproduction Steps

Equip sodium and look at slime blocks.

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/13172069/latest.log)

### Crash Report

[crash-2023-10-26_12.26.14-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/13172079/crash-2023-10-26_12.26.14-client.txt)

**Comment by TheUserCreated** [comment] 2023-10-26 02:40
Duplicate of #38 
Might be solved eventually by #2016 (if it gets merged)

**Closed as not planned** 2023-10-26 10:15 UTC
Labels: E-duplicate
