### ISSUE TITLE
FPS counter like optifine ?

### ISSUE THREAD

**Issue by Maaattqc** [jellysquid3/Sodium#137] opened 2020-07-22 13:30 UTC
Hello, I know that a lot a people don't want to use Sodium because with optifine they could activate an option to show the fps withtout downloading a new mod for that.
So my idea is to create an option in video settings like V-sync button so we can activate/disable the fps counter on the top left corner for example
Thank you have a good day!

**Comment by np22-jpg** [comment] 2020-07-22 18:00
I mean, minihud not only does what you're asking but displays a lot more data than just fps

**Comment by ghost** [comment] 2020-07-22 18:31
This is better than Optifine:
https://www.curseforge.com/minecraft/mc-mods/ash-another-simple-hud

**Comment by Altirix** [comment] 2020-07-23 18:45
pretty sure you can get an fps overlay at a driver level from both AMD and Nvidia, which should be a solution for now (also probs would have less overhead than a ingame version)

**Comment by steenburgh** [comment] 2020-07-24 02:12
I can't speak on behalf of Jelly (Sodium's owner), but if I had to guess, it looks like she's trying make this mod *just graphical optimizations/minor graphical improvements.* No extra features like zoom/shaders/fps counters/whatever. It's easy enough to add an FPS counter to Minecraft, so imo it's better to just keep that as a separate mod so it can be updated more quickly + less likely to conflict with other mods.

**Comment by Dan-Gamin** [comment] 2020-07-24 12:27
I want to use shaders with Sodium. high fps shaders would be amazing.

**Comment by jellysquid3** [comment] 2020-08-06 01:37
Closing as duplicate of #214 -- the issue is better described there.

**Closed as completed by jellysquid3** 2020-08-06 01:37 UTC
Labels: E-duplicate, T-enhancement
