### ISSUE TITLE
?

### ISSUE THREAD

**Issue by bvtunc35** [jellysquid3/Sodium#850] opened 2021-08-21 23:00 UTC
### Version information

sodium-fabric-mc1.17.1-0.3.0+build.5

### Expected Behavior

?

### Actual Behavior

?

### Reproduction Steps

?

### Java version

Java 8

### CPU

 i5-2450M

### GPU

AMD Radeon HD 7500/7600 Series 

### Additional information

![2021-08-22_01 15 28](https://user-images.githubusercontent.com/89322555/130336826-95bcf24d-a0fe-4ad6-9b78-93170a75b19d.jpg)

**Comment by RealRTTV** [comment] 2021-08-22 03:02
?

**Comment by ghost** [comment] 2021-08-22 10:36
?

**Comment by Sneakometer** [comment] 2021-08-23 10:50
?

**Comment by LucilleTea** [comment] 2021-08-23 10:53
duplicate of #771

**Closed as completed by LucilleTea** 2021-08-23 10:53 UTC
Labels: E-duplicate
