### ISSUE TITLE
Sodium Build 7 (Expected Behavior) vs Build 8 graphical glitching.

### ISSUE THREAD

**Issue by AerodinMC** [jellysquid3/Sodium#1003] opened 2021-11-28 19:57 UTC
### Version information

Sodium 0.3.2+build.7 vs Sodium 0.3.2+build.8

### Expected Behavior

Normal behavior with Sodium 0.3.2+build.7 vs Glitchy behavior in Sodium 0.3.3+build.8

Vanilla MC with Fabric 12.5 and only the following mods:
Fabric API 0.43.1+1.17

Sodium 0.3.2+build.7 vs Sodium 0.3.3+build.8

Full video documentation of this bug to easily see the issue for yourself.  No other mods involved.  Same texture packs (PureBDCraft x128 if that matters).

(Please note I typo'd the sodium versions but it's listed correctly here - Sodium 0.3.2+build.7 is first, then second is Sodium 0.3.3+build.8)
https://www.youtube.com/watch?v=CjYvWDXC_vI

### Actual Behavior

Black chunks instead of loaded chunks flickering on and off.

### Reproduction Steps

See video:

(Please note I typo'd the sodium versions but it's listed correctly here - Sodium 0.3.2+build.7 is first, then second is Sodium 0.3.3+build.8)
https://www.youtube.com/watch?v=CjYvWDXC_vI

### Java version

Java 16

### CPU

AMD Ryzen 5 5600X

### GPU

AMD Radeon RX 6700 XT

**Comment by jellysquid3** [comment] 2021-12-01 22:11
Duplicate of #1006.

**Closed as completed by jellysquid3** 2021-12-01 22:11 UTC
