### ISSUE TITLE
i  have a problem with Sodium mod.  

### ISSUE THREAD

**Issue by cristi154** [jellysquid3/Sodium#253] opened 2020-08-14 08:30 UTC
### Expected Behavior
when i open a world with sodium after 5 minutes my texture get bugged out and i get under map 

### Actual Behavior

the mod doesn t increase my fps and my texture get bugged out._

### Reproduction Steps
when i start a map with Sodium,phosphor and lithium and the mods are not working like it should be at the begining i have some frame drops and then it continued with fame drops and my fps are not increasing and after some time i get bugged out like i use spectator mode

### Attachments
![2020-08-14_11 49 42](https://user-images.githubusercontent.com/69671349/90232064-c5fb6f80-de24-11ea-96b9-3827360690ae.png)
![2020-08-14_11 49 34](https://user-images.githubusercontent.com/69671349/90232074-c98ef680-de24-11ea-8854-01ea3e3ab07f.png)

### System Information
You can obtain this information from the in-game debug screen or through using [DxDiag](https://support.microsoft.com/en-us/help/4028644/windows-open-and-run-dxdiagexe) on Windows.

- Java Version: [java 14]
- CPU: [Intel Celeron 2 ghz]
- GPU: [intel HD Graphics]

**Comment by ZtereoHYPE** [comment] 2020-08-14 08:36
You left half of the bug report empty...
Does the piston look like not extended, or does it not even push blocks it has before?
Sodium only touches the rendering side of the game so if the piston didn't extend at all, server side, it's probably unrelated to Sodium.

**Comment by cristi154** [comment] 2020-08-14 09:04
sorry my bad, i updated now

**Comment by ZtereoHYPE** [comment] 2020-08-14 09:07
To fix this issue, go to the video settings, "Advanced" tab, and set the OpenGL version from 4.3 (multidraw) to 3.0 or 2.0 (oneshot).

**Comment by cristi154** [comment] 2020-08-14 09:10
ok i m gonna try this now

**Comment by FlashyReese** [comment] 2020-08-14 09:11
You can hop on [Jelly's Discord](https://jellysquid.me/discord) and drop a message in ```#tech-support``` if you encounter any further problems. If I recall correctly this is to track bugs/issues with sodium.

**Comment by cristi154** [comment] 2020-08-14 09:13
ok i puted onm 3.0 oneshot and it worked, should i put on 2.0?

**Comment by amnotbananaama** [comment] 2020-08-14 15:14
This is a duplicate of #179. You should prefer whichever renderer gives you better performance. Almost always this will be the highest version you can run.

For further questions or support, please direct yourself to `#tech-support` as stated above

**Closed as completed** 2020-08-15 00:13 UTC
Labels: E-duplicate, T-question
