### ISSUE TITLE
[1.16.next branch] Using MiniHuds Light overlay feature causes the edges of water to not render properly

### ISSUE THREAD

**Issue by Hyperbean18** [jellysquid3/Sodium#669] opened 2021-05-30 12:38 UTC
### Version Information

> sodium-fabric-mc1.16.4-0.1.1+build.13

### Expected Behavior

> Water should render as touching the adjacent blocks
![2021-05-22_21 28 36](https://user-images.githubusercontent.com/79054980/120104055-43079380-c170-11eb-9f85-38d3ec9153de.png)

### Actual Behavior

> At some angles, the water doesn't render properly
![2021-05-22_21 28 39](https://user-images.githubusercontent.com/79054980/120104064-5450a000-c170-11eb-8b33-cc5b2643f55d.png)

### Reproduction Steps

> Place solid blocks next to water sources.
> Turn on Minihuds Light overlay
> Try changing the angles at which you look at the water

### System Information

> - Java Version: 1.8.0_74 64 bit
> - CPU: 4x Intel(R) Core (TM) i5-4250U CPU @ 1.30GHz
> - GPU: Intel HD Graphics 5000 Open GL Engine

### Other Information

> Provide a list of any other mods you are using, along with their respective versions. If you have any screenshots,
> videos, or other information that you feel is necessary to explain the issue, feel free to attach them here.

**Comment by CodeF53** [comment] 2021-10-07 18:18
Minihud renders the numbers through a transparent texture, slightly above the block surface.
Technically that makes this a duplicate of #38 

A temporary fix is to switch from number rendering to cross rendering
`h` + `c` > `generic` > change "lightLevelNumbers" to `None` and "lightLevelMarkers" to `Cross`

**Comment by MeeniMc** [comment] 2023-05-11 02:36
can't replicate with Sodium 0.4.10, MiniHud 0.26.2. Seems resolved.

**Closed as completed** 2023-05-11 11:36 UTC
Labels: T-bug, A-mods, S-fixed
