### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException in Chunk Render Task Executor upon entering world

### ISSUE THREAD

**Issue by mpfaff** [jellysquid3/Sodium#596] opened 2021-03-21 04:46 UTC
This error occurs seemingly at random immediately upon entering a singleplayer or multiplayer world.

```
Exception in thread "Chunk Render Task Executor #10" java.lang.ArrayIndexOutOfBoundsException: Index 5879 out of bounds for length 5832
	at me.jellysquid.mods.sodium.client.world.WorldSlice.getBlockState(WorldSlice.java:232)
	at me.jellysquid.mods.sodium.client.world.WorldSlice.getFluidState(WorldSlice.java:241)
	at net.minecraft.block.FluidBlock.getCollisionShape(FluidBlock.java:55)
	at net.minecraft.block.AbstractBlock$AbstractBlockState.getCollisionShape(AbstractBlock.java:797)
	at net.minecraft.block.AbstractBlock$AbstractBlockState.getCollisionShape(AbstractBlock.java:793)
	at net.minecraft.block.AbstractBlock$AbstractBlockState.isFullCube(AbstractBlock.java:985)
	at net.minecraft.block.AbstractBlock.getAmbientOcclusionLightLevel(AbstractBlock.java:304)
	at net.minecraft.block.AbstractBlock$AbstractBlockState.getAmbientOcclusionLightLevel(AbstractBlock.java:723)
	at me.jellysquid.mods.sodium.client.model.light.data.LightDataAccess.compute(LightDataAccess.java:67)
	at me.jellysquid.mods.sodium.client.model.light.cache.ArrayLightDataCache.get(ArrayLightDataCache.java:56)
	at me.jellysquid.mods.sodium.client.model.light.data.LightDataAccess.get(LightDataAccess.java:39)
	at me.jellysquid.mods.sodium.client.model.light.smooth.AoFaceData.initLightData(AoFaceData.java:57)
	at me.jellysquid.mods.sodium.client.model.light.smooth.SmoothLightPipeline.getCachedFaceData(SmoothLightPipeline.java:182)
	at me.jellysquid.mods.sodium.client.model.light.smooth.SmoothLightPipeline.applyAlignedFullFace(SmoothLightPipeline.java:171)
	at me.jellysquid.mods.sodium.client.model.light.smooth.SmoothLightPipeline.calculate(SmoothLightPipeline.java:79)
	at me.jellysquid.mods.sodium.client.render.pipeline.BlockRenderer.renderQuadList(BlockRenderer.java:102)
	at me.jellysquid.mods.sodium.client.render.pipeline.BlockRenderer.renderModel(BlockRenderer.java:73)
	at me.jellysquid.mods.sodium.client.render.pipeline.context.ChunkRenderContext.renderBlock(ChunkRenderContext.java:43)
	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.performBuild(ChunkRenderRebuildTask.java:93)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:347)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

### Reproduction Steps
Not sure how to reproduce. Occurs roughly once every 3 weeks for me.

### System Information

- Minecraft Version: 1.16.4
- Sodium Version: 1.16.3-0.1.0
- Java Version: Adopt OpenJDK 1.15.0-1
- CPU: Intel Core i7-8750H
- GPU: Radeon Pro 555X 4GB

**Comment by comp500** [comment] 2021-03-21 09:50
I think this is a duplicate of #189

**Closed as completed** 2021-03-24 22:14 UTC
Labels: T-bug, E-duplicate
