### ISSUE TITLE
Ability to render more than 32 chunks?

### ISSUE THREAD

**Issue by respectablenoob-source** [jellysquid3/Sodium#787] opened 2021-07-21 21:15 UTC
Any way to go over the 32 Chunk render distance limit without changing the options file? I tried changing and it indicates it is rendering 64 chunks but it is indeed still rendering 32 chunks.

**Comment by saadatxyz** [comment] 2021-07-22 00:44
While this is likely not the answer you want to hear, Sodium will likely never add the ability to go past a 32 chunk render distance (the Vanilla limit that you can't circumvent with just the options file). As such, it is up to other mods to enable higher than 32 chunk render distances.

You can join the CaffeineMC discord to ask in the lounge channel for mods that do this.

**Comment by amnotbananaama** [comment] 2021-07-22 01:11
Duplicate of #178

**Closed as completed by amnotbananaama** 2021-07-22 01:11 UTC
Labels: E-duplicate
