### ISSUE TITLE
Game crash when i get in menu

### ISSUE THREAD

**Issue by KastroMugnaio** [jellysquid3/Sodium#393] opened 2020-11-14 11:52 UTC
1. Game finished loading
2. The game crashes

### Crash Report File
https://gist.github.com/KastroMugnaio/8514d72bb8620d678fa62b053d079187

**Comment by amnotbananaama** [comment] 2020-11-14 17:42
In the future please use the issue template. It exists so that we have as much information about your configuration as possible. 

Closing as a duplicate of #16. You need to compile Sodium with Java 8 if you are going to run with Java 8. At the moment Sodium uses Java 14 to build the stable branch in GitHub Actions, there is a Pull Request open to change this.

You can use a service such as [JitPack](https://jitpack.io) if you don’t have access to a JDK 8.

**Closed as completed by amnotbananaama** 2020-11-14 17:42 UTC
Labels: E-duplicate, T-crash
