### ISSUE TITLE
Sodium crashes upon joining world on Terascale 2 GPUs

### ISSUE THREAD

**Issue by Darkissou** [jellysquid3/Sodium#1646] opened 2023-03-01 20:35 UTC
### Version information

mc1.19.3-0.4.9+build.23

### Reproduction Steps

1. Go into any world on Sodium 0.4.9
2. No chuncks load and the game freezes quickly and has to be forcefully stopped

### Crash Report file

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/10865051/latest.log)

### Additional information

0.4.10 beta 4 also crashes.

**Comment by papamaionise** [comment] 2023-03-02 12:02
Same issue on 1.19.3 
but works on 1.18.2

**Comment by Timolino456** [comment] 2023-03-02 17:57
There is no crash in the log you attached. Did you attach the wrong file?

**Comment by papamaionise** [comment] 2023-03-03 09:37
@Timolino456  because game doesnt crashes smart guy it freezes
only entities render on first frame that freezes blocks are invisible

**Comment by Chris6ix** [comment] 2023-03-03 18:18
>

> @Timolino456 because game doesnt crashes smart guy it freezes only entities render on first frame that freezes blocks are invisible

Ey smart guy...the issue is titled "Sodium **crashes** upon joining world on Terascale 2 GPUs", so leave the guy alone, he's just trying to help.

**Comment by papamaionise** [comment] 2023-03-04 08:48
@Chris6ix  Wasn't being disrespectful or something I'm sorry 

I found a work around use sodium 0.4.8 instead

the 0.4.9 version causes this issue well that's the case for me.

edit: also issue presists in some earlier versions 0.4.7 crashes on loading screen plus i didnt mentioned the bad fps with 0.4.8

**Comment by MegWATTT** [comment] 2023-03-08 05:12
I can confirm this bug on HD 5770 with the 15.7.1 WHQL driver (havent tested the 16.2.1) . Sodium 0.4.9 does however work fine on linux.

Disabling/Tweaking sodium's advanced options has no effect on the crash.

Windows's event observer  shows that the driver has recovered from the crash after the game froze.

**Comment by Darkissou** [comment] 2023-03-14 18:06
Sorry for the late answer. The log is indeed seemingly fine because the game froze and didn't actually crash. Tested on driver version 16.2.1 and modded Amernime drivers. 0.4.8 works fine and 0.5 beta seems to have solved the problem as well. However I didn't notice performance problems running 0.4.8 nor crashes on older versions of Sodium

**Comment by jellysquid3** [comment] 2023-03-14 18:29
This might have been fixed in [Sodium 0.4.10](https://github.com/CaffeineMC/sodium-fabric/releases/tag/mc1.19.4-0.4.10) as a side effect of us fixing some empty draw calls that were getting submitted. Could you check and see?

**Comment by MegWATTT** [comment] 2023-03-27 23:05
I can confirm that it does work fine now on 15.7.1 driver with Sodium 0.4.10

**Comment by jellysquid3** [comment] 2023-07-22 01:24
Closing this as it user reports seem to indicate it was fixed in the most recent release.

**Closed as completed by jellysquid3** 2023-07-22 01:24 UTC
Labels: A-drivers, T-crash
