### ISSUE TITLE
X-Ray Flash

### ISSUE THREAD

**Issue by Cilla-H** [jellysquid3/Sodium#1466] opened 2022-09-27 22:39 UTC
### Version information

sodium-fabric-mc1.19-0.4.2+build.16.jar

### Expected Behavior

Not randomly flash X-Rays of the land around you

### Actual Behavior

Sometimes when I place or break blocks I get like flashes of X-Ray vision 

### Reproduction Steps

1. Open Minecraft with Sodium.
2. Place or break a block.
3. Ow my eyes.

### Java version

Java 1.19.

### CPU

Core i7 10th Gen I think

### GPU

Intel Iris Plus Graphics I think

**Comment by Phoenix-Starlight** [comment] 2022-09-29 03:51
Logs, thanks. (Of the relevant instances when this occurred)

**Comment by netflexy** [comment] 2022-10-03 14:01
Solved
https://www.youtube.com/watch?v=HJ0p6PjoO8g

**Comment by Cilla-H** [comment] 2022-10-07 19:05
![image](https://user-images.githubusercontent.com/106939310/194635953-3d54b5fa-4b80-4bb6-a2b0-e9f08f5f5c5f.png)

When I️ click that link from netflexy it gives me this

**Comment by netflexy** [comment] 2022-10-08 12:23
https://youtu.be/5ekFkAU96RQ

**Comment by netflexy** [comment] 2022-10-08 12:24
New one

**Comment by pajicadvance** [comment] 2023-05-10 17:05
Duplicate of #869.

**Closed as not planned by pajicadvance** 2023-05-10 17:05 UTC
Labels: T-bug, E-duplicate, A-drivers
