### ISSUE TITLE
The rendering of the iron railing is incorrect

### ISSUE THREAD

**Issue by Vector2053** [jellysquid3/Sodium#2342] opened 2024-02-16 13:45 UTC
### Request Description

![Snipaste_2024-02-16_21-42-41](https://github.com/CaffeineMC/sodium-fabric/assets/160245269/cd19c61c-0000-4a21-9da3-61d967662850)

If there are other blocks below it, it will behave like this.

**Comment by Lolothepro** [comment] 2024-02-16 13:46
duplicate of https://github.com/CaffeineMC/sodium-fabric/issues/460

**Closed as not planned** 2024-02-16 20:15 UTC
Labels: E-duplicate
