### ISSUE TITLE
Only animate nearby textures/Only make nearby transparent textures transparent?

### ISSUE THREAD

**Issue by googleooer** [jellysquid3/Sodium#776] opened 2021-07-18 20:02 UTC
**Is your feature request related to a problem? Please describe.**
When using high render distances like 32 chunks or higher, textures that are far away from the camera are still animated/transparent (leaves and water), even though those effects are not noticeable from far away.

**Describe the solution you'd like**
A feature that makes it so leaves use their opaque "Fast graphics" counterparts and water is not animated when they are far away. Could be activated by either a toggle or a slider (How many chunks away they should be before they stop being rendered at a high quality)

**Describe alternatives you've considered**
I haven't found any other mods that offer something like this. OptiFine lets you disable animations, but that affects everything regardless of how far the textures are.

**Comment by nkappler** [comment] 2021-07-24 10:46
duplicate of #741

**Comment by jellysquid3** [comment] 2021-08-29 18:44
Closing as duplicate of #741.

**Closed as completed by jellysquid3** 2021-08-29 18:44 UTC
Labels: T-enhancement
