### ISSUE TITLE
Slime blocks are not rendered behind a glass block

### ISSUE THREAD

**Issue by tatounee** [jellysquid3/Sodium#311] opened 2020-09-19 20:00 UTC
### Expected Behavior
Slime block should appear behind a glass block.

### Actual Behavior
Slime block are not rendered behind a glass block.

### Reproduction Steps
1. Place a slime block.
2. Place a glass block next to it.
3. Look the slime block through the glass block.
4. Nothing appear !

### Attachments
![screen](https://i.ibb.co/7Vhpfgd/screen.png)

### System Information
- Java Version: 1.8.0_251
- CPU: AMD Ryzen 5 2600
- GPU: Radeon RX 570 Series

**Comment by amnotbananaama** [comment] 2020-09-19 20:02
Duplicate of #38

**Closed as completed by amnotbananaama** 2020-09-19 20:02 UTC
Labels: T-bug, E-duplicate
