### ISSUE TITLE
Fix a culling problem of a certain surface when a translucent block placed just above another different translucent block

### ISSUE THREAD

**Issue by BlankMya** [jellysquid3/Sodium#2620] opened 2024-07-25 11:27 UTC
### Bug Description

I used just a fabric loader with the latest version sodium mod itself, so this theoretically should be a problem with sodium.
When placing a translucent block like a stained glass just above another different type of translucent block, looking into the bottom one through the upper translucent block in a certain direction, the very top surface of the bottom block won't render.
![Minecraft_ 1 21 - Singleplayer 25_07_2024 21_09_53](https://github.com/user-attachments/assets/89b7be02-fc12-4239-8d8c-9fd1d4688810)
If you look through another direction, then the bottom block will render properly, so I reckon this is a bug.
![Minecraft_ 1 21 - Singleplayer 25_07_2024 21_09_58](https://github.com/user-attachments/assets/e8cf995a-c0a5-453b-903a-ae047f232730)
These are tests for other blocks and other situations.
![Minecraft_ 1 21 - Singleplayer 25_07_2024 21_10_11](https://github.com/user-attachments/assets/387be298-9fb8-42e7-9b6b-4a209829500e)
![Minecraft_ 1 21 - Singleplayer 25_07_2024 21_10_16](https://github.com/user-attachments/assets/cb966c92-1dda-4a21-9c1d-5bfa449bced3)
![Minecraft_ 1 21 - Singleplayer 25_07_2024 21_10_43](https://github.com/user-attachments/assets/9c1d60b8-0447-467d-a3f0-a12c6528d982)
![Minecraft_ 1 21 - Singleplayer 25_07_2024 21_13_33](https://github.com/user-attachments/assets/e28212d0-8642-4f0a-b13d-f5f4a26d6281)
![Minecraft_ 1 21 - Singleplayer 25_07_2024 21_13_35](https://github.com/user-attachments/assets/ae203158-111c-4ac1-80eb-ee1f54944969)
![Minecraft_ 1 21 - Singleplayer 25_07_2024 21_14_44](https://github.com/user-attachments/assets/2c48eefc-33c9-4fa4-a57f-5284624e145d)

My platform: 
minecraft: 1.21
fabric: 0.15.11
sodium: 0.5.11
Windows device with an Nvidia GPU, RTX 4060 laptop.

### Reproduction Steps

To reproduce this step, just place a translucent block on another translucent block. Find the certain direction to look through, and you will notice that a surface has been culled.

### Log File

[2024-07-25-7.log.gz](https://github.com/user-attachments/files/16376838/2024-07-25-7.log.gz)

### Crash Report

[2024-07-25_21_17_25-Shader_Test-1_21.zip](https://github.com/user-attachments/files/16376749/2024-07-25_21_17_25-Shader_Test-1_21.zip)

**Comment by MCRcortex** [comment] 2024-07-25 11:28
Duplicate of #38

**Closed as not planned** 2024-07-25 11:31 UTC
Labels: E-duplicate
