### ISSUE TITLE
Fireworks have white elements

### ISSUE THREAD

**Issue by NotroDev** [jellysquid3/Sodium#1494] opened 2022-10-30 08:06 UTC
### Version information

sodium-fabric-mc1.19.2-0.4.4+build.18

### Expected Behavior

Fireworks shouldn't have weird, unexpected white elements.

### Actual Behavior

Fireworks have weird, unexpected white elements.

### Reproduction Steps

1. Just use any firework.

### Java version

Java 17.0.4.1

### CPU

AMD Ryzen 5 2600

### GPU

AMD Radeon RX 580 4GB

### Additional information

![obraz](https://user-images.githubusercontent.com/77281214/198868550-0a06f905-1238-4ce7-ac06-9e69edd23160.png)
I only have sodium:
![obraz](https://user-images.githubusercontent.com/77281214/198868644-3bc7928e-f4e3-4b61-9dea-4d44baa6eb41.png)
And fabric-api 0.60.0

**Comment by NotroDev** [comment] 2022-11-01 17:33
Hey.
It seems that the sodium extra is causing this issue.

**Comment by Timolino456** [comment] 2022-11-03 21:33
In that case you should probably report it to them [here](https://github.com/FlashyReese/sodium-extra-fabric/issues), if you haven't already (and this issue can be closed as it's not caused by Sodium)

**Closed as completed** 2022-11-04 13:36 UTC
Labels: T-bug, S-needs-triage
