### ISSUE TITLE
Consistent flickering in some chunks

### ISSUE THREAD

**Issue by lukebemish** [jellysquid3/Sodium#869] opened 2021-08-29 21:55 UTC
### Version information

mc1.17.1-0.3.2+build.7

### Expected Behavior

Chunks should all render fairly normally (and not consistently flicker)

### Actual Behavior

Chunks consistently flicker. This does not seem to be true of all chunks; for instance, those in a large desert area did not flicker.

See video: [https://vimeo.com/594303814](https://vimeo.com/594303814)

### Reproduction Steps

1. Enter world
2. See chunk oddness

I suspect that this may be an issue with how Sodium interacts with either my hardware or software (I am running an Ubuntu 21.04 variant). I have confirmed that vanilla minecraft, or minecraft with fabric but no sodium, does not behave this way.

### Java version

Java 16

### CPU

Intel Core i7-1165G7

### GPU

Mesa Intel Xe Graphics (TGL GT2)

### Additional information

Other mods installed:

modmenu 2.0.6
fabric api 0.39.2

**Comment by MenacingPerson** [comment] 2021-09-07 09:04
I can confirm this is related to #853.

**Comment by NightEule5** [comment] 2021-09-08 22:45
My i5-8250U (UHD 620) has the same issue. In the 1.16 version of Sodium, changing the renderer to GL3.0 fixed a similar flickering issue, but there's no option for that in this version. The problem seems to be intromittent for me

**Comment by Rick1029** [comment] 2021-09-14 19:40
I have this issue as well, on an i7-11800H with UHD graphics, TGL GT1. Running Mesa 21.0.1 on Pop_OS! 20.10, kernel 5.14.

This issue is only present when running sodium on 1.17+, and when using the above system but with an rtx 3050ti there is no flickering.

**Comment by jaz3001** [comment] 2021-09-30 03:09
Experiencing the same issue on a i5-1035G1. Got it to consistently flicker using some pistons and tested several graphics settings. Toggling the "chunk memory allocator" under advanced video settings from Async to swap made the flickering much less consistent but didn't fully fix the issue.

**Comment by jellysquid3** [comment] 2021-09-30 03:20
I unfortunately do not understand what's going on here. We had bug reports in an earlier version of Sodium that Intel users were affected by a (very similar) issue to this, but only when moving the camera. It seems that something with the Intel drivers just doesn't like Sodium, or we're doing something that is subtly broken.

Because the terrain flickers even _without_ chunk/block updates, it suggests the draw calls are getting messed up (can't understand how), rather than the chunk data being corrupted by the chunk memory allocator.

If we could get any confirmation that this affects a non-Intel user, that would help significantly. Otherwise, without me having access to an Intel-equipped computer that suffers from this problem, it's not likely I will be able to find or debug the issue. Volunteers are welcome to figure out what's going on here if they have time to debug.

**Comment by lukebemish** [comment] 2021-10-02 03:44
Can we confirm whether this is only present on certain types of intel graphics or on all intel graphics? I noticed that most of the people reporting this issue seem to be using 11th gen processors; just wondering if this is coincidental or important.

Or, alternatively, is anyone able to run sodium on 1.17 with intel graphics and NOT get flickering?

**Comment by lukebemish** [comment] 2021-10-02 04:00
An interesting note relevant to the above; I can no longer reproduce this bug. I set everything up as I had before to attempt to mess with it again today, and found that the flickering no longer occurred. I am currently trying to figure out what changed; I updated several parts of my OS at some point, and also installed a firmware update; this could have been the cause?

**Comment by MenacingPerson** [comment] 2021-10-02 11:02
Sometimes it doesn't occur for me, but when I tab out and back in there's a chance it starts happening.

**Comment by lukebemish** [comment] 2021-10-04 01:56
I tested this a bit more; before, it had been consistently reproducible, no matter what I did. Now, I cannot reproduce it at all. @Rick1029, you mentioned also using Pop!_OS. Did the problem persist for you after installing firmware updates or OS updates? For reference, I am currently on mesa 21.2.1; some apt history searching reveals that I was, at the time of the original issue, using mesa 21.0.1.

**Comment by saadatxyz** [comment] 2021-10-10 15:17
I believe this issue in particular was a result of Xe Graphics having a problem on older Mesa versions: https://gitlab.freedesktop.org/mesa/mesa/-/issues/4454. Newer versions of Mesa do not exhibit this issue. I don't know if this issue is related to the other similar ones, in that case.

**Comment by saadatxyz** [comment] 2021-10-10 15:23
e: Also, cannot reproduce issue on a TGL GT2 on newer versions of Mesa.

**Comment by MenacingPerson** [comment] 2021-10-11 14:58
Changing the chunk memory allocator to swap completely fixed the issue for me (with more lag included). The weird thing is that I already tried this before and it didn't do anything, and there was no driver update or sodium update since then. Toggling the chunk memory allocator back to async made the issue occur again. I've toggled it multiple times, and closed and reopened the game as well. All of the times swap fixed the issue and async brought it back.

Edit: Windows 10, intel 10th gen cpu

**Comment by saadatxyz** [comment] 2021-10-11 15:59
Yeah, I think there's a separate issue between Linux (now old issue) and Windows (a possibly persistent issue).

**Comment by farblos** [comment] 2021-12-15 21:27
@SER-3604 Not sure if you need more confirmation, but for me the patch from https://gitlab.freedesktop.org/mesa/mesa/-/issues/4454 fixed my flickering.  Here the data of my system:

```
Dell Lattitude 7420
Debian GNU/Linux 11 (bullseye)
Intel Corporation TigerLake GT2 [Iris Xe Graphics] (rev 01)
11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
OpenGL version string: 4.6 (Compatibility Profile) Mesa 20.3.5
Minecraft 1.16.4
sodium-fabric-mc1.16.5-0.2.0+build.4
```

I rebuilt the relevant package `libgl1-mesa-dri` including shared library `/usr/lib/x86_64-linux-gnu/dri/iris_dri.so` as of 20.3.5 plus the patch provided in issue 4454: Flickering gone.

**Comment by y2k04** [comment] 2021-12-27 08:22
I started experiencing this issue a couple months ago (around when 1.18 came out) on my computer running Windows 11.

A easy way to show off the entire chunk glitching is by creating a zero-tick piston loop such as the one shown in the video below:
https://drive.google.com/file/d/1dGbeqHpwYrYY1SmPNHr1upArEeGzrXwO/view?usp=sharing

**Comment by Rick1029** [comment] 2022-01-08 07:38
> I tested this a bit more; before, it had been consistently reproducible, no matter what I did. Now, I cannot reproduce it at all. @Rick1029, you mentioned also using Pop!_OS. Did the problem persist for you after installing firmware updates or OS updates? For reference, I am currently on mesa 21.2.1; some apt history searching reveals that I was, at the time of the original issue, using mesa 21.0.1.


Can't reproduce the issue either. Using Sodium 0.3.3, mesa drivers 21.2.2, same hardware as before. I haven't noticed it since upgrading to Pop 21.10 (from 20.10) but then again I haven't touched Minecraft in a while, so this might've been resolved by some system upgrades on 20.10 or 21.04.

**Comment by farblos** [comment] 2022-01-08 11:52
For the record (Linux only):

- Issue: https://gitlab.freedesktop.org/mesa/mesa/-/issues/4412
- Merge Request: https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/9903
- Commit: https://gitlab.freedesktop.org/mesa/mesa/-/commit/0f247cc8a9edafdb2d952d552c4c61d38c1dbfbe

I haven't been able to read the commit graph on https://gitlab.freedesktop.org, but from this [blame](https://gitlab.freedesktop.org/mesa/mesa/-/blame/mesa-21.2.0/src/gallium/drivers/iris/iris_batch.c) I understand that above commit is at least contained in mesa 21.2.0.

**Comment by deeoxys** [comment] 2022-01-09 12:48
Having this issue however this is only occurring for me when I am far out in the world (millions of blocks) and not near spawn.
```
Minecraft 1.18.1
Pop!_OS 21.10
Ryzen 5 3600
Radeon RX 570
sodium 0.4.0-alpha5+build.9
Mesa 21.2.2
```

edit: fixed using `sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14`

**Comment by TheForgottenKing** [comment] 2022-01-16 19:41
> Having this issue however this is only occurring for me when I am far out in the world (millions of blocks) and not near spawn.

I can confirm that I also had this issue when millions of blocks out from spawn. It was quite pronounced, the entire world flickered and stopped rendering randomly. I resolved it by updating to the most recent version of sodium, `mc1.18.1-0.4.0-alpha6`.

```
Minecraft 1.18.1
Windows 11 21H2
Intel Core i7-7500U
Intel HD 620
```

**Comment by Dvdboy42** [comment] 2022-02-05 21:05
This is also happening to me, though only when breaking and placing blocks. I think its from the Intel drivers. This morning I managed to fix it by installing older drivers, but it all got ruined by a windows update, which also updated the drivers to the newest version. Now its flickering again. Also, it seems to flicker way more when close to 0 0 in the w
orld. Here is a video (sorry for being recorded on a phone): 
1. https://drive.google.com/file/d/1XUvyPQBB4w3oWgKB7JhYr8YVSWP0hsjK/view?usp=sharing
2. https://user-images.githubusercontent.com/69913728/152659067-eba0efac-cf53-40f0-a7fa-ad815e19c3fe.mov
 (if the first one doesn't work for some reason)

Minecraft 1.18.1
Windows 10 21H1
Intel(R) Core(TM) i7-1065G7
sodium 1.18.1-0.4.0-alpha6+build.14

**Comment by jessicarod7** [comment] 2022-02-06 01:47
@Dvdboy42 Do you know which version of the drivers seemed to work? I can try to reproduce it on my setup.

**Comment by jessicarod7** [comment] 2022-03-04 01:35
I no longer encounter this issue on the latest version, near spawn or millions of blocks away.

Version: Minecraft 1.18.2
Sodium: 0.4.1+build.15
OS: Windows 11 21H2 (22000.493)
Processor/Graphics: Intel Core i7-1065G7 (Iris Plus)
Driver version: 30.0.101.1340

**Comment by bafgd** [comment] 2022-03-29 22:44
So i recently downloaded Sodium (sodium-fabric-mc1.18.2-0.4.1+build.15.jar) and the flicker still happens to me and i tied loading a new pack even and that wont work. (i have noticed that it only flickers in the chunks the block was placed or broken in)
(Intel Core i5-1035G1 1.00 GHZ)

**Comment by Bitslayn** [comment] 2022-04-26 20:07
Flickering seems to only occur with blocks which do not randomly tick. Chunks also blink when there's any tile update in said chunk. Issues also seem to be tied to the Chunk Memory Allocator setting which when changed to Swap fixes the issue entirely. 
![image](https://user-images.githubusercontent.com/96226175/165383304-d49eaae3-da18-49ab-baf6-0aff4b2ea388.png)

**Comment by izwk** [comment] 2022-04-30 09:26
I had this problem some days ago on my laptop. I updated the graphics drivers and sodium versions and the flickering stopped entirely. If anyone has the same problem, try updating the graphics drivers and sodium versions.

Minecraft: 1.18.2
Sodium: 0.4.1+build.15
OS: Windows 11 21H2 (22000.613)
Processor: Intel(R) Core(TM) i3-1005G1 CPU
Integrated Graphics: Intel(R) UHD Graphics
Graphics Driver Version: 30.0.101.1338

**Comment by Bitslayn** [comment] 2022-04-30 16:08
> I had this problem some days ago on my laptop. I updated the graphics drivers and sodium versions and the flickering stopped entirely. If anyone has the same problem, try updating the graphics drivers and sodium versions.
> 
> Minecraft: 1.18.2 Sodium: 0.4.1+build.15 OS: Windows 11 21H2 (22000.613) Processor: Intel(R) Core(TM) i3-1005G1 CPU Integrated Graphics: Intel(R) UHD Graphics Graphics Driver Version: 30.0.101.1338

Turns out upgrading the graphic driver did the trick

**Comment by dallor09** [comment] 2022-08-25 16:11
for some reason I turned on the YoFPS shaders and it fixed this for me.  I am playing lunar client+sodium beta with an intel(R) core(TM) i5 cpu and an intel(R) UHD graphics gpu.  could something that shaders do fix this?

**Comment by y2k04** [comment] 2022-09-03 04:27
It is still happening for me. It started up again recently.
My mods: https://pastebin.com/rkHNeerD

Video of flickering: https://drive.google.com/file/d/1gOS234eHetskRYxeKsv35B4e6Sp_r0Yl/view

**Comment by Tialo** [comment] 2022-11-21 23:50
I've had the same issue: after breaking blocks had flickering. 

Minecraft: 1.18.2
Sodium: 0.4.1
CPU: Interl i7-1065G7
GPU: Iris Plus Graphics

After updating GPU drivers to the newest version (31.0.101.2114) problem has gone.

**Comment by jellysquid3** [comment] 2023-07-22 01:48
The problem is now extensively reported to be solved by updating the Intel graphics driver. We have also included this issue in our [wiki](https://github.com/CaffeineMC/sodium-fabric/wiki/Driver-Compatibility).

**Closed as completed by jellysquid3** 2023-07-22 01:48 UTC
Labels: T-bug, A-drivers, F-help-wanted
