### ISSUE TITLE
Game crash when attempting to change video options

### ISSUE THREAD

**Issue by lnvaIid** [jellysquid3/Sodium#301] opened 2020-09-10 16:48 UTC
Whenever I attempt to change the game's video settings, it results to:

The game crashed whilst mouseclicked event handler
Error: java.lang.ExceptionInInitializerError
Exit Code: -1

I have been dealing with this ever since I first started using the mod.

**Comment by amnotbananaama** [comment] 2020-09-10 17:05
In the future, please use the templates they exist for a reason. For example, I’m fortunate that I know that crash occurs when you try to use Sodium on 1.16.2. If not, you and I would have wasted a lot of time trying to investigate this.

You’re attempting to use Sodium on 1.16.2, which it doesn’t support. Currently Sodium only supports 1.16.1. This is a known issue and will be fixed when it’s updated.

**Comment by lnvaIid** [comment] 2020-09-10 20:08
It was 1.16.1 for both...

**Comment by amnotbananaama** [comment] 2020-09-10 21:25
Please provide the full crash log. You can find it in the [.minecraft](https://help.minecraft.net/hc/en-us/articles/360035131551-Where-are-Minecraft-files-stored-)/crash-reports folder. The latest one should be the one with your issue.

If you do not see or cannot find it, please provide the full `latest.log` file from .minecraft/logs

**Comment by lnvaIid** [comment] 2020-09-10 21:49
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 9/10/20 4:13 PM
Description: mouseClicked event handler

java.lang.ExceptionInInitializerError
	at me.jellysquid.mods.sodium.client.gui.SodiumOptionsGUI.<init>(SodiumOptionsGUI.java:46)
	at net.minecraft.class_429.handler$zzm000$open(class_429.java:523)
	at net.minecraft.class_429.method_19828(class_429.java)
	at net.minecraft.class_429$$Lambda$2921/1777053705.onPress(Unknown Source)
	at net.minecraft.class_4185.method_25306(class_4185.java:33)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:149)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:92)
	at net.minecraft.class_312$$Lambda$2911/1366152551.run(Unknown Source)
	at net.minecraft.class_437.method_25412(class_437.java:431)
	at net.minecraft.class_312.method_1601(class_312.java:92)
	at net.minecraft.class_312.method_22686(class_312.java:162)
	at net.minecraft.class_312$$Lambda$2910/102776044.run(Unknown Source)
	at net.minecraft.class_1255.execute(class_1255.java:94)
	at net.minecraft.class_312.method_22684(class_312.java:162)
	at net.minecraft.class_312$$Lambda$2263/845739620.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:102)
	at net.minecraft.class_1041.method_15998(class_1041.java:308)
	at net.minecraft.class_310.method_1523(class_310.java:1041)
	at net.minecraft.class_310.method_1514(class_310.java:654)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at com.google.gson.Gson.fromJson(Gson.java:825)
	at me.jellysquid.mods.sodium.client.gui.SodiumGameOptions.load(SodiumGameOptions.java:147)
	at me.jellysquid.mods.sodium.client.SodiumClientMod.loadConfig(SodiumClientMod.java:37)
	at me.jellysquid.mods.sodium.client.SodiumClientMod.options(SodiumClientMod.java:22)
	at me.jellysquid.mods.sodium.client.gui.options.storage.SodiumOptionsStorage.<init>(SodiumOptionsStorage.java:10)
	at me.jellysquid.mods.sodium.client.gui.SodiumGameOptionPages.<clinit>(SodiumGameOptionPages.java:26)
	... 32 more
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213)
	... 39 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.jellysquid.mods.sodium.client.gui.SodiumOptionsGUI.<init>(SodiumOptionsGUI.java:46)
	at net.minecraft.class_429.handler$zzm000$open(class_429.java:523)
	at net.minecraft.class_429.method_19828(class_429.java)
	at net.minecraft.class_429$$Lambda$2921/1777053705.onPress(Unknown Source)
	at net.minecraft.class_4185.method_25306(class_4185.java:33)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:149)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:92)
	at net.minecraft.class_312$$Lambda$2911/1366152551.run(Unknown Source)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_429
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:431)
	at net.minecraft.class_312.method_1601(class_312.java:92)
	at net.minecraft.class_312.method_22686(class_312.java:162)
	at net.minecraft.class_312$$Lambda$2910/102776044.run(Unknown Source)
	at net.minecraft.class_1255.execute(class_1255.java:94)
	at net.minecraft.class_312.method_22684(class_312.java:162)
	at net.minecraft.class_312$$Lambda$2263/845739620.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:102)
	at net.minecraft.class_1041.method_15998(class_1041.java:308)
	at net.minecraft.class_310.method_1523(class_310.java:1041)
	at net.minecraft.class_310.method_1514(class_310.java:654)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 474299688 bytes (452 MB) / 1476395008 bytes (1408 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 2
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: fabric-loader-0.9.3+build.207-1.16.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) HD Graphics GL version 4.0.0 - Build 10.18.10.4425, Intel
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 2x Intel(R) Celeron(R) CPU N2840 @ 2.16GHz

[note from person reporting the crash on github: yeah, ik my specs are kind of slow. but it usually gets past this without the use of sodium]

**Comment by amnotbananaama** [comment] 2020-09-10 22:01
Duplicate of #211 and #219. Something is wrong with Sodium’s config file. If you’ve edited it manually, you’ll need to fix it to make the file valid JSON. If you’re using other mods that are breaking this file, report it to those authors. 

> Your config file is corrupted. Delete the `sodium-options.json` file from your game's `config` folder. 

In the next release, Sodium will reset the config file to default rather than crash if it is invalid.

**Closed as completed by amnotbananaama** 2020-09-10 22:01 UTC
Labels: E-duplicate, T-crash
