### ISSUE TITLE
Game Crashes When Opening Any World

### ISSUE THREAD

**Issue by PilotgamerGuy** [jellysquid3/Sodium#959] opened 2021-11-03 01:23 UTC
### Version information

sodium-extra-mc1.17.1-0.3.4.jar

### Reproduction Steps

Probable:
1. Start removing entities in the world files using some NBT Editor or just removing the entities folder.
2. Make sure sodium is installed and attempt to open the world that you edited.
3. Game should crash.

### Crash Report file

https://bytebin.lucko.me/ax5SOph8rA

### Additional information

I am also using reeses_sodium_options-mc1.17.1-1.2.0.jar, and iris-and-sodium-mc1.17-1.1.2+build.9.jar

I was editing nbtData of one specific world, when one time when I tried to open a world, it failed. I tried opening other worlds that wasn't edited, but the game also crashed. However, when running the vanilla version (just 1.17.1), all the worlds can be opened. So I do not think this is the trigger, but it was the only thing that could have caused the crashes.

The only reason I believe sodium is causing this crash is because not enough crashes says sodium is a likely cause.

I also have a a lot of other mods, if you need the full list, please mention.

**Comment by coderbot16** [comment] 2021-11-03 02:13
You should try to reproduce this without NotEnoughCrashes installed as well as with the official version of Sodium.

NotEnoughCrashes often has the effect of letting the game limp along for a little bit longer after a fatal crash until the game inevitably explodes somewhere else, which has the side effect of often making it hard to get useful diagnostic information out of crash reports when NotEnoughCrashes is installed.

**Comment by PilotgamerGuy** [comment] 2021-11-04 18:50
I tried putting the official sodium version mod into the mod folder but it says to remove it because iris is installed (picture attached). Also if I just don't put sodium in the mods folder the game is able to fine (I can open all worlds). I think it is just a problem with sodium extra.
![image](https://user-images.githubusercontent.com/67031448/140400372-2d02bc57-d4ea-4b85-b6d8-41af2391c947.png)

Otherwise, the only difference is that I no longer have a FPS counter and coordinates without using F3 but I guess that is fine.

**Comment by amnotbananaama** [comment] 2021-11-18 19:35
You cannot use Iris 1.1.2 and Sodium together at the moment. That version of Iris bundles a modified version of Sodium, which is why you see that error message.

> I think it is just a problem with sodium extra.  
  
Unfortunately your log has expired, so I will have to go off this assumption. Sodium Extra is a (great) third party mod that we don't control, and is produced by another developer. You should report any issues with Sodium Extra to their issue tracker.

I'm going to close this as an external issue, as it seems clear your crash is caused by something other than Sodium.

**Closed as completed by amnotbananaama** 2021-11-18 19:35 UTC
Labels: E-external, T-crash
