### ISSUE TITLE
Blocks not rendering at chunk borders (see-through chunks)

### ISSUE THREAD

**Issue by matejbrezovic** [jellysquid3/Sodium#1522] opened 2022-11-27 12:52 UTC
### Version information

mc1.19.2-0.4.4+build.18

### Expected Behavior

Blocks should render normally within selected render distance.

### Actual Behavior

Blocks don't render in specific situations. I wasn't able to replicate the issue in any other world, but I am quite sure that it is an issue with sodium. I use a lot of mods so I isolated Sodium and Oh the Biomes You'll Go, and the issue was still there. The game doesn't render blocks in certain relatively small areas, like when there is a passage or a small hole, all within one chunk wide. It just shows what is at the other side so it's kinda like x ray, I can see caves and surfaces through such holes which normally I wouldn't be able to. It really destroys the immersion in the game. It is the same even if I don't use BYG and don't use any resource packs, sodium only. Here are some images of the issue. It seems that while I am in the same chunk as the place where the bug happens, it doesn't happen, but if I am outside of the chunk the bug appears.

Link to the zipped save: https://we.tl/t-COvseCJPPo

![2022-11-27_11 56 43](https://user-images.githubusercontent.com/66316617/204133454-83ddde6a-0d62-46c5-9b1b-872425c44414.png)
![2022-11-27_11 56 56](https://user-images.githubusercontent.com/66316617/204133458-4d6dd72d-252a-4432-b73e-ec68a41fa2fb.png)
![2022-11-27_11 57 19](https://user-images.githubusercontent.com/66316617/204133463-ae25333b-a182-46a1-aa7b-d0806eff0668.png)
![2022-11-27_11 57 30](https://user-images.githubusercontent.com/66316617/204133473-0e7dba96-956f-41ce-b2e9-02b1c191d787.png)
![2022-11-27_11 57 34](https://user-images.githubusercontent.com/66316617/204133486-b0e8e20b-a291-4bb9-b53e-21057ee1bc05.png)
![2022-11-27_11 57 54](https://user-images.githubusercontent.com/66316617/204133489-234c42e2-2e69-43b0-a789-d6a6db873796.png)
![2022-11-27_12 05 29](https://user-images.githubusercontent.com/66316617/204133493-b2c7512a-2c95-488a-9d36-6702f5119a42.png)
![2022-11-27_12 05 54](https://user-images.githubusercontent.com/66316617/204133503-06034a74-8bfc-46ea-9b84-d4ffbcd6f233.png)
![2022-11-27_12 05 59](https://user-images.githubusercontent.com/66316617/204133508-fc767d65-dff3-4431-a8cb-5d74842cb862.png)
![2022-11-27_12 07 37](https://user-images.githubusercontent.com/66316617/204133509-73f356e3-0143-4a25-9a5e-827220cf67ae.png)
![2022-11-27_12 07 39](https://user-images.githubusercontent.com/66316617/204133514-894468c1-6b6a-4eac-85ea-efa2c12d2266.png)

### Reproduction Steps

I didn't manage to reproduce this issue in any other world. That's why here is a link to a zipped folder of my save. I have removed all the unnecessary chunks and dimensions. It looks a bit cursed because I tried it without BYG so some modded blocks aren't there. That's why the bug in my base at staircase going down isn't happening, probably because there aren't any stairs now as they were modded from BYG wood type and once I loaded the game with sodium only they were destroyed. Other two situations are still affected (at the side of the mountain and in caves). You can try removing and adding some blocks to the areas affected by the bug to see how the bug will behave. You can see the coords or those areas in the top left in screenshots. These aren't the only places this has happened, but are the ones I know the locations of. It happened in the caves in a few more places. 

### Java version

Java 17.0.1 64bit

### CPU

Ryzen 5 2600X

### GPU

Nvidia GeForce GTX 1650 SUPER

**Comment by pajicadvance** [comment] 2023-05-10 17:23
Duplicate of #872.

**Closed as not planned by pajicadvance** 2023-05-10 17:23 UTC
Labels: T-bug, E-duplicate
