### ISSUE TITLE
Fps not applying

### ISSUE THREAD

**Issue by Pumpidunki** [jellysquid3/Sodium#1391] opened 2022-07-20 09:56 UTC
### Version information

mc1.19 fabric-loader 0.14.8 

### Expected Behavior

Than fps apply after rebooting game.

### Actual Behavior

When I boot the game and going to the graphics part my fps are locked at 140 fps and when I change it to 145 fps, apply and close the settings, the game its limited to 145 fps but when I open the graphics settings, its sets to 140 fps and by rebootings the game, its sets on its own to 140 fps. The same happens with 155 fps, 165 fps, 175 fps, 185 fps, 195 fps... The things is than every time i open the game I need to change the fps value. 

https://drive.google.com/file/d/12fyZyhosfCC4YsrxhBK3dAtiHvNxnGqH/view?usp=sharing (Video)

### Reproduction Steps

1. Enter graphic settings set fps to 145 fps
2. Fps should apply
3. Restart game.
4. Fps will be locket to 140 fps

### Java version

java version 1.8.0_321

### CPU

AMD Ryzen 5 5600X 6-Core Processor

### GPU

NVIDIA GeForce RTX 3060 Ti

### Additional information

![Captura de pantalla 2022-07-20 115131](https://user-images.githubusercontent.com/109632690/179953448-be709480-fbaa-4da0-a9b6-0bb3cc48a5f0.png)

**Comment by PweSol** [comment] 2022-08-03 00:14
I can confirm this issue. The FPS gets applied for the current session but doesn't save for the next one. This only happens with 1.19.x version.

**Comment by EsterMew** [comment] 2022-08-20 00:47
It also happen to me, i have the same GPU and my fps stuck at 60. I need to resetting my monitor to get 144 fps but when i leaving minecraft, even only change the window for another application (alt+tab) it come back to 60 fps

**Comment by Oyssis** [comment] 2022-08-30 13:06
this was fixed in 0.4.3

**Comment by EsterMew** [comment] 2022-10-04 13:50
Still happen after i update my Nvidia driver

**Comment by Oyssis** [comment] 2022-10-09 05:36
its not an issue with your driver its an issue with sodium and it was fixed in the latest version

**Comment by EsterMew** [comment] 2022-10-11 12:45
I know it's not my driver problem. And yes, It has been fixed before, I've updating my sodium version and the issue is disappear, but then after i update my nvidia driver my fps is stuck again, same issues is still happening for me

**Comment by EsunR** [comment] 2022-10-13 15:25
Amd 6600xt also has the same problem, I need to restart the system to solve

**Comment by EsterMew** [comment] 2022-10-27 13:58
I just discover when this problem happen, if i disable my vsync setting my fps goes to above 500

**Comment by piuvas** [comment] 2023-05-03 00:01
should be closed.

**Closed as completed** 2023-05-10 17:53 UTC
Labels: T-bug, E-external
