### ISSUE TITLE
Block model cuboids and their textures are misaligned compared to vanilla

### ISSUE THREAD

**Issue by WeegeeTheDoggo** [jellysquid3/Sodium#1902] opened 2023-07-22 12:08 UTC
### Bug Description

Expected: Block models and textures to line up as they normally do in vanilla

Actual: Block models and textures are slightly out of line

I believe this to be a bug. It does not happen with any other mods, or just by using Fabric itself, or in vanilla. I'm not aware of a setting that could remedy this, after looking through all the in-game settings for Sodium and testing each one. This bug affects an unknown number of block models, but I can verify it in end rods, torches, and fences. I expect that it affects many more.

Normal:
![2023-07-22_07 35 25](https://github.com/CaffeineMC/sodium-fabric/assets/47928239/74f9af8a-fe65-4e8c-ab22-ac58eb17f104)
Using Sodium:
![2023-07-22_07 33 26](https://github.com/CaffeineMC/sodium-fabric/assets/47928239/733ff24a-8cc1-4e95-9c32-c05cb7a00d9a)

### Reproduction Steps

- Make sure fabric-loader-0.14.21-1.20.1 is installed
- Download fabric-api-0.86.0+1.20.1 and sodium-fabric-mc1.20-0.4.10+build.27 and place them into the mods folder
- Launch Minecraft Launcher
- Select fabric-loader-0.14.21-1.20.1 profile
- Wait for game to load, then enter a world and look closely at block model (such as end rod) (use spectator mode if needed)

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12136305/latest.log)

### Crash Report

[crash-2023-07-22_07.39.29-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12136303/crash-2023-07-22_07.39.29-client.txt)

**Comment by pajicadvance** [comment] 2023-07-25 17:59
I can reproduce this on my system.

**Comment by muzikbike** [comment] 2023-08-12 21:15
Vanilla has its own alignment issues with models as well. (#1316)

I wonder if it'd be possible for Sodium to fix this issue and the vanilla cases as well (#1607). There exist mods such as Model Gap Fix and Model Fix Multi which resolve vanilla's issues with this, so integrating such a fix into Sodium as well so that more people can benefit would be a nice touch.

**Comment by jellysquid3** [comment] 2023-08-14 18:20
We can't really fix any of these vertex precision issues until the fluid renderer is rewritten to not abuse them. At that point, it should become possible to correct the off-by-one issue which affects texture coordinates, since it won't cause texture gaps in fluid rendering.

**Comment by jellysquid3** [comment] 2024-04-29 06:37
The issue described here should be fixed with https://github.com/CaffeineMC/sodium-fabric/commit/ea0172768a5da9907b5a5711160dc3984fafea83.

**Closed as completed by jellysquid3** 2024-04-29 06:37 UTC
Labels: T-bug, S-confirmed, A-vanilla-parity
