### ISSUE TITLE
Mod confilct with OptiFabric Mod. 

### ISSUE THREAD

**Issue by Triheron** [jellysquid3/Sodium#483] opened 2021-01-18 08:25 UTC
Error:
```
Found conflicting mods: sodium conflicts with {optifabric @ [*]}
    Creating Empty clause ?

```
Could you fix it?

**Comment by dbl7id** [comment] 2021-01-18 08:27
Optifine and sodium will never work together.
Both mods change how the game renders so they conflict with each other.

**Comment by LambdAurora** [comment] 2021-01-18 08:28
Optifine and Sodium both replace the game renderer, they can't work together at all.

Also duplicate of #132.

**Closed as completed by LambdAurora** 2021-01-18 08:28 UTC
Labels: E-duplicate, E-will-not-fix, T-crash

**Comment by msufyany** [comment] 2021-08-05 12:40
Can you make sodium and optifabric? Or texture pack
