### ISSUE TITLE
Game crashes with EXCEPTION_ACCESS_VIOLATION when loading chunks quickly

### ISSUE THREAD

**Issue by ChristopherHaws** [jellysquid3/Sodium#1448] opened 2022-09-01 04:25 UTC
### Version information

mc1.19.2-0.4.4+build.18

### Reproduction Steps

All I need to do to reproduce this is load chunks quickly by flying fast in the overworld.

### Crash Report file

Minecraft Log:
https://mclo.gs/RLzvLsr

Crash Report:
https://mclo.gs/j18dvzx

**Comment by gudenau** [comment] 2022-09-13 16:16
Someone managed to trigger this, or a very similar error.

[hs_err_pid18836.txt](https://github.com/CaffeineMC/sodium-fabric/files/9558904/hs_err_pid18836.txt)

**Comment by XspeedPL** [comment] 2022-09-13 22:54
I managed to trigger it when having multiple video players open, the issue could be related to VRAM?

**Comment by ChristopherHaws** [comment] 2022-09-13 23:16
I have a GeForce 2080 Super which has 12gb of RAM. I would be very surprised if MC was eating up that much VRAM unless there was a massive memory leak xD

**Comment by jadelily18** [comment] 2022-10-13 14:25
I'm having the [same issue](https://mclo.gs/fd6iK2w) running a 3090 with 24GB VRAM :')

**Comment by RedSyven** [comment] 2022-11-02 18:49
I have the same issue, it happens consistently when holding f3+a. Also happened after playing a while and pressing f3+t once.

**Comment by radiant-ai** [comment] 2022-12-07 14:10
I am a server owner and I recommend using Sodium for all players. Recently I have more and more complaints about exactly same error happening for people. It started to happen for them after they updated their video drivers. They are forced to switch to Optifine until this is resolved.

**Comment by elboletaire** [comment] 2023-02-27 19:08
If any of you having these issues have the "iris shaders" mod installed (no need to have shaders enabled btw), remove it and give it a try. 

I've been the past two hours trying everything with and without the iris mod (thanks to what's said in #1486) and, even tho [they say this is a sodium issue](https://github.com/IrisShaders/Iris/issues/884#issuecomment-927171034), the fact is that I could not reproduce none of these issues with iris removed from my mods folder.

Instead, having iris installed I've been able to reproduce all the issues described here: crashes crossing nether portals, crashes while flying (fast load of chunks), and even crashes walking or changing settings (I could enable shaders, but it crashed with this error when disabling them).

**Comment by IMS212** [comment] 2023-02-27 19:21
This is not caused by Iris; however, Iris makes it happen more often.

The real cause is Litematica, and a fix has been in place for over a month. You just need to update your mods.

**Comment by elboletaire** [comment] 2023-02-28 14:31
> This is not caused by Iris; however, Iris makes it happen more often.
> 
> The real cause is Litematica, and a fix has been in place for over a month. You just need to update your mods.

That's a terrible luck from my side... it's the only mod I did not upgrade (had its previous version installed). Thanks for the heads-up!

**Closed as completed** 2023-05-10 17:43 UTC
Labels: A-mods, T-crash, S-fixed
