### ISSUE TITLE
Boat causing crash with the new vertex writing

### ISSUE THREAD

**Issue by Grayray75** [jellysquid3/Sodium#450] opened 2020-12-27 18:50 UTC
### Reproduction Steps
Unfortunately I can't give much information on how to recreate the crash.

1. I join my world and fly to a specific area
2. The game crashes with: java.lang.IllegalArgumentException: Backing buffer is using vertex format

### Crash Report File
https://gist.github.com/Grayray75/050ccdc3cb9be64f6ad33bedbc1f7911

### Additional Information
This crash only happens to me only in a specific area, not anywhere else.
I'm using the latest version of the "1.16.x/next" branch.

If necessary, I can provide additional informations.

**Comment by Heitzenberg** [comment] 2020-12-27 19:01
Can confirm.

**Comment by ImperatorStorm** [comment] 2020-12-27 19:02
Known bug with Boat rendering, seems to be a regression from test build fvs4

**Comment by Numpty-Clodpole** [comment] 2020-12-27 22:53
I can also confirm this crash: https://pastebin.com/Hed5BZLB
Built from the latest commit.

**Comment by jellysquid3** [comment] 2020-12-27 23:20
Fixed with f25ea17.

**Closed as completed by jellysquid3** 2020-12-27 23:20 UTC
Labels: T-crash, S-confirmed
