### ISSUE TITLE
World keeps glitching is i use sodium

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#1367] opened 2022-06-28 16:08 UTC
### Version information

sodium-fabric-mc1.19-0.4.2+build.16    --for 1.19

### Expected Behavior

the game to run more smoothly

### Actual Behavior

The world glitches every time i place a block or if a block update happens
[https://youtu.be/GXJ_DI2M708](url)

### Reproduction Steps

I have no idea why this is happening or how to make it

### Java version

17.0.3

### CPU

Intel Core i5-1035G1

### GPU

Intel UHD Graphics

### Additional information

I also use wthit, starlight and nofog as well as the fabric api

**Comment by offbeat-stuff** [comment] 2022-06-28 16:10
how are u using java 8 to run mc 1.19

**Comment by ghost** [comment] 2022-06-28 16:12
> 

um how do i check which one i use?

**Comment by offbeat-stuff** [comment] 2022-06-28 16:25
f3 menu

**Comment by offbeat-stuff** [comment] 2022-06-28 16:25
send a screenshot of f3 menu
press f3 then f2

**Comment by offbeat-stuff** [comment] 2022-06-28 16:26
also send your log file probably from
%APPDATA%/.minecraft/logs/latest.log

**Comment by ghost** [comment] 2022-06-28 17:09
ah its 17.0.3

**Comment by burgerindividual** [comment] 2022-07-09 00:48
Hopefully one of the new chunk render backends in 1.19 will fix this issue. I have absolutely no clue what is going on here, and not a lot of info was provided.

**Comment by huskeee** [comment] 2022-07-09 20:38
> I have absolutely no clue what is going on here, and not a lot of info was provided.

Same bug here. Whenever you place/remove/update a block, the entire chunk reloads. There's a 95% probability of it happening, and while not game breaking per se, it is really annoying.

**Comment by Minesartz** [comment] 2022-07-27 20:40
I'n having the exact same problem. It's glitching above y=64-63 where a random bunch of blocks reloads or whatever im looking at. happens to give me the ability to see through the ground. This happens when I break place or a block updates on its own or if I'm doing it like has been mentioned by @huskeee. And yes... it is EXTREMELY annoying...

**Comment by jellysquid3** [comment] 2023-07-22 02:26
This is a duplicate of https://github.com/CaffeineMC/sodium-fabric/issues/869.

**Closed as not planned by jellysquid3** 2023-07-22 02:26 UTC
Labels: T-bug, E-duplicate
