### ISSUE TITLE
Above a certain Y coordinate all the blocks in a chunk overlap and form a flat plane. Underneath this plane, all of the textures of the blocks in the chunk are floating around the player.

### ISSUE THREAD

**Issue by Sophoster** [jellysquid3/Sodium#215] opened 2020-07-30 21:46 UTC
![2020-07-30_14 06 44](https://user-images.githubusercontent.com/65441911/88976332-b4d13100-d270-11ea-8099-82f786609d69.png)
![2020-07-30_14 06 51](https://user-images.githubusercontent.com/65441911/88976360-c0bcf300-d270-11ea-9af9-50a5dca1494a.png)
![2020-07-30_14 15 41](https://user-images.githubusercontent.com/65441911/88976380-cb778800-d270-11ea-8a77-89f93e3a4fc6.png)

Operating System: Windows 8.1 64-bit (6.3, Build 9600)
System Manufacturer: ASUSTeK COMPUTER INC.
System Model: TX201LA
Processor: Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz 2.30 GHz
Memory: 4096 MB RAM
Page file: 6732MB used, 6436MB avaliable
DirectX Version: DirectX11

- Java Version: 1.16.1
- CPU: 1.60GHz 2.30 GHz
- GPU: idk

**Comment by LucilleTea** [comment] 2020-07-31 01:03
Duplicate of #179 
You can work around the issue by disabling the Multi-Draw chunk renderer in the Advanced tab of the video settings.

**Comment by Sophoster** [comment] 2020-07-31 02:57
thank you

**Closed as completed** 2020-08-15 00:31 UTC
Labels: T-bug, E-duplicate
