### ISSUE TITLE
Nether portal and end portal 

### ISSUE THREAD

**Issue by lll100327** [jellysquid3/Sodium#1499] opened 2022-11-02 16:49 UTC
### Version information

1.19.2 0.4.4 and other versions 

### Reproduction Steps

1. enter the nether portal
2. loading terrain
3. crash the game without error code

### Crash Report file

Without

**Comment by jellysquid3** [comment] 2022-11-02 17:32
duplicate of #1486

**Closed as completed by jellysquid3** 2022-11-02 17:32 UTC
Labels: E-duplicate, T-crash
