### ISSUE TITLE
Lags when crossing chunk borders

### ISSUE THREAD

**Issue by SerhiiNadtoka** [jellysquid3/Sodium#954] opened 2021-10-27 17:27 UTC
### Version information

sodium-fabric-mc1.17.1-0.3.2+build.7

### Expected Behavior

Smooth gameplay.

### Actual Behavior

Lags happen when moving from one chunk to another.

### Reproduction Steps

Moving around in any world.

### Java version

Java 16

### CPU

Ryzen 5 5600H

### GPU

RTX 3050 Mobile 80W

### Additional information

Despite the pretty decent CPU and GPU, I can't help noticing lags exactly when crossing chunk borders. I think this might be caused by the lack of optimization to the new Ryzen processors because I played on weaker ones like Ryzen 5500U and 4700U (with an older Zen 2 architecture) and everything was fine and no lags occurred. But I don't consider it a hardware problem, because when playing with Optifine there are no lags too. I love Sodium though, and I dream about seeing this problem resolved.

**Comment by SerhiiNadtoka** [comment] 2021-10-27 19:32
Also, I have this issue with the vanilla version of Minecraft, it seems that only Optifine is able to fix it. Maybe because of the option of lazy chunks loading, I don't know.

**Comment by CesarASC** [comment] 2021-10-27 19:41
Yes, it's a bug since 1.14.4 version 
https://bugs.mojang.com/browse/MC-162253

**Comment by SerhiiNadtoka** [comment] 2021-10-27 19:44
I'm surprised that I haven't encountered it while playing on a weaker laptop, also it's strange that such a great mod as sodium has not fixed it.

**Comment by ghost** [comment] 2021-10-28 12:04
I have this problem too
I have intel core i5 7th gen

**Comment by jellysquid3** [comment] 2021-10-29 17:27
It's probably related to the issue described with #909.

**Comment by SerhiiNadtoka** [comment] 2021-10-29 17:40
Can I sign up as a tester for early builds of Sodium versions targeting this issue? Also, it’s surprising that not all the processors are affected.

**Comment by mikesbytes** [comment] 2021-11-09 22:01
Confirmed on my end as well, ryzen 5950x + vega 64 + 64gb memory with 16gb allocated and zgc scheduler running under arch linux. Solid 144fps on max render distance but tanks when crossing certain chunk borders around my house, especially walking across chunk corner.

Occurs in vanilla, with sodium, and with optifine. Looks to be the issue that @CesarASC mentioned. Sodium does improve the frame drops a bit, but not by a lot.

Phosphor does appear to mostly fix this issue. It still drops frames on certain chunk borders but it hangs for more like 10-20ms instead of 100-200ms. Issue seems to be related to having blocks high up with space underneath which is exacerbated by playing on an amplified world. My guess is the vanilla algorithm for heightmapping for sunlight is poorly optimized and not concurrent.

**Comment by MeeniMc** [comment] 2023-05-11 04:21
This is a well known Vanilla issue, presumably fixed in MC 1.20

https://bugs.mojang.com/browse/MC-162253

**Comment by jellysquid3** [comment] 2023-07-22 02:23
Per changes in policy on our issue tracker, we are closing issues which are general inquiries about performance issues and such. If you are experiencing performance issues and need help, then please use the [Discord server](https://caffeinemc.net/discord).

**Closed as not planned by jellysquid3** 2023-07-22 02:23 UTC
Labels: S-needs-triage
