### ISSUE TITLE
game don't crash... the world does

### ISSUE THREAD

**Issue by Alen-Gorner** [jellysquid3/Sodium#2557] opened 2024-06-19 01:36 UTC
### Bug Description

when open the game there is no problem with any other mod but as soon i install sodium 0.5.9 fabric, quite 1.21 world don't even start it's like {click on world - 0 to 100 - save the world - close the Minecraft program} and i only from starting the world not the game

### Reproduction Steps

when open the game there is no problem with any other mod but as soon i install sodium 0.5.9 fabric, quite 1.21 world don't even start it's like {click on world - 0 to 100 - save the world - close the app} and i only from starting the world not the game

### Log File

[latest.log](https://github.com/user-attachments/files/15894225/latest.log)
[2024-06-19-7.log.gz](https://github.com/user-attachments/files/15894231/2024-06-19-7.log.gz)
[2024-06-19-6.log.gz](https://github.com/user-attachments/files/15894233/2024-06-19-6.log.gz)
[2024-06-19-5.log.gz](https://github.com/user-attachments/files/15894235/2024-06-19-5.log.gz)

### Crash Report

no report

**Comment by jellysquid3** [comment] 2024-06-19 02:14
> game doesn't crash... the world does.

![image](https://github.com/CaffeineMC/sodium-fabric/assets/1363084/7d0b3b58-6288-4995-882f-84bff516bc2e)

**Comment by jellysquid3** [comment] 2024-06-19 02:15
This is a duplicate of https://github.com/CaffeineMC/sodium-fabric/issues/2552. The clouds texture in your resource pack is all empty and the game crashes because it tries to render the vast empty space of nothingness. It will be fixed in a future version.

**Closed as not planned by jellysquid3** 2024-06-19 02:15 UTC
Labels: E-duplicate
