### ISSUE TITLE
Compatibility issue with TechReborn

### ISSUE THREAD

**Issue by Logic530** [jellysquid3/Sodium#106] opened 2020-07-18 08:02 UTC
### Expected Behavior
Cells and Buckets item render normally.
[TechReborn](https://www.curseforge.com/minecraft/mc-mods/techreborn)

### Actual Behavior
Cells and Buckets item become invisible.

### Reproduction Steps
Install Sodium with TechReborn.

### Attachments
![image](https://user-images.githubusercontent.com/22793670/87847955-9e40e680-c90e-11ea-96a1-2660c653771f.png)
In this screenshot, "empty" slots are actually items, which becomes invisible.

### System Information
This issue should have noting to do with my system, filling anyway.

- Java Version: 1.8.0
- CPU: Intel i5-5200U
- GPU: Mesa Intel HD Grapics 5500

**Comment by amnotbananaama** [comment] 2020-07-18 15:00
Tech Reborn [uses the Fabric Rendering API (FRAPI)](https://github.com/TechReborn/TechReborn/blob/c4ef977f16c28761e8d04214d50d1f701c55f3fe/src/main/java/techreborn/client/render/BaseDynamicFluidBakedModel.java) to render models, which is why they are not visible. This is a duplicate of #5 which is on the [Roadmap](https://github.com/jellysquid3/sodium-fabric/wiki/Roadmap) to be fixed soon!

**Comment by jellysquid3** [comment] 2020-07-25 18:11
Closing as #5 covers this issue.

**Closed as completed by jellysquid3** 2020-07-25 18:11 UTC
Labels: T-bug, E-duplicate
