### ISSUE TITLE
The game crashed whilst encountered exception while building chunk meshes

### ISSUE THREAD

**Issue by Yellowsam4145** [jellysquid3/Sodium#2184] opened 2023-11-27 01:45 UTC
### Bug Description

All I know is sodium is doing it. Might be an incompatibility problem.

```
The game crashed whilst encountered exception while building chunk meshes
Error: java.lang.NullPointerException: Cannot read field "permissions" because "net.minecraft.class_836.avatar" is null
```

In the crash file:

at me.jellysquid.mods.**_sodium_**.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:119)

### Reproduction Steps

Some chunks just cause this, no other way I could find the crash.

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/13468892/latest.log)

### Crash Report

[crash-2023-11-26_17.33.50-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/13468835/crash-2023-11-26_17.33.50-client.txt)

**Comment by Yellowsam4145** [comment] 2023-11-27 01:48
NOTE:
I'm using Quilt, may have to do with something.

**Comment by alekso56** [comment] 2023-11-27 02:00
Duplicate of https://github.com/CaffeineMC/sodium-fabric/issues/2032

**Closed as not planned** 2023-11-27 02:20 UTC
Labels: E-duplicate
