### ISSUE TITLE
Cant change resolution of game 

### ISSUE THREAD

**Issue by Inys11** [jellysquid3/Sodium#240] opened 2020-08-07 05:35 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by amnotbananaama** [comment] 2020-08-07 05:45
Duplicate of #46 

Use `Shift + P` in "Video Settings" as a workaround.

**Closed as completed** 2020-08-08 17:55 UTC
Labels: E-duplicate, T-enhancement
