### ISSUE TITLE
Glass rendering issues

### ISSUE THREAD

**Issue by srcomptn** [jellysquid3/Sodium#2394] opened 2024-03-28 18:57 UTC
### Bug Description

Viewing glass blocks/panes through other glass panes or blocks will cause the distant blocks not to render correctly.

Showing the setup:
![shot_240328_185141](https://github.com/CaffeineMC/sodium-fabric/assets/92361528/79249b19-8c0a-4761-88d0-f1325057a614)

Showing how blocks/panes are not rendered correctly when viewing through glass:
![shot_240328_185128](https://github.com/CaffeineMC/sodium-fabric/assets/92361528/d3cb7766-c794-4821-86b1-3487d8c5d6c1)

I could not replicate this with normal glass, only coloured glass.

### Reproduction Steps

Its as simple as placing down a 2x4 set of glass panes, then viewing them through another glass block/pane. Usually changing the angle you're looking at them from changes this. 

### Log File

[2024-03-28-5.log](https://github.com/CaffeineMC/sodium-fabric/files/14794260/2024-03-28-5.log)

### Crash Report

[crash-2024-03-28_18.57.05-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/14794275/crash-2024-03-28_18.57.05-client.txt)

**Comment by douira** [comment] 2024-03-28 19:01
Duplicate of #38 which has been fixed. The fix is going to be released in the next update of sodium.

**Comment by srcomptn** [comment] 2024-03-28 23:20
> Duplicate of #38 which has been fixed. The fix is going to be released in the next update of sodium.

Sorry, missed this. Closed my issue

**Closed as not planned** 2024-03-28 23:19 UTC
Labels: S-needs-triage
