### ISSUE TITLE
Blocks Everywhere

### ISSUE THREAD

**Issue by izzmylk** [jellysquid3/Sodium#352] opened 2020-10-15 17:48 UTC
### Expected Behavior
I expected for a clean fps mod so I can run Minecraft above 35 fps on my Laptop.

### Actual Behavior
When I ran Minecraft and went into a world there was a ton of blocks in my screen.

### Attachments
![2020-10-15_10 31 39](https://user-images.githubusercontent.com/72905488/96167173-daff8800-0ed3-11eb-9100-09a1eb992135.png)
![2020-10-15_10 32 37](https://user-images.githubusercontent.com/72905488/96167180-de930f00-0ed3-11eb-92c0-c78a92e17a06.png)

### System Information

- Java Version: [1.8.0_261]
- CPU: [Intel(R) Core (TM) i3-3227U CPU @ 1.90GHz  1.90Ghz]
- GPU: [Intel(R) HD Graphics 4000]

**Comment by amnotbananaama** [comment] 2020-10-15 17:59
This sounds like a duplicate of #179. You can workaround this by going to Options -> Video Settings -> Advanced and setting "Chunk Renderer" to 3.0 or 2.1. This should fix your issue for now.

This will be fixed in the next release of Sodium.

**Closed as completed by amnotbananaama** 2020-10-15 17:59 UTC
Labels: T-bug, E-duplicate
