### ISSUE TITLE
You can't see glass panes through other glass panes in the same chunk higher than you are

### ISSUE THREAD

**Issue by Insane96** [jellysquid3/Sodium#356] opened 2020-10-17 07:05 UTC
### Expected Behavior
See glass panes through glass panes blocks correctly

### Actual Behavior
You can't see glass panes through other glass panes in the same chunk higher than you are.
After some testing this turned out to be more complicated. Check screenshots at the bottom.

### Reproduction Steps
1. Build two walls of colored glass panes in the same chunk
2. Look through one of them
3. Profit

### Attachments
![2020-10-17_08 55 42](https://user-images.githubusercontent.com/7185104/96330691-97ce2200-1057-11eb-9bba-edece9798ad3.png)
![2020-10-17_08 55 46](https://user-images.githubusercontent.com/7185104/96330692-98ff4f00-1057-11eb-8e66-62c6ff47b718.png)
![2020-10-17_09 01 27](https://user-images.githubusercontent.com/7185104/96330693-98ff4f00-1057-11eb-94c4-7315426ec83c.png)
![2020-10-17_09 01 35](https://user-images.githubusercontent.com/7185104/96330694-9a307c00-1057-11eb-9619-dc373cf804d6.png)

### System Information
- Java Version: 1.8_261
- CPU: i7-4710HQ
- GPU: GeForce GTX 850M/PCIe/SSE2

**Comment by LambdAurora** [comment] 2020-10-17 09:13
This seems to be a duplicate of #38.

**Comment by Insane96** [comment] 2020-10-17 09:45
Can confirm. Closing

**Closed as completed** 2020-10-17 09:45 UTC
Labels: T-bug, E-duplicate
