### ISSUE TITLE
Glowing effect uses incorrect team colors

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#2571] opened 2024-06-23 17:45 UTC
### Bug Description

The glowing effect can be colored by using the /team command. The issue is that the glow uses the incorrect color. The issue also applies to the armor you're wearing and the items you're holding but not with various other models stuck to the entity, such as arrows sticking in your body or the flame texture that appears when you are on fire.

![2024-06-23_12 21 57](https://github.com/CaffeineMC/sodium-fabric/assets/55501262/a9491441-4dbf-4a10-b5aa-027c4c1fe548)
![2024-06-23_12 23 03](https://github.com/CaffeineMC/sodium-fabric/assets/55501262/b4c14c5d-6d9c-40ec-8973-0f042819b8c7)
![image](https://github.com/CaffeineMC/sodium-fabric/assets/55501262/28c9d88d-360a-4594-a24b-47424c2d36f9)

### Reproduction Steps

- Create a Team
- Set Team Color [issue is most clearly visible with any shade of red, blue, or yellow]
- Add entities to Team you created
- Give said entities the glowing effect

### Log File

[latest.log](https://github.com/user-attachments/files/15945455/latest.log)

### Crash Report

[crash-2024-06-23_12.23.53-client.txt](https://github.com/user-attachments/files/15945460/crash-2024-06-23_12.23.53-client.txt)

**Comment by Lolothepro** [comment] 2024-06-23 17:46
duplicate of https://github.com/CaffeineMC/sodium-fabric/issues/2547

**Closed as not planned** 2024-06-23 18:49 UTC
Labels: T-bug, E-duplicate
