### ISSUE TITLE
Crashing Everytime you open.

### ISSUE THREAD

**Issue by thatguywiththeboringface** [jellysquid3/Sodium#500] opened 2021-01-26 13:16 UTC
The game keeps crashing, even though I tried many different ways, even trying to delete other mods (Lithium and Phosphor) and it still doesn't work. Tried a fork of Sodium on Forge too, and same problem. Whenever you open a WORLD or open Video Settings, it crashes, saying "Saving World" and crashing. I even tried downgrading to previous Fabric API and Fabric Launcher versions, and it still bugs me. Here is the crash log: https://pastebin.com/X39fGXke

Please leave some solutions in the replies!

**Comment by silversquirl** [comment] 2021-01-26 13:19
Delete `sodium-options.json` from `.minecraft/config`

**Comment by amnotbananaama** [comment] 2021-01-26 13:47
Duplicate of #219

**Closed as completed by amnotbananaama** 2021-01-26 13:47 UTC
Labels: E-duplicate, T-crash
