### ISSUE TITLE
Glass isnt rendering properly while using sodium

### ISSUE THREAD

**Issue by ninetails999** [jellysquid3/Sodium#499] opened 2021-01-26 06:38 UTC
While looking thru a glass block it will make more that is under it invisible and it does not like water either
Also have a weird lighting bug that I found (screenshot included)

- Java Version: Minecraft 1.16.5
- CPU: Ryzen 9 3900x
- GPU: Nvidia 2080 super ko
![2021-01-26_01 16 49](https://user-images.githubusercontent.com/78011552/105808810-75ad3f80-5f76-11eb-9252-7f23fe058713.png)
![2021-01-26_01 16 59](https://user-images.githubusercontent.com/78011552/105808817-7ba32080-5f76-11eb-8a58-ebb90dccfe28.png)
![2021-01-26_01 18 02](https://user-images.githubusercontent.com/78011552/105808822-7d6ce400-5f76-11eb-9132-d19efaebe877.png)
![2021-01-26_01 41 54](https://user-images.githubusercontent.com/78011552/105809560-e86aea80-5f77-11eb-9ce9-56541214b93c.png)

**Comment by DragonEggBedrockBreaking** [comment] 2021-01-26 08:34
Is this a duplicate of #38

**Closed as completed** 2021-01-26 13:46 UTC
Labels: T-bug, E-duplicate

**Comment by Emeraldog** [comment] 2022-08-16 01:37
It's been a bug for over 2 years, so why has it not been directly fixed yet??
