### ISSUE TITLE
Glass doesn't render/look right

### ISSUE THREAD

**Issue by Delukasor** [jellysquid3/Sodium#340] opened 2020-10-05 20:54 UTC
Expected Behavior
Glass suppossed to look normal without any visual breaks

Actual Behavior
Has all these weird breaks and stuff (visual)

Reproduction Steps
Load minecraft with sodium and look at a large sheet of vertical glass

![expected](https://user-images.githubusercontent.com/72415494/95130879-3343c680-072b-11eb-8752-c9f728a3542d.png)
![with sodium ](https://user-images.githubusercontent.com/72415494/95130892-38087a80-072b-11eb-80f3-32cbf26ba114.png)
ws.

- Java Version: [Version 8 Update 261 (build 1.8.0_261-b12)]
- CPU: [Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz, 3600 Mhz, 8 Core(s), 8 Logical Processor(s)]
- GPU: [GeForce 1660 TI ]

**Comment by LambdAurora** [comment] 2020-10-05 20:57
Duplicate of #38.

**Closed as completed by LambdAurora** 2020-10-05 20:57 UTC
Labels: T-bug, E-duplicate
