### ISSUE TITLE
Texture ABSOLUTELY gets messed up. Gets unplayable.

### ISSUE THREAD

**Issue by hissamdev** [jellysquid3/Sodium#549] opened 2021-02-28 14:43 UTC
### Expected Behavior
Just Minecraft without the issues
_Example: The Piston should extend._

### Actual Behavior
Brings up weird stuff in my screen 
![image](https://user-images.githubusercontent.com/70649701/109422431-abc26100-7a05-11eb-981f-06bc86c6701d.png)

_Example: The Piston does not extend._

### Reproduction Steps
Join a world or server, move your mouse to the right until this happens. 

### Attachments
Add any relevant screenshots or videos to this issue as you feel necessary to explain the issue.
This is what happened, none of what you see is real. Infact, I was floating on water, plain water. Before diving in water, 
![image](https://user-images.githubusercontent.com/70649701/109422272-0effc380-7a05-11eb-848e-8e2e8c111a35.png)
After diving in water, 
![image](https://user-images.githubusercontent.com/70649701/109422278-16bf6800-7a05-11eb-90a5-0e639daaba44.png)

Diving in water kinda fixes it.

### System Information
You can obtain this information from the in-game debug screen or through using [DxDiag](https://support.microsoft.com/en-us/help/4028644/windows-open-and-run-dxdiagexe) on Windows.

- Java Version: Version 8 Update 281
- CPU: Intel i3
- GPU: Intel(R) HD 4000 [Idk]

**Comment by FlashyReese** [comment] 2021-02-28 14:45
Go to `Advanced > Chunk Renderer > Oneshot 3.0` to work around this

**Comment by amnotbananaama** [comment] 2021-02-28 19:15
Duplicate of #179

**Closed as completed by amnotbananaama** 2021-02-28 19:15 UTC
Labels: T-bug, E-duplicate
