### ISSUE TITLE
Crashing when you join a server

### ISSUE THREAD

**Issue by timothytay** [jellysquid3/Sodium#495] opened 2021-01-25 07:28 UTC
Reproduction steps:
1. Attempt to join a server with sodium and fabric
2. It crashes

I have tested and concluded that this is not a server issue as I am able to join normally with vanilla and Optifine.

[crash-2021-01-24_22.53.52-client.txt](https://github.com/jellysquid3/sodium-fabric/files/5864861/crash-2021-01-24_22.53.52-client.txt)

**Comment by amnotbananaama** [comment] 2021-01-25 07:39
Please do not post edited or incomplete crash logs. The list of installed Fabric mods and resource packs have been removed from the crash log. I am going to assume this was done intentionally, and I am closing this issue as invalid. If you can provide a complete crash log with only Sodium installed the issue will be re-opened.

**Closed as completed by amnotbananaama** 2021-01-25 07:39 UTC
Labels: E-invalid, T-crash

**Comment by altrisi** [comment] 2021-01-25 12:09
Note that the modlist is actually added by Fabric API, not loader, and Sodium doesn't require it, so it may still be a legit report. It is added by the [`fabric-crash-report-info-v1`](https://github.com/FabricMC/fabric/blob/1.16/fabric-crash-report-info-v1/src/main/java/net/fabricmc/fabric/mixin/crash/report/info/MixinCrashReport.java) module.

**Comment by Kroppeb** [comment] 2021-01-25 15:17
It seems it's caused by this line (if no mods mixed in here)
`float f = MathHelper.lerp(tickDelta, this.client.player.lastNauseaStrength, this.client.player.nextNauseaStrength) * this.client.options.distortionEffectScale * this.client.options.distortionEffectScale;`
`this.client` and `this.client.options` are both not null as that would have caused an NPE earlier. So I'm guessing `this.client.player` is `null`.
