### ISSUE TITLE
Sodium hates integrated graphics (and flickers)

### ISSUE THREAD

**Issue by zhuzh3l1c4** [jellysquid3/Sodium#1876] opened 2023-07-10 23:36 UTC
### Version information

All of the minecraft versions that sodium supports, have this issue

### Expected Behavior

Minercaft should load properly

### Actual Behavior

Every time mc gets a block update, it seems like it's updating all the chunks

https://youtu.be/VuQb1Urn_7c

### Reproduction Steps

Update a block (ex.: place/break blocks, use pistons etc.)

### Java version

Java 20

### CPU

Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz   1.19 GHz

### GPU

Intel(R) UHD graphics

### Additional information

All of my drivers are up to date, yes I checked in the device manager, through intel & lenovo
RAM: 8.00 GB (7.80 GB usable)
System: 64-bit operating system, x64-based processor
OS: Windows 11 Home (Windows Feature Experience Pack 1000.22644.1000.0)
Nor official or cracked minecraft work properly (lunar, sk, modrinth, license, multimc)
All forge, fabric and quilt have the same problem on all versions
The issue is present with the mod on it's own, in a modpack or with other mods
For some reason the bug starts to show itself within 3 - 5 minutes from the installation of the mod
My computer is not in the best shape, and the mod worked perfectly for a lot of time (~1.5 years), when it randomly broke mid game

![Screenshot 2023-07-11 015936](https://github.com/CaffeineMC/sodium-fabric/assets/127420433/ed570ad7-845f-4afc-babb-bdd14852b5e1)
![Screenshot 2023-07-11 015927](https://github.com/CaffeineMC/sodium-fabric/assets/127420433/4f4c09b9-1767-49d6-a956-879c33f1bcf9)

**Comment by Fnige** [comment] 2023-07-11 00:03
What sodium settings are you using?

**Comment by pajicadvance** [comment] 2023-07-11 00:17
This is most likely a duplicate of #869

**Closed as not planned** 2023-07-11 00:17 UTC
Labels: T-bug, E-duplicate, A-drivers

**Comment by jellysquid3** [comment] 2023-07-11 01:05
The [Modrinth page for Sodium](https://modrinth.com/mod/sodium#known-issues) also clearly describes this issue and the fact that your graphics drivers need to be updated.

Just because Windows _says_ your drivers are up-to-date does not mean they are. You must download them from the [Intel website](https://www.intel.com/content/www/us/en/download-center/home.html). The default driver which Windows installs is _known to be broken_ and it will mislead you by saying it's up-to-date.
