### ISSUE TITLE
Water textures are broked

### ISSUE THREAD

**Issue by Disketaa** [jellysquid3/Sodium#1903] opened 2023-07-22 12:48 UTC
### Bug Description

**sodium-fabric-mc1.20-0.4.10+build.27**, **fabric 0.14.21-1.20**

![image](https://github.com/CaffeineMC/sodium-fabric/assets/76956762/f0bf030f-8255-46d7-a788-04ea11fb6be5)
![image](https://github.com/CaffeineMC/sodium-fabric/assets/76956762/c58192c2-ea6a-468c-86ab-ad26e829e9a2)
![image](https://github.com/CaffeineMC/sodium-fabric/assets/76956762/ea3c2ae4-f640-4dfb-a056-5fea1d364a6f)

### Reproduction Steps

Create a big water-one-block fall and fly around

### Log File

Not needed

### Crash Report

Not crushed

**Comment by Timolino456** [comment] 2023-07-22 12:50
Duplicate of #38

**Closed as completed** 2023-07-22 12:50 UTC
Labels: E-duplicate, E-invalid

**Comment by Disketaa** [comment] 2023-07-22 13:12
Sorry for duplicating, I didn't know the issue is too common
