### ISSUE TITLE
The Driver of GPU wrong

### ISSUE THREAD

**Issue by jfglzs** [jellysquid3/Sodium#2516] opened 2024-05-24 06:29 UTC
### Bug Description

Driver of GPU Error

### Reproduction Steps

Win build 19045.3930
CPU I5 3320M 
GPU Intel GPU HD 4000
First installed sodium5.8 1.20.6 with Fabirc 0.15.11(ZH.CN)
Second start the Game with Fabric 0.15.
![a BUG](https://github.com/CaffeineMC/sodium-fabric/assets/127277607/08399e7d-47b0-4a0a-9168-4dadbffac7ac)
11
Third found out some Error And a messagebox 
But on the Intel Mianpage found (GPU build 10.18.10.5161 = 15.33.53.5161)

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/15428543/latest.log)

### Crash Report

[crashed output.txt](https://github.com/CaffeineMC/sodium-fabric/files/15428600/crashed.output.txt)

**Comment by jfglzs** [comment] 2024-05-24 06:33
I am Chinese. I English is bad

**Comment by mrjasonn** [comment] 2024-05-24 08:13
Please try to update the graphics drivers for your Intel 3rd gen. If it still happens after update, it might be a duplicate of #2432. If you can't update, please say what is the problem it tells you.

**Closed as completed** 2024-05-24 12:40 UTC
Labels: S-needs-triage
