### ISSUE TITLE
Compatibility with vanilla shaders

### ISSUE THREAD

**Issue by FredTheNerd** [jellysquid3/Sodium#838] opened 2021-08-15 15:40 UTC
**Is your feature request related to a problem? Please describe.**
In 1.17, mojang added the ability to edit vanilla shaders through resource packs. Sodium messes with or disables a lot of these shaders.

**Describe the solution you'd like**
they work like vanilla

**Describe alternatives you've considered**
idk...

**Additional context**
using either vanilla tweaks wavy leaves/water or farther fog packs are broken
[VanillaTweaks_r315077.zip](https://github.com/CaffeineMC/sodium-fabric/files/6988401/VanillaTweaks_r315077.zip)
[less-nether-fog.zip](https://github.com/CaffeineMC/sodium-fabric/files/6988405/less-nether-fog.zip)

**Comment by amnotbananaama** [comment] 2021-08-15 15:44
Closing as a duplicate of #754. See [this comment](https://github.com/CaffeineMC/sodium-fabric/issues/754#issuecomment-879172873) specifically

**Closed as completed by amnotbananaama** 2021-08-15 15:44 UTC
Labels: E-duplicate
