### ISSUE TITLE
Core shader rendertype_solid.fsh disabled in resource pack

### ISSUE THREAD

**Issue by ImPlotzes** [jellysquid3/Sodium#2252] opened 2024-01-09 18:02 UTC
### Bug Description

The core shader `assets/minecraft/shaders/core/rendertype_solid.fsh` in a resource pack isn't applied.

If I have a resource pack with that shader being:
```glsl
#version 150

#moj_import <fog.glsl>

uniform sampler2D Sampler0;

uniform vec4 ColorModulator;
uniform float FogStart;
uniform float FogEnd;
uniform vec4 FogColor;

in float vertexDistance;
in vec4 vertexColor;
in vec2 texCoord0;
in vec4 normal;

out vec4 fragColor;

void main() {
    // Every block has pure white texture
    vec4 textureColor = vec4(1.0, 1.0, 1.0, 1.0);

    vec4 color = textureColor * vertexColor * ColorModulator;
    fragColor = linear_fog(color, vertexDistance, FogStart, FogEnd, FogColor);
}
```
then I expect every solid block (those are affected by this shader) to be pure white because the texture is being overwritten. This works when using Fabric without Sodium in 1.20.1.
When Sodium (v0.5.3) is used, all solid blocks will have their normal texture, this shader isn't being run anymore.

### Reproduction Steps

Create a resource pack with the file `assets/minecraft/shaders/core/rendertype_solid.fsh` which should contain the following code:
```glsl
#version 150

#moj_import <fog.glsl>

uniform sampler2D Sampler0;

uniform vec4 ColorModulator;
uniform float FogStart;
uniform float FogEnd;
uniform vec4 FogColor;

in float vertexDistance;
in vec4 vertexColor;
in vec2 texCoord0;
in vec4 normal;

out vec4 fragColor;

void main() {
    // Every block has pure white texture
    vec4 textureColor = vec4(1.0, 1.0, 1.0, 1.0);

    vec4 color = textureColor * vertexColor * ColorModulator;
    fragColor = linear_fog(color, vertexDistance, FogStart, FogEnd, FogColor);
}
```

Open Minecraft without Sodium and observe many white blocks when using the resource pack.

Restart Minecraft but now with Sodium, and observe that those previously affected blocks are now normal again, the shader doesn't work anymore.

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/13877381/latest.log)

### Crash Report

[crash-2024-01-09_19.00.49-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/13877400/crash-2024-01-09_19.00.49-client.txt)

**Comment by pajicadvance** [comment] 2024-01-09 18:13
Duplicate of #1569

**Closed as not planned by pajicadvance** 2024-01-09 18:13 UTC
Labels: E-duplicate
