### ISSUE TITLE
Strange water rendering behind large glass walls

### ISSUE THREAD

**Issue by Shukle** [jellysquid3/Sodium#1103] opened 2022-01-03 15:21 UTC
### Version information

sodium-fabric-mc1.18-0.4.0-alpha5+build.9

### Expected Behavior

water should render smoothly everywhere behind glass

### Actual Behavior

renders strange squares 

### Reproduction Steps

make water wall
make glass wall in front of it
look at it from glass side

### Java version

17.0.1

### CPU

Processor	Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz, 2304 Mhz, 4 Core(s), 8 Logical Processor(s)

### GPU

NVIDIA GeForce MX250

### Additional information

happens behind stained and normal glass blocks as well as all types of glass pane
![2022-01-03_15 54 04](https://user-images.githubusercontent.com/97039981/147947937-41ce46c1-9b5e-421f-b686-ab6172739548.png)

**Comment by DioEgizio** [comment] 2022-01-03 16:56
Duplicate of https://github.com/CaffeineMC/sodium-fabric/issues/38

**Closed as completed** 2022-01-04 05:38 UTC
Labels: T-bug, E-duplicate
