### ISSUE TITLE
Culling issue on Glass and Slime blocks up, east and south sides 

### ISSUE THREAD

**Issue by wKaffel** [jellysquid3/Sodium#2632] opened 2024-08-04 15:28 UTC
### Bug Description

The bug is that on the south, east and up sides there is a visual bug that causes undesirable lines and the lack of the fog effect that alternating glass blocks normally causes. 

![2024-08-04_12 19 17](https://github.com/user-attachments/assets/51659bcc-bdfe-4cc5-aa01-799f0a2a44b6)
![2024-08-04_12 18 37](https://github.com/user-attachments/assets/e0b965c2-c729-4864-8f05-e16fec0ef39b)
![2024-08-04_12 18 57](https://github.com/user-attachments/assets/0aa6c1a9-6c93-4434-9e55-27c7628596f1)
![2024-08-04_12 18 59](https://github.com/user-attachments/assets/66cf1d99-d1cb-428d-bfe8-56b29abb668d)
![2024-08-04_12 19 05](https://github.com/user-attachments/assets/580dd3b3-fe04-45cd-b20b-adfe38f4b387)
![2024-08-04_12 17 10](https://github.com/user-attachments/assets/8237da25-e764-4fb9-8061-3d90d6916892)
![2024-08-04_12 17 16](https://github.com/user-attachments/assets/86f14dad-940f-4f88-9ec4-3b5a6efee205)
![2024-08-04_12 17 23](https://github.com/user-attachments/assets/8ba50e9c-a527-4065-b2da-b595ee6e3e5c)
![2024-08-04_12 17 29](https://github.com/user-attachments/assets/629a9874-9b61-43f2-8c6f-17a1d4e54a18)
![2024-08-04_12 18 12](https://github.com/user-attachments/assets/f52160c1-ca70-4b7f-bc5a-c9238f8e6c69)
![2024-08-04_12 18 21](https://github.com/user-attachments/assets/6e205c00-ad72-4664-bbea-69284380e1f3)

### Reproduction Steps

alternately placing glass blocks, changing into other colors of glass or empty blocks

### Log File

[latest.log](https://github.com/user-attachments/files/16488031/latest.log)

### Crash Report

[crash-2024-08-04_12.25.46-client.txt](https://github.com/user-attachments/files/16488038/crash-2024-08-04_12.25.46-client.txt)

**Comment by Timolino456** [comment] 2024-08-04 15:29
Looks like a duplicate of #38, will be fixed in Sodium 0.6

**Comment by wKaffel** [comment] 2024-08-04 15:47
even the problems with the slime block?

Em dom., 4 de ago. de 2024 12:29, Timolino456 ***@***.***>
escreveu:

**Comment by Timolino456** [comment] 2024-08-04 15:54
It's the same problem (layered translucent blocks not rendering correctly), so yes.

**Closed as not planned** 2024-08-04 17:20 UTC
Labels: E-duplicate
