### ISSUE TITLE
Crashes when trying to relog into a server

### ISSUE THREAD

**Issue by QPCrummer** [jellysquid3/Sodium#448] opened 2020-12-26 22:18 UTC
### Reproduction Steps
1. Log into a server
2. Log out of the server
3. Log back into the server
### Crash Report File
[crash-2020-12-26_17.15.41-client.txt](https://github.com/jellysquid3/sodium-fabric/files/5743740/crash-2020-12-26_17.15.41-client.txt)

### Additional Information
I am using the latest github release.

**Comment by amnotbananaama** [comment] 2020-12-26 23:22
Duplicate of #430

**Closed as completed by amnotbananaama** 2020-12-26 23:22 UTC
Labels: E-duplicate, T-crash
