### ISSUE TITLE
Random crash prolly due to armor stand

### ISSUE THREAD

**Issue by stevefan1999-personal** [jellysquid3/Sodium#218] opened 2020-07-31 12:07 UTC
### Reproduction Steps
1. Login to a somewhat decent server portal with custom NPCs and lots of fancy shit?
2. ???
3. Crashes

### Crash Report File
```
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 7/31/20 8:02 PM
Description: Rendering entity in world

java.lang.IndexOutOfBoundsException
	at java.nio.Buffer.checkIndex(Buffer.java:546)
	at java.nio.DirectByteBuffer.putFloat(DirectByteBuffer.java:893)
	at net.minecraft.class_287.method_22897(class_287.java:267)
	at net.minecraft.class_4584.method_22913(class_4584.java:55)
	at net.minecraft.class_382.method_22944(class_382.java:55)
	at net.minecraft.class_327$class_5232.method_27531(class_327.java:285)
	at net.minecraft.class_327.method_27530(class_327.java:302)
	at net.minecraft.class_327.method_1723(class_327.java:159)
	at net.minecraft.class_327.method_22942(class_327.java:121)
	at net.minecraft.class_897.method_3926(class_897.java:111)
	at net.minecraft.class_897.method_3936(class_897.java:70)
	at net.minecraft.class_922.method_4054(class_922.java:144)
	at net.minecraft.class_922.method_3936(class_922.java:29)
	at net.minecraft.class_898.method_3954(class_898.java:260)
	at net.minecraft.class_761.method_22977(class_761.java:1435)
	at net.minecraft.class_761.method_22710(class_761.java:1199)
	at net.minecraft.class_757.method_3188(class_757.java:717)
	at net.minecraft.class_757.method_3192(class_757.java:540)
	at net.minecraft.class_310.method_1523(class_310.java:1021)
	at net.minecraft.class_310.method_1514(class_310.java:654)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.nio.Buffer.checkIndex(Buffer.java:546)
	at java.nio.DirectByteBuffer.putFloat(DirectByteBuffer.java:893)
	at net.minecraft.class_287.method_22897(class_287.java:267)
	at net.minecraft.class_4584.method_22913(class_4584.java:55)
	at net.minecraft.class_382.method_22944(class_382.java:55)
	at net.minecraft.class_327$class_5232.method_27531(class_327.java:285)
	at net.minecraft.class_327.method_27530(class_327.java:302)
	at net.minecraft.class_327.method_1723(class_327.java:159)
	at net.minecraft.class_327.method_22942(class_327.java:121)
	at net.minecraft.class_897.method_3926(class_897.java:111)
	at net.minecraft.class_897.method_3936(class_897.java:70)
	at net.minecraft.class_922.method_4054(class_922.java:144)
	at net.minecraft.class_922.method_3936(class_922.java:29)

-- Entity being rendered --
Details:
	Entity Type: minecraft:armor_stand (net.minecraft.class_1531)
	Entity ID: 1
	Entity Name: 前往【空島伺服器】
	Entity's Exact location: -5.48, 73.48, -5.41
	Entity's Block location: World: (-6,73,-6), Chunk: (at 10,4,10 in -1,-1; contains blocks -16,0,-16 to -1,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.class_877@503c6c4d
	Location: 0.02,-0.76,-9.18 - World: (0,-1,-10), Chunk: (at 0,-1,6 in 0,-1; contains blocks 0,0,-16 to 15,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Rotation: 1.40625
	Delta: 0.12000275
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:260)
	at net.minecraft.class_761.method_22977(class_761.java:1435)
	at net.minecraft.class_761.method_22710(class_761.java:1199)
	at net.minecraft.class_757.method_3188(class_757.java:717)

-- Affected level --
Details:
	All players: 12 total; [class_746['~redacted~'/14085, l='ClientLevel', x=-5.50, y=72.66, z=3.78], class_745['nova_Efina'/14080, l='ClientLevel', x=-6.93, y=72.00, z=3.97], class_745['Melinvina'/14052, l='ClientLevel', x=-4.86, y=71.00, z=7.39], class_745['Kmountainpig'/14040, l='ClientLevel', x=-8.22, y=71.00, z=0.36], class_745['l___Chen___l'/14051, l='ClientLevel', x=-1.30, y=71.00, z=11.47], class_745['FongMoon'/14043, l='ClientLevel', x=-4.89, y=72.00, z=6.72], class_745['william__donkey'/14062, l='ClientLevel', x=-6.03, y=72.00, z=5.37], class_745['jesse0322'/14045, l='ClientLevel', x=-2.66, y=71.50, z=4.40], class_745['water0212'/14069, l='ClientLevel', x=-5.74, y=72.00, z=0.53], class_745['l___Sun___l'/14047, l='ClientLevel', x=-2.81, y=71.50, z=6.02], class_745['janet70'/14056, l='ClientLevel', x=-3.27, y=71.00, z=9.65], class_745['con886653'/14049, l='ClientLevel', x=-2.78, y=71.00, z=7.31]]
	Chunk stats: SodiumChunkCache: 289
	Level dimension: minecraft:overworld
	Level spawn location: World: (-6,72,3), Chunk: (at 10,4,3 in -1,0; contains blocks -16,0,0 to -1,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 149789 game time, 7663089372 day time
	Server brand: Waterfall <- Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2181)
	at net.minecraft.class_310.method_1514(class_310.java:672)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 931786984 bytes (888 MB) / 1912602624 bytes (1824 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 16
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric: Fabric API 0.16.2+build.385-1.16.1
		fabric-api-base: Fabric API Base 0.1.3+12a8474c02
		fabric-biomes-v1: Fabric Biomes (v1) 0.2.7+059ea86602
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8902
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339802
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083602
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f02
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86602
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d02
		fabric-dimensions-v1: fabric-dimensions-v1 1.0.0+a71b305302
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.3+7066030f02
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b02
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.0+fe81e12502
		fabric-item-api-v1: Fabric Item API (v1) 1.0.0+16acbe5b02
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963602
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+f404f3be02
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c502
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+e83e061c02
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.0+386eb69e02
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9902
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d602
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b02
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f02
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.5.6+a2d21ddd02
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.1+a2d21ddd02
		fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a7002
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.3.8+7dba2d6c02
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb802
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.4+34d6c87102
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a6002
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d02
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.8+b7084faa02
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+5341049002
		fabric-rendering-v1: Fabric Rendering (v1) 1.1.2+346247d702
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.6+f41e209802
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+97324d1102
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.2.7+a4c57d8e02
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb802
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.0+55e0cc5f02
		fabricloader: Fabric Loader 0.8.8+build.202
		lithium: Lithium 0.5.1
		minecraft: Minecraft 1.16.1
		phosphor: Phosphor 0.6.0+build.7
		sodium: Sodium 0.1.0
	Launched Version: fabric-loader-0.8.8+build.202-1.16.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce RTX 2070/PCIe/SSE2 GL version 4.6.0 NVIDIA 451.67, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 16x AMD Ryzen 7 3700X 8-Core Processor 
```

**Comment by amnotbananaama** [comment] 2020-07-31 14:26
Duplicate of #189

**Comment by jellysquid3** [comment] 2020-08-02 22:51
Closing as a duplicate of the aforementioned issue.

**Comment by coderbot16** [comment] 2021-03-17 02:13
This does not appear to be a duplicate, it should be reopened per comp500's comments on Discord.

**Comment by comp500** [comment] 2021-03-28 01:35
I've managed to fairly reliably replicate this issue, with the following steps:

1. Run the `/summon armor_stand ~ ~ ~ {CustomName:'{"text":"前往【空島伺服器】"}',CustomNameVisible:1b}` command a few times, to spawn armor stands with the previous text
2. Restart the game entirely and open the same world again (potentially several times)

It often doesn't occur when the armor stands are spawned in one by one, as other code will have already grown the vertex consumer that entity name rendering uses, so it doesn't run into the out of bounds BufferBuilder write.

Also see https://github.com/CaffeineMC/sodium-fabric/issues/189#issuecomment-794377765 for another crash log related to this issue.

**Closed as completed** 2021-04-10 02:27 UTC
Labels: E-duplicate, T-crash
