### ISSUE TITLE
Conflict?

### ISSUE THREAD

**Issue by jakerules** [jellysquid3/Sodium#451] opened 2020-12-28 04:30 UTC
Just crashes on launch. Conflict?

[crash-2020-12-27_23.25.51-client.txt](https://github.com/jellysquid3/sodium-fabric/files/5745857/crash-2020-12-27_23.25.51-client.txt)

### Additional Information
Provide any additional information or context which may be relevant to the issue. If you have none to add, you can remove this section.

**Comment by amnotbananaama** [comment] 2020-12-28 06:46
This appears to be a duplicate of #445

**Closed as completed by amnotbananaama** 2020-12-28 06:46 UTC
Labels: E-duplicate, T-crash
