### ISSUE TITLE
Water looking weird behing glass with iris+sodium, indium and CTMF. It doesn't happens without sodium. It does this with and without shaders

### ISSUE THREAD

**Issue by Aeldit** [jellysquid3/Sodium#901] opened 2021-09-12 19:16 UTC
### Version information

sodium-fabric-mc1.17.1-0.3.2+IRIS2-unknown

### Expected Behavior

The water should not show as a sort of cross

### Actual Behavior

![2021-09-12_19 21 18](https://user-images.githubusercontent.com/81476169/132999915-e2f8cd73-b72d-49e2-9e60-1f39c52552f0.png)
![2021-09-12_19 21 30](https://user-images.githubusercontent.com/81476169/132999918-a9909afa-1c80-4926-9380-03c4fc21528e.png)

### Reproduction Steps

place water under glass - colored glass

### Java version

16

### CPU

core i-5 8300H

### GPU

NVIDIA GTX 1050

### Additional information

indium, iris, sodium, CTMF, ferritcore, starlight

**Comment by jellysquid3** [comment] 2021-09-13 00:01
Duplicate of #38.

**Closed as completed by jellysquid3** 2021-09-13 00:01 UTC
