### ISSUE TITLE
When using Litematica this mod, the rendering will have problems, please fix it (machine translation)

### ISSUE THREAD

**Issue by xiaowine** [jellysquid3/Sodium#237] opened 2020-08-06 11:26 UTC
When using Litematica this mod, the rendering will have problems, please fix it (machine translation)
![2020-08-06_19 21 21](https://user-images.githubusercontent.com/68009112/89526690-b378a900-d81a-11ea-8e72-223cb57859b4.png)
![2020-08-06_19 26 44](https://user-images.githubusercontent.com/68009112/89526740-c8553c80-d81a-11ea-8350-554671eb9430.png)

**Comment by amnotbananaama** [comment] 2020-09-06 20:56
Hi @xiaowine, I am not able to reproduce this issue in singleplayer using the latest code commit on the dev branch (1df506f), with or without texture packs. Litematica seems to work well for me.

```
fabric-api-0.18.0+build.387-1.16.1.jar
litematica-fabric-1.16.1-0.0.0-dev.20200711.162756.jar
malilib-fabric-1.16.1-0.10.0-dev.21+arne.1.jar
sodium-fabric-1df506f.jar
voyager-1.0.0.jar
```
Can you share an [Alt+F3](https://minecraft-zh.gamepedia.com/%E8%B0%83%E8%AF%95%E7%95%8C%E9%9D%A2#.E5.B8.A7.E7.94.9F.E6.88.90.E6.97.B6.E9.97.B4.E5.9B.BE.E8.A1.A8) screenshot please? And also what versions of Litematica, Sodium, MaLiLib, and Minecraft you are using?

**Comment by xiaowine** [comment] 2020-09-16 01:34
> @xiaowine，您好：我无法使用具有或不带有纹理包的dev分支（[1df506f](https://github.com/jellysquid3/sodium-fabric/commit/1df506fd39dac56bb410725c245e6e51208ec732)）上的最新代码提交在单人游戏中重现此问题。Litematica似乎对我来说效果很好。
> 
> ```
> fabric-api-0.18.0+build.387-1.16.1.jar
> litematica-fabric-1.16.1-0.0.0-dev.20200711.162756.jar
> malilib-fabric-1.16.1-0.10.0-dev.21+arne.1.jar
> sodium-fabric-1df506f.jar
> voyager-1.0.0.jar
> ```
> 
> 您可以分享[Alt + F3](https://minecraft-zh.gamepedia.com/%E8%B0%83%E8%AF%95%E7%95%8C%E9%9D%A2#.E5.B8.A7.E7.94.9F.E6.88.90.E6.97.B6.E9.97.B4.E5.9B.BE.E8.A1.A8)屏幕截图吗？还有，您正在使用什么版本的Litematica，Sodium，MaLiLib和Minecraft？

I don’t know how this bug market appeared, I can’t reproduce it

**Comment by IceFreez3r** [comment] 2020-12-31 12:44
![2020-12-31_13 15 41](https://user-images.githubusercontent.com/39794212/103410917-da3ecf80-4b6d-11eb-88a5-1f83fb5c9b1f.png)
![2020-12-31_13 16 39](https://user-images.githubusercontent.com/39794212/103410921-dca12980-4b6d-11eb-849a-52d263c6a32b.png)
![2020-12-31_13 20 38](https://user-images.githubusercontent.com/39794212/103410923-de6aed00-4b6d-11eb-9179-ec258fd1bb8d.png)
![2020-12-31_13 22 09](https://user-images.githubusercontent.com/39794212/103410926-e034b080-4b6d-11eb-947d-9de6d5167017.png)

Installed mods:
fabric-api-0.20.1+build.401-1.16
litematica-fabric-1.16.4-0.0.0-dev.20201103.184101
malilib-fabric-1.16.4-0.10.0-dev.21+arne.2
minihud-fabric-1.16.4-0.19.0-dev.20201103.184029
modmenu-1.14.13+build.19
sodium-fabric-mc1.16.3-0.1.0

No problems before installing Sodium

EDIT: F3 Screen
![2020-12-31_14 25 13](https://user-images.githubusercontent.com/39794212/103412210-49b7bd80-4b74-11eb-9c70-ec66a0f3465d.png)

**Comment by LucilleTea** [comment] 2021-06-03 06:04
Going to close this for lack of information and reproducibility.

**Closed as completed by LucilleTea** 2021-06-03 06:04 UTC
Labels: T-bug, S-cannot-repro
