### ISSUE TITLE
Incorrect rendering of snow overlay on blocks when using a 32x32 resource pack.

### ISSUE THREAD

**Issue by Giacomino99** [jellysquid3/Sodium#972] opened 2021-11-16 23:20 UTC
### Version information

sodium-fabric-mc1.17.1-0.3.2+build.7

### Expected Behavior

When using a 32x32 texture pack, snow on the top of a block adds an overlay to the side of blocks to make them look snowy. The blocks are rendered correctly in vanilla Minecraft as well as in Fabric without Sodium. 
![vin](https://user-images.githubusercontent.com/37887995/142080520-951029aa-8215-4c38-8782-dcaf0546c7cd.png)

### Actual Behavior

When using Sodium the snow overlay is rendered incorrectly. Half the faces are rendered with the overlay but the block texture is incorrect. The other half of the faces have Z-fighting between the correct block texture and the solid color. This happens when snow is placed on all blocks, not just grass.
![wrongt](https://user-images.githubusercontent.com/37887995/142081029-ff0ab964-f654-4910-b094-4ddbaa99b8ef.png)
![zfight](https://user-images.githubusercontent.com/37887995/142081040-0133ada5-0e50-4591-8155-25c436a226c7.png)

### Reproduction Steps

1. Load Minecraft with Fabric and Sodium.
2. Load a resource pack (The exact one I used: [Dokucraft Light](https://dokucraft.co.uk/resource-packs/light/)).
3. Place snow on any block.
4. Snow will not render correctly.

### Java version

Java 17

### CPU

Intel Core i7-9700K

### GPU

Nvidia GeForce RTX 2080

### Additional information

I can't confirm if this issue is specific to the resource pack that I am using or not, but the pack does work properly without Sodium.

**Comment by MESLewis** [comment] 2021-11-18 18:46
![2021-11-18_12 38 08](https://user-images.githubusercontent.com/597053/142477300-ee20b5b7-1694-4662-88a2-61a2531b80a0.png)
![2021-11-18_12 42 30](https://user-images.githubusercontent.com/597053/142477309-d181be24-0779-4032-a6e2-691bec9e4289.png)

Can confirm issue on my system in release. Also confirmed in 1.17.x/dev
I suspect the issue has to do with how this texture pack applies the snow overlay. Snow appears on the side of every block with snow above, not just grass like in the default texture pack.

**Comment by MESLewis** [comment] 2021-11-21 00:54
Duplicate of #815

**Comment by jellysquid3** [comment] 2021-11-23 16:25
Closing as duplicate of the aforementioned issue.

**Closed as completed by jellysquid3** 2021-11-23 16:25 UTC
