### ISSUE TITLE
Rare chunk fragments disappearing

### ISSUE THREAD

**Issue by MaxIsV** [jellysquid3/Sodium#1118] opened 2022-01-09 12:28 UTC
### Version information

mc1.18-0.4.0-alpha5+build.9

### Expected Behavior

All visible blocks should render:
![2022-01-09_14 20 29](https://user-images.githubusercontent.com/58142896/148681973-0b12a271-9b86-4908-87f3-a92e3ba64e68.png)

### Actual Behavior

Some fragments aren't rendered for some reason:
![2022-01-09_14 18 51](https://user-images.githubusercontent.com/58142896/148681962-5952edb9-31ea-4ea1-a7cc-3620f1c14327.png)

### Reproduction Steps

Unfortunately, I could not find anything unique in these fragments

### Java version

Java 17

### CPU

Ryzen 3 3100

### GPU

Radeon RX 580 4gb

### Additional information

More details in the video: https://imgur.com/a/RGZss7z

Sometimes I come across such fragments that are not rendered at a certain position of the player. Tested with only Sdoium installed

**Comment by christofin** [comment] 2022-01-25 04:11
https://user-images.githubusercontent.com/43354771/150909221-59639abe-ec4b-41c9-a413-c56113186294.mp4

This is happening to me as well specifically with Sodium - look at how the tower disappears due to some weirdness with the frustrum culling. 

Doesn't happen in Vanilla.

**Comment by pajicadvance** [comment] 2023-05-09 22:18
Duplicate of #872.

**Closed as not planned** 2023-05-10 18:28 UTC
Labels: T-bug, E-duplicate
