### ISSUE TITLE
Process exited with code -1.

### ISSUE THREAD

**Issue by Jonzll** [jellysquid3/Sodium#1240] opened 2022-03-24 19:04 UTC
### Version information

mc1.18.2-0.4.1+build.15

### Reproduction Steps

1. Launch an instance in MultiMC on version 1.18.2 that has sodium
2. You will get the message 'Process exited with code -1.'

### Crash Report file

MultiMC version: 0.6.14-3001

Launched instance in online mode

authserver.mojang.com resolves to:
    [65.9.22.35, 65.9.22.39, 65.9.22.64, 65.9.22.63]

session.minecraft.net resolves to:
    [52.205.99.166, 3.224.239.34, 3.211.39.224]

textures.minecraft.net resolves to:
    [65.9.187.116, 65.9.187.83, 65.9.187.126, 65.9.187.111]

api.mojang.com resolves to:
    [65.9.187.82, 65.9.187.90, 65.9.187.56, 65.9.187.48]

Minecraft folder is:
C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/instances/fps/.minecraft

Java path is:
C:/Program Files/Common Files/Oracle/Java/javapath/javaw.exe

Checking Java version...
Java is version 17.0.2, using 64-bit architecture, from Oracle Corporation.

Main Class:
  net.fabricmc.loader.impl.launch.knot.KnotClient

Native path:
  C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/instances/fps/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/libraries/com/mojang/logging/1.0.0/logging-1.0.0.jar
  C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/libraries/com/github/oshi/oshi-core/5.8.5/oshi-core-5.8.5.jar
  C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/libraries/net/java/dev/jna/jna/5.10.0/jna-5.10.0.jar
  C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/libraries/net/java/dev/jna/jna-platform/5.10.0/jna-platform-5.10.0.jar
  C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar
  C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.16.0/log4j-slf4j18-impl-2.16.0.jar
  C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/libraries/com/ibm/icu/icu4j/70.1/icu4j-70.1.jar
  C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/libraries/com/mojang/javabridge/1.2.24/javabridge-1.2.24.jar
  C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/libraries/io/netty/netty-all/4.1.68.Final/netty-all-4.1.68.Final.jar
  C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/libraries/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar
  C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
  C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/libraries/com/mojang/datafixerupper/4.1.27/datafixerupper-4.1.27.jar
  C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/libraries/com/google/code/gson/gson/2.8.9/gson-2.8.9.jar
  C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/libraries/com/mojang/authlib/3.3.39/authlib-3.3.39.jar
  C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.4.14/httpcore-4.4.14.jar
  C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/libraries/it/unimi/dsi/fastutil/8.5.6/fastutil-8.5.6.jar
  C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/libraries/com/mojang/text2speech/1.12.4/text2speech-1.12.4.jar
  C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/libraries/net/fabricmc/intermediary/1.17.1/intermediary-1.17.1.jar
  C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/libraries/net/fabricmc/tiny-mappings-parser/0.3.0+build.17/tiny-mappings-parser-0.3.0+build.17.jar
  C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/libraries/net/fabricmc/sponge-mixin/0.11.2+mixin.0.8.5/sponge-mixin-0.11.2+mixin.0.8.5.jar
  C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/libraries/net/fabricmc/tiny-remapper/0.8.1/tiny-remapper-0.8.1.jar
  C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/libraries/net/fabricmc/access-widener/2.1.0/access-widener-2.1.0.jar
  C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/libraries/org/ow2/asm/asm/9.2/asm-9.2.jar
  C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/libraries/org/ow2/asm/asm-analysis/9.2/asm-analysis-9.2.jar
  C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/libraries/org/ow2/asm/asm-commons/9.2/asm-commons-9.2.jar
  C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/libraries/org/ow2/asm/asm-tree/9.2/asm-tree-9.2.jar
  C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/libraries/org/ow2/asm/asm-util/9.2/asm-util-9.2.jar
  C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/libraries/net/fabricmc/fabric-loader/0.13.3/fabric-loader-0.13.3.jar
  C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/libraries/com/mojang/minecraft/1.18.2/minecraft-1.18.2-client.jar

Native libraries:
  C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/libraries/com/mojang/text2speech/1.12.4/text2speech-1.12.4-natives-windows.jar

Mods:
  [❌] fabric-api-0.48.0+1.18.2.jar (disabled)
  [❌] lambdynamiclights-2.1.0+1.17 (1).jar (disabled)
  [✔️] lithium-fabric-mc1.18.2-0.7.9
  [❌] logical_zoom-0.0.14.jar (disabled)
  [✔️] phosphor-fabric-mc1.18.x-0.8.1 (1)
  [✔️] sodium-fabric-mc1.18.2-0.4.1+build.15

Params:
  --username  --version MultiMC5 --gameDir C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/instances/fps/.minecraft --assetsDir C:/Users/jonat/Downloads/mmc-stable-win32 (2)/MultiMC/assets --assetIndex 1.18 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 16684

Using onesix launcher.

[19:59:55] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.13.3
[19:59:56] [main/WARN]: Incomplete remapped file found! This means that the remapping process failed on the previous launch. If this persists, make sure to let us at Fabric know!
[19:59:56] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...
Mapping source name conflicts detected:
  ega METHOD b (()V) -> [ega/method_1748, dwq/method_1793]
  eeu METHOD b (()V) -> [dwq/method_1793, eeu/method_1748]
  aly METHOD a ((Ljava/lang/String;)Ljava/lang/String;) -> [amu/method_5185, aly/method_5179, ana/method_24326]
  aoc METHOD a ((Lcom/mojang/datafixers/Typed;)Lcom/mojang/datafixers/Typed;) -> [aoc/method_5041, alt/method_18852, akr/method_5011, alv/method_5121]
  enl METHOD a (()V) -> [eoa/method_3345, enl/method_23516, eob/method_20544]
  ehr METHOD b (()V) -> [ehr/method_1748, dwq/method_1793]
  eev METHOD b (()V) -> [eev/method_1748, dwq/method_1793]
  eob METHOD a (()V) -> [eoa/method_3345, eob/method_20544, eob/method_23516]
  eoi METHOD a (()V) -> [eoi/method_23516, eoa/method_3345, eob/method_20544]
  dvz METHOD b (()V) -> [dwq/method_1793, dvz/method_1748]
  ecv METHOD b (()V) -> [ecv/method_1748, dwq/method_1793]
  ffe METHOD b (()V) -> [ffe/method_1748, dwq/method_1793]
  egs METHOD b (()V) -> [dwq/method_1793, egs/method_1748]
  amr METHOD a ((Lcom/mojang/datafixers/Typed;)Lcom/mojang/datafixers/Typed;) -> [alt/method_18852, amr/method_5041, akr/method_5011, alv/method_5121]
  edt METHOD b (()V) -> [dwq/method_1793, edt/method_1748]
  amg METHOD a ((Lcom/mojang/datafixers/Typed;)Lcom/mojang/datafixers/Typed;) -> [alt/method_18852, amg/method_5041, akr/method_5011, alv/method_5121]
  ake$1 METHOD a ((Lcom/mojang/datafixers/Typed;)Lcom/mojang/datafixers/Typed;) -> [alt/method_18852, ake$1/method_5041, akr/method_5011, alv/method_5121]
  epc METHOD a (()V) -> [epc/method_23516, eoa/method_3345, eob/method_20544]
  ecp METHOD b (()V) -> [dwq/method_1793, ecp/method_1748]
  apx METHOD a ((Lcom/mojang/datafixers/Typed;)Lcom/mojang/datafixers/Typed;) -> [alt/method_18852, apx/method_5041, akr/method_5011, alv/method_5121]
  aof METHOD a ((Lcom/mojang/datafixers/Typed;)Lcom/mojang/datafixers/Typed;) -> [alt/method_18852, akr/method_5011, alv/method_5121, aof/method_5041]
  eft METHOD b (()V) -> [eft/method_1748, dwq/method_1793]
  ecz METHOD b (()V) -> [ecz/method_1748, dwq/method_1793]
  aqc METHOD a ((Lcom/mojang/datafixers/Typed;)Lcom/mojang/datafixers/Typed;) -> [alt/method_18852, akr/method_5011, alv/method_5121, aqc/method_5041]
  eno METHOD a (()V) -> [eno/method_23516, eoa/method_3345, eob/method_20544]
  ehs METHOD b (()V) -> [dwq/method_1793, ehs/method_1748]
  ego METHOD b (()V) -> [dwq/method_1793, ego/method_1748]
  ecs METHOD b (()V) -> [ecs/method_1748, dwq/method_1793]
  eoo METHOD a (()V) -> [eoo/method_23516, eoa/method_3345, eob/method_20544]
  epm METHOD a (()V) -> [eoa/method_3345, epm/method_23516, eob/method_20544]
  dvv METHOD b (()V) -> [dwq/method_1793, dvv/method_1748]
  eeb METHOD b (()V) -> [dwq/method_1793, eeb/method_1748]
  eok METHOD a (()V) -> [eok/method_23516, eoa/method_3345, eob/method_20544]
  dwg METHOD b (()V) -> [dwq/method_1793, dwg/method_1748]
  eho METHOD b (()V) -> [dwq/method_1793, eho/method_1748]
  efi METHOD b (()V) -> [efi/method_1748, dwq/method_1793]
  epn METHOD a (()V) -> [eoa/method_3345, epn/method_23516, eob/method_20544]
  eot METHOD a (()V) -> [eot/method_23516, eoa/method_3345, eob/method_20544]
  eer METHOD b (()V) -> [eer/method_1748, dwq/method_1793]
  dwi METHOD b (()V) -> [dwi/method_1748, dwq/method_1793]
  edh METHOD b (()V) -> [dwq/method_1793, edh/method_1748]
  amq METHOD a ((Lcom/mojang/datafixers/Typed;)Lcom/mojang/datafixers/Typed;) -> [alt/method_18852, amq/method_5041, akr/method_5011, alv/method_5121]
  efl METHOD b (()V) -> [efl/method_1748, dwq/method_1793]
  egk METHOD b (()V) -> [dwq/method_1793, egk/method_1748]
  enr METHOD a (()V) -> [eoa/method_3345, eob/method_20544, enr/method_23516]
  efu METHOD b (()V) -> [efu/method_1748, dwq/method_1793]
  dwf METHOD b (()V) -> [dwq/method_1793, dwf/method_1748]
  enq METHOD a (()V) -> [enq/method_23516, eoa/method_3345, eob/method_20544]
  amj METHOD a ((Lcom/mojang/datafixers/Typed;)Lcom/mojang/datafixers/Typed;) -> [alt/method_18852, amj/method_5041, akr/method_5011, alv/method_5121]
  ehm METHOD b (()V) -> [ehm/method_1748, dwq/method_1793]
  akv METHOD a ((Lcom/mojang/datafixers/Typed;)Lcom/mojang/datafixers/Typed;) -> [alt/method_18852, akv/method_5041, akr/method_5011, alv/method_5121]
  edl METHOD b (()V) -> [dwq/method_1793, edl/method_1748]
  dwk METHOD b (()V) -> [dwq/method_1793, dwk/method_1748]
  eou METHOD a (()V) -> [eoa/method_3345, eob/method_20544, eou/method_23516]
  dwj METHOD b (()V) -> [dwq/method_1793, dwj/method_1748]
  ecy METHOD b (()V) -> [ecy/method_1748, dwq/method_1793]
  api METHOD a ((Ljava/lang/String;)Ljava/lang/String;) -> [amu/method_5185, ana/method_24326, api/method_5179]
  amv METHOD a ((Ljava/lang/String;)Ljava/lang/String;) -> [amv/method_5179, amu/method_5185, ana/method_24326]
  ede METHOD b (()V) -> [dwq/method_1793, ede/method_1748]
  dwc METHOD b (()V) -> [dwq/method_1793, dwc/method_1748]
  amz METHOD a ((Lcom/mojang/datafixers/Typed;)Lcom/mojang/datafixers/Typed;) -> [alt/method_18852, amz/method_5041, akr/method_5011, alv/method_5121]
  epa METHOD a (()V) -> [eoa/method_3345, eob/method_20544, epa/method_23516]
  efh METHOD b (()V) -> [efh/method_1748, dwq/method_1793]
  alv METHOD a ((Lcom/mojang/datafixers/Typed;)Lcom/mojang/datafixers/Typed;) -> [alt/method_18852, alv/method_5041, akr/method_5011, alv/method_5121]
  epb METHOD a (()V) -> [eoa/method_3345, epb/method_23516, eob/method_20544]
  eoe METHOD a (()V) -> [eoa/method_3345, eoe/method_23516, eob/method_20544]
  dvw METHOD b (()V) -> [dvw/method_1748, dwq/method_1793]
  efx METHOD b (()V) -> [efx/method_1748, dwq/method_1793]
  edb METHOD b (()V) -> [edb/method_1748, dwq/method_1793]
  eel METHOD b (()V) -> [eel/method_1748, dwq/method_1793]
  dwn METHOD b (()V) -> [dwq/method_1793, dwn/method_1748]
  alt METHOD a ((Lcom/mojang/datafixers/Typed;)Lcom/mojang/datafixers/Typed;) -> [alt/method_5041, alt/method_18852, akr/method_5011, alv/method_5121]
  dwo METHOD b (()V) -> [dwq/method_1793, dwo/method_1748]
  een METHOD b (()V) -> [een/method_1748, dwq/method_1793]
  eds METHOD b (()V) -> [eds/method_1748, dwq/method_1793]
  efs METHOD b (()V) -> [efs/method_1748, dwq/method_1793]
  anv METHOD a ((Lcom/mojang/datafixers/Typed;)Lcom/mojang/datafixers/Typed;) -> [anv/method_5041, alt/method_18852, akr/method_5011, alv/method_5121]
  akr METHOD a ((Lcom/mojang/datafixers/Typed;)Lcom/mojang/datafixers/Typed;) -> [akr/method_5041, alt/method_18852, akr/method_5011, alv/method_5121]
  enp METHOD a (()V) -> [enp/method_23516, eoa/method_3345, eob/method_20544]
  edp METHOD b (()V) -> [dwq/method_1793, edp/method_1748]
  amx METHOD a ((Lcom/mojang/datafixers/Typed;)Lcom/mojang/datafixers/Typed;) -> [alt/method_18852, akr/method_5011, alv/method_5121, amx/method_5041]
  efb METHOD b (()V) -> [dwq/method_1793, efb/method_1748]
  dwr METHOD b (()V) -> [dwq/method_1793, dwr/method_1748]
  edd METHOD b (()V) -> [edd/method_1748, dwq/method_1793]
  dwl METHOD b (()V) -> [dwl/method_1748, dwq/method_1793]
  efr METHOD b (()V) -> [dwq/method_1793, efr/method_1748]
  dwm METHOD b (()V) -> [dwm/method_1748, dwq/method_1793]
  apt METHOD a ((Lcom/mojang/datafixers/Typed;)Lcom/mojang/datafixers/Typed;) -> [apt/method_5041, alt/method_18852, akr/method_5011, alv/method_5121]
  dwb METHOD b (()V) -> [dwq/method_1793, dwb/method_1748]
  eex METHOD b (()V) -> [eex/method_1748, dwq/method_1793]
  ecu METHOD b (()V) -> [ecu/method_1748, dwq/method_1793]
  ecq METHOD b (()V) -> [ecq/method_1748, dwq/method_1793]
  ehp METHOD b (()V) -> [dwq/method_1793, ehp/method_1748]
  enx METHOD a (()V) -> [eoa/method_3345, enx/method_23516, eob/method_20544]
  dws METHOD b (()V) -> [dwq/method_1793, dws/method_1748]
  amu METHOD a ((Ljava/lang/String;)Ljava/lang/String;) -> [amu/method_5185, amu/method_5179, ana/method_24326]
  dvx METHOD b (()V) -> [dvx/method_1748, dwq/method_1793]
  apv METHOD a ((Lcom/mojang/datafixers/Typed;)Lcom/mojang/datafixers/Typed;) -> [apv/method_5041, alt/method_18852, akr/method_5011, alv/method_5121]
  aml METHOD a ((Ljava/lang/String;)Ljava/lang/String;) -> [amu/method_5185, aml/method_5179, ana/method_24326]
  aky METHOD a ((Lcom/mojang/datafixers/Typed;)Lcom/mojang/datafixers/Typed;) -> [aky/method_5041, alt/method_18852, akr/method_5011, alv/method_5121]
  edn METHOD b (()V) -> [edn/method_1748, dwq/method_1793]
  ana METHOD a ((Ljava/lang/String;)Ljava/lang/String;) -> [amu/method_5185, ana/method_5179, ana/method_24326]
  dwh METHOD b (()V) -> [dwh/method_1748, dwq/method_1793]
  eoc$e METHOD a (()V) -> [eoc$e/method_23516, eoa/method_3345, eob/method_20544]
  aps METHOD a ((Lcom/mojang/datafixers/Typed;)Lcom/mojang/datafixers/Typed;) -> [alt/method_18852, akr/method_5011, alv/method_5121, aps/method_5041]
  eog METHOD a (()V) -> [eoa/method_3345, eob/method_20544, eog/method_23516]
  ecw METHOD b (()V) -> [ecw/method_1748, dwq/method_1793]
  ehq METHOD b (()V) -> [ehq/method_1748, dwq/method_1793]
  eep METHOD b (()V) -> [eep/method_1748, dwq/method_1793]
  efw METHOD b (()V) -> [efw/method_1748, dwq/method_1793]
  dwp METHOD b (()V) -> [dwp/method_1748, dwq/method_1793]
  edz METHOD b (()V) -> [edz/method_1748, dwq/method_1793]
  edc METHOD b (()V) -> [edc/method_1748, dwq/method_1793]
  epo METHOD a (()V) -> [eoa/method_3345, epo/method_23516, eob/method_20544]
  dwq METHOD b (()V) -> [dwq/method_1748, dwq/method_1793]
  eet METHOD b (()V) -> [eet/method_1748, dwq/method_1793]
  dtw METHOD b (()V) -> [dtw/method_1748, dwq/method_1793]
  epp METHOD a (()V) -> [eoa/method_3345, eob/method_20544, epp/method_23516]
  eee METHOD b (()V) -> [dwq/method_1793, eee/method_1748]
  enk METHOD a (()V) -> [enk/method_23516, eoa/method_3345, eob/method_20544]
  aoj METHOD a ((Lcom/mojang/datafixers/Typed;)Lcom/mojang/datafixers/Typed;) -> [alt/method_18852, akr/method_5011, alv/method_5121, aoj/method_5041]
  dvu METHOD b (()V) -> [dwq/method_1793, dvu/method_1748]
  ens METHOD a (()V) -> [eoa/method_3345, eob/method_20544, ens/method_23516]
  eff METHOD b (()V) -> [dwq/method_1793, eff/method_1748]
  efa METHOD b (()V) -> [efa/method_1748, dwq/method_1793]
  eda METHOD b (()V) -> [dwq/method_1793, eda/method_1748]
  eox METHOD a (()V) -> [eox/method_23516, eoa/method_3345, eob/method_20544]
  eoc$c METHOD a (()V) -> [eoc$c/method_23516, eoa/method_3345, eob/method_20544]
  aoz METHOD a ((Lcom/mojang/datafixers/Typed;)Lcom/mojang/datafixers/Typed;) -> [alt/method_18852, akr/method_5011, alv/method_5121, aoz/method_5041]
  dwd METHOD b (()V) -> [dwd/method_1748, dwq/method_1793]
  edg METHOD b (()V) -> [edg/method_1748, dwq/method_1793]
  eov METHOD a (()V) -> [eoa/method_3345, eob/method_20544, eov/method_23516]
  eny METHOD a (()V) -> [eny/method_23516, eoa/method_3345, eob/method_20544]
  ecx METHOD b (()V) -> [dwq/method_1793, ecx/method_1748]
  enu METHOD a (()V) -> [enu/method_23516, eoa/method_3345, eob/method_20544]
  edr METHOD b (()V) -> [edr/method_1748, dwq/method_1793]
  eoa METHOD a (()V) -> [eoa/method_23516, eoa/method_3345, eob/method_20544]
  ent METHOD a (()V) -> [ent/method_23516, eoa/method_3345, eob/method_20544]
  dwa METHOD b (()V) -> [dwa/method_1748, dwq/method_1793]
  eez METHOD b (()V) -> [eez/method_1748, dwq/method_1793]
  akx METHOD a ((Lcom/mojang/datafixers/Typed;)Lcom/mojang/datafixers/Typed;) -> [akx/method_5041, alt/method_18852, akr/method_5011, alv/method_5121]
  efq METHOD b (()V) -> [efq/method_1748, dwq/method_1793]
  akw METHOD a ((Lcom/mojang/datafixers/Typed;)Lcom/mojang/datafixers/Typed;) -> [alt/method_18852, akw/method_5041, akr/method_5011, alv/method_5121]
  eed METHOD b (()V) -> [eed/method_1748, dwq/method_1793]
  apm METHOD a ((Lcom/mojang/datafixers/Typed;)Lcom/mojang/datafixers/Typed;) -> [apm/method_5041, alt/method_18852, akr/method_5011, alv/method_5121]
  edw METHOD b (()V) -> [edw/method_1748, dwq/method_1793]
  aks METHOD a ((Lcom/mojang/datafixers/Typed;)Lcom/mojang/datafixers/Typed;) -> [aks/method_5041, alt/method_18852, akr/method_5011, alv/method_5121]
  ake$2 METHOD a ((Lcom/mojang/datafixers/Typed;)Lcom/mojang/datafixers/Typed;) -> [alt/method_18852, akr/method_5011, ake$2/method_5041, alv/method_5121]
  ege METHOD b (()V) -> [ege/method_1748, dwq/method_1793]
  edx METHOD b (()V) -> [dwq/method_1793, edx/method_1748]
  amd METHOD a ((Lcom/mojang/datafixers/Typed;)Lcom/mojang/datafixers/Typed;) -> [alt/method_18852, akr/method_5011, alv/method_5121, amd/method_5041]
  epi METHOD a (()V) -> [epi/method_23516, eoa/method_3345, eob/method_20544]
  eoh METHOD a (()V) -> [eoa/method_3345, eob/method_20544, eoh/method_23516]
  epq METHOD a (()V) -> [eoa/method_3345, eob/method_20544, epq/method_23516]
  dvy METHOD b (()V) -> [dwq/method_1793, dvy/method_1748]
  efd METHOD b (()V) -> [efd/method_1748, dwq/method_1793]
  amm METHOD a ((Ljava/lang/String;)Ljava/lang/String;) -> [amu/method_5185, amm/method_5179, ana/method_24326]
  edy METHOD b (()V) -> [dwq/method_1793, edy/method_1748]
  eea METHOD b (()V) -> [dwq/method_1793, eea/method_1748]
  epg METHOD a (()V) -> [epg/method_23516, eoa/method_3345, eob/method_20544]
  eec METHOD b (()V) -> [eec/method_1748, dwq/method_1793]
  and METHOD a ((Lcom/mojang/datafixers/Typed;)Lcom/mojang/datafixers/Typed;) -> [and/method_5041, alt/method_18852, akr/method_5011, alv/method_5121]
  dwe METHOD b (()V) -> [dwe/method_1748, dwq/method_1793]
  alf METHOD a ((Lcom/mojang/datafixers/Typed;)Lcom/mojang/datafixers/Typed;) -> [alt/method_18852, alf/method_5041, akr/method_5011, alv/method_5121]
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: Unfixable conflicts
	at net.fabricmc.tinyremapper.TinyRemapper.handleConflicts(TinyRemapper.java:861)
	at net.fabricmc.tinyremapper.TinyRemapper.propagate(TinyRemapper.java:761)
	at net.fabricmc.tinyremapper.TinyRemapper.mrjRefresh(TinyRemapper.java:1040)
	at net.fabricmc.tinyremapper.TinyRemapper.apply(TinyRemapper.java:892)
	at net.fabricmc.loader.impl.game.GameProviderHelper.deobfuscate0(GameProviderHelper.java:283)
	at net.fabricmc.loader.impl.game.GameProviderHelper.deobfuscate(GameProviderHelper.java:217)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.initialize(MinecraftGameProvider.java:281)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:136)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	... 8 more
Exiting with -1
Process exited with code -1.
MultiMC: Log upload triggered at: 24 Mar 2022 20:00:22 +0100

**Comment by MeeniMc** [comment] 2022-03-24 23:27
I think your problem is here: `: Incomplete remapped file found! This means that the remapping process failed on the previous launch. If this persists, make sure to let us at Fabric know!`

Not sure why it happened in the first place, but probably is not related to Sodium. 

Anyway, you may be able to fix it by removing the `.fabric` directory from the game directory. That will force fabric loader to regenerate the whole thing and presumably fix this error.

**Comment by jellysquid3** [comment] 2022-04-23 02:57
Closing this as it seems your Fabric installation is corrupted, and that Sodium is not the cause of this problem.

**Closed as completed by jellysquid3** 2022-04-23 02:57 UTC
Labels: E-external, T-crash
