### ISSUE TITLE
Sodium causes water to render weird

### ISSUE THREAD

**Issue by haakke1** [jellysquid3/Sodium#2375] opened 2024-03-11 02:10 UTC
### Bug Description

looking at flowing water from specific angles causes the water to render strangely
![2024-03-10_22 04 55](https://github.com/CaffeineMC/sodium-fabric/assets/162938622/3cdc4edb-540f-447b-8c1f-ccd363dfe1fe)

### Reproduction Steps

really not sure what exactly causes it, just full block flowing water that isnt a source block

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/14552789/latest.log)

### Crash Report

[crash-2024-03-10_17.56.10-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/14552792/crash-2024-03-10_17.56.10-client.txt)

**Comment by Lolothepro** [comment] 2024-03-11 03:45
Duplicate of #38

**Closed as not planned** 2024-03-11 14:22 UTC
Labels: E-duplicate
