### ISSUE TITLE
Performance drop over vanilla renderer when using LambDynamicLights

### ISSUE THREAD

**Issue by AeiouEnigma** [jellysquid3/Sodium#1035] opened 2021-12-08 19:11 UTC
### Version information

mc1.18-0.4.0-alpha5+build.9

### Expected Behavior

Performance (FPS) should be at least as high with sodium as without sodium

### Actual Behavior

Using Sodium together with LambDynamicLights results in a severe framerate drop compared to using LambDynamicLights without Sodium.

Here are my Alt+F3 performance graphs in a test scenario when using only LambDynamicLights (vanilla renderer):
![LDL-vanilla](https://user-images.githubusercontent.com/3160746/145268541-276e85d7-31bd-4bbd-80ae-6c859f271467.png)

Here are the graphs in the same test scenario when using only LambDynamicLights and Sodium:
![LDL-sodium](https://user-images.githubusercontent.com/3160746/145268552-a5a26d83-920d-42f9-973a-4d349ded3d88.png)

### Reproduction Steps

Install LambDynamicLights and Sodium.

Enter a world and run around with dynamic lights. Fly over the surface of an ocean with a bunch of glow squid for a more noticeable result.

### Java version

Java 17

### CPU

Intel Core i5-8400

### GPU

NVIDIA GTX 1060 (6GB)

### Additional information

LambDynamicLights version 2.1.0

**Comment by jellysquid3** [comment] 2021-12-09 08:30
Does this issue only occur in the alpha builds of Sodium 0.4 or can you also reproduce it with older versions?

**Comment by AeiouEnigma** [comment] 2021-12-09 15:42
The issue only seems to occur with the alpha builds for 1.18. I just tested in 1.17.1 and found that Sodium substantially outperforms the vanilla renderer in a similar test scenario.

1.17.1 LambDynamicLights without Sodium:
![2021-12-09_10 37 11](https://user-images.githubusercontent.com/3160746/145427714-1bc28705-cc67-45e9-b1e3-387b03c7a992.png)

1.17.1 LambDynamicLights with Sodium: 
![2021-12-09_10 39 22](https://user-images.githubusercontent.com/3160746/145427850-1c1a8aae-226a-49b7-bada-38c0505ab115.png)

**Comment by Cloudperry** [comment] 2021-12-10 22:33
At first I thought that Sodium 0.4 had pretty bad performance but it turns out it was this performance regression. It can be noticed even with very few dynamic lights like holding a torch and a few mobs being on fire. Without dynamic lights on Sodium 0.4 actually runs really well. I only needed to drop my render distance a few chunks down from 28 to get the same performance as I had on sodium 0.3.3.

**Comment by jellysquid3** [comment] 2021-12-10 22:52
This might be resolved with #1026 as we had a number of regressions in our biome blending code caused by the quick changes to get it working in MC 1.18.

**Comment by jellysquid3** [comment] 2021-12-11 21:45
This appears to be caused by poor chunk re-building performance, which is a different issue and will be tracked in #1044.

**Comment by Icyyfr** [comment] 2022-01-06 04:41
(Install Mod Menu for the steps given below to change the mod settings in game)

Turning off "Water Sensitivity Check" in LambDynamicLights config improves the fps by a lot when near water bodies, though that would make it so that some light sources that shouldn't emit light in water will emit light, but it's totally fine for me.

Fps also drops in the nether when in Basalt Deltas, I just usually disable LambDynamicLights for a while then because there is a lot of light around anyway.

Even though my reply is 25 days after the issue was reported, it's so you can still use LambDynamicLights with Sodium without using any bleeding edge build fixing the issue, however I hope a new release is on the way soon.

**Comment by jellysquid3** [comment] 2023-09-17 17:36
LambDynamicLights is always going to be miserably slow due to how it spams chunk updates to update light values. There is nothing which can really be done to solve this, unless someone implements a shader-based approach for dynamic lights which does not require chunk updates.

**Closed as not planned by jellysquid3** 2023-09-17 17:36 UTC
Labels: T-bug, E-will-not-fix
