### ISSUE TITLE
Crash on Joining a Minigame 

### ISSUE THREAD

**Issue by frqnny** [jellysquid3/Sodium#189] opened 2020-07-26 18:58 UTC
### Reproduction Steps
Provide information on how to reproduce this game crash. This step is critical for ensuring that your crash can be debugged by other developers. You can either fill in the example below or do something else -- just make sure your instructions are minimal and clear. If applicable, provide a Minecraft save containing a minimal example on how to reproduce this crash as a compressed ZIP file.

I went into a world and for some reason it crashed, IDK why to have enough reasons. 

### Crash Report File
Please upload your crash report as a file to [GitHub Gist](https://gist.github.com/) and replace this text with a link to the uploaded report.
https://pastebin.com/JuMYXa2i

the bottom crash is the one that killed my game and froze it

### Additional Information
Provide any additional information or context which may be relevant to the issue. If you have none to add, you can remove this section.

**Comment by embeddedt** [comment] 2021-03-09 19:57
I've run into this issue as well. I'm using HolographicDisplays 2.4.6 on a Paper 1.16.5 server proxied through the latest version of Waterfall.

The issue can be worked around by disabling HolographicDisplays or removing Sodium (neither of which I want to do :wink:).

I should note that the issue doesn't occur if you create the hologram (armor stand) after the world has been loaded. It only happens if the armor stand is pre-existing when you join the world.

Crash log: https://gist.github.com/embeddedt/81cd9b52fff933fb399827d339caf5e1

**Comment by comp500** [comment] 2021-03-16 22:15
#581 should fix this crash, though it's surprising that it occurs so rarely. I've managed to replicate the crash by setting the water BlockState's shape cache to null in a debugger - it doesn't seem to happen when the shape cache is set as it usually would be. Not sure exactly why the shape cache would be null, as it's set during tag loading... it could be a race condition when syncing that data with the server?

Edit: Could be related to the use of protocol translation mods/plugins - see https://github.com/CaffeineMC/sodium-fabric/issues/208#issuecomment-665831827

**Comment by comp500** [comment] 2021-03-16 23:15
@embeddedt I can't replicate this behaviour (and I think it's actually https://github.com/CaffeineMC/sodium-fabric/issues/218 which I don't think is a duplicate of this issue) - does this happen with a brand new world? Is there specific text which makes it occur, or does it happen with any holographic display?

**Comment by embeddedt** [comment] 2021-03-16 23:18
It seems to happen with holographic displays in a particular position. I wasn't having any problems till I rebuilt the lobby in my world. When I moved the holographic displays to the new lobby's location (maybe 200 blocks away) the crash started happening. The text I was using on my holographic display is "Survival 2" but I'm doubtful that that helps.

EDIT: This was happening on both the stable 0.1.0 release and the 1.16.x/next branch.

**Comment by comp500** [comment] 2021-03-17 00:13
Can you test with this branch of my fork? <https://github.com/comp500/sodium-fabric/tree/bufferbuildergroworder>

It seems that Sodium isn't growing BufferBuilders in the way vanilla code expects, which causes crashes when it tries to append vertices to a full buffer.

**Comment by embeddedt** [comment] 2021-03-17 00:26
@comp500 Thank you! It looks like this build fixes the issue.

As a side note, I kept running into OutOfMemoryErrors while trying to compile, so I raised the maximum heap space in `gradle.properties` from 1 gigabyte to 4 gigabytes. I'm not sure if this affects anyone else or not.

**Comment by Inpaladin** [comment] 2021-05-15 09:46
> Can you test with this branch of my fork? https://github.com/comp500/sodium-fabric/tree/bufferbuildergroworder
> 
> It seems that Sodium isn't growing BufferBuilders in the way vanilla code expects, which causes crashes when it tries to append vertices to a full buffer.

this appears to now be a dead link, currently having a similar issue and want to see if this fixes it.

**Comment by embeddedt** [comment] 2021-05-15 12:59
I believe it’s fixed in the latest upstream dev builds.

**Comment by mrmangohands** [comment] 2021-07-11 06:45
Should be fixed by 4046bbd and 7dafc0b, closing.

**Closed as completed by mrmangohands** 2021-07-11 06:45 UTC
Labels: T-crash
