### ISSUE TITLE
Sodium x-ray flash when breaking blocks

### ISSUE THREAD

**Issue by 6553gter** [jellysquid3/Sodium#1485] opened 2022-10-27 20:42 UTC
### Version information

mc:1.17-1.19

### Expected Behavior

Whenever I break blocks there is a bit of xray vision at the bottom of the screen I tried installing some lighting mods e.g. phosphor and starlight but they don't fix the issue.
Computer Specs
![image](https://user-images.githubusercontent.com/85507525/198392667-ea0e3a6b-7744-4dc4-a981-9db925d359d1.png)

Java:
![image](https://user-images.githubusercontent.com/85507525/198393412-79251201-1dc9-4758-afa8-30c145a69d60.png)

### Actual Behavior

Whenever break blocks/blocks break a small flash of xray

### Reproduction Steps

place down/break block
small flash of xray

### Java version

Java 17.0.3

### CPU

intel core i5

### GPU

intel(R) UHD Graphics

**Comment by 6553gter** [comment] 2022-10-27 20:50
please get in contact with me soon
you can do it by adding me on discord and or here
discord:6553gter#9099

**Comment by Felix14-v2** [comment] 2022-10-28 01:12
Make sure you have "always defer chunk updates" disabled. You can also try to increase the number of "chunk update threads".

**Comment by 6553gter** [comment] 2022-10-28 06:57
Thank you, life saver when I made my chunk updates 5 it stopped also disabling always defer chunk updates worked, thanks

**Comment by 6553gter** [comment] 2022-10-28 07:06
nope still getting them, doesn't work

**Comment by Nigdu** [comment] 2022-11-06 21:46
Yo, I had the same issue and here's what I figured out regarding this bug:

It gets triggered when you reload resource packs (F3+T)

Fixing: go into your .minecraft folder, mods folder, then simply delete the sodium mod and copy it in again {I recommend keeping the mod file copy somewhere else you can copy it again if the issue resurfaces}

I hope this will work for you, it does for me. And don't worry about your settings getting reset or something, they don't change even if you go through this process.

**Comment by 6553gter** [comment] 2023-01-28 19:54
No it wasn't that and I just figured out it was my graphics driver out of date I learned this while I was in my Graphics Command Centre and then I saw that it required an update
![image](https://user-images.githubusercontent.com/85507525/215287980-1373d33e-b428-4377-a324-73e1f6201df4.png)
and this bit right here had a red dot
![image](https://user-images.githubusercontent.com/85507525/215288016-d0d544a8-5bcf-49c6-8c0e-881b5473cd5e.png)
So I had to install this app
![image](https://user-images.githubusercontent.com/85507525/215288043-f524914c-f681-41d8-b88e-da7a878ce1ce.png)
and now all I need to do is stay up to date with it but thanks for the help

**Comment by 6553gter** [comment] 2023-01-28 19:57
Put about 4 hours of research into it

**Comment by piuvas** [comment] 2023-05-03 00:04
should be closed? i can't tell if you mean you fixed it.

**Comment by pajicadvance** [comment] 2023-05-10 17:07
Duplicate of #869.

**Closed as not planned by pajicadvance** 2023-05-10 17:07 UTC
Labels: T-bug, E-duplicate, A-drivers
