### ISSUE TITLE
Sides of water do not render on the edge of loaded chunks

### ISSUE THREAD

**Issue by djmrFunnyMan** [jellysquid3/Sodium#2435] opened 2024-04-27 18:06 UTC
### Bug Description

In vanilla, when a water is next to unloaded chunks it'll have a water flowing texture facing into the unloaded chunk. Sodium removes this behaviour.

This causes issues for iris shaders as the the light doesn't get processed as having passed through water which looks wrong in deep ocean.
![image](https://github.com/CaffeineMC/sodium-fabric/assets/68905776/9c73eb1e-cd38-46c9-ae84-9b6e83f6f4b4)
![image](https://github.com/CaffeineMC/sodium-fabric/assets/68905776/b2606183-4a8f-4e32-a3da-d20dc39a8c35)

### Reproduction Steps

1. Run the vanilla game
2. Lag the game by searching for a rare biome like eroded badlands
3. Go to the edge of your loaded chunks and see the water side.
![2024-04-27_19 53 14](https://github.com/CaffeineMC/sodium-fabric/assets/68905776/268f7861-d7ab-4f9d-ba1f-9720edbb418a)
4. Do the same thing with sodium
5. Notice the water side is missing
![2024-04-27_19 48 56](https://github.com/CaffeineMC/sodium-fabric/assets/68905776/26909844-0a26-4e84-bd39-01ec1e1315b9)
6. Get shaders+iris+sodium
7. Go to a deep ocean or lower your render distance and observe the issue below
![image](https://github.com/CaffeineMC/sodium-fabric/assets/68905776/9c73eb1e-cd38-46c9-ae84-9b6e83f6f4b4)

### Log File

Not necessary

### Crash Report

Not necessary

**Comment by embeddedt** [comment] 2024-04-27 18:44
Pretty sure this is by design and not really fixable. Doing it the vanilla way would cause a significant increase in the number of required chunk remeshes (because every time a neighbor is loaded, the chunk itself has to be updated to remove the water wall).

**Comment by douira** [comment] 2024-04-27 18:53
The issue with shadows is something that iris could fix specifically to prevent light leaking like this. There's a few ideas but it's complicated.

**Comment by djmrFunnyMan** [comment] 2024-04-27 19:19
Should I open an issue on the iris repository then?

**Comment by jellysquid3** [comment] 2024-04-27 19:22
This is the same problem as https://github.com/CaffeineMC/sodium-fabric/issues/2031, where chunks that shouldn't be meshed are forced to when the player gets close enough at a short render distance. It won't be fixed.

**Closed as not planned by jellysquid3** 2024-04-27 19:22 UTC
Labels: E-will-not-fix, A-vanilla-parity

**Comment by douira** [comment] 2024-04-27 19:25
Iris is aware of the light leaking problem, you don't need to make an issue for it.
