### ISSUE TITLE
Sodium Crashes MC When Joining/Creating New World

### ISSUE THREAD

**Issue by cookie-GHUB** [jellysquid3/Sodium#1690] opened 2023-04-09 23:09 UTC
### Version information

mc1.19.4-0.4.10+build.24

### Reproduction Steps

1. Open minecraft with sodium mod
2. Create/Join A World
3. Game Crashes After A Few Seconds (Blocks Don't Even Load)

### Crash Report file

[Crash Report For Sodium.txt](https://github.com/CaffeineMC/sodium-fabric/files/11186489/Crash.Report.For.Sodium.txt)

### Additional information

IDK if you need this, cuz the title says it already, but when I join/create a world, mc crashes, giving me the crash report, read a little bit of it, and assume that it is because of sodium, so im giving you this issue to let you guys know :)

**Comment by pajicadvance** [comment] 2023-04-09 23:30
The crash seems to be caused by a conflict between Dropz and Sodium. Try disabling Dropz.

**Comment by jellysquid3** [comment] 2023-05-08 16:25
This is just a symptom of #1620. Closing.

**Closed as not planned by jellysquid3** 2023-05-08 16:25 UTC
Labels: E-duplicate, A-mods, T-crash
