### ISSUE TITLE
Transparent textures  sodium and snow real magic (1.21.1 neoforge)

### ISSUE THREAD

**Issue by kontrola111** [jellysquid3/Sodium#2925] opened 2024-12-08 01:45 UTC
### Bug Description

Hi, I noticed  when snow begins to cover the stairs or plants (e.g. short grass) it becomes invisible/transparent.

I checked which mod causes this and it turned out that the problem occurs only with
sodium

Minecraft version: 1.21.1
Modloader: Neoforge 21.1.83
Mods: Kiwi, Snow Real Magic, Sodium

![image](https://github.com/user-attachments/assets/34e50dda-49ba-431f-9324-43617b246e66)

### Reproduction Steps

Just install Snow Real Magic and sodium

### Log File

[latest.log](https://github.com/user-attachments/files/18050435/latest.log)

### Crash Report

[crash-2024-12-08_02.38.18-client.txt](https://github.com/user-attachments/files/18050434/crash-2024-12-08_02.38.18-client.txt)

**Comment by douira** [comment] 2024-12-08 01:47
Duplicate of https://github.com/CaffeineMC/sodium/issues/2848, closing in favor of the older issue. Thanks for providing a screenshot though.

**Closed as not planned by douira** 2024-12-08 01:47 UTC
Labels: E-duplicate
