### ISSUE TITLE
[QUESTION] It is possible to integrate with Vulkan mod

### ISSUE THREAD

**Issue by Nerus87** [jellysquid3/Sodium#2598] opened 2024-07-14 20:36 UTC
### Request Description

As in the thread, Is it possible to integrate somehow API with Vulkan to override OpenGL?
https://modrinth.com/mod/vulkanmod

**Comment by Lolothepro** [comment] 2024-07-14 20:39
Duplicate of https://github.com/CaffeineMC/sodium-fabric/issues/1496

**Comment by jellysquid3** [comment] 2024-07-14 21:15
The issue tracker is not for questions.

Regardless, we've given our two cents on this in a lot of other closed issues already. Yes, it is _theoretically_ possible to use Vulkan, but it's outside the project's goals and we don't think it's necessary for good performance.

**Closed as not planned by jellysquid3** 2024-07-14 21:15 UTC
Labels: T-question

**Comment by Felix14-v2** [comment] 2024-07-14 22:46
> ### Request Description
> As in the thread, Is it possible to integrate somehow API with Vulkan to override OpenGL? https://modrinth.com/mod/vulkanmod

If you want to use Sodium with Vulkan, just use VulkanMod. It uses Sodium chunk rendering engine since 0.4.0.

**Comment by Nerus87** [comment] 2024-07-16 18:13
But crashing with Iris.

**Comment by ghost** [comment] 2024-07-16 19:01
> But crashing with Iris.

That's because Iris also utilizes OpenGL.
And FYI, if Sodium moved to Vulkan, Iris would crash too. And even if Iris moved to Vulkan too, it'd make every shader incompatible since they're based around OpenGL.

**Comment by Nerus87** [comment] 2024-07-17 19:08
> And FYI, if Sodium

I thought Iris was utilizing Sodium as a dependency
