### ISSUE TITLE
Game only showing the chunk im standing on

### ISSUE THREAD

**Issue by Astromyl** [jellysquid3/Sodium#643] opened 2021-04-27 06:17 UTC
not only that, but the chunk im seeing also combines with others making it almost impossible to see

version is mc1.16.3-0.1.0.
i also tried it with the other version. it seems to have the same problem

**Comment by LucilleTea** [comment] 2021-04-28 06:44
Probably a duplicate of #179 , depending on your hardware or settings. Going to video settings > advanced and then setting the chunk renderer to Oneshot (GL 3.0) will fix it.

**Closed as completed by LucilleTea** 2021-04-28 06:44 UTC
Labels: T-bug, E-duplicate
