### ISSUE TITLE
i get GBs of errors in my logs with high priority

### ISSUE THREAD

**Issue by MrFireSword** [jellysquid3/Sodium#2119] opened 2023-10-11 16:54 UTC
### Bug Description

I ran an instance on Modrith as well as prism, both have been the same

**Mods present**: 

- Sodium
- fabric API

hardware:

- 3060ti Graphics card
- Ryzen 3700x CPU

![image](https://github.com/CaffeineMC/sodium-fabric/assets/62079225/9a3a2946-f8ec-4b0d-bd87-cc5a5db1acc1)

and this is how big the logs got just by opening the game
It once consumed the entirety of my storage

![image](https://github.com/CaffeineMC/sodium-fabric/assets/62079225/fbedf8cf-9d43-41ad-a552-c200bbb85761)

sometimes it happens at random, and i restart my PC to solve it, now no matter how many times i restart it's the same, i need to make another instance:

 

### Reproduction Steps

For me it's just 

Fabric API and Sodium on 1.20.1 Client 

### Error in the logs: 
https://pastebin.com/EREUKJVd

_side note, the logs just repeat these error and create a MASSIVE file_

### Crash Report

-

**Comment by Lolothepro** [comment] 2023-10-11 16:56
duplicate of https://github.com/CaffeineMC/sodium-fabric/issues/2048

**Comment by pajicadvance** [comment] 2023-10-11 16:59
You most likely have an external application interfering with the game. Check the issue report linked above.

**Closed as not planned by pajicadvance** 2023-10-11 16:59 UTC
Labels: E-duplicate

**Comment by MrFireSword** [comment] 2023-10-11 17:44
Hii, thanks you the reference! 

i uninstallaed Rivatuner and IT SOLVED IT 
thank you sooo much for the swift and accurante response. 

Guys you have saved me hours. 
from the bottom by my heart, you have my deepest Thank yous
