### ISSUE TITLE
Armor stands cause the game to crash

### ISSUE THREAD

**Issue by Aeldit** [jellysquid3/Sodium#634] opened 2021-04-17 16:33 UTC
The game crashed when i connected on my server, so i looked in the crash report and it was saying that the game crashed because the rendering of an armor stand didn't succeed. I reconnect to the server whith an other account and i removed the armor stand and it resolved the probleme (even when i replaced the armor stand at the exact same place and with the same parameters

**Comment by QPCrummer** [comment] 2021-04-18 15:40
This is a big problem on Hypixel too. Whenever joining, it crashes.

**Comment by Aeldit** [comment] 2021-04-18 15:42
Well it never happend on my computer but on the one my sister use (i have a graphic card and not her, don't know if this can be the cause)

**Comment by QPCrummer** [comment] 2021-04-18 15:44
I do have a graphics card

**Comment by Kroppeb** [comment] 2021-04-18 16:03
It would be very useful if either of you could provide a crashlog.

**Comment by Aeldit** [comment] 2021-04-18 16:55
I'll try next week but like its not on my computer i don't know when i could do it

**Comment by Aeldit** [comment] 2021-04-19 18:22
[crash-2021-04-17_18.19.44-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/6338199/crash-2021-04-17_18.19.44-client.txt)

**Comment by Aeldit** [comment] 2021-04-19 18:22
here is the crash report for the rendering of the armor stand. But now that i reread it i'm not sure the bug comes from sodium (but it is the only mod changing the render in the game)

**Comment by embeddedt** [comment] 2021-04-24 14:49
@Raphoulfifou I haven't checked the crash log, but this might be the same issue that was fixed in #614. The fix is in the `1.16.x/next` branch so you will need to use a newer build of Sodium than the current 0.1.0 release.

**Comment by LucilleTea** [comment] 2021-04-28 06:48
This does appear to be a duplicate of #218 , so should be fixed in sodium builds after the mentioned PR was merged, yes.

**Closed as completed by LucilleTea** 2021-04-28 06:48 UTC
Labels: E-duplicate, T-crash
