### ISSUE TITLE
Astromine liquids render with normal water color

### ISSUE THREAD

**Issue by CerbTheOne** [jellysquid3/Sodium#485] opened 2021-01-20 22:18 UTC
### Expected Behavior
Astromine's liquids should have distinct colors.

### Actual Behavior
They all render using vanilla water color, minus transparency.

### Reproduction Steps

1. Install Fabric Modloader 0.11.1, Astromine 1.11.5 and Fabric API 0.29.4.
2. Find or place down any of Astromine's custom liquids.
3. Notice they use the water color instead of their actual color.

### Attachments
![2021-01-20_18 14 55](https://user-images.githubusercontent.com/22283069/105245501-b8bf7b00-5b50-11eb-9d76-e56172f438fd.png)
Without Sodium

![2021-01-20_18 19 58](https://user-images.githubusercontent.com/22283069/105245513-bc530200-5b50-11eb-8eff-9db6a5db9021.png)
With Sodium

### System Information

- Java Version: 1.8.0_281
- CPU: Intel Core i7-9750H
- GPU: GTX 1050 3GB

**Comment by fsharpseven** [comment] 2021-01-21 23:24
This is likely due to Sodium not being compatible with the Fabric Rendering API (see [the issue on the Astromine repository](https://github.com/Mixinors/Astromine/issues/334#issue-722026884)). Until it is supported, the mod won't work with Astromine, which uses the API.

**Comment by amnotbananaama** [comment] 2021-02-04 00:27
Closing as a duplicate of #5, as fixing that issue will solve this one as well

**Closed as completed by amnotbananaama** 2021-02-04 00:27 UTC
Labels: T-bug, E-duplicate
