### ISSUE TITLE
All textures (not entities) are loaded in a single chunk

### ISSUE THREAD

**Issue by K0smic** [jellysquid3/Sodium#447] opened 2020-12-26 17:57 UTC
### Expected Behavior
The chunks must load correctly.

### Actual Behavior
All textures (not entities) are loaded in a single chunk but the block hitboxes remain in place. When the character changes chunk everything is loaded into it. When the character moves the camera the textures also change.

### Reproduction Steps
Enter a world with these mods installed and after a short time it happens.
I don't know which mod is causing the conflict.
Mods:
https://gist.github.com/K0smic/faf27f0d0d97754cd6ace1a16cfbd02a

### Attachments
![2020-12-26_18 03 01](https://user-images.githubusercontent.com/74264648/103156293-9a5f9d00-47a7-11eb-90c6-e527260aae30.png)
![2020-12-26_18 03 10](https://user-images.githubusercontent.com/74264648/103156294-9c296080-47a7-11eb-84dc-d15183c82441.png)
![2020-12-26_18 03 12](https://user-images.githubusercontent.com/74264648/103156296-9cc1f700-47a7-11eb-8038-b79536efe3e7.png)
![2020-12-26_18 03 21](https://user-images.githubusercontent.com/74264648/103156297-9d5a8d80-47a7-11eb-8489-4de3c61d84f8.png)

### System Information
- Java Version: [1.8.0_51 64Bit]
- CPU: [Intel Celeron CPU 1007U @1.50GHz (2 CPUs)]
- GPU: [Intel HD Graphics]

**Comment by amnotbananaama** [comment] 2020-12-26 21:21
Duplicate of #179. You can workaround this by going to Options -> Video Settings -> Advanced and setting "Chunk Renderer" to 3.0 or 2.1.

**Closed as completed by amnotbananaama** 2020-12-26 21:21 UTC
Labels: T-bug, E-duplicate
