### ISSUE TITLE
"Use compact vertex format" causes severe flickering with iron bars

### ISSUE THREAD

**Issue by FewerFlaws** [jellysquid3/Sodium#460] opened 2020-12-31 11:52 UTC
### Expected Behavior
The bottom of iron bars should be clearly visible with no flickering or z-fighting.

### Actual Behavior
The bottom of iron bars flickers with the texture of the block below it.

### Reproduction Steps
1. Place two iron bars next to each other on the ground.
2. Enable "Use compact vertex format" in Video Settings -> Advanced.
3. Move camera slowly while watching the base of the bars.

### Attachments
Compact Vertex Format Enabled: 
![2020-12-31_03 42 56](https://user-images.githubusercontent.com/75643699/103409407-83a8a580-4b1b-11eb-9609-37d1435c2ebe.png)

Compact Vertex Format Disabled, f3 debug activated:
![2020-12-31_03 50 41](https://user-images.githubusercontent.com/75643699/103409418-94591b80-4b1b-11eb-892f-dfac01edde27.png)

### System Information
- Java Version: 1.8.0_271 64 bit
- CPU: Intel Core i7 3770
- GPU: Nvidia GTX 1060

**Comment by amnotbananaama** [comment] 2021-01-03 18:20
It's my understanding that Sodium is displaying [an underlying  vanilla bug](https://bugs.mojang.com/browse/MC-192420) here. Relevant info from Jelly:
> The problem is that Mojang relies on infinitesimally small offsets in some edge cases. There's not much we can do other than to try and retain as much precision as possible. But in the case of iron bars there, it looks unrelated. Their bottom face should not be visible if there's a block beneath it, so we're probably looking at some problem in the occlusion test.

**Comment by FewerFlaws** [comment] 2021-01-03 20:11
Ah, okay.  Following a link from there I found a fix for it in the fixes section of [Vanilla Tweaks Resource Packs](https://vanillatweaks.net/picker/resource-packs/).  I'll try that out =D

**Comment by Kichura** [comment] 2021-01-05 14:11
The vanilla tweaks context seems to resolve this issue above for time being although i'm pretty concerned on how mojang never provided a resolution to this and instead nagged the users to update drivers (See comments section for this one). 

As for reproduction: Yes this is confirmed.

**Comment by felix91gr** [comment] 2021-07-19 07:55
This has now been fixed, right? As in, since the just-released 0.3.0?

**Comment by Lolothepro** [comment] 2022-06-08 15:48
Note: this also occurs with mangrove roots.

**Comment by mrjasonn** [comment] 2023-04-02 15:08
Still is like this on Sodium 1.19.4, even with the default sodium settings

**Comment by MeeniMc** [comment] 2023-05-11 02:12
This is still present in 0.4.10 (one cannot remove 'compact vertex format' anymore).

This used to be a bug inherited from Vanilla, but ~~this has been fixed in Vanilla (as of 1.19.4, at least).~~ I can't reproduce it anymore in vanilla (1.19.4) but the issue remains open on mojang tracker (see below).

**Comment by Lolothepro** [comment] 2023-05-11 06:04
https://bugs.mojang.com/browse/MC-192420
Not fixed with Minecraft 1.19.4

**Comment by jellysquid3** [comment] 2024-04-29 06:37
This is fixed with https://github.com/CaffeineMC/sodium-fabric/commit/ea0172768a5da9907b5a5711160dc3984fafea83.

**Closed as completed by jellysquid3** 2024-04-29 06:37 UTC
Labels: T-bug, S-confirmed
