### ISSUE TITLE
Fabric doesn't load while using Sodium

### ISSUE THREAD

**Issue by Foxren** [jellysquid3/Sodium#1347] opened 2022-06-19 12:59 UTC
### Version information

mc1.19-0.4.2-build.16

### Reproduction Steps

Simply putting Sodium in the mods folder results in a "crash"

### Crash Report file

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/9056544/latest.log)

### Additional information

The mod worked fine the first day, along with Phosphor and Lithium, but suddenly doesn't work

**Comment by mikk357** [comment] 2022-06-21 14:06
no logs?

```
⠈⡄⠀⣼⣿⠏⠀⢀⡀⠸⣿⣧⣀⠙⣄⣠⢶⣦⣤⣀⣀⠀⠀⠀⠀⠀⣷⣾⡀⠀⣤⡟
⢰⠃⣸⣿⣿⣶⠾⠟⠁⣻⡿⢿⣿⣿⣟⠁⠀⠉⡿⢿⣿⣷⣦⣀⣴⣥⣿⣿⠇⢰⣿⠃
⣄⠀⠈⠉⠁⠀⢀⣠⣾⣿⣷⣀⠙⠿⢿⣶⣷⣷⣷⣦⣍⡿⣿⣿⣿⣿⡛⠋⢀⣾⠃⠀
⣿⣾⣧⠀⣿⣿⣿⣿⣿⣿⣿⣿⣷⣄⣀⠀⠀⠀⠀⠈⠙⢿⣿⣿⣿⡟⠀⢀⡾⠃⠀⢀
⣛⣽⡏⠀⠀⠙⠿⠿⠻⠻⣿⣿⠘⠻⣿⣿⣿⣶⣦⣄⡀⠀⢻⣿⣿⠃⡰⠟⠁⢀⣴⣿
⢿⡱⠅⠀⠀⠀⢀⣾⠄⢀⢹⣿⣠⠐⠉⠛⠙⠻⢿⣿⣿⡦⢈⣿⣯⢀⣤⠄⢠⣾⣿⣿
⢶⠃⡐⣁⡠⠀⣼⡿⠀⠀⢸⣿⡇⠀⣾⡏⢀⡄⢀⠙⡟⠁⣸⡟⠠⠪⠋⠀⠘⣿⣽⣿
⢀⣠⠒⠁⠀⠀⣿⣷⣤⣴⡿⠛⠃⠀⢿⣆⠄⠀⡼⢢⣿⣿⡿⠔⠊⠀⠀⠀⠙⠻⣿⣿
⠁⠉⠿⢷⣿⠧⢹⣿⣿⠟⠀⠀⣷⣄⣄⣀⣀⣠⣽⣿⣿⡟⠁⠀⠀⢠⠬⡰⠠⠀⠈⠛
⠀⡰⣆⠀⣶⡀⣼⣿⠇⣀⣤⣤⠀⠈⠿⠻⠛⠉⠉⣨⣿⡀⠄⣢⣀⠀⣠⡄⠀⢈⡅⠀
⠘⣗⡟⠀⠋⢠⣿⣿⣾⣿⣿⣿⣾⠇⠀⠐⠀⢀⣾⡿⠀⠟⢾⣿⣿⣍⡸⡃⠀⠈⠇⠂
⠰⢲⣷⠀⢰⣿⣿⣿⣿⡿⠋⢉⣀⡀⠀⠀⣰⣿⡿⠁⠀⠀⠀⠛⠛⠊⢿⣿⣶⣄⢄⠀
⠡⠸⣿⡆⠀⠙⠋⡏⠁⠐⠻⣛⠻⢿⡆⠀⣿⡟⠁⠀⠠⣄⠀⠀⠀⠀⠒⢌⠙⣿⣷⠉
⠠⠳⠟⠁⠀⠀⠰⠇⠀⠀⠈⠉⠛⠦⠁⠸⠟⠀⠀⠀⠀⠿⠷⠄⠀⠤⠖⠆⠀⠀⠉⠃
```

and no information about the environment (launcher, jdk), how long you wait before killing window, how it looks

**Comment by LuishMC** [comment] 2022-06-21 17:30
The same problem happens to me, before it worked correctly, but days later it stopped working out of nowhere. The game freezes on the loading screen.

Here's the only thing that appears in my log:
`[19:33:55] [Render thread/WARN]: Static binding violation: PRIVATE @Overwrite method method_23182 in sodium.mixins.json:features.item.MixinItemRenderer from mod sodium cannot reduce visibiliy of PUBLIC target method, visibility will be upgraded.
[19:33:57] [Worker-Main-1/ERROR]: Failed to retrieve profile key pair
java.io.IOException: Could not retrieve profile key pair
	at net.minecraft.class_7434.method_43605(class_7434.java:112) ~[client-intermediary.jar:?]
	at net.minecraft.class_7434.method_44291(class_7434.java:56) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]`
Then, the typical "Loading Resources" message appears followed by all the mod resources and resource packs and then nothing else.

I have tried uninstalling all the mods and leaving only Sodium, I tried to install other mods like LazyDFU, DashLoader, I reinstalled Fabric, I deleted the "config" folder, I restored the ".fabric" folder and other things, but apparently nothing has worked for me.

Sorry for my english.

**Comment by Teh404Gal** [comment] 2022-06-23 19:49
are you running an older version of mc or fabric loader by any chance?

**Comment by pajicadvance** [comment] 2023-05-09 16:40
Duplicate of #899. Update your drivers.

**Closed as not planned** 2023-05-10 18:13 UTC
Labels: E-duplicate, A-drivers, T-crash

**Comment by vAbrann2** [comment] 2024-01-26 01:30
Hello everyone, i am from venezuela, I know a little bit of english, I have the same error, does anyone know how to solve it?
