### ISSUE TITLE
Is it possible to add the ability to change the resolution in-game?

### ISSUE THREAD

**Issue by leneleaf** [jellysquid3/Sodium#392] opened 2020-11-11 20:49 UTC
If its not, maybe you could make it only change the resolution when you restart the game.

**Comment by amnotbananaama** [comment] 2020-11-11 22:36
This is either a duplicate of #46 or #121, depending on what exactly you mean by resolution. Both will be coming to Sodium eventually

**Closed as completed by amnotbananaama** 2020-11-11 22:36 UTC
Labels: E-duplicate, T-enhancement
