### ISSUE TITLE
Stained glass behind stained glass sometimes disappear

### ISSUE THREAD

**Issue by csdt** [jellysquid3/Sodium#85] opened 2020-07-14 18:01 UTC
### Bug description

When stained glass is behind stained glass, some front faces are not rendered.
This seems to appear only when the first and the second face traversed are in the same subchunk.

No option seems to have any effect on this bug.

| Vanilla | Sodium |
|:---------:|:----------|
| ![2020-07-14_19 45 18](https://user-images.githubusercontent.com/9721130/87458857-e01a1600-c60a-11ea-9f6f-6c52a06d4ecd.png) | ![2020-07-14_19 44 47](https://user-images.githubusercontent.com/9721130/87458994-0fc91e00-c60b-11ea-8526-6e516923d2ba.png) |

Here is a super simple test world showing this: [void.zip](https://github.com/jellysquid3/sodium-fabric/files/4920388/void.zip) (you should spawn in exactly the same angle as in the screenshot)

### System Information

- Java Version: 11.0.6
- CPU: Intel i9-7900X
- GPU: RTX 2080 Ti
- drivers: nvidia 440.100
- OS: Linux

Also:
- Java Version: 14
- CPU: AMD R7 3800X
- GPU: GTX 1660
- drivers: nvidia 446.14
- OS: Windows 10

**Comment by jellysquid3** [comment] 2020-07-14 19:08
Duplicate of #38.

**Closed as completed by jellysquid3** 2020-07-14 19:08 UTC
Labels: T-bug, E-duplicate
