### ISSUE TITLE
Top surfaces of waterfalls and lavafalls are culled too aggressively

### ISSUE THREAD

**Issue by thescyphozoa** [jellysquid3/Sodium#572] opened 2021-03-09 10:38 UTC
### Expected Behavior
The slanted top surfaces of this waterfall should remain visible at least until the player perspective is completely underneath them.

### Actual Behavior
These surfaces become invisible when the player perspective gets below a certain Y-coordinate, even though they are still in view from the top. In some cases I can even see it happen with vertical surfaces, though I suspect these won't be visible once the top surfaces are fixed.

### Reproduction Steps
Find a decently sized waterfall, stand a few blocks back from it, move up and down.

### Attachments
https://streamable.com/v57a0y (top surfaces)
https://streamable.com/vv6eab (vertical surfaces)

### System Information
- Java Version: 8.0.51
- CPU: AMD Ryzen 5 5600x
- GPU: Nvidia RTX 3060 Ti
- Also happened on a different computer with Intel Core i5-6500 and Nvidia GTX 1070

**Comment by LucilleTea** [comment] 2021-03-09 10:57
Duplicate of #171.
This is already fixed in the next branch, or on the release branch you can work around the issue by disabling the "chunk face culling" option.

**Closed as completed by LucilleTea** 2021-03-09 10:57 UTC
Labels: T-bug, E-duplicate
