### ISSUE TITLE
Running out of memory when using Nether portal.

### ISSUE THREAD

**Issue by EquityX** [jellysquid3/Sodium#1717] opened 2023-05-01 20:43 UTC
### Version information

sodium-fabric-mc1.19.4-0.4.11+build.26

### Reproduction Steps

Place a Nether portal & go through it to the Nether. Then go back through to the Overworld. Repeat until memory usage is very high. Eventually the game starts lagging really bad. If you go through a portal when this happens it will either never load or you load into a black screen.

This happens on a clean profile with only Sodium installed. Doing the same thing on a more modded pack simply makes it happen faster.

### Crash Report file

I could not get a crash report to be produced. The game would just freeze and never seemed to actually fully crash.

**Comment by hexadecimal233** [comment] 2023-07-22 07:06
I cannot reproduce it on sodium 0.4.10 or latest dev build, prob it's a sodium 0.4.11 issue

**Comment by jellysquid3** [comment] 2023-07-30 06:16
I can't seem to reproduce this in Sodium 0.5 either and nobody has reported an issue either. So I'm going to close this as fixed...

If you encounter the problem again in Sodium 0.5, please ask for this issue to be re-opened.

**Closed as completed by jellysquid3** 2023-07-30 06:16 UTC
Labels: P-high, S-cannot-repro, T-crash
