### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by BrokenDawn627** [jellysquid3/Sodium#1175] opened 2022-02-10 09:19 UTC
### Version information

mc1.18.1-fabric

### Reproduction Steps

 when teleport to other player

### Crash Report file

[错误报告-2022-2-10_17.08.39.zip](https://github.com/CaffeineMC/sodium-fabric/files/8039708/-2022-2-10_17.08.39.zip)

**Comment by Nekosha** [comment] 2022-02-10 12:41
see #1016

**Comment by silversquirl** [comment] 2022-02-16 06:22
Duplicate of #1016

**Closed as completed by silversquirl** 2022-02-16 06:22 UTC
Labels: E-duplicate, T-crash
