### ISSUE TITLE
Compatibility - Packages v1.0 for MC 1.16.1 and Sodium v0.1.0

### ISSUE THREAD

**Issue by rxay579** [jellysquid3/Sodium#167] opened 2020-07-24 17:46 UTC
### Expected Behavior
Mod's block should render and interact normally.

### Actual Behavior
Mod's block does not render texture/model and behaves abnormally.

### Reproduction Steps
Launch game, create package at package crafter from two materials and a dye.
Hold and/or place package in world.

### Attachments
Log without Sodium:
[latest.log](https://github.com/jellysquid3/sodium-fabric/files/4973479/latest.log)

Log with Sodium:
[2020-07-24-2.log](https://github.com/jellysquid3/sodium-fabric/files/4973481/2020-07-24-2.log)

Screenshots of broken texture:
![2020-07-24_12 19 54](https://user-images.githubusercontent.com/67221030/88419129-34ab5700-cdaa-11ea-89b7-0e37f6a772e6.png)
![2020-07-24_12 20 01](https://user-images.githubusercontent.com/67221030/88419137-370db100-cdaa-11ea-9f94-aa84c4c45b3c.png)

MultiMC Instance with Sodium currently disabled including world save:
[TEST - Packages.zip](https://github.com/jellysquid3/sodium-fabric/files/4973516/TEST.-.Packages.zip)

### System Information
You can obtain this information from the in-game debug screen or through using [DxDiag](https://support.microsoft.com/en-us/help/4028644/windows-open-and-run-dxdiagexe) on Windows.

- Java Version: 1.8u51
- CPU: AMD Ryzen 5 3600
- GPU: Nvidia GeForce GTX 1060 6GB

**Comment by Rongmario** [comment] 2020-07-24 17:50
Duplicate of #5

**Closed as completed** 2020-07-25 17:29 UTC
Labels: T-bug, E-duplicate
