### ISSUE TITLE
Game crash when leaving Nether

### ISSUE THREAD

**Issue by freundf** [jellysquid3/Sodium#1015] opened 2021-12-02 12:12 UTC
### Version information

mc1.18-0.4.0-alpha5+build.9

### Reproduction Steps

I was only able to reliably reproduce this issue on a multiplayer server (it might be related to server lag).

1.) Go to the Nether
2.) Step back into the portal to go to the Overworld
3.) Once the loading screen starts press and hold W to walk forward
4.) When I get to the Overworld the game crashes about 50% of the time

### Crash Report file

[crash-2021-12-02_12.44.45-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/7641559/crash-2021-12-02_12.44.45-client.txt)

#### Server information:
- Version 1.18
- Fabric
- No mods installed

**Comment by dukesteen** [comment] 2021-12-09 11:51
Getting this same issue! From what I've seen it mostly only does it when you hold w in the loading screen as OP said.

**Comment by Lolothepro** [comment] 2022-01-22 09:55
I reproduced the same crash report using perls enders in the overworld (I used the 22w03a version of Sodium provided for Iris)

**Comment by jellysquid3** [comment] 2023-07-22 02:38
Duplicate of #1223.

**Closed as not planned by jellysquid3** 2023-07-22 02:38 UTC
Labels: T-crash
