### ISSUE TITLE
Ice does not render behind water

### ISSUE THREAD

**Issue by CalXee** [jellysquid3/Sodium#135] opened 2020-07-21 23:01 UTC
### Expected Behavior
When putting ice blocks inside of water, you should be able to see the ice underwater since water is transparent.

### Actual Behavior
You do not see the ice at all as soon as it's behind water.

### Reproduction Steps
1. Put water in at least a 3x3 formation.
2. Place ice in the center of the 3x3.
3. The part of the ice that is submerged in water does not render.

- Java Version: [JDK 13.0.1]
- CPU: [Intel Core i7 8750H]
- GPU: [GTX 1050 Ti]

I'm new to Github and not sure how to submit attachments XD

**Comment by amnotbananaama** [comment] 2020-07-21 23:14
Duplicate of #38

**Closed as completed** 2020-08-25 06:27 UTC
Labels: T-bug, E-duplicate
