### ISSUE TITLE
big bug

### ISSUE THREAD

**Issue by Scretchyy** [jellysquid3/Sodium#316] opened 2020-09-27 15:44 UTC
### Expected Behavior
to not be all messed up
### Actual Behavior
is very messed up

### Reproduction Steps
you go on a crappy computer like mine and try to go into a minecraft world with sodium

### Attachments
![2020-09-26_15 35 09](https://user-images.githubusercontent.com/71979179/94369228-80ce8c80-00b6-11eb-9916-5552c3132db5.png)

- Java Version: idk
- CPU: intel(r) celeron(r) cpu n2830@ 2.16ghz
- GPU: none

**Comment by amnotbananaama** [comment] 2020-09-27 16:56
This sounds like a duplicate of #179. You can workaround this by going to Options -> Video Settings -> Advanced and setting "Chunk Renderer" to 3.0 or 2.1. This should fix your issue for now.

This will be fixed in the next release of Sodium.

**Closed as completed by amnotbananaama** 2020-09-27 16:56 UTC
Labels: T-bug, E-duplicate
