### ISSUE TITLE
Allow chunks to remain loaded within the client render distance when on servers

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#547] opened 2021-02-27 18:11 UTC
### Expected Behavior
When I have 32 render distance on a server, and i move forward 20 chunks i should still be able to see the chunks that were loaded before (Like on optifine)

### Actual Behavior
the chunks immediately load behind me, at the render distance of the server, which looks bad and is distracting.

### Reproduction Steps
Play on a server and fly around, observe chunks being unloaded at server render distance.

### Attachments
https://imgur.com/a/B36ZseA

- CPU: Ryzen 7
- GPU: AMD Radeon 5700 XT

**Comment by Zefyro** [comment] 2021-02-27 18:20
That really isn't a bug afaik. Thats vanilla behaviour.

**Comment by ghost** [comment] 2021-02-27 18:38
> That really isn't a bug afaik. Thats vanilla behaviour.

its vanilla behavior but its very distracting.

**Comment by akiraveliara** [comment] 2021-02-27 19:04
Sodium is attempting to mirror vanilla behaviour rather than changing it. This would be outside sodium's scope

**Comment by ghost** [comment] 2021-02-27 19:04
This is not outside of sodiums scope, optifine has this, atleast have it be an option, playing multiplayer without this option looks terrible

**Comment by jellysquid3** [comment] 2021-02-27 19:08
You're reporting this as a bug, but it's vanilla functionality and Sodium is acting consistently. Please use the correct issue template in the future or your issue will be closed as invalid. Just because OptiFine implements something does not mean it is within Sodium's scope.

**Comment by DragonEggBedrockBreaking** [comment] 2021-02-27 19:44
> This is not outside of sodiums scope, optifine has this

OptiFine speeds up the game up a bit but mostly has enhancements (e.g. shaders, connected textures). Sodium is a mod designed to speed up the game *without* changing vanilla behaviour, which is why you need other mods for connected textures, dynamic lighting, shaders, etc. Here is something JellySquid wrote on discord (in #faq):

> Sodium is first and foremost an optimization mod. This means that generally we won't take the approach of adding as many features into one mod as possible.

*Edit: I can't speak for the devs on what they add and what not, so don't take this as a comment saying that it will not be added, as I have no control over that.*

**Comment by amnotbananaama** [comment] 2021-02-27 20:17
Closing as this has already been requested several times. See #149

**Closed as completed by amnotbananaama** 2021-02-27 20:17 UTC
Labels: E-duplicate, T-enhancement

**Comment by ghost** [comment] 2021-02-28 01:52
@amnotbananaama this really sucks since its the only reason I use optifine over sodium, chunks unloading behind is basically unplayable

**Comment by LucilleTea** [comment] 2021-02-28 02:20
Luckily Sodium doesn't have to do everything itself. Though I've never tried it myself and don't know about its compatibility, you can look into using Bobby for this. https://modrinth.com/mod/bobby

**Comment by amnotbananaama** [comment] 2021-02-28 03:01
> @amnotbananaama this really sucks since its the only reason I use optifine over sodium, chunks unloading behind is basically unplayable

I closed this issue because it is a duplicate of the one I linked (which is still open).  Echoing Lucy's recommendation

**Comment by ghost** [comment] 2021-03-01 14:14
> Luckily Sodium doesn't have to do everything itself. Though I've never tried it myself and don't know about its compatibility, you can look into using Bobby for this. https://modrinth.com/mod/bobby

@LucilleTea thank you so much! this mod fits my needs.

**Comment by ghost** [comment] 2021-03-05 12:12
nvm it lags out my game
