### ISSUE TITLE
Bigger GUI Scale

### ISSUE THREAD

**Issue by nisutec** [jellysquid3/Sodium#452] opened 2020-12-28 15:11 UTC
### Expected Behavior
Please add on the “GUI Scale” option also 5x, 6x, 7x, and 8x as an option for Screens with high Resolution like 4k (UHD). 

### Actual Behavior
It is only possible to select auto, 1x, 2x, 3x and 4x on the “GUI Scale” option. But for a 4k Resolution 4x is too small and the auto option make the GUI to big.

### Attachments
Screenshot 4x: https://drops.n-tp.de/RBu9rAnD
Screenshot Auto: https://drops.n-tp.de/GGu27BK9

### System Information

- Java Version: Java 8
- CPU: intel i7
- GPU: nvidia geforce 1080

**Comment by amnotbananaama** [comment] 2020-12-28 16:03
Duplicate of #259

**Closed as completed by amnotbananaama** 2020-12-28 16:03 UTC
Labels: T-bug, E-duplicate
