### ISSUE TITLE
Water not visible behind glass

### ISSUE THREAD

**Issue by Sm1thTVexe** [jellysquid3/Sodium#2575] opened 2024-06-25 14:22 UTC
### Bug Description

![2024-06-25_16 17 25](https://github.com/CaffeineMC/sodium-fabric/assets/173813574/7dd7d7fc-abcb-4abe-8cdc-0d12549534bf)

### Reproduction Steps

Just put flowing water behind colored glass, normal glass is not affected

### Log File

[latest.log](https://github.com/user-attachments/files/15972891/latest.log)

### Crash Report

[crash-2024-06-25_16.22.14-client.txt](https://github.com/user-attachments/files/15972907/crash-2024-06-25_16.22.14-client.txt)

**Comment by douira** [comment] 2024-06-25 14:25
Duplicate of #38 which is now fixed in dev.

**Closed as not planned** 2024-06-25 14:32 UTC
Labels: E-duplicate
