### ISSUE TITLE
1.18 sodium alpha 6, Crashes on loading screen

### ISSUE THREAD

**Issue by RockStone-God** [jellysquid3/Sodium#1136] opened 2022-01-16 05:37 UTC
### Version information

sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14.jar

### Reproduction Steps

Apparently happens only on my pc, anyways:
1) Add sodium version mentioned above in mods folder
2) Start minecraft fabric.
3) Stops loading on the Mojang screen and crashes.

### Crash Report file

MultiMC version: 0.6.14-3001

Launched instance in online mode

authserver.mojang.com resolves to:
    [13.35.236.74]

session.minecraft.net resolves to:
    [3.213.200.53, 34.205.58.168, 52.21.65.46]

textures.minecraft.net resolves to:
    [54.240.167.32, 54.240.167.129, 54.240.167.66, 54.240.167.46]

api.mojang.com resolves to:
    [13.249.230.21]

Minecraft folder is:
C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/instances/1.18.1/.minecraft

Java path is:
C:/Program Files/Java/jdk-17.0.1/bin/javaw.exe

Checking Java version...
Java is version 17.0.1, using 64-bit architecture, from Oracle Corporation.

Main Class:
  net.fabricmc.loader.impl.launch.knot.KnotClient

Native path:
  C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/instances/1.18.1/natives

Traits:
traits XR:Initial
traits FirstThreadOnMacOS

Libraries:
  C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/com/mojang/blocklist/1.0.6/blocklist-1.0.6.jar
  C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/com/mojang/patchy/2.1.6/patchy-2.1.6.jar
  C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/com/github/oshi/oshi-core/5.8.2/oshi-core-5.8.2.jar
  C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/net/java/dev/jna/jna/5.9.0/jna-5.9.0.jar
  C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/net/java/dev/jna/jna-platform/5.9.0/jna-platform-5.9.0.jar
  C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar
  C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.16.0/log4j-slf4j18-impl-2.16.0.jar
  C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/com/ibm/icu/icu4j/69.1/icu4j-69.1.jar
  C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/com/mojang/javabridge/1.2.24/javabridge-1.2.24.jar
  C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/io/netty/netty-all/4.1.68.Final/netty-all-4.1.68.Final.jar
  C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar
  C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
  C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/com/google/code/gson/gson/2.8.8/gson-2.8.8.jar
  C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/com/mojang/authlib/3.2.38/authlib-3.2.38.jar
  C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.4.14/httpcore-4.4.14.jar
  C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/it/unimi/dsi/fastutil/8.5.6/fastutil-8.5.6.jar
  C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/net/fabricmc/intermediary/1.18.1/intermediary-1.18.1.jar
  C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/net/fabricmc/tiny-mappings-parser/0.3.0+build.17/tiny-mappings-parser-0.3.0+build.17.jar
  C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/net/fabricmc/sponge-mixin/0.10.7+mixin.0.8.4/sponge-mixin-0.10.7+mixin.0.8.4.jar
  C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/net/fabricmc/tiny-remapper/0.6.0/tiny-remapper-0.6.0.jar
  C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/net/fabricmc/access-widener/2.0.1/access-widener-2.0.1.jar
  C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/org/ow2/asm/asm/9.2/asm-9.2.jar
  C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/org/ow2/asm/asm-analysis/9.2/asm-analysis-9.2.jar
  C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/org/ow2/asm/asm-commons/9.2/asm-commons-9.2.jar
  C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/org/ow2/asm/asm-tree/9.2/asm-tree-9.2.jar
  C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/org/ow2/asm/asm-util/9.2/asm-util-9.2.jar
  C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/net/fabricmc/fabric-loader/0.12.12/fabric-loader-0.12.12.jar
  C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/com/mojang/minecraft/1.18.1/minecraft-1.18.1-client.jar

Native libraries:
  C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Mods:
  [❌] replaymod-1.18.1-2.6.3.jar (disabled)
  [✔️] sodium-fabric-mc1.18.1-0.4.0-alpha6+replaymod.rev.b90e7f3

Params:
  --username  --version MultiMC5 --gameDir C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/instances/1.18.1/.minecraft --assetsDir C:/Users/{directory}/Downloads/mmc-stable-win32 (1)/MultiMC/assets --assetIndex 1.18 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms1024m, -Xmx3096m, -Duser.language=en]

Minecraft process ID: 11852

Using onesix launcher.

[10:51:35] [main/INFO]: Loading Minecraft 1.18.1 with Fabric Loader 0.12.12
[10:51:35] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...
[10:51:49] [main/WARN]: Warnings were found!
 - Mod 'Fabric Rendering Fluids (v1)' (fabric-rendering-fluids-v1) 0.1.18+3ac43d95c8 recommends any version of fabric-textures-v0, which is missing!
	 - You should install any version of fabric-textures-v0 for the optimal experience.
[10:51:49] [main/INFO]: Loading 9 mods:
	- fabric-api-base 0.4.1+b4f4f6cdc8 via sodium
	- fabric-rendering-data-attachment-v1 0.3.4+7242e9d7c8 via sodium
	- fabric-rendering-fluids-v1 0.1.18+3ac43d95c8 via sodium
	- fabric-resource-loader-v0 0.4.11+3ac43d95c8 via sodium
	- fabricloader 0.12.12
	- java 17
	- minecraft 1.18.1
	- org_joml_joml 1.10.2 via sodium
	- sodium 0.4.0-alpha6+replaymod.rev.b90e7f3
[10:51:49] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/C:/Users/{directory}/Downloads/mmc-stable-win32%20(1)/MultiMC/libraries/net/fabricmc/sponge-mixin/0.10.7+mixin.0.8.4/sponge-mixin-0.10.7+mixin.0.8.4.jar Service=Knot/Fabric Env=CLIENT
[10:51:49] [main/INFO]: Compatibility level set to JAVA_16
[10:51:49] [main/INFO]: Compatibility level set to JAVA_17
[10:51:49] [main/INFO]: Loaded configuration file for Sodium: 29 options available, 0 override(s) found
[10:51:49] [main/INFO]: Trying to switch memory allocators to work around memory leaks present with Jemalloc 5.0.0 through 5.2.0 on Windows
[10:52:01] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[10:52:03] [Render thread/INFO]: Setting user: No profile (Spookyyy6090)
[10:52:04] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 build 10
[10:52:06] [Render thread/INFO]: Narrator library for x64 successfully loaded
[10:52:06] [Render thread/INFO]: Reloading ResourceManager: Default, Fabric Mods (Fabric API Base, Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Resource Loader (v0), Fabric Loader, Sodium)
Process crashed with exitcode -805306369.

**Comment by Blitszy** [comment] 2022-01-16 18:00
Is this crashing or just not responding? Because for me when I launch it stops responding. Could be a duplicate of #1134

**Comment by DioEgizio** [comment] 2022-01-18 14:57
[10:52:03] [Render thread/INFO]: Setting user: No profile (Spookyyy6090)




uh

**Comment by FlashyReese** [comment] 2022-01-18 15:07
> sodium 0.4.0-alpha6+replaymod.rev.b90e7f3

Not official

**Comment by RockStone-God** [comment] 2022-01-19 12:51
> Is this crashing or just not responding? Because for me when I launch it stops responding. Could be a duplicate of #1134

It stops responding. Yes, exactly.

**Comment by RockStone-God** [comment] 2022-01-19 12:52
> 

Its the exact same case with all other 1.18 alpha versions too.

**Comment by jellysquid3** [comment] 2022-01-19 19:05
This should've been reported as a bug rather a crash, but I guess our issue templates don't make that clear. We need hardware information, including your GPU model and driver version, along with the version of Java being used.

You can most easily obtain this information by booting a clean version of Minecraft, entering a world, and holding F3+C for ten seconds or until the game crashes. This will produce a crash report with the necessary information.

More likely than not, though, this is caused by #899, which can be solved by upgrading your graphics drivers.

**Comment by RockStone-God** [comment] 2022-01-20 06:11
version 10.0
	Java Version: 17.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1004218368 bytes (957 MB) / 1830813696 bytes (1746 MB) up to 3246391296 bytes (3096 MB)
	CPUs: 4
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx3096m
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) HD Graphics 4000 GL version 4.0.0 - Build 10.18.10.4358, Intel
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz

I guess, this is the information you're looking for?

**Comment by jellysquid3** [comment] 2022-01-20 06:43
Yes, so you have broken drivers installed and need to update. See [here](https://github.com/CaffeineMC/sodium-fabric/issues/899#issuecomment-939522243) for the more information and a link to where you can download the updated driver.

**Closed as completed by jellysquid3** 2022-01-20 06:43 UTC
Labels: T-crash, S-needs-triage

**Comment by RockStone-God** [comment] 2022-01-21 07:34
Yeah you are right, my driver was broken and after reinstalling the driver it works just fine. Thanks for your time!
