### ISSUE TITLE
stop loading in the beginning 

### ISSUE THREAD

**Issue by Mufi432** [jellysquid3/Sodium#1710] opened 2023-04-30 12:49 UTC
### Version information

1.19.4

### Reproduction Steps

1. Restart my computer
2. Reinstall sodium
3. Disable other mods

Not worked

### Crash Report file

Here is the errors and warns

[13:58:01] [Render thread/WARN]: Assets URL 'quilt.zfs://transformed-mod-minecraft.i0:0/assets/.mcassetsroot' uses unexpected schema

[13:58:01] [Render thread/WARN]: Assets URL 'quilt.zfs://transformed-mod-minecraft.i0:0/data/.mcassetsroot' uses unexpected schema

[13:58:02] [Render thread/ERROR]: Failed to verify authentication

[13:58:08] [Render thread/WARN]: Static binding violation: PRIVATE @Overwrite method method_23182 in #sodium:sodium.mixins.json: features.item.MixinItemRenderer from mod sodium cannot reduce visibiliy of PUBLIC target method, visibility will be upgraded.

**Comment by pajicadvance** [comment] 2023-04-30 12:50
Upload the full log please.

**Comment by Mufi432** [comment] 2023-04-30 12:53
[minecraft-exported-logs-2023-04-30T14-51-30.log](https://github.com/CaffeineMC/sodium-fabric/files/11361340/minecraft-exported-logs-2023-04-30T14-51-30.log)

**Comment by pajicadvance** [comment] 2023-04-30 13:00
Seems to be a duplicate of #899. Try updating your graphics driver from the link provided in the mentioned issue report.

**Comment by Mufi432** [comment] 2023-04-30 13:07
thanks for help

**Comment by jellysquid3** [comment] 2023-05-07 18:34
Not an issue with Sodium. You probably just need to update your graphics drivers as described above.

**Closed as not planned by jellysquid3** 2023-05-07 18:34 UTC
Labels: T-crash, S-needs-triage
