### ISSUE TITLE
is that mod can't support

### ISSUE THREAD

**Issue by Mcpe64** [jellysquid3/Sodium#148] opened 2020-07-22 21:25 UTC
i can't use immersive portals and sodium at same time, it failed to launch
![註解 2020-07-23 052313](https://user-images.githubusercontent.com/68666576/88230414-f6783f80-cca4-11ea-80ef-6c2761808bc1.png)

**Comment by mrmangohands** [comment] 2020-07-22 21:28
This is a known issue, see #15

**Comment by jellysquid3** [comment] 2020-07-22 21:39
Closing as duplicate of the aforementioned issue.

**Closed as completed by jellysquid3** 2020-07-22 21:39 UTC
Labels: E-duplicate, T-crash
