### ISSUE TITLE
Slime block texture partaily cut off

### ISSUE THREAD

**Issue by spottyunderdog** [jellysquid3/Sodium#230] opened 2020-08-03 00:20 UTC
### Expected Behavior
full slime block texture to show
### Actual Behavior
Part of the slime blocks texture doesn't show
### Reproduction Steps
Using the Venom Faithfull 1.16 resource pack along with lithium, sodium, and phosphor place three slime blocks behind a block of white stained glass then place another near on one of the sides of that slime block with the first glass block. and have a solid non-translucent block behind the second glass block then move to a corner. Happens when graphics are set to fast fancy or fabulous.

### Attachments
![2020-08-02_20 06 11](https://user-images.githubusercontent.com/69127347/89135522-3b4d7300-d4fc-11ea-8182-916a7f644c9a.png)
![2020-08-02_15 09 56](https://user-images.githubusercontent.com/69127347/89135525-3ee0fa00-d4fc-11ea-82a1-c583ee59d530.png)

### System Information
You can obtain this information from the in-game debug screen or through using [DxDiag](https://support.microsoft.com/en-us/help/4028644/windows-open-and-run-dxdiagexe) on Windows.

- Java Version: [1.8.0_51 64 bit]
- CPU: [4x intel core i3-5015 Cpu @ 2.10GHz]
- GPU: [Intel Hd graphics 5500 ]
### My settings sodium video settings

![2020-08-02_20 18 10](https://user-images.githubusercontent.com/69127347/89135717-7f8d4300-d4fd-11ea-942d-8b27c0876b0e.png)
![2020-08-02_20 18 13](https://user-images.githubusercontent.com/69127347/89135718-81ef9d00-d4fd-11ea-9f0e-1aa8c2b35904.png)
![2020-08-02_20 18 15](https://user-images.githubusercontent.com/69127347/89135721-8451f700-d4fd-11ea-875f-1650d6916db1.png)

**Comment by jellysquid3** [comment] 2020-08-15 00:23
Duplicate of #38.

**Closed as completed by jellysquid3** 2020-08-15 00:23 UTC
Labels: T-bug, E-duplicate
