### ISSUE TITLE
3D models on full blocks that emit light look weird

### ISSUE THREAD

**Issue by MithicSpirit** [jellysquid3/Sodium#493] opened 2021-01-23 20:08 UTC
### Expected Behavior
Blocks that emit light (e.g.: redstone lamps, furnaces) should look bright when turned on, even if they have a 3D model.

### Actual Behavior
While they still emit light, the inner part of full blocks (that can emit light) that have a 3D model look very dark (as if they were somewhere with light level 0).

### Reproduction Steps

1. Get a resource pack that adds 3D models to blocks that emit light (personally I use [Lithos 3D](https://www.curseforge.com/minecraft/texture-packs/lithos-3d), which also requires [Lithos Core](https://www.curseforge.com/minecraft/texture-packs/lithos-core-32x-1-6-1-11-complete))
2. Go in a world and place a block that can emit light and has a 3D model (in Lithos 3D you can use furnaces)
3. Place the block and turn it on (if necessary), it should look normal/bright
4. Restart your game with Sodium and look at it again, it should look really dark even when turned on

### Attachments
![2021-01-23_15 00 42](https://user-images.githubusercontent.com/24192522/105612752-f1976400-5d8b-11eb-8202-5c982eb0af01.png) Off (without sodium)

![2021-01-23_15 00 47](https://user-images.githubusercontent.com/24192522/105612750-f0fecd80-5d8b-11eb-8410-4761b1da7034.png) On (without sodium)

![2021-01-23_15 01 25](https://user-images.githubusercontent.com/24192522/105612747-f0663700-5d8b-11eb-8333-964c036a0620.png) On (with sodium)

### System Information
Info copied from F3 screen verbatim:
- Java Version: 15.0.1 64bit
- CPU: 12x AMD Ryzen 5 2600 Six-Core Processor
- GPU: Radeon RX 570 Series (POLARIS10, DRM 3.40.0, 5.10.9-rt24-xanmod1-1-xanmod-rt, LLVM 11.0.1)

Additional info:
- Java: `jdk-openjk` v15.0.1.u9-1 in the Archlinux repo
- OS: Archlinux with Xanmod RT kernel from AUR (numa and tracers disabled, cachy and ns enabled)

**Comment by fsharpseven** [comment] 2021-01-23 23:22
Duplicate of #226.

**Closed as completed** 2021-01-23 23:24 UTC
Labels: T-bug, E-duplicate
