### ISSUE TITLE
Adjustable render resolution

### ISSUE THREAD

**Issue by JibbityJobbity** [jellysquid3/Sodium#360] opened 2020-10-19 08:52 UTC
I have a laptop with a very high resolution display, but not quite enough power to run the game at that resolution and would like to lower it for better performance. Along with that, it would be nice to let my desktop render the game at a high resolution and scale the image down for anti-aliasing through supersampling. Other forms of AA would be nice, but I think this would be the first step.

What I am suggesting is to allow users to be able to change the resolution of the render target which the world is rendered to let people render at different resolutions from their display. I think the best approach to this would be to have a slider to give a coefficient of the current resolution (eg. any value from x0.5 to x2). Please let me know what you think.

**Comment by amnotbananaama** [comment] 2020-10-19 17:24
Duplicate of #121

**Closed as completed by amnotbananaama** 2020-10-19 17:24 UTC
Labels: E-duplicate, T-enhancement
