### ISSUE TITLE
some chunks are not rendered, compared to Minecraft Vanilla

### ISSUE THREAD

**Issue by Lolothepro** [jellysquid3/Sodium#2031] opened 2023-08-21 20:52 UTC
### Bug Description

some chunks are not rendered, compared to Minecraft Vanilla

![2023-08-21_22 50 07](https://github.com/CaffeineMC/sodium-fabric/assets/68275908/6edbe1bc-b53e-4cf7-a7a4-f41902f917a3)

### Reproduction Steps

-7863674087020843295
/execute in minecraft:overworld run tp @s 992.61 71.88 -380.73 -105.35 90.00
RD: 2

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12402455/latest.log)

### Crash Report

[crash-2023-08-21_22.51.38-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12402456/crash-2023-08-21_22.51.38-client.txt)

**Comment by TheUserCreated** [comment] 2023-08-22 04:03
Can reproduce with 0.5.2

**Comment by ghost** [comment] 2023-08-22 17:12
Can reproduce as well (0.5.2)
![2023-08-22_19 10 56](https://github.com/CaffeineMC/sodium-fabric/assets/63958709/12c07c58-6276-40b8-9110-6cea18a44776)

**Comment by jellysquid3** [comment] 2023-08-25 02:50
What? There is no issue here.

**Comment by jellysquid3** [comment] 2023-08-25 02:52
![2023-08-24_21 50 00](https://github.com/CaffeineMC/sodium-fabric/assets/1363084/5d62e933-6e16-47d8-8110-aa2a2635b907)
![2023-08-24_21 50 38](https://github.com/CaffeineMC/sodium-fabric/assets/1363084/46d0c7bc-7c6b-4c4f-8ede-de3b7b04a02d)

Vanilla and Sodium render exactly the same, and there isn't any "missing chunk"... It's just that the water temple is slightly offset into the ocean floor, and that causes a "gap" to appear since the fog cuts off rendering before the floor of the temple is rendered.

**Comment by jellysquid3** [comment] 2023-08-25 02:54
Oh for fucks sake, I just noticed the almost impossible to see black circle that you left on the original image.

**Comment by jellysquid3** [comment] 2023-08-25 03:07
The problem is that the server doesn't send enough chunks around the player, because the algorithm used is not exactly correct, and sometimes stuff at the very edge of the view distance is omitted. The corner which doesn't render will only appear once you move close enough to it, at which point the server sends the adjacent chunks, and the renderer becomes able to load it.

Why does this not happen in Vanilla? Well, it does, but there is a hack so that chunks which are closer than 24 blocks to the camera will _always_ be eligible for loading, even if their neighboring chunks aren't loaded. Disabling this code results in the same behavior being seen in both renderers.

Unfortunately, simply copying this behavior into Sodium isn't really feasible, because our renderer has a hard requirement that all adjacent chunks are present before loading of a chunk can begin.

Even if we could do it, it feels like a _really_ bad idea. Because it effectively means every time a chunk loads near a player, all the adjacent chunks will have to be re-loaded, as they were built too early and now have invalid data. At a short render distance, this results in each chunk being being submitted for reloads _nine times each_, which has a serious performance cost, and distracts the renderer from loading stuff in the distance.

So I'm just going to close this issue as "won't fix", as we can't reasonably work around it. The solution is to simply use a higher render distance.

**Closed as not planned by jellysquid3** 2023-08-25 03:07 UTC
Labels: E-will-not-fix, A-vanilla-issue
