### ISSUE TITLE
Game crashes in combination with physics mod pro

### ISSUE THREAD

**Issue by snappie321** [jellysquid3/Sodium#1754] opened 2023-05-12 15:09 UTC
### Version information

mc1.19.4-0.4.11 and mc1.19.4-0.4.10

### Reproduction Steps

1. install sodium, fabric api and physics mod pro
2. start the game and join/create a world
3. you'll crash

### Crash Report file

[crash-2023-05-12_17.05.06-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/11465490/crash-2023-05-12_17.05.06-client.txt)

### Additional information

game doesn't crash with my brothers laptop, using the exact same mod setup and versions, I reinstalled all mods, and even the last Minecraft version of fabric for 1.19.4

**Comment by Octol1ttle** [comment] 2023-05-12 16:00
Duplicate of #1745. Use Sodium 0.4.10 and Physics Mod 2.12.3

**Comment by snappie321** [comment] 2023-05-12 16:59
im talking about the pro version and not the normal version, which only has a few features

**Comment by pajicadvance** [comment] 2023-05-12 17:14
In that case, you need to use Sodium 0.4.10 and `physics-mod-pro-v152-fabric-1.19.4`.

**Closed as completed by pajicadvance** 2023-05-12 17:14 UTC
Labels: T-crash
