### ISSUE TITLE
Game crash when using Fabric with fabric skyboxes

### ISSUE THREAD

**Issue by thebaum64** [jellysquid3/Sodium#2573] opened 2024-06-24 22:14 UTC
### Bug Description

-Game crashes whenever a user who has fabric with fabric skyboxes uses a skybox resource pack (in this case Dramatic Skys) though the pack itself does not matter

### Reproduction Steps

-Have Sodium
-Have Fabric
-Have Fabric Skyboxes
-Load a sky resource pack

(This can be fixed by going to .minecraft/config/sodium-mixins.properties and add mixin.features.render.world.clouds=false)

### Log File

[crash.txt](https://github.com/user-attachments/files/15961847/crash.txt)

### Crash Report

[crash.txt](https://github.com/user-attachments/files/15961848/crash.txt)

**Comment by jellysquid3** [comment] 2024-06-25 02:47
Duplicate of https://github.com/CaffeineMC/sodium-fabric/issues/2552. See the information there.

**Closed as not planned** 2024-06-25 02:47 UTC
Labels: E-duplicate
