### ISSUE TITLE
Honey blocks are more transparent with sodium. 

### ISSUE THREAD

**Issue by JimmySallofficial** [jellysquid3/Sodium#2075] opened 2023-09-16 21:04 UTC
### Bug Description

[https://imgur.com/a/UEk34cv](url) [](https://imgur.com/a/UEk34cv)

### Reproduction Steps

https://imgur.com/a/UEk34cv

### Log File

https://imgur.com/a/UEk34cv

### Crash Report

https://imgur.com/a/UEk34cv

**Comment by Lolothepro** [comment] 2023-09-16 21:11
duplicate of #38

**Comment by JimmySallofficial** [comment] 2023-09-16 21:23
> duplicate of #38

oh ok, I didnt see it, should I remove my post?

**Comment by Poopooracoocoo** [comment] 2023-09-17 05:25
> > duplicate of #38
> 
> oh ok, I didnt see it, should I remove my post?

No need to delete anything. You can just close this issue as a duplicate. The button is at the bottom
<img width="316" alt="image" src="https://github.com/CaffeineMC/sodium-fabric/assets/51363864/bf8c9bf4-9c52-422e-b8ae-8d191291ebd0">

**Comment by jellysquid3** [comment] 2023-09-17 17:13
zzz

**Closed as not planned by jellysquid3** 2023-09-17 17:13 UTC
Labels: E-duplicate
