### ISSUE TITLE
Textures on flowing water blocks are not rendering properly (weird squares are forming behind water blocks)

### ISSUE THREAD

**Issue by Lythael** [jellysquid3/Sodium#1216] opened 2022-03-05 17:21 UTC
### Version information

sodium-fabric-mc1.18.2-0.4.1+build.15

### Expected Behavior

This is how it supposed to look correctly rendered water blocks and their textures in vanilla 1.18 :
![vanilla](https://user-images.githubusercontent.com/74063211/156893781-e7cc4a08-e7ee-4bb2-b07c-2169ad6b922a.png)

### Actual Behavior

Flowing water textures segment in a weird way causing odd "squares" to form at the back of said water blocks
Example:
![sodium bug](https://user-images.githubusercontent.com/74063211/156893765-0788868a-12ad-411c-97c0-105bb873325e.png)

### Reproduction Steps

1. Observe any vertical flowing water blocks with no blocks behind them.
2. Notice the textures alpha looking odd and weird "squares" that form behind said water blocks.

### Java version

Java 1.18

### CPU

AMD APU A8-6600K Quad-Core

### GPU

AMD Radeon RX 560 Gigabyte Gaming OC 4GB

### Additional information

I tried fiddling with sodium settings even disabling them all this issue still happens.
Issue is not present on vanilla game.

**Comment by Pectacular** [comment] 2022-03-11 07:19
Looks like another duplicate of #38

**Comment by cowsha** [comment] 2022-04-04 11:28
Same version, same bug.

**Closed as not planned** 2023-05-10 18:26 UTC
Labels: T-bug, E-duplicate

**Comment by Lythael** [comment] 2023-05-11 08:05
I see these blokes don't care for ever fixing this glaring issue.
Thankfully performance in latest snapshot is much better than before with the lighting engine optimizations being implemented so this crappy buggy mod won't be needed for much longer.

Meanwhile gonna stick to Optifine a more versatile mod which person who runs the project actually fixes reported issues instead blindly closing them

**Comment by asumagic** [comment] 2023-05-11 08:34
Notice that the issue was closed as a _duplicate_, because it is known and has been reported already many times. It was _not_ closed because developers don't want it fixed.  
GitHub recommends this way of closing issues for duplicates, as far as I remember, and it shows as "not planned" regardless.

The lighting engine optimizations have nothing to do with what Sodium does :)

**Comment by Lythael** [comment] 2023-05-11 08:52
> Notice that the issue was closed as a _duplicate_, because it is known and has been reported already many times. It was _not_ closed because developers don't want it fixed. GitHub recommends this way of closing issues for duplicates, as far as I remember, and it shows as "not planned" regardless.
> 
> The lighting engine optimizations have nothing to do with what Sodium does :)

Duplicate of an issue from several years ago.
You are naive if you think this is ever planned to be fixed

I am not saying that it has anything to do with what Sodium does i am saying that performance is now much better in vanilla MC thank to lighting engine optimizations Mojang did. 
So this mod will not be as needed for much longer. 

Understand what you are reading before replying.

**Comment by MCRcortex** [comment] 2023-05-11 08:58
> So this mod will not be as needed for much longer.

You sure your not talking about phosphor? (even then, there may be more places to optimize, who knows)

**Comment by Felix14-v2** [comment] 2023-05-11 22:00
> You are naive if you think this is ever planned to be fixed

You are incredibly naive if you think that no one has tried to solve this problem. Transparency sorting is one of the most difficult problems that you may encounter when working with graphics at all. In Discord, developers have returned to this problem and tried to solve it many times. But in the end, they came to the conclusion that the only way to make it fast enough is to use the functions of modern OpenGL. And this means that half of those in need will no longer be able to use Sodium due to outdated hardware.

You can't even imagine how many problems in Sodium have yet to be solved. And if you are really interested in following the progress, you can do it in the development channel in the CaffeineMC Discord. But be prepared to read hundreds and thousands of messages daily. Also keep in mind that Sodium is being developed by enthusiasts in their free time. Sodium doesn't sell capes. Donations and creator payouts are too small to allow developers to give up their job and devote themselves entirely to the development of Sodium. So, contribution would be greatly appreciated.

By the way, you can track the progress [here](https://github.com/CaffeineMC/sodium-fabric/pull/1687) or [here](https://github.com/CaffeineMC/sodium-fabric/pull/963), and explore the previous public attempt to solve it: #519
