### ISSUE TITLE
Multiconnect and sodium

### ISSUE THREAD

**Issue by Titaniumtown** [jellysquid3/Sodium#208] opened 2020-07-29 16:16 UTC
### Expected Behavior
Should be able to connect to a 1.13 server (In my case cuberite)

### Actual Behavior
Connects, renders some blocks, then freezes and crashes.

### Reproduction Steps
connect to a 1.13 server (in my case, cuberite)

### Attachments
https://pastebin.com/4mz4BN7W

### System Information

- Java Version: openjdk 14
- CPU: Xeon x5470 oc'd to 4ghz
- GPU: GTX 980 Ti

**Comment by amnotbananaama** [comment] 2020-07-29 18:35
This looks very similar to #189, which is interesting. In that case, the user is joining a Spigot/Bukkit/etc 1.8.x server with a multi-version plugin (likely [ViaVersion](https://github.com/ViaVersion/ViaVersion)). Here you are joining a 1.13.0 server with a multi-version client mod. This suggests something is fishy with the packet data itself, or at least how Sodium is interpreting it.

**Comment by Earthcomputer** [comment] 2020-07-31 09:21
It would help if you report these issues to the multiconnect repository where I see them, rather than having to be told days later by a user who did see this.
Your crash log is missing information. Please post the full log and not just what you think is relevant.

**Comment by amnotbananaama** [comment] 2020-08-25 15:21
@Titaniumtown Can you post the full log please as Earthcomputer suggested?

**Comment by comp500** [comment] 2021-03-16 22:57
I'm pretty sure this is a duplicate of #189, but the use of protocol translation mods/plugins might be a clue? Maybe the protocol translation code syncs tags in a different order (or not at all) which causes the blockstate shape caches to not be loaded.

**Comment by Earthcomputer** [comment] 2021-03-17 18:06
Tags are synchronized in a hashmap order, and multiconnect has had a check for ages that all required tags are present (vanilla also added a similar check more recently). The actual problem was that multiconnect was incompatible with the SodiumChunkCache, which was fixed a long time ago now.

**Comment by amnotbananaama** [comment] 2021-05-22 16:10
Closing as this user is unable to reply anymore, and Earth says the problem is fixed.

**Closed as completed by amnotbananaama** 2021-05-22 16:10 UTC
Labels: T-bug
