### ISSUE TITLE
incompatible with Materialisation

### ISSUE THREAD

**Issue by Jenssons** [jellysquid3/Sodium#207] opened 2020-07-29 13:41 UTC
now i wanna say i would love to add this mod to all my future fabric modpacks, but my server i play with my discord kinda "needs" a tinkers construct style of weapons and tools mod

### Expected Behavior
to be able to see the tools and weapon textures with Materialisation

### Actual Behavior
all the tools and weapons are invisible 

### Reproduction Steps

1. add sodium and materialistaion with roughly enough items to your fabric
2. go into a map 
3. find the materialistaion part of roughly enough items and as you can see the weapons and tools are invisible 

### Attachments
![image](https://user-images.githubusercontent.com/17034639/88807103-2ba2f700-d1a9-11ea-84e4-7dc1792a6832.png)

### System Information

- Java Version: java 8 251
- CPU: AMD ryzen 9 3900x
- GPU: GTX 1070

**Comment by Titaniumtown** [comment] 2020-07-29 13:46
Prob related to #5

**Comment by amnotbananaama** [comment] 2020-08-25 05:53
Closing as a duplicate of the aforementioned issue.

**Closed as completed by amnotbananaama** 2020-08-25 05:53 UTC
Labels: T-bug, E-duplicate
