### ISSUE TITLE
Sodium makes the game crash while on the loading screen

### ISSUE THREAD

**Issue by AngelH2328** [jellysquid3/Sodium#2089] opened 2023-09-23 21:37 UTC
### Bug Description

I use sodium to play at stable fps (30+) and to use it with other mods for better perfomance, but one day, i can't use it because the game just crashes at the loading screen, i tried only using sodium without other mods but, the same problem appears with the same result.

The error code is -805306369

![image](https://github.com/CaffeineMC/sodium-fabric/assets/145874741/cc21839a-d2d4-41ac-b685-51aacef2a0a4)

### Reproduction Steps

I don't know how to reproduce it or why it happens in the first place, but i will say that this only happen with sodium, if i run normal vanilla minecraft or with other mods, i can play.

My computer has 6GB of ram

### Log File

[2023-09-23-4.log.gz](https://github.com/CaffeineMC/sodium-fabric/files/12707301/2023-09-23-4.log.gz)

### Crash Report

[crash-2023-09-11_21.05.51-server.txt](https://github.com/CaffeineMC/sodium-fabric/files/12707302/crash-2023-09-11_21.05.51-server.txt)

**Comment by Lolothepro** [comment] 2023-09-23 21:41
duplicate of #899

**Comment by FlashyReese** [comment] 2023-09-23 22:10
Ensure your graphics drivers are up-to-date by checking the [official Intel website](https://www.intel.com/content/www/us/en/download-center/home.html). If you are still experiencing issues and need help, then please use the [Discord server](https://caffeinemc.net/discord).

**Closed as completed** 2023-09-23 22:38 UTC
Labels: E-duplicate
