### ISSUE TITLE
 New nVidia Driver update causing issues perhaps?

### ISSUE THREAD

**Issue by sakura-ryoko** [jellysquid3/Sodium#1491] opened 2022-10-29 16:46 UTC
### Version information

sodium-fabric-mc1.19.2-0.4.4+build.18.jar

### Reproduction Steps

So, Litematica/Sodium has been working fine for quite some time, and I didnt even update the MOD or anything too recently, but this happens whenever I try joining a specific SMP server.  It worked fine the night before, and I even just finished using Litematica on the same server.  I tried going through and updating Fabric API and all of my other mods to no avail.

Maybe its a PaperMC / Pufferfish+ thing that they might have changed in the server settings recently also?

**Removing Either Sodium or Litematica (But not having both) fixes the crash.**

(nVidia Driver 526.47)

_MC: 1.19.2
Fabric API: 0.64.0
Mod menu: 4.0.6
Lithium: 0.10.0
Phosphor: 0.8.1_

* Sodium: 0.4.4.build18
* Malib:  0.13.0
* Litematica: 0.12.3- 0.12.5 tested

Other MODs, but without them I can still reproduce the error:
MiniHUD: 0.23.3
Tweakroo: 0.14.3
Itemscroller: 0.17.1
Xareo's Minimap: 22.16.0
Xareo's World Map: 1.28.1
Advanced Compass: 1.2.12

I've also been able to reproduce the error trying to edit the Sodium render distance while on the server = crash.

### Crash Report file

[hs_err_pid10172--edited.log](https://github.com/CaffeineMC/sodium-fabric/files/9933082/hs_err_pid10172--edited.log)

### Additional information

Since I'm not sure which MOD is causing the crash, or server settings, I also posted under Litematica's Issues:

https://github.com/maruohon/litematica/issues/601

**Comment by ErinLilyM** [comment] 2022-10-29 22:20
There is already a post regarding this issue :)

**Comment by jellysquid3** [comment] 2022-10-29 22:35
Duplicate of #1486. NVIDIA seems to have really broken something this time.

**Closed as not planned by jellysquid3** 2022-10-29 22:35 UTC
Labels: T-crash, S-needs-triage
