### ISSUE TITLE
Game crashes when hovering over items

### ISSUE THREAD

**Issue by App4ri** [jellysquid3/Sodium#1619] opened 2023-02-12 14:53 UTC
### Version information

sodium-fabric-mc1.19.3-0.4.9+build.23.jar

### Reproduction Steps

1. Start survival world
2. craft a wooden pickaxe
3. game crashes instantly when you hover your mouse over the pickaxe in the crafting menu

### Crash Report file

[crash-2023-02-12_08.35.09-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/10716300/crash-2023-02-12_08.35.09-client.txt)

### Additional information

All my drivers are up to date, as far as I can tell. As far as I can tell, sodium-fabric-mc1.19.3-0.4.9+build.23.jar is the cause of the issue, because it doesn't occur on any other versions. I'll test to see if my version of java is the cause.

**Comment by App4ri** [comment] 2023-02-12 15:06
The crash still occurs after updating java and I've confirmed that it only happens when you hover over any tool or armor piece that now shows a 3d render in the item tooltip. Still doesn't occur on older versions of sodium.

**Comment by Timolino456** [comment] 2023-02-12 15:30
Disable 3D item previews in the Legendary Tooltips config. Some of the Iceberg renderer (that's the library mod of Legendary Tooltips) is currently incompatible with Sodium. After Sodium 0.4.10 releases, the author of Iceberg and Legendary Tooltips will release a fix. Duplicate of #1602.

**Closed as completed** 2023-02-12 15:56 UTC
Labels: T-crash, S-needs-triage
