### ISSUE TITLE
Smooth Lighting + Sodium 0.5.x: In some cases, blocks don't obstruct the passage of light.

### ISSUE THREAD

**Issue by Lolothepro** [jellysquid3/Sodium#2052] opened 2023-08-30 12:07 UTC
### Bug Description

https://github.com/CaffeineMC/sodium-fabric/assets/68275908/87677b86-3ae9-43b6-9431-83a5559a85b6

This does not happen with Sodium 0.4.10

### Reproduction Steps

Watch the video (snow required)

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12475356/latest.log)

### Crash Report

[crash-2023-08-30_14.04.50-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12475361/crash-2023-08-30_14.04.50-client.txt)

**Comment by Altirix** [comment] 2023-08-30 15:31
reproduced, also heres the world preset string `minecraft:bedrock,minecraft:snow,10*minecraft:air,minecraft:grass_block;minecraft:plains`

**Comment by Technici4n** [comment] 2023-08-30 15:48
Can you post the expected result?

**Comment by Lolothepro** [comment] 2023-08-30 15:53
> Can you post the expected result?


https://github.com/CaffeineMC/sodium-fabric/assets/68275908/1b473158-e3f5-4db9-be4e-3f7069e5a9de

**Comment by jellysquid3** [comment] 2023-09-17 17:04
The behavior in vanilla is indescribably insane and I have no idea what it's doing (or what it's even trying to accomplish for that matter.)

![image](https://github.com/CaffeineMC/sodium-fabric/assets/1363084/e5a15a5b-cf30-4b47-82cf-3a4f9d8c04b0)
![image](https://github.com/CaffeineMC/sodium-fabric/assets/1363084/128179c2-6fcf-403a-b686-70018fa1a3c6)

I'm not going to  "fix" our renderer so that it replicates the insane vanilla behavior.

**Comment by embeddedt** [comment] 2023-09-17 18:39
@jellysquid3 When it was being discussed on Discord, I recall finding that the issue with it not dimming when Sodium is installed is fixed by rounding the lightmap coordinates before they are encoded - see below patch.

```diff
diff --git a/src/main/java/me/jellysquid/mods/sodium/client/render/chunk/vertex/format/impl/CompactChunkVertex.java b/src/main/java/me/jellysquid/mods/sodium/client/render/chunk/vertex/format/impl/CompactChunkVertex.java
index c192ac7c..1a25dd09 100644
--- a/src/main/java/me/jellysquid/mods/sodium/client/render/chunk/vertex/format/impl/CompactChunkVertex.java
+++ b/src/main/java/me/jellysquid/mods/sodium/client/render/chunk/vertex/format/impl/CompactChunkVertex.java
@@ -62,6 +62,14 @@ public class CompactChunkVertex implements ChunkVertexType {
         int block = (light >> 4) & 0xF;
         int sky = (light >> 20) & 0xF;
 
+        // round
+        if(((light >> 0) & 0xF) > 0x7 && block < 0xF) {
+            block++;
+        }
+        if(((light >> 16) & 0xF) > 0x7 && sky < 0xF) {
+            sky++;
+        }
+
         return ((block << 0) | (sky << 4));
     }
```

**Closed as not planned** 2023-12-30 07:12 UTC
Labels: S-confirmed, P-low, A-vanilla-parity

**Comment by jellysquid3** [comment] 2023-12-30 07:14
Closing in favor of #2228 since this is a symptom of that problem.
