### ISSUE TITLE
Textures on block faces do not line up correctly - issue affects every block in game

### ISSUE THREAD

**Issue by shaan94** [jellysquid3/Sodium#958] opened 2021-10-31 18:01 UTC
### Version information

sodium-fabric-mc1.17.1-0.3.2+build.7

### Expected Behavior

Textures on each block face should line up perfectly.

### Actual Behavior

Textures on block faces do not line up. It appears only the south facing block-face lines up.
![2021-10-31_17 51 24](https://user-images.githubusercontent.com/24356997/139595967-7b1fe536-eaad-48db-9974-de7cc5737095.png)

![2021-10-31_17 51 38](https://user-images.githubusercontent.com/24356997/139595968-ae309d2c-ead9-41f2-977a-040813d44e34.png)

![2021-10-31_17 51 49](https://user-images.githubusercontent.com/24356997/139595970-403e5166-b0c6-4c3a-93ac-77bf3caf71dd.png)

![2021-10-31_17 52 08](https://user-images.githubusercontent.com/24356997/139595972-b273f598-2435-4eeb-b96f-b39a3924234b.png)

### Reproduction Steps

1. Place a block
2. Look at block

### Java version

Java 16

### CPU

i5-6600k

### GPU

AMD R9 390

**Comment by Altirix** [comment] 2021-11-02 05:14
could not reproduce with sodium or iris, ended up finding this seems to occur when continuity is installed

**Comment by shaan94** [comment] 2021-11-05 13:25
> could not reproduce with sodium or iris, ended up finding this seems to occur when continuity is installed

The bug still happens when running only Sodium - I have also confirmed this with 2 other people running different hardware.

I am surprised that you do not have the bug. Did you look at all sides of the block or just the side where the textures line up?

**Comment by l1cash** [comment] 2021-11-05 16:57
I could not reproduce any texture misalignment with only sodium (same build), nor with my normal set of mods including sodium (lithium, lambdynamiclights, fabric api). I don't have the continuity mod.

Tested on Java 16.0.1, with AMD RX Vega 64 GPU and the "amdgpu" driver (Mesa) on Ubuntu 20.04 LTS.

**Comment by Altirix** [comment] 2021-11-05 18:20
> > could not reproduce with sodium or iris, ended up finding this seems to occur when continuity is installed
> 
> The bug still happens when running only Sodium - I have also confirmed this with 2 other people running different hardware.
> 
> I am surprised that you do not have the bug. Did you look at all sides of the block or just the 
side where the textures line up?

yup even made a texture overlay to make it a bit easier. 
[melon.zip](https://github.com/CaffeineMC/sodium-fabric/files/7488133/melon.zip) that's quite strange does it happen on any prior versions of sodium?

**Comment by shaan94** [comment] 2021-11-05 20:03
> yup even made a texture overlay to make it a bit easier. [melon.zip](https://github.com/CaffeineMC/sodium-fabric/files/7488133/melon.zip) that's quite strange does it happen on any prior versions of sodium?

Yeah, I first noticed it on the last release of sodium, and it was still there on the latest mc1.17.1-0.3.2+build.7

![2021-11-05_20 00 24](https://user-images.githubusercontent.com/24356997/140571612-49ba0ff4-664f-416a-8200-fdb9a04ee927.png)

![2021-11-05_20 00 45](https://user-images.githubusercontent.com/24356997/140571622-00f87564-557e-4582-8e7f-08c4f7477661.png)

![2021-11-05_20 00 50](https://user-images.githubusercontent.com/24356997/140571630-67562d13-a751-4e01-9c2f-bb6eaa2a1cc7.png)

These are my settings - I wonder if it's any of these causing the misalignment?

**Comment by Derklong** [comment] 2021-11-11 15:28
I have the same problem when running only a fresh install of Sodium.

**Comment by MESLewis** [comment] 2021-11-18 19:09
![2021-11-18_13 07 37](https://user-images.githubusercontent.com/597053/142480674-110a7679-df6a-4eb5-aaeb-741b7f2a3c31.png)
Windows 10
Radeon version 21.10.2

Please update your graphics drivers and post a screenshot of the minecraft f3 screen along with your operating system and graphics card driver version.

**Comment by LucilleTea** [comment] 2021-11-25 03:48
I cannot reproduce this on Sodium 0.3.2 or 0.3.3 using an nvidia gtx 1070 and driver 496.49. It seems like it must be hardware/driver related in some way. If everyone experiencing the issue with just sodium installed could confirm their gpu and driver version that would be helpful.

**Comment by jellysquid3** [comment] 2021-12-01 22:46
Probably some kind of driver-specific bug and larger texture atlases... I can't reproduce the problem on my machine.

```
$ lspci
0c:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Navi 14 [Radeon RX 5500/5500M / Pro 5500M] (rev c5)

$ glxinfo
...
OpenGL vendor string: AMD
OpenGL renderer string: Radeon RX 5500 XT (NAVI14, DRM 3.42.0, 5.15.4-201.fc35.x86_64, LLVM 13.0.0)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 21.2.5
OpenGL core profile shading language version string: 4.60

$ uname -srm
Linux 5.15.4-201.fc35.x86_64
```

@shann94 @Derklong Can you two provide a client log file and a list of any resource packs you are using?

**Comment by Lolothepro** [comment] 2022-11-01 14:48
Is it fixed?

**Comment by Lolothepro** [comment] 2023-05-10 20:18
Can you close this bug report?

**Comment by jellysquid3** [comment] 2024-04-29 06:38
This is fixed with https://github.com/CaffeineMC/sodium-fabric/commit/ea0172768a5da9907b5a5711160dc3984fafea83.

**Closed as completed by jellysquid3** 2024-04-29 06:38 UTC
Labels: T-bug, S-cannot-repro, A-drivers
