### ISSUE TITLE
Sodium 1.17 0.3.2 stuck at loading screen but sodium 0.3.0 is working correctly!

### ISSUE THREAD

**Issue by TechBlaze009** [jellysquid3/Sodium#978] opened 2021-11-19 18:01 UTC
### Version information

mc.1.17.1-0.3.2+build.7

### Reproduction Steps

when i start the game the game stuck at loading screen for too long and not responding anything

### Crash Report file

Game stuck at loading screen so please fix this

**Comment by LucilleTea** [comment] 2021-11-20 03:45
Sounds like a duplicate of #899 - updating your intel graphics drivers should fix this. If you're not using intel graphics this can be reopened as not a duplicate.

**Closed as completed by LucilleTea** 2021-11-20 03:45 UTC
Labels: E-duplicate

**Comment by TechBlaze009** [comment] 2022-01-04 06:41
> Sounds like a duplicate of #899 - updating your intel graphics drivers should fix this. If you're not using intel graphics this can be reopened as not a duplicate.

This problem is same in alpha 5 1.18 version

**Comment by LucilleTea** [comment] 2022-01-04 07:33
Correct, you need to update your graphics driver as you're encountering a glitch in the driver itself. Sodium has not worked around this issue.
