### ISSUE TITLE
Stained Glass, Stanined Glass Pane and Tinted Glass visual bug

### ISSUE THREAD

**Issue by wdis01** [jellysquid3/Sodium#962] opened 2021-11-09 22:01 UTC
### Version information

mc1.17.1-0.3.2+build.692

### Expected Behavior

It is supposed to render the inside of the glass

![2021-11-09_17 25 00](https://user-images.githubusercontent.com/70643585/141011134-9aee4853-a237-4634-b8cb-53d649c1eca5.png)
![2021-11-09_17 25 18](https://user-images.githubusercontent.com/70643585/141011140-45d3285f-80f9-4d5a-9b69-abbd218d436e.png)
![2021-11-09_17 25 40](https://user-images.githubusercontent.com/70643585/141011147-7d737e15-db37-4d3c-bc6c-42c20960ee07.png)

### Actual Behavior

This happens:

![2021-11-09_17 32 38](https://user-images.githubusercontent.com/70643585/141011197-8ad56e8c-921b-410f-a8cf-7adea4be1999.png)
![2021-11-09_17 17 39](https://user-images.githubusercontent.com/70643585/141011215-baab87ca-8a28-4a64-95e3-7da983a02ef6.png)
![2021-11-09_17 19 02](https://user-images.githubusercontent.com/70643585/141011220-6936034e-3426-4ea8-bedc-e7b0c332fb7c.png)
![2021-11-09_17 19 35](https://user-images.githubusercontent.com/70643585/141011223-912a82eb-b5ee-4c4b-b18a-19b881faf440.png)

### Reproduction Steps

Place stained glass

### Java version

Java 16

### CPU

Intel Core i3-2120

### GPU

NVIDIA GeForce GT 1030

### Additional information

I know this bug has been reported several times but I just want it not to overlook.

Sorry for my bad english :(

**Comment by MESLewis** [comment] 2021-11-18 18:57
Duplicate of #38

**Comment by amnotbananaama** [comment] 2021-11-18 19:08
> I know this bug has been reported several times but I just want it not to overlook.  

Don't worry, this bug is not forgotten! It is just a lot of work to fix. There is [a Pull Request](https://github.com/CaffeineMC/sodium-fabric/pull/963) open that will hopefully resolve the bug when merged.

**Closed as completed by amnotbananaama** 2021-11-18 19:08 UTC
Labels: T-bug, E-duplicate
