### ISSUE TITLE
Game freezes

### ISSUE THREAD

**Issue by katehasdied** [jellysquid3/Sodium#1390] opened 2022-07-19 05:12 UTC
### Version information

mc1.18.2-0.4.1+build.15.jar

### Reproduction Steps

**Example:**
1. Input [sodium-fabric-mc1.18.2-0.4.1+build.15.jar](https://www.curseforge.com/minecraft/mc-mods/sodium/download/3669187) into your mods folder.
2. Launch [fabric-loader-0.13.3-1.18.2](https://fabricmc.net/use/installer/) (no other mods required).

**Expectation:** Runs fine, no issues.
**Reality:** It freezes and stops responding.

### Crash Report file

It will not write a crash report. Instead, attached is a log file for attempting to run Sodium, Lithium, and Phosphor.
[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/9137706/latest.log)

**Comment by Phoenix-Starlight** [comment] 2022-07-25 02:53
How long did you wait?

**Comment by katehasdied** [comment] 2022-07-28 06:52
Probably 3 hours

**Comment by Phoenix-Starlight** [comment] 2022-07-29 00:23
Can you try without resource packs? Also fabric loader will require updating if you plan on using other mods, since they may build against more recent loader versions. (Just delete/move the resourcepacks you have)

**Comment by pajicadvance** [comment] 2023-05-09 16:05
I'll make a guess and assume that this is a duplicate of #899.

**Closed as not planned** 2023-05-10 17:54 UTC
Labels: E-duplicate, A-drivers, T-crash
