### ISSUE TITLE
Clouds stitching

### ISSUE THREAD

**Issue by GrenFlem** [jellysquid3/Sodium#1364] opened 2022-06-27 08:10 UTC
### Version information

sodium-fabric-mc1.19-0.4.2+build.16

### Expected Behavior

clouds to look clean and proper

### Actual Behavior

clouds have distinct white lines on them, differentiating the squares that make up the cloud

### Reproduction Steps

install sodium, open miencraft, look at the clouds.
![2022-06-27_01 09 35](https://user-images.githubusercontent.com/108261952/175891836-5d0ac19d-6bef-460b-8225-6d78c1b7f0f0.png)

### Java version

java 8

### CPU

AMD Ryzen 5 3400G

### GPU

Radeon Vega 11

**Comment by LuishMC** [comment] 2022-07-02 22:04
Java 8???

**Comment by IMS212** [comment] 2022-08-24 17:11
Duplicate of #1128

**Closed as not planned by IMS212** 2022-08-24 17:11 UTC
Labels: T-bug, S-needs-triage
