### ISSUE TITLE
game showing 144fps+ but 144hz monitor only showing 60

### ISSUE THREAD

**Issue by Jokupoika24** [jellysquid3/Sodium#689] opened 2021-06-15 19:26 UTC
> sodium-fabric-mc.1.16.3-0.1.0

> So, i recently downloaded this mod, and at first, it worked perfectly. I gained 100+ fps and it worked well. But after a week or so, when i started the game, first it looked normal. But when i did go to the game, it felt low fps, so i checked F3 and it said 190fps~. My second monitor that is 60hz may effect in this, and i checked from windows settings all the things like if my main 144hz monitor wasn't selected to be the main monitor, but it was. I also checked the sodium settings, (fps cap, vsync and everything i could think about lol. I've been having this problem for about 2 weeks now, and i just don't want to play on 60hz. Is there any fix to this problem available?
It happens everytime I start the fabric loader

> - Java Version: -
> - CPU: i5-2400
> - GPU: MSI gtx 1050 ti

### Other Information

I use only fabric API, and none other mods.

(edit) i fixed the problem, i ran the game with only fabric and for some reason it was set on 1920x1080 60 instead of the current thing. i put sodium back and it worked well. it would be nice if you could change the resolution in sodium.

**Comment by jellysquid3** [comment] 2021-06-15 23:45
Can you reproduce this problem _without_ Sodium or Fabric installed? (just vanilla)

Chances are that something has changed on your system that is causing the problem. Having monitors with different refresh rates has historically been a problem on Windows, but I don't really have a way to test this.

**Comment by Eyebqll** [comment] 2021-06-17 05:27
im pretty sure this is a problem with windowed/borderless fullscreen with a video on your second monitor your game will feel like 60 fps. this doesn't just happen in minecraft it happens in every game for me

**Comment by Altirix** [comment] 2021-06-19 01:03
this might be the nvidia driver issue, do a clean install with DDU and try again. no idea why it happens but it seems to be the fix for it.

**Comment by Snivine** [comment] 2021-06-19 20:13
at mercy of drivers?

**Comment by Jokupoika24** [comment] 2021-06-20 07:38
> Can you reproduce this problem _without_ Sodium or Fabric installed? (just vanilla)
> 
> Chances are that something has changed on your system that is causing the problem. Having monitors with different refresh rates has historically been a problem on Windows, but I don't really have a way to test this.

no i can't, it happens only with sodium. (haven't tested it with only fabric yet.

**Comment by Jokupoika24** [comment] 2021-06-21 09:03
> this might be the nvidia driver issue, do a clean install with DDU and try again. no idea why it happens but it seems to be the fix for it.

i updated to the latest nvidia driver, but it didn't help

**Comment by mrmangohands** [comment] 2021-07-11 02:40
Closing as per the edit in the original message the issue is resolved.

**Closed as completed by mrmangohands** 2021-07-11 02:40 UTC
Labels: T-bug
