### ISSUE TITLE
Crashing When hitting f3 or entering a portal

### ISSUE THREAD

**Issue by OhixD** [jellysquid3/Sodium#1704] opened 2023-04-25 09:08 UTC
### Version information

minecraft version 1.19

### Reproduction Steps

Hitting f3+a to reload chunks or entering a portal will cause the game to fully crash 

### Crash Report file

https://pastebin.com/C01PNYy1

### Additional information

I've got a few other mods added, but they do not seem to cause the issue as I have tried adding mods 1 by 1 and from what it seems like it has something to do with sodium, although I could be entirely wrong

Hopefully this is the correct location to make this issue

https://imgur.com/a/15ocyjI Here is a list of other mods i have

**Comment by pajicadvance** [comment] 2023-04-25 12:28
Duplicate of #1486. A workaround for this problem was implemented starting from Sodium versions for MC 1.19.3, so you need to use at least version 0.4.9.

**Closed as not planned** 2023-05-08 16:21 UTC
Labels: E-duplicate, T-native
