### ISSUE TITLE
(Transferred from Iris) Request: Fix vanilla AO bug with resource packs (bug does not occur with OptiFine)

### ISSUE THREAD

**Issue by coderbot16** [jellysquid3/Sodium#1396] opened 2022-07-24 04:59 UTC
While [this issue](https://github.com/IrisShaders/Iris/issues/1049) was reported to Iris, I think this makes more sense for Sodium to fix, given that Sodium already replaces vanilla's AO code. I think Pepper was already looking at this, but I just wanted to formally move it over here for proper issue tracking.

> ![Broken AO on Iris/Sodium](https://user-images.githubusercontent.com/54046029/144714250-dd0a5446-6baf-44cf-a89a-c7bfc4a13040.png)
>
> I know OptiFine fix this problem of the vanilla AO shader. I already spoke with the owner of Complementary Shaders, it could be fixed but ruin the visual quality, so it is not a viable solution. I think it could be useful for Iris to fix this problem directly from the source and that it can benefit to the maximum of the users in the case where it would use resource packs that brings 3D to some elements.
>
> Iris 1.1.3 for Minecraft 1.18 and for the resource pack used it's [Fantasy Ores](https://www.curseforge.com/minecraft/texture-packs/fantasy-ores-by-cesarzorak)

**Comment by PepperCode1** [comment] 2022-07-24 07:36
Testing with release Iris 1.2.5, release Sodium 0.4.2, and Complementary 4.5.1 on 1.19; cannot reproduce issue. I do not know if the dark ore parts are part of the issue since a comparison screenshot of OptiFine was not included. It is also possible that they are fixed with the new lighting fixes, but I cannot test this at the moment.
![image](https://user-images.githubusercontent.com/44146161/180637122-d337cdd2-df9b-439e-846b-4031fabfef88.png)

**Comment by coderbot16** [comment] 2022-07-24 07:37
Thanks for testing. Apologies for not properly confirming before moving. Seems like this was fixed a long time ago and forgotten about somehow.

**Closed as not planned** 2022-07-24 07:38 UTC
