### ISSUE TITLE
Crash when using Iceberg.

### ISSUE THREAD

**Issue by GoldenFurredFox** [jellysquid3/Sodium#1654] opened 2023-03-06 18:22 UTC
### Version information

mc1.19.3-0.4.9+build.23

### Expected Behavior

Blocks in rendered overworld chunks wouldn't be invisible, and I wouldn't receive a crash at random while opening user interfaces. (Blocks in nether chunks weren't invisible, but I wasn't able to test The End.)

### Actual Behavior

Everything in the overworld was effectively invisible except other mobs and player entities.

### Reproduction Steps

1. Install the aforementioned version of Sodium, alongside Iris (mc1.19.3-1.5.2), Iceberg (1.19.3-fabric-1.1.4), Advancement Plaques (1.19.3-fabric-1.4.8), Equipment Compare (1.19.3-fabric-1.3.2), and LegendaryTooltips (1.19.3-fabric-1.4.1).
2. Join a server where you have access to some form of nether TP that doesn't involve a portal (and optionally an End TP if you'd like to help test further)
3. When joining, ensure you're joining into the overworld initially. If blocks are all invisible, teleport to the nether. If blocks in the nether are visible, you are good so far, everything is accurate to my experience.
4. (Optional) Play in the server like you normally would for a while. Open Plugin UIs like an auction house or backpack on occasion. Compare equipment on occasion in your inventory. See if any tooltips cause crashes.
5. Check if enchanted Netherite Boots crash your game. If yes, all steps have been replicated properly.

### Java version

Java 16

### CPU

Intel Core i5-7200U

### GPU

(Dual GPU) Intel HD Graphics 620/Nvidia GeForce 940MX

### Additional information

[An image of my mods folder](https://i.imgur.com/dasTKpW.png) [My crash log](https://mclo.gs/05NZEwL)

**Comment by pajicadvance** [comment] 2023-03-17 13:06
Duplicate of #1602

**Closed as not planned** 2023-05-08 16:21 UTC
Labels: E-duplicate, T-crash
