### ISSUE TITLE
ResolutionControl 3 regression in 0.6.0-beta.1

### ISSUE THREAD

**Issue by xirreal** [jellysquid3/Sodium#2712] opened 2024-08-24 12:02 UTC
### Bug Description

Image scaling does not work on beta-1, while it worked fine on alpha-3.
Tested in a minimal environment (sodium, modmenu, resolution control 3 and fapi)
beta-1:
![beta-1](https://github.com/user-attachments/assets/888221d3-1084-444e-81bf-2978a4d58951)
alpha-3:
![alpha-3](https://github.com/user-attachments/assets/77be855c-0679-4c48-b21f-8bc203d26a61)

### Reproduction Steps

1. Install mods
2. Change resolution scale in mod menu

### Log File

[alpha-3 log](https://github.com/user-attachments/files/16736474/latest.log)
[beta-1 log](https://github.com/user-attachments/files/16736480/latest.log)

### Crash Report

[forced crash alpha-3](https://github.com/user-attachments/files/16736477/crash-2024-08-24_14.00.36-client.txt)
[forced crash beta-1](https://github.com/user-attachments/files/16736479/crash-2024-08-24_14.01.57-client.txt)

**Comment by IMS212** [comment] 2024-08-24 16:09
This is caused by RC3 (ab)using the blit shader to get it's scaling done via textures. The new hardware blit code doesn't provide this.

**Comment by IMS212** [comment] 2024-08-24 16:10
I have contacted the RC3 dev; an easy workaround will be enabling the shader at all times, but it's in their best interest to fix it on their side as 1.21.2 will have the same issue.

**Comment by pajicadvance** [comment] 2024-08-24 23:56
Mod just got updated with a fix for this issue.

**Closed as completed by pajicadvance** 2024-08-24 23:56 UTC
Labels: T-bug, A-mods
