### ISSUE TITLE
Translucent blocks are being rendered too translucent

### ISSUE THREAD

**Issue by altrisi** [jellysquid3/Sodium#84] opened 2020-07-14 15:41 UTC
### Expected Behavior
Translucent blocks such as honey or slime blocks should render as in Vanilla/without Sodium.

### Actual Behavior
Translucent blocks such as honey or slime blocks render too translucent in comparison with vanilla, some extremely translucent (honey).
The same blocks, when in item form, render correctly.
Happens in all 3 graphics quality (starting at Fabulous and changing from there, if this may be related).

### Reproduction Steps
1. Place honey or slime blocks (honey is easier to spot)
2. Stare at them

#### Without Sodium:
![2020-07-14_16 23 10](https://user-images.githubusercontent.com/17107132/87437362-80ae0d00-c5ee-11ea-9691-7aa8693eec15.png)

#### With Sodium:
![2020-07-14_16 05 52](https://user-images.githubusercontent.com/17107132/87435809-8276d100-c5ec-11ea-9bca-f26c73ec89b8.png)

### System Information

- Java Version: 1.8.0_51 x64
- CPU: Intel Core i7-7700HQ @ 2.80GHz
- GPU: NVIDIA GeForce GTX 1050

### Additional information
Interestingly (maybe?) when the blocks are being moved (36 or piston_extension) they render correctly, making it look even worse in flying machines since they kind-of blink. Attachment:
![2020-07-14_16 41 48](https://user-images.githubusercontent.com/17107132/87439973-b1dc0c80-c5f1-11ea-9cb4-a7d36ddea016.png)
#### Reproduction of this part:
1. Place some slime/honey blocks (honey is easier to spot) separated from the ground
2. Attach them to a sticky piston
3. Power the piston on and off
4. See they blinking (easier to see with carpet mod by slowing the game to 5-10 tps and turning on smoothClientAnimations, since the extension then lasts longer)

This entire issue doesn't seem to apply to stained glass, but stained glass has some other issues relating to these blocks that I'll probably fill another issue for.
Edit: Ice also doesn't apply to this issue.

**Comment by jellysquid3** [comment] 2020-07-14 19:08
Duplicate of #38.

**Closed as completed by jellysquid3** 2020-07-14 19:08 UTC
Labels: T-bug, E-duplicate
