### ISSUE TITLE
Sodium 

### ISSUE THREAD

**Issue by lopopoishere** [jellysquid3/Sodium#618] opened 2021-04-01 18:09 UTC
> Replace this text with the exact version of the mod you are using. Every part of the version is important! If you
> do not know what version you are using, look at the file name in your "mods" folder.
> 
> Example: mc1.16.5 (your current version of sodium.

### Expected Behavior

I was going to open a new world to test out sodium then I should be playing regular minecraft. 

But instead in the floor in chunks and overall looked really corrupted like if i were in the far lands but worse.

I opened a new world with fabric launcher.
It loaded me in.
world corrupted.
### System Information

> You can obtain this information from the right-side of the in-game debug screen (F3) or through using DxDiag
> (https://support.microsoft.com/en-us/help/4028644/windows-open-and-run-dxdiagexe) on Windows. 
> 
> - Java Version: 1.8.0
> - CPU: n2930
> - GPU: n/a

![2021-04-01_10 58 19](https://user-images.githubusercontent.com/81770994/113335964-8b264900-92da-11eb-868b-64b5dcb3bbe1.png)

**Comment by silversquirl** [comment] 2021-04-01 18:10
Go to Video Settings -> Advanced and change the chunk renderer to Oneshot (3.0)

**Comment by silversquirl** [comment] 2021-04-01 18:12
Duplicate of #179

**Comment by lopopoishere** [comment] 2021-04-01 18:12
YOUR A LIFESAVER TYSM

**Closed as completed by silversquirl** 2021-04-01 18:12 UTC
Labels: T-bug, E-duplicate
