### ISSUE TITLE
Chunks flickering when breaking and placing blocks

### ISSUE THREAD

**Issue by Dvdboy42** [jellysquid3/Sodium#1113] opened 2022-01-08 20:42 UTC
### Version information

sodium-fabric-mc1.18-0.4.0-alpha5+build.9

### Expected Behavior

The game should render normally.

### Actual Behavior

The game flickers, turning transparent for a split second everytime I break or place a block.

### Reproduction Steps

Install the latest version of sodium. Run minecraft with sodium. Game flickers.

### Java version

17.0.1

### CPU

Intel Core i7-1065G7 CPU @1.30GHz

### GPU

Intel Iris Plus Graphics (Integrated Graphics)

### Additional information

I shot a video on my phone but the file is too big so I uploaded a link to the video here: https://ufile.io/vmdep1yh. I have noticed that similar issues happen to other people on intel cpus. I also have other mods installed, but the issue persists without them. I also played around with the settings and changing the "Chunk memory allocator" and setting it to swap seems to make it worse. Also changing the amount of ram allocated to the game doesn't seem to make it better or worse.
I think the main problem seems to be the intel cpu. Other issues similar to this one are #869 and #853 and #819.

**Comment by beansOnT0ast** [comment] 2022-01-19 20:14
This happened to me as well. I am on a laptop and have a Intel i3 10th Gen with in-built graphics

**Comment by y2k04** [comment] 2022-02-06 02:28
Me too

**Comment by pranshuthegamer** [comment] 2022-02-08 04:53
i3 1005g1
16 gb ram

**Comment by jessicarod7** [comment] 2022-03-04 01:37
[Copied from issue 869] I no longer encounter this issue on the latest version, near spawn or millions of blocks away.

Version: Minecraft 1.18.2
Sodium: 0.4.1+build.15
OS: Windows 11 21H2 (22000.493)
Processor/Graphics: Intel Core i7-1065G7 (Iris Plus)
Driver version: 30.0.101.1340

**Comment by Xenapte** [comment] 2022-03-12 15:04
The same problem for me with exactly the same processor and gpu. Seems to be an intel issue since my laptop also comes with an nvidia gpu but it runs without any problems on that.

**Comment by Mohotzgui** [comment] 2022-03-13 17:30
Well I was wondering what the cause of this was. I get it in 1.18.2 now as well. I'm on a gaming laptop with Intel chips. I moved to fabric because forge was just getting too slow.

**Comment by jonatandorozco** [comment] 2022-07-25 23:48
Any update on this?

**Comment by JCionx** [comment] 2022-08-29 17:21
i have the same problem on my intel i3

**Comment by pajicadvance** [comment] 2023-05-10 16:53
Duplicate of #869.

**Closed as not planned by pajicadvance** 2023-05-10 16:53 UTC
Labels: T-bug, E-duplicate, A-drivers

**Comment by happyfox2222** [comment] 2023-11-19 16:17
this hapens for me to if some one finds a solution pls tell me :)

**Comment by FlashyReese** [comment] 2023-11-19 16:18
> this hapens for me to if some one finds a solution pls tell me :)

https://github.com/CaffeineMC/sodium-fabric/issues/869#issuecomment-1646374792
