### ISSUE TITLE
Crash with SodiumWorldRenderer

### ISSUE THREAD

**Issue by Dueris** [jellysquid3/Sodium#1834] opened 2023-06-22 01:32 UTC
### Version information

Latest 1.20.1/1.20 version, minecraft 1.20.1

### Reproduction Steps

I was switching in and out of spectator mode, and was running around, had some fire, glass, and water and other random blocks around me. Im unsure how exactly to explain what happened because I was bug testing some stuff for my plugin lol. I had just gone out of spectator mode, with blindness, it got removed, was running around, some cows were chilling to my right. Not really the best explanation, if you want more information let me know. The error:
```
[18:22:29] [Render thread/ERROR]: Reported exception thrown!
 
net.minecraft.class_148: Rendering Block Entity
 
	at net.minecraft.class_824.method_3554(class_824.java:111) ~[client-intermediary.jar:?]
 
	at net.minecraft.class_824.method_3555(class_824.java:79) ~[client-intermediary.jar:?]
 
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderTileEntities(SodiumWorldRenderer.java:275) ~[sodium-fabric-mc1.20-0.4.10+build.27.jar:?]
 
	at net.minecraft.class_761.handler$cgp000$sodium$onRenderTileEntities(class_761.java:12608) ~[client-intermediary.jar:?]
 
	at net.minecraft.class_761.method_22710(class_761.java:1372) ~[client-intermediary.jar:?]
 
	at net.minecraft.class_757.method_3188(class_757.java:1110) ~[client-intermediary.jar:?]
 
	at net.minecraft.class_757.method_3192(class_757.java:880) ~[client-intermediary.jar:?]
 
	at net.minecraft.class_310.method_1523(class_310.java:1219) ~[client-intermediary.jar:?]
 
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
 
	at net.minecraft.client.main.Main.main(Main.java:250) ~[1.20.1-0.14.21.jar:?]
 
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
 
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
 
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
 
Caused by: java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because the return value of "net.fabricmc.fabric.api.renderer.v1.RendererAccess.getRenderer()" is null
 
	at me.pepperbell.continuity.impl.client.ProcessingContextImpl.<init>(ProcessingContextImpl.java:19) ~[continuity-3.0.0-beta.2+1.20.jar:?]
 
	at me.pepperbell.continuity.client.model.CTMBakedModel$CTMQuadTransform.<init>(CTMBakedModel.java:83) ~[continuity-3.0.0-beta.2+1.20.jar:?]
 
	at me.pepperbell.continuity.client.model.ModelObjectsContainer.<init>(ModelObjectsContainer.java:10) ~[continuity-3.0.0-beta.2+1.20.jar:?]
 
	at java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305) ~[?:?]
 
	at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195) ~[?:?]
 
	at java.lang.ThreadLocal.get(ThreadLocal.java:172) ~[?:?]
 
	at me.pepperbell.continuity.client.model.ModelObjectsContainer.get(ModelObjectsContainer.java:18) ~[continuity-3.0.0-beta.2+1.20.jar:?]
 
	at me.pepperbell.continuity.impl.client.ContinuityFeatureStatesImpl.get(ContinuityFeatureStatesImpl.java:16) ~[continuity-3.0.0-beta.2+1.20.jar:?]
 
	at me.pepperbell.continuity.api.client.ContinuityFeatureStates.get(ContinuityFeatureStates.java:10) ~[continuity-3.0.0-beta.2+1.20.jar:?]
 
	at net.minecraft.class_835.handler$zfi000$continuity$beforeRenderModels(class_835.java:518) ~[client-intermediary.jar:?]
 
	at net.minecraft.class_835.method_3576(class_835.java:39) ~[client-intermediary.jar:?]
 
	at net.minecraft.class_835.method_3569(class_835.java:20) ~[client-intermediary.jar:?]
 
	at net.minecraft.class_824.method_23079(class_824.java:90) ~[client-intermediary.jar:?]
 
	at net.minecraft.class_824.method_23081(class_824.java:79) ~[client-intermediary.jar:?]
 
	at net.minecraft.class_824.method_3554(class_824.java:104) ~[client-intermediary.jar:?]
 
	... 12 more
 
```

After reading the log it also seems to be a Continuity issue. I can open an issue there if you would like me to. I saw sodium was in there and thought to report it here. Apologies if this issue is not related to Sodium, or I was a waste of your time.

### Crash Report file

[crash-2023-06-21_18.22.29-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/11827785/crash-2023-06-21_18.22.29-client.txt)

### Additional information

My mod list:
-BetterF3
-Blur
-Cloth Config
-C2ME
-Continuity
-Entity Culling
-Fabric API
-Fastload
-FerriteCore
-ImmediatelyFast
-Iris(had Complementary Reimagined 2.2 on at the time)
-Krypton
-Lamb Dynamic Lights
-Lithium
-Logical Zoom
-Mod Menu
-More Culling
-Puzzle
-Reese's Sodium Options
-Replay Mod
-Smooth Boot
-Sodium
-Sodium Extra
-VMP

**Comment by Dueris** [comment] 2023-06-22 01:42
This seems to be caused randomly, I was just afk at the time typing in Discord and it crashed with the same report

**Comment by astridellensdottir** [comment] 2023-06-22 02:56
this appears to be a duplicate of #38, it’s an issue with transparency sorting. the fix is non-trivial, but it’s being worked on.

**Comment by Dueris** [comment] 2023-06-22 02:57
alright thank you, would you like me to close this issue?

**Comment by astridellensdottir** [comment] 2023-06-22 02:59
> alright thank you, would you like me to close this issue?

my apologies, i replied to the wrong issue.

**Comment by Timolino456** [comment] 2023-06-22 04:54
You seem to be missing Indium. You need it when using Continuity with Sodium.

**Closed as completed** 2023-06-22 08:19 UTC
Labels: E-external, A-mods, T-crash
